### ISSUE TITLE
Chef cookbook issue 

### ISSUE THREAD

**Issue by Jas659** [chef/chef#10006]
Hi Team,

Below is my recipe for docker. I have installed docker using chef and its installed properly but when i am trying to pull the image through chef its not working:

ccwdfgl9880:~/chef-repo/cookbooks/docker/recipes # cat default.rb
#
# Cookbook:: docker
# Recipe:: default
#
# Copyright:: 2020, The Authors, All Rights Reserved.
package 'docker' do
   action :install
end

service 'default' do
   action [ :enable, :start ]
end

docker_image 'nginx' do
     tag 'latest'
     action :pull
end
ccwdfgl9880:~/chef-repo/cookbooks/docker/recipes #

I am getting below error when running chef client locally and testing:

NoMethodError
-------------
undefined method `docker_image' for cookbook: docker, recipe: default :Chef::Recipe

As I  am new to chef so need help on above issue

Regards
Jaspreet

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
