### ISSUE TITLE
Error in syncing public github repository in javascript application cookbook

### ISSUE THREAD

**Issue by HinaHumayun16** [chef/chef#10076]
Hi, I am having the following error while syncing a public github repository in my javascript application cookbook. The error picture is attached as well. Kindly help as I am new in chef :sweat:
https://github.com/mnazir23/conFusionServer

![image](https://user-images.githubusercontent.com/56160000/85897179-3c132b00-b813-11ea-8b60-56f33bb5fb6d.png)

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
