### ISSUE TITLE
macos_userdefaults cannot manage an array value idempotently.

### ISSUE THREAD

**Issue by natewalck** [chef/chef#10084]
## Description
When setting an array as a value for a key using `macos_userdefaults`, chef will set the array every chef run. 

## Chef Version
16.2.50

## Platform Version
10.16 (but probably <= 10.15 as well)

## Replication Case
Attempt to set an array as a value for a key using `macos_userdefaults`

## Client Output
Nothing relevant. Run chef 2-3 times, it will set the key every run as the idempotence check isn't working correctly.

**Comment by erikng** [comment]
putting some debug prints in the macos_userdefaults

```
defaults read '/Library/Preferences/ManagedInstalls' 'AdditionalHttpHeaders' | grep -qx '["Authorization: Basic basdadfsdfwsdfswdfwerf=="]'
      * execute[defaults write '/Library/Preferences/ManagedInstalls' 'AdditionalHttpHeaders' -array 'Authorization: Basic basdadfsdfwsdfswdfwerf=='] action run
```

the grep is wrong, so it returns nothing.

chef is running
```
defaults read '/Library/Preferences/ManagedInstalls' 'AdditionalHttpHeaders' | grep -qx '["Authorization: Basic basdadfsdfwsdfswdfwerf=="]' 

$?
zsh: command not found: 1
```

```
defaults read '/Library/Preferences/ManagedInstalls' 'AdditionalHttpHeaders'                                                                                           
(
    "Authorization: Basic basdadfsdfwsdfswdfwerf=="
)
```

This is going to be very ugly to unpack (and why using `CFPreferences` API over `defaults read` is better) but one potential solution (that likely will not work with more advanced arrays):

```
defaults read '/Library/Preferences/ManagedInstalls' 'AdditionalHttpHeaders' | grep -qx '    "Authorization: Basic basdadfsdfwsdfswdfwerf=="'
$?
zsh: command not found: 0
```

The command above takes off the `[]` since that's not a format that defaults read uses and adds four `spaces`. This then allows the line to return correctly.
