### ISSUE TITLE
16.2 custom resource `:provides` breaking change not reflected in docs

### ISSUE THREAD

**Issue by rjhornsby** [chef/chef#10112]
## Description

Ran into the same issue described in #10016.

This was a chef-infra client breaking change as noted in #10016 that was discussed in #9890, and #9885 but isn't reflected in the Custom Resources documentation at https://docs.chef.io/custom_resources/#provides.

There is a section on `provides` in the doc but there's no indication that it is *required* or that 16.2 clients trying to compile custom resources will break without it. To the contrary, the docs seem to suggest that `provides` is optional, and intended for a specific use case where different code is needed for different platforms.

--

I don't mean to give the devs writing the chef code a hard time, I know y'all are trying to cover a lot of ground across a bunch of different platforms in short amounts of time. However, it's frustrating to spend a few hours wondering why a custom resource stopped working despite seeming to be correct as far as the published docs are concerned.

> _Tweak tweak tweak_ Hrm. _Tweak tweak tweak_ Crap. What did I do? _Tweak tweak tweak_ Did I break something? _frustrated tweaking_ Am I reading the docs wrong? _more tweaking_ Argh, what is happening here?

No, tbh, I don't always keep up with the CHANGELOGs. I should do better at that. I do, however, try to read the documentation when I need a reminder, don't know, or something goes wrong -- kind of counting on it to be up to date with the stable releases.

The custom resources area of documentation has always felt like it gets far less love than most of the rest of the chef docs. Often - against recommendations like "these are not examples of how to do it" - I have to go into the chef code to figure out the right way to construct a custom resource or to figure out what I'm doing wrong. Maybe the tech writers (who are hopefully tracking changes like #9890) could help out here?

## Chef Version
16.2.73

**Comment by tas50** [comment]
I realize this one is a pretty painful breaking change, but we did outline the change in several places.

Here are the release notes for 16.2:

https://docs.chef.io/release_notes/#breaking-change-in-resources

We implemented two different Cookstyle rules that will autocorrect legacy HWRPs, LWRPs, and custom resources: 

https://github.com/chef/cookstyle/blob/master/RELEASE_NOTES.md#improvements-for-chef-infra-client-162

This last week we merged in a deprecation warning to Chef Infra Client 15, which will be shipping as well to help users that are going from the latest 15.x to a 16.x release. That will link to tha deprecation docs page here:

https://docs.chef.io/deprecations_resource_name_without_provides/

We also removed references to the resource_name call from the docs a few weeks back:

https://github.com/chef/chef-web-docs/commit/ad3bb0eef37e88d671f0538063b3cf7b18ee3721

The original resource cleanup in Chef Infra Client 16 didn't involve this large breaking change, but it exposed several pretty nasty edge cases in resource naming that required some breaking changes. That's why this shipped outside the major release. It's not our intention to make out of band changes, but sometimes it has to happen and the timeline here meant that we couldn't push those cookstyle rules out for a year before making the breaking change like we usually try to do.
