### ISSUE TITLE
only_if guard with lazy behavior

### ISSUE THREAD

**Issue by evandam** [chef/chef#10243]
Assuming the following Chef code:

```ruby
log 'A => this should not run, no lazy' do
  only_if  { nil }
end

log 'B => this should not run, with lazy' do
  only_if { lazy { nil } }
end

log 'C => this should not run, with lazy and error' do
  only_if { lazy { raise } }
end

log 'D => this should not run, without lazy but with error' do
  only_if { raise }
end
```

Here is the result of the Chef run with `Chef Infra Client: 15.13.8`:

```
         * log[A => this should not run, no lazy] action write[2020-07-31T22:24:21+00:00] INFO: Processing log[A => this should not run, no lazy] action write (wo-sudo::default line 18)
        (skipped due to only_if)
         * log[B => this should not run, with lazy] action write[2020-07-31T22:24:21+00:00] INFO: Processing log[B => this should not run, with lazy] action write (wo-sudo::default line 22)
       [2020-07-31T22:24:21+00:00] INFO: this should not run, with lazy


         * log[C => this should not run, with lazy and error] action write[2020-07-31T22:24:21+00:00] INFO: Processing log[C => this should not run, with lazy and error] action write (wo-sudo::default line 26)
       [2020-07-31T22:24:21+00:00] INFO: this should not run, with lazy and error


         * log[D => this should not run, without lazy but with error] action write[2020-07-31T22:24:21+00:00] INFO: Processing log[D => this should not run, without lazy but with error] action write (wo-sudo::default line 30)


           ================================================================================
           Error executing action `write` on resource 'log[D => this should not run, without lazy but with error]'
           ================================================================================
```

I would expect **B** and **C** to not run (and **C** should also raise a runtime error similar to **D**).

Is this intended behavior or a bug?

**Comment by phiggins** [comment]
Hi,

`lazy` is meant to be used to provide a lazily evaluated value for properties when defining resources. What `lazy` is doing under the covers is capturing the block provided and creating a wrapper object for it that gets called at the appropriate time. `only_if` evaluates the block passed to it and considers the condition satisfied if the result is a `true` value (ie, not `nil` or `false`). Since `lazy` creates an object, this is equivalent to `only_if { Object.new }`, meaning it will always pass.

This is intended behavior to the extent that `lazy` only has utility in a few cases, and it isn't meant to be universally applicable. Do you have a use case for using `lazy` with `only_if` that you can't satisfy with the current methods?

**Comment by lamont-granquist** [comment]
The `only_if {}` as a block is already lazy.  There's not a bug here, there's just no reason to use `lazy {}` with an `only_if` block.
