### ISSUE TITLE
ZD : Chef Infra Client private key /etc/chef/client.pem appears in clear text

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef#10272]
## Description

The below private key is not encrypted as per some customer standards
/etc/chef/client.pem
## Related Issue
https://github.com/chef/customer-bugs/issues/211

## Replication Case

Bootstrap a chef-client and notice its /etc/chef/client.pem is unencrypted
## Expected Behavior
The customer expects /etc/chef/client.pem to be encrypted
## Actual Behavior
In all versions of chef-client, chef-client's required file /etc/chef/client.pem is unencrypted

**Comment by lamont-granquist** [comment]
This needs some kind of design because if the pem key is encrypted, then we need a decryption key for the key, so where are we pulling that?  And if it is another service that we pull the key from, how do we authenticate to that service and where do we store that key?  At some point there needs to be either console input so that someone has to type in a passphrase to start chef-client (which does not scale across 1000s of servers) or else there needs to be a credential which is unprotected at rest.  And this is similar to e.g. Kerberos where host credentials are stored in /etc/krb5.conf unprotected other than by root readonly privs on the file.

**Comment by trickyearlobe** [comment]
Maybe we could implement keyless encryption such as ROT13 or better still ROT26?

**Comment by stevendanna** [comment]
Unless I am misssing something, I think we need to do the following:

- Have a conversation with the customer about this to understand their expectations here better and explain (perhaps with some documenation we write) about how `client.pem` is for us the host-specific credential for chef-client and how we expect it to be protected with operating system level file permissions.

Based on that conversation, I imagine we might have 1 of 3 outcomes:

1.  We do nothing.
2. We implement an integration point into chef-client to make it easier to manage client.pem keys using key/credential management systems that the user already trusts.  For example, I could imagine us designing a way to integrate with Hashicorp Vault.
3. We implement some kind of obfuscation strategy.

I am pretty strongly against (3) as it encourages a misunderstanding of the security properties fo the system.  

One may argue that (3) is what we did in Chef Server, but in that case we both (a) put down the ground work for implementing other KSM integrations and (b) moved credentials from a few dozen places on disk to a single place on disk. While we did add a little obfuscation along the way, we only tolerated that because we were also doing other things that _did_ improve the security of the system (since the user only then had to protect a single file rather than many files).

**Comment by trickyearlobe** [comment]
I'm also against (3) as it gives people a false sense of security and is usually trivial to break for anyone serious about hacking.

In addition to Hashi, (2) could for sure work in clouds that have their own secrets management solutions like AWS/Azure where secrets can be protected by IAM or Service Principals assigned to the machine by the provisioner. The downside to that is managing the lifecycle of a cloud vault per machine (which I guess brings different headaches in the provisioning space)

**Comment by dheerajd-msys** [comment]
Closing this per https://github.com/chef/customer-bugs/issues/211#issuecomment-727004238
