### ISSUE TITLE
Cannot edit_resource of a resource defined in a custom resource's action

### ISSUE THREAD

**Issue by evandam** [chef/chef#10333]
## Description
Very often I come across cookbooks that use custom resources to wrap other resources, but I need to edit the underlying resource. When I attempt to `edit_resource!`, Chef is unable to find it.

Is this a bug, or is there a correct way to be doing this? Not sure if @lamont-granquist can provide some insight 🙏 

## Chef Version

```
Chef: 14.15.6
```

I also verified the same behavior on `15.13.8` and `16.4.41`.

## Platform Version

Ubuntu 18.04

## Replication Case

Example resource:
```ruby
property :my_name, name_property: true
provides :my_custom_resource

action :create do
  file "/tmp/#{new_resource.my_name}" do
    action :create
  end
end

action :delete do
  file "/tmp/#{new_resource.my_name}" do
    action :delete
  end
end
```

Example recipe:
```ruby
my_custom_resource 'test' do
  action :create
end

edit_resource!(:file, '/tmp/test') do
  action :delete
end
```

## Client Output

```
Chef::Exceptions::ResourceNotFound
----------------------------------
Cannot find a resource matching file[/tmp/test] (did you define it first?)

Cookbook Trace:
---------------
  /var/tmp/kitchen/cache/cookbooks/wo-common/recipes/debug_resource.rb:5:in `from_file'

Relevant File Content:
----------------------
/var/tmp/kitchen/cache/cookbooks/wo-common/recipes/debug_resource.rb:

  1:  my_custom_resource 'test' do
  2:    action :create
  3:  end
  4:
  5>> edit_resource!(:file, '/tmp/test') do
  6:    action :delete
  7:  end
  8:

System Info:
------------
chef_version=14.15.6
platform=ubuntu
platform_version=18.04
ruby=ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
program_name=/opt/chef/bin/chef-client
executable=/opt/chef/bin/chef-client
```

**Comment by lamont-granquist** [comment]
No that isn't possible.  Until you execute the custom resources action the sub-resource collection doesn't exist, the action hasn't been parsed the resource does not exist as an object.  The sub-resource compile/converge then runs when the action runs.  Control does not return to the recipe context until after it has all been executed (and even the delayed notifications in the subresource have run).

This is flatly impossible.

A common misconception is that there is one big compile phase of all the recipe code and the resources, and then one big converge phase.  That isn't how it works at all.  The recipe compile phase completes before any sub-resource is touched.  As resources fire in recipe mode, their actions cause the sub-resource compile/converge modes to fire.  So the compile+converge phases of every sub-resources all happen at converge time in the enclosing context.

This is why I did unified_mode in resources since there's no point to the split compile/converge modes of sub-resources at all.  Eventually all sub-resources are going to execute without any split phase at all.

Really edit_resource is a bad hack to work around poor recipe design.  The real fix is to fix the custom resource.  If there's a supermarket resource which sorta does the right thing, but is abandoned, and you need to hack it up then the right solution is to fork it and maintain it (either internally or take over maintainership of it).  Hacking things up with edit_resource is simple, easy and the wrong thing to do.  The custom resource probably needs a new property to inject different behavior into it, which is more of dependency-injection kind of style (see e.g. [Monkeypatching is Destroying Ruby](https://avdi.codes/why-monkeypatching-is-destroying-ruby/) which may be hyperbole, but I basically agree with it).

Anyway, I couldn't fix this even if I wanted to.
