### ISSUE TITLE
Chef Workstation Bootstrap fails - incorrect directory created. 

### ISSUE THREAD

**Issue by Firenice03** [chef/chef#10623]
## Description
When Chef fails on AIX (known problem Thread Error) creates an incorrect directory. Formatted to mimic Windows C:/ 
/home/MINE/Cefche/chef-stacktrace.out

256 Oct 20 17:26 Cefche
ls Cefche
ls: 0653-341 The file Cefche does not exist.

ls C:^Hef^Ache/
chef-client-running.pid  chef-stacktrace.out      cookbooks

Its attempting to mimic the Windows directory in Nix... I've seen similarly in another CW version that affected Linux too - I assume this would to.. I'll be having to remove this version and revert to another. 

## Chef Workstation Version
Chef Workstation version: 20.9.158

## Platform Version
Windows 10 - Bootstrapping AIX 7.1

Aha! Link: https://chef.aha.io/features/SH-392

**Comment by tas50** [comment]
@Firenice03 I've moved this to the chef/chef repo since that's where the bootstrap code actually lives. I suspect we've fixed this with the latest code here. That code shipped in the last few releases of workstation. Can you confirm if you're running into this issue with the latest workstation release?

**Comment by Firenice03** [comment]
@tas50 Thanks, I will test the newer version - it may be sometime next week thou..

**Comment by tas50** [comment]
Closing this out since we never heard back. If it's still an issue feel free to open a new issue with the new output.
