### ISSUE TITLE
compile_time property not found in yum_repository resource

### ISSUE THREAD

**Issue by haidangwa** [chef/chef#10905]
## Description

Chef Infra Client fails when the `compile_time` property is used with the `yum_repository` resource. This is [documented here](https://docs.chef.io/resources/yum_repository/#resources-common-properties) as a supported property.

## Chef Version

16.9.20

## Platform Version

RHEL8

## Replication Case

Use this resource declaration in a recipe:

```
yum_repository 'chef-stable' do
   action :remove
   compile_time true
   only_if { platform_family?('rhel', 'amazon') }
end
```

## Client Output

```
       NoMethodError
       -------------
       undefined method `compile_time' for Chef::Resource::YumRepository

```

**Comment by lamont-granquist** [comment]
I can't replicate, the compile_time property is there on that resource for me, and that has been a property for all resources since 16.0.60.

All I can think of is that you're testing on Chef 15 or earlier, or that one of the characters like `_` has an encoding issue and isn't U+005F but one of the other variants.
