### ISSUE TITLE
Chef::ChefFS::Parallelizer failures in test

### ISSUE THREAD

**Issue by tas50** [chef/chef#10911]
We see this sort of failure from time to time, which adds over an hour to the build/test cycle:

```
  1) Chef::ChefFS::Parallelizer With a Parallelizer with 1 thread when the thread is occupied with a job resizing the Parallelizer to 2 does not stop the job
     Failure/Error: expect(@occupying_job_finished).to eq([ true ])

       expected: [true]
            got: [false]

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -[true]
       +[false]
     # ./spec/unit/chef_fs/parallelizer_spec.rb:263:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'
```

**Comment by lamont-granquist** [comment]
more than that though:

- we wound up permanently disabling the parallelizer tests on the mac because they were busted and we forgot to try to debug them
- we're having constant issues with the parallelizer tests failing hard and aborting the rspec runs with a hard exit(1) on windows
- it uses a roll-your-own actorey thread model with a mess of code that is difficult to determine what it is meant to do
- it is undocumented
- some of the features seem to be untested in unit tests (although there's coverage over everything in the knife integ/func tests)
- it is overengineered for what it does and designed to be a standalone software project
- i don't even particularly like the direction it takes though

The idea is to replace it with something simpler that reuses constructs like threadpools and futures from the concurrent-ruby gem, which is designed a bit more like a bit of useful machinery that could be put until chef-utils and reused elsewhere as a simple primitive to implement parallel_map.

Prior art of this approach in ruby is here:

https://github.com/aemadrid/parallel_map/blob/master/lib/parallel_map.rb#L22-L30

Not much more than that, although it requires teasing apart what Parallelizer actually provides out of its uncommented source code.

**Comment by tas50** [comment]
This work took 6 workdays to resolve
