### ISSUE TITLE
yum_package on Red Hat 8 fails

### ISSUE THREAD

**Issue by johnypony3** [chef/chef#11207]
## Description
yum_package does not work on Red Hat 8.

## Chef Version
15.x.x

## Platform Version
Red Hat 8

## Replication Case
> yum_package 'bingo'

## Client Output
cannot find yum libraries, you may need to use dnf_package

**Comment by tas50** [comment]
@johnypony3 This is the expected output. RHEL 8 no longer ships with yum out of the box so there's no yum utilities for chef to interact with. You can update this code to be dnf_package, which will use the dnf utility in RHEL 8, but you'd probably be better off just using `package` instead. Package includes the magic to use the appropriate tooling under the hood depending on release.

**Comment by johnypony3** [comment]
This should not be chefs stance on this. We now need to convert hundreds of cookbooks to use package. It would be much better if chef switched to dnf_package and added a deprecated call out to the log.

**Comment by tas50** [comment]
We've always taken the stance that users should not use `yum_package` directly unless they absolutely needed to access yum on a system. The documentation for yum_package itself suggests using `package` instead: https://docs.chef.io/resources/yum_package. The `package` resource is designed for a user that wants a package installed and doesn't particularly care how chef-client goes about doing that. The lower level specific resources are designed for power users that want to override the guidance of chef-client. Since these are designed to interface with particular package managers it wouldn't be appropriate to have yum_package using dnf_package instead. 

If you need a quick workaround you can just install yum during bootstrap or use chef to run `package 'yum'`.

**Comment by lamont-granquist** [comment]
You can do that manually yourself just by throwing something like:

```
Chef::Resource::DnfPackage.provides :yum_package, platform_family: "rhel", platform_version: ">= 8"
Chef::Provider::Package::Yum.provides :yum_package, platform_family: "rhel", platform_version: ">= 8"
```

Into any library file

**Comment by johnypony3** [comment]
we have hundreds of cookbooks controlled by two chef servers across multiple orgs with policies and environments. this is not a `great` solution.

**Comment by lamont-granquist** [comment]
That globally fixes it across all cookbooks running on the machine, you just have to add that to any base cookbook or drop a library into any set of base cookbooks that winds up on every server.

**Comment by johnypony3** [comment]
thanks! i will test that. i appreciate your time.
