### ISSUE TITLE
Chef (say v20) on Crystal?

### ISSUE THREAD

**Issue by hedgehog** [chef/chef#11350]
Thank you to all the contributors for their efforts in making Chef, and for making it open source.

I am a long time user of Chef since 2012, and have contribute in various ways since 2012 - under different accounts.

I have noticed the secular decline in Chef and Ruby.  
The premise behind this proposal is

i. that Chef has intellectual capital in the form of recipes 
ii. the utility of Chef's intellectual capital is independent of Ruby
iii. the size of the Crystal community will surpass the size of the Ruby community
iv. Chef's recipe intellectual capital is not unassailable

While personally I am turning more to Rust and Packer+Terraform I am not convinced there is not a place for Chef like tools.  However performance is increasingly becoming an issue - all our Packer builders apply  Policyfiles via Chef-Zero.
While Chef is not the bottleneck when provisioning - network and install latencies dominate. However Chef does not offer an advantage over salt/ansible etc, and the size of those communities means the accumulated knowledge in Chef recipes is likely to be eclipsed - sooner rather than later - if it is not already.  
From my PoV Chef is starting to reach the level of mind share where the community size of other provisioning software overpowers/overtakes the accumulated knowledge in Chef recipes.

One significant comparative advantage that Chef (indirectly) has is the accumulated knowledge that resides in Chef recipes.  This advantage is not unassailable - the recipes are open source and that knowledge is readily ported to salt/ansible etc. and vice versa.

Acknowledge the Crystal compile times will initially be an issue - but hopefully the tooling will evolve such that only changed recipes need to be recompiled - e.g. our developer Cookbook has 40-50 recipes (applied via Policyfiles) often none change when a recipe is run, very rarely are more than 2 recipes changed.
 
Hopefully this proposal is taken constructively, if nothing else it could track the state of any discussion/effort to move Chef onto Crystal.
 
## Motivation

    As a Chef user who is agnostic about Ruby,
    I want to preserve the accumulated knowledge in Chef recipes,
    so that vm/container configurations have this wisdom inbuilt,
    and so that Chef is part of language ecosystem with growing mind-share (a proxy for growing the IP in recipes)

## Specification

Port Chef, Chef-Zero, etc. to run on Crystal

## Downstream Impact

Inspec, Auditor, Chef-Workstation, etc.

**Comment by lamont-granquist** [comment]
There's just no way we're rebuilding it all in another language.  We did add YAML recipe support since that can be done in ruby with the same core engine.  We don't have the developer time to rewrite core chef in anything else, that is rewinding to zero on 10 years of developer effort.  We also cannot support some kind of FFI into having foreign language support in recipes, that is similarly too much developer effort.  Doesn't matter what the language is, although crystal would not be the first choice and right now it would most likely be Python for a scripting language or go for something more strongly typed.  Rust would be great for safety but is terrible for the broad majority of users.  There does not exist 1/10th of the resources for any of that to happen.
