### ISSUE TITLE
bash resource getting executed at compile time even though compile_time is set to false

### ISSUE THREAD

**Issue by HarshRajIN** [chef/chef#11406]
## Description
[bash resource](https://docs.chef.io/resources/bash/) is getting executed at compile time even though `compile_time` is set to false. So if we are referring to some file that gets created just before the bash resource call during convergence, the bash script is failing because that file is not being found.

## Chef Version
Chef client 16.8.14

## Platform Version
Oracle Linux 7.3

##Sample code
```
bash 'post_cert_req_and_download_cert' do
      Chef::Log.info('post_cert_req_and_download_cert')
      csr = File.read(::File.join(node['abc_ca_certs']['scripts_dir'], node['abc_ca_certs']['hostname'] + '.csr')).gsub(/\n/, '%0A').gsub(/\r/, '%0D').gsub('/','%2F').gsub('+','%2B').gsub(/\s/,'+')
      Chef::Log.info('post_cert_req_and_download_cert csr:' + csr)
      password = abcPassword.decrypt(node['cacredentials.password'])
      cert_fnsh_url = ::File.join( node['caserverurl'], '/certfnsh.asp')
      cert_new_url = ::File.join( node['caserverurl'], '/certnew.cer')
      certificate_destination = ::File.join( node['abc_ca_certs']['scripts_dir'], node['abc_ca_certs']['hostname'] + '.cer')
      code <<-EOH
    echo "Executing bash script to fetch certificate from CA server for #{node['cacredentials.user']}"
    echo "CSR is: #{csr}"

    ResponseBody=$(curl -k -v -u "#{node['cacredentials.domain']}\\#{node['cacredentials.user']}:#{password}" --ntlm \
        #{cert_fnsh_url} \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
        -H 'Accept-Encoding: gzip, deflate' \
        -H 'Accept-Language: en-US,en;q=0.5' \
        -H 'Connection: keep-alive' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        --data "Mode=newreq&CertRequest=#{csr}&CertAttrib=CertificateTemplate%3A#{node['csr_template']}&TargetStoreFlags=0&SaveCert=yes&ThumbPrint=" )
    echo "Response Body: $ResponseBody"

    ReqID=`echo $ResponseBody | grep -oP 'ReqID=\\K\\d+' | head -1` #note the double \ here. Chef escapes one.
    echo "Request ID is $ReqID"
    if [ -z "$ReqID" ]
    then
       echo "\nERROR- Request ID not found in the response body. Check response data for any error.\n".
       exit 1
    fi
    echo "\nRequesting certificate from CA server for Request ID: $ReqID\n"
    curl -X GET -k -v --ntlm -u "#{node['cacredentials.domain']}\\#{node['cacredentials.user']}:#{password}" "#{cert_new_url}?ReqID=${ReqID}&Enc=b64" -o "#{certificate_destination}"
      EOH
      retries 3
      retry_delay 10
      only_if { do_new_cert }
    end
```

It's failing at line 3 above with error **ENOENT: No such file or directory @ rb_sysopen - /opt/abc/app/data/security/scripts/hostname.csr**

The above code should get executed during convergence. But it's getting executed during compile time because of which it's failing to find .csr file. This file gets created during convergence just before the bash resource.

**Comment by lamont-granquist** [comment]
The only code which is lazied to converge time is the bash code in the `code` block.  All the ruby code inside the bash script is executed at compile_time as is all ruby code embedded in the declaration blocks of resources.  The block passed to a resource is executed in order to build the resource and fill it out with properties.  This is why node objects which are mutated during the run often need to be `lazy {}`'d inside of resource declaration blocks.  This isn't a bug and can't be fixed even if it was.  Ruby code inside the block MUST be parsed in order to build the resource to put on the resource collection.

All of this code needs to go into a ruby_block then the back resource needs to be lazied, and the variables that pass between the resources need to be lazied:

```
csr = password = cert_fnsh_url = cert_new_url = certification_destination = nil

ruby_block "stuff" do
  block do
      Chef::Log.info('post_cert_req_and_download_cert')
      csr = File.read(::File.join(node['abc_ca_certs']['scripts_dir'], node['abc_ca_certs']['hostname'] + '.csr')).gsub(/\n/, '%0A').gsub(/\r/, '%0D').gsub('/','%2F').gsub('+','%2B').gsub(/\s/,'+')
      Chef::Log.info('post_cert_req_and_download_cert csr:' + csr)
      password = abcPassword.decrypt(node['cacredentials.password'])
      cert_fnsh_url = ::File.join( node['caserverurl'], '/certfnsh.asp')
      cert_new_url = ::File.join( node['caserverurl'], '/certnew.cer')
      certificate_destination = ::File.join( node['abc_ca_certs']['scripts_dir'], node['abc_ca_certs']['hostname'] + '.cer')
  end
end

bash "more stuff" do
  code lazy { <<EOH
[...]
EOH
}
end
```

If, instead, you extract the whole download-and-build process to some kind of custom resource, then you can set `unified_mode true` to make compile+converge mode locally go away within the action block of the resource and all this goes away.  If you cannot do that and are stuck with recipe mode, you should also consider eagerly downloading/creating the file at compile_time to avoid having to lazy the world like this, unless that creates a worse race to push everything in recipe context to compile time.  A prior art example of that is the way the hostname resource sets compile_time to true to force itself to run at compile time, so that every reference to the node's hostname doesn't have to be later lazied.

But this is behaving exactly as it has to and isn't a bug.  And impossible to suggest forcefully enough that extracting a custom resource to do this work and then setting `compile_time true` on the resource makes this go away.

**Comment by HarshRajIN** [comment]
Thank you @lamont-granquist for your suggestions. Let me take the best solution.
