### ISSUE TITLE
Do not include data/spec in the RubyGems releases of knife

### ISSUE THREAD

**Issue by mensfeld** [chef/chef#11582]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessment for OSS libraries using WhiteSource Diffend.io.

### Describe the Enhancement:

While reviewing the changes for this lib, I noticed, that the `data/spec` directory is being included.

ref: https://rubygems.org/gems/knife
ref: https://my.diffend.io/gems/knife/17.0.246/17.1.35/page/1#d2h-882321

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

If the presence of `data/spec` data is valid I would love the reasoning. Thanks!

### Describe the Need:

Any user that wants to see all the changed between releases would benefit from it, as would only have to review actual functional code changes included in the release that could affect the gem usage.

### Current Alternative

None.

### Can We Help You Implement This?:

I can fix the gemspec to exclude those files in a PR.

**Comment by lamont-granquist** [comment]
Yeah that is unfortunately deliberate.  The way we do our build process is that we build our omnibus packages on builders and we ship the built artifact to artifactory, then tester will download the artifact and run the test which are baked into the image.  That validates in a very hard sense that what we ship has been tested as it will actually get delivered to customers with no race conditions around running the wrong tests against the shipped version of code.  Since we promote out of the output of the builder stage there's also no chance to cleanup the tests after they've been run and repackage (something could go wrong with the "cleanup" scripts that destroy something that invalidates testing, etc).  Fixing that so that the tests are downloaded/checked-out to the testers via a side-channel in such a way that we know we're getting the right tests has been talked about for a long time, but never done.  The mechanism that we've relied upon is to ship the code and the tests as the gem and then install (which is simple enough we're sure that it is always correct).
