### ISSUE TITLE
Investigate the difficulty of running Target mode clients concurretly

### ISSUE THREAD

**Issue by tas50** [chef/chef#12477]
Initially it's fine if our proxy nodes (Bastian nodes?) run the Infra Client one at a time using the configs in the /etc/chef/client.d directory. Eventually we need to determine the difficulty of running these at the same time so we don't take longer than 30 minutes when running a large number of nodes. This is a placeholder issue for engineering to do feasibility tests on different mechanisms for running in parallel.

**Comment by lamont-granquist** [comment]
We aren't multithreaded and have piles of global state, so this has to be a forked-process-per-controlled-node.

We probably don't want to go back to using the old chef-client daemon interval runs only forking off on the server, so we probably want to write a standalone app that is a bit of a minmal job scheduler for target mode parallel runs.  Maybe systemd could be leveraged to do this a bit if that could take some kind of matrix?  But it probably looks like an external thing.

Going the other direction and making chef-client itself multithreaded would be difficult due to accumulation of 12+ years of design decisions which are now public APIs and difficult to unwind (Chef::Config, Chef.whatever, etc)

**Comment by tas50** [comment]
Works for me
