### ISSUE TITLE
Add the ability to run Infra Client multiple times from .d configs

### ISSUE THREAD

**Issue by tas50** [chef/chef#12476]
As a followup from https://github.com/chef/chef/issues/12475 we need the ability to run multiple Target mode runs using multiple client.rb definitions in the `/etc/chef/client.d` directory. We should load these files alphabetically and execute them one at a time to avoid concurrency issues.

**Comment by lamont-granquist** [comment]
This probably makes more sense to fire individual forked chef-client runs off one at a time and kill and cleanup the process afterwards to deal with global state issues.  Even though you're not running concurrently you still have the mess of global state.

You take the ruby startup cost then every time in between client runs, but I would argue that we need to again seriously stop accepting rubygems perf issues as being a force of nature and go fix them by wrapping rubygems with a cache of gem-to-filename mappings.  We're still stuck in the Denial/Bargianing stage of the 5 stages of grief over needing to do that, and we need to hit acceptance at some point and take the time to do it, because its going to cost more eventually to not do it.

**Comment by tas50** [comment]
Migrating to https://chefio.atlassian.net/browse/INFC-38
