### ISSUE TITLE
Add ability to load client.rb files from a client.d directory

### ISSUE THREAD

**Issue by tas50** [chef/chef#12475]
We should add initial support for a `/etc/chef/client.d` directory. In this initial release we will support loading a single client.rb file within this directory. No different behavior. Just a new location for now.

**Comment by lamont-granquist** [comment]
Yeah somehow this needs to be tied in fairly automagically so that `--target` invocation goes looking for the right client.d or something like that.  When using solo/local mode we also need to consider keeping the chef-zero data for the nodes separate as well, so this is quite a bit larger of a project than just the configs.  We also need to consider that when managing 100 different servers people probably don't really want 100 different client.rb's but want some kind of default template.

**Comment by tas50** [comment]
Migrating to https://chefio.atlassian.net/browse/INFC-38
