### ISSUE TITLE
Deprecation warnings when running our specs

### ISSUE THREAD

**Issue by tas50** [chef/chef#12522]
We need to track this one and fix it:

NOTE: Gem::DependencyInstaller#find_gems_with_sources is deprecated with no replacement. It will be removed on or after 2019-12-01.

**Comment by tas50** [comment]
Looks like we fixed this on main actually

**Comment by tas50** [comment]
Still there in 17 but with a new message

```
NOTE: Gem::DependencyInstaller#find_gems_with_sources is deprecated with no replacement. It will be removed in Rubygems 4
```

**Comment by lamont-granquist** [comment]
We don't need to do anything about this really.  When we pull in Rubygems 4 we remove that option.  We already run by default on the other codepath.  I doubt anyone even knows the old codepath exists since I've never told someone to use it before.  I built the button to go back to the old way just in case anyone complained about the new behavior, but nobody ever did.
