### ISSUE TITLE
Gemfile.lock update policy

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#13290]
During today's Chef Infra Client PR meeting, we discussed the need for a standard policy for updating `Gemfile.lock`s.

In theory, these should never be updated by hand, but today many PRs come through with hand-edited updates. Without any standard approach, these are impossible to review meaningfully.

What follows is some basic concerns and then some possible options. There are many paths forward, but we should decide how we want to handle these, document the policy, and enforce it. We can, of course, iterate on that policy if it does not suit our needs.

# Possibilities

1. *Hand-edit* - Manually update lock files. This is *error-prone* and can lead to subtle problems on platforms the user didn't test on, that will only show up for new installs, or only weeks later on `bundle update`. **We should not do this.**
2. *Conservative Updates* (`bundle lock --conservative --update <gem_name>`) - This will update the lock for <gem_name> and the *minimum* number of other gems to statisfy dependencies
3. *Full update* (`bundle update`) - This will update everything to the latest version that is satisfied by the constrains in the Gemfile.

# Concerns

* Hand-editing is not supported, can cause projects with multiple lockfiles to get badly broken or unnecessarily use multiple versions of gems
* Conservative updates are much quicker than full updates, but if those are the default, a regular process to get *fully* up-to-date is necessary. Keeping up-to-date can prevent security issues, prevent having to debug issues that have been fixed upstream already, etc.
* Bundle updates can delay releases, especially if one hasn't been done in a while

# Options

1. We can move to `bundle update`s going forward. This will be a one-time very-painful cost, but should be less painful going forward. However, it will certainly require developers who want to update a single gem to have to do some work when several gems get updated.
2. We can move to conservative updates, and then have a bot that does a `bundle update` and make a PR on a regular basis, ideally no less than once a month.
3. We start with conservative updates for now to get off of hand-edits, and make a project to get us to full updates.

# Additional notes and thoughts

* Ideally whatever policy we iterate on in _client_ can eventually be used for all Ruby projects at Progress-Chef
* While the various lockfiles in _client_ are all built on the same version of bundler, in _server_ they have various different versions. Whatever policy we come up with should ensure we use a single version in any given repo (we're already in compliance for _client_).
* Some projects, like Inspec, don't even commit their lockfiles, so we should make that a clear part of the policy

Thanks to @ramereth, @tpowell-progress, @marcparadise and @Stromweld for their thoughts on this in today's meeting, hopefully I've represented everything. CC @GeorgeWestwater who is interested in this as well.

**Comment by ramereth** [comment]
Here's my take on this given an "ideal" world for a long term goal:

1. New major releases should always be current with the updated gems so developers can adapt any changes to dependent gems at that time
2. Only perform security updates on stable branches (i.e. chef-18, chef-17) via dependabot, but _not_ version updates
3. If  a gem needs updated in a "stable" branch, it should be done via the conservative method and should have a PR specifically for it with reasoning for the update

Now given the current situation, we will need to do something different. Since 18 is still in "RC" mode, I think we should still do a `bundle update` in the main branch before it goes to GA. However I realize that this may impact the release timeline of 18, so perhaps we might just give up that for this release and work towards getting that done for 19.

Historically (before Progress), after a new major version goes GA, the `main` branch is still considered the "stable" branch for that release until the start of the calendar year when a `chef-18` branch is cut and the `main` branch is switched to the next development branch. IMHO I'd like to propose the following which will help this issue in the long run:

1. Cut the `chef-18` stable branch when GA happens instead of waiting later
2. Make `main` always the development branch for the next release (i.e. it becomes 19 after chef-18 is out)

If we go with this approach, we don't have to worry about doing `bundle update` "once a year". Of course will need to do a one-time `bundle update` at some point.

After that one-time `bundle update`, we can enable dependabot version updates (in addition to security updates) on the `main` branch. That way `main` is always up to date and can be tested by folks to catch bugs/issues. The `main` branch should still be cutting releases in the `current` channel which Sous Chefs typically uses for their CI. This usually catches a lot of issues and forces a fix faster in `main`.

Now the downside of doing this is constantly having to do backport PRs in the stable branch instead of just relying on the `main` branch as the "current stable". But if the pipelines are working properly, this shouldn't be a huge problem.

**Comment by jaymzh** [comment]
I dislike the idea of branching chef-18 as soon as GA comes out. That's a year of new resources, features, etc. that will just never make it to 18. And given that Progress is looking to, at least temporarily, _slow_ the rate of major releases, that would mean new features won't get to users for even longer. `main` branch should be the current stable version until we're ready to start doing work on a new version.

I like the idea of `bundle update` every major version, but only as a stop-gap. We really should be doing these *more* often, not less - at least in ideally. Otherwise it's like pushing to prod every year - when something breaks, you have no idea what it is. Smaller updates, more often, is The Way(TM).

**Comment by jasonwbarnett** [comment]
@ramereth I agree with @jaymzh that cutting a new `chef-18` branch as soon as 18 is GA would be costly to backport all relevant PRs until the next major release. I don't think this pattern is sustainable, especially given that Chef Progress has moved away from the annual major version bump so I couldn't imagine the overhead of backporting every relevant PR to a `chef-18` stable *and* `chef-17` branch for multiple years. Anecdotally, in my experience master/main/trunk has been the current major version where releases are cut from and it's only until a new major release comes out that a new stable branch is cut. This last point should be weighted the least since it's anecdotal and subjective.

@jaymzh I think you did a good job presenting/documenting the possibilities/options as you/the group discussing sees it, but you failed to clearly articulate the problem that you're trying to solve which makes it hard to come along side and help solve the specific problem this project is facing with the best/most appropriate solution. (for more context Russ Cox wrote a lovely article titled ["Toward Go 2"][1], where he describes their process to solve problems; the two sections I think applies in this context are "Process" and "Explaining Problems"). With that article for context, I think in this case you failed to articulate the technical problem as well as the significance of the problem. Not to say you literally skipped it, just that it's either missing or buried in this issue. I think it would be much more approachable for others to come alongside and help if that was done well. For example, I'm asking myself: "What updates are they referring to? Is it limited to PATCH releases or is this inclusive of every literal update to the `Gemfile.lock` which would include adding or removing gems."

With that said, from the limited context I gathered from this issue I think you'd have most success from taking a two pronged approach.

1. working diligently to update gems using the conservative method, focusing on specific gems in a targeted way.
   1. targeted: meaning either for security updates, features, supportable, etc and then taking the more challenging cases and setting aside issues for each of the challenging ones to track progress against.
2. strategize how you plan to keep the `Gemfile.lock` up-to-date through time so that once you've fought your way through the backlog of work you will have a strategy to maintain it going forward
   1. I don't foresee a black/white approach of running `bundle update` monthly will be enough because it doesn't take into account major/minor updates to gems that may require code updates along side the updates or the various nuances of the types of gem updates. I say this under the assumption that this topic isn't strictly talking about how to promote the latest PATCH releases from gems this project depends on. If that's the limited scope of this discussion, then that may work really well.

[1]: https://go.dev/blog/toward-go2

**Comment by jaymzh** [comment]
The problem:

Given there is no consistent strategy for Gemlock updates, everyone does it differently - sometimes by hand, sometimes with a "--conservative" update and sometimes with a full update. That has many negative side effects:

* Any PR that touches the file is impossible to review - you don't know if they hand edited it, and if they did, if it'll break anything, and if they didn't how much unnecessary stuff was updated that could break things, and so on
* There's no consistent update schedule so we often end up chasing bugs that are fixed in later gems
* There's no consistent update schedule so we are often scrambling to accommodate MANY API changes at once when we have to do a major update to get a security/feature fix on some gem A that has many recursive update dependencies, when we could have spread that load out over time
* There's no consistent update schedule so we often are missing security updates (non-major ones, those tend to get escalated and solved quickly, but still)
* New (and old) developers alike have no idea what to do when they need to update a Gem because there's no policy. Any of the 3 possible approaches can be catastrophic when there's no consistency. And depending on the reviewer, they may be asked to do a different thing in different PRs because of different reviewers

And I'm sure many more problems and ancillary issues that arise from a situation like this.

**Comment by jasonwbarnett** [comment]
@jaymzh Regarding the reviewer not knowing how it was manipulated is super interesting, given I naively assumed no one would manually edit a `Gemfile.lock` 🤣  -- but I definitely see the problem here (in terms of enforcement and ownership of reviewing and merging PRs). At the very least it seems like you could tactically add some PR review principles around this process:

1. The author of the PR MUST present in their method of change with steps on how to re-produce
2. The PR reviewer MUST validate that the re-production steps produces the same `Gemfile.lock`.
3. No one can modify the `Gemfile.lock` by hand, unless there is literally no other way. I don't know if a valid use case ever exists for manually modifying the `Gemfile.lock` by hand, but I would assume there are some nasty edge cases where it might be valuable. At the very least, it should be documented that manually modifying the `Gemfile.lock` by hand is a last resort.

Before digging into how the `Gemfile.lock` is to be updated, I think it's probably valuable to document when updates need to occur. I will list of few, but hopefully together we can get a full list of use cases and then based on those suggest strategies/approaches for each. Some may even have overlap.

1. Bug in a dependent library.
2. Security vulnerability in a dependent library.
3. New features, either in 1st part or 3rd dependencies.
4. Ruby version updates that require 1st part or 3rd dependency updates.

What else am I missing?

**Comment by Stromweld** [comment]
@jasonwbarnett 3 there is not very easy to track when you take into account the number of gems. I also think there should be a more robust like maybe once a month full update of all gems as I've found it easier to keep up with and try to stay close to latest releases helps when a breakage is found, then it's a lot less changes to go through to figure out how to fix. Depending on the amount of work needed for the fix a quick PR can be made or pin to previous working version with an issue opened to address the issue with the latest version. As mentioned before it also helps to avoid bugs if they are fixed before we run into it.

**Comment by Stromweld** [comment]
keeping with concept of CI the more frequent the schedule, the less gem changes will come up and thus builds with smaller changes will be easier to diagnose and fix.

**Comment by jasonwbarnett** [comment]
@Stromweld I'm 100% in agreement with some sort of regular cadence 👍  -- The more frequent the updates and the more reliable the test suite, it should make it far easier to understand issues if/when they arise as a result of a `Gemfile.lock` update.

**Comment by Stromweld** [comment]
Sorry that 3 the other one on when updates need to occur. I agree with the 3 principals. No. 3 at the end where you mention

> New features, either in 1st part or 3rd dependencies.

This is what I was referring to about it being hard to track new gem feature update in 1st and 3rd party dependencies due to number of deps.

**Comment by ramereth** [comment]
> keeping with concept of CI the more frequent the schedule, the less gem changes will come up and thus builds with smaller changes will be easier to diagnose and fix.

Yes I agree this the ideal long term solution. To do that, we need to do the following:

- Get the current state as current as possible
- Get CI automation in place to do frequent (weekly checks?) of gems via dependabot (or some other automation tool)
- Make sure those get merged in quickly (assuming CI is working)

Of course, this all depends on getting the CI pipeline in a stable state

**Comment by ramereth** [comment]
> I dislike the idea of branching chef-18 as soon as GA comes out. That's a year of new resources, features, etc. that will just never make it to 18. And given that Progress is looking to, at least temporarily, _slow_ the rate of major releases, that would mean new features won't get to users for even longer. `main` branch should be the current stable version until we're ready to start doing work on a new version.

Good point.

> I like the idea of `bundle update` every major version, but only as a stop-gap. We really should be doing these _more_ often, not less - at least in ideally. Otherwise it's like pushing to prod every year - when something breaks, you have no idea what it is. Smaller updates, more often, is The Way(TM).

Yes I completely agree. It needs to happen more often.

**Comment by jaymzh** [comment]
This is done.

**Comment by Stromweld** [comment]
Is there any documentation to link to for the final policy is?

**Comment by jaymzh** [comment]
Yes: https://github.com/chef/chef/pull/13962

**Comment by jaymzh** [comment]
or more usefully: https://github.com/chef/chef/blob/main/CONTRIBUTING.md#gem-maintenance
