### ISSUE TITLE
Fixing the net-ssh deps

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#13337]
Quick writeup from mtg:

* Upate traincore gemspec to use newer net-ssh
* Update knife gemspec in 18 to use new traincore
* Release knife 18.0.17X to pull in above, plus unreleased but already merged bump of net-ssh dep

That should fix the updater stuff on 18

Then do the same for 17, which should then also allow https://github.com/chef/chef/pull/13332 to get merged.

Then... maybe... do the same for 16?

CC @PrajaktaPurohit and @Stromweld and @tpowell-progress

**Comment by Stromweld** [comment]
PR #13338 updated chef.gemspec and knife.gemspec to use train-core 3.10.7 with the updated dependencies to allow net-ssh 7.x with the ssh fix for newer Linux OSs. The same update is added to #13332 to backport these changes to chef-17 to allow net-ssh 7.x. Due to train-core being restricted to 3.2.x it didn't have the dependencies to allow net-ssh 7.x and thus after our previous manual update of the Gemfile.lock for net-ssh 7.x were being reverted to net-ssh 6.x when running `bundler upgrade`.

Release of knife 18.0.179+ and chef-client 18.0.179+ will have the updated gems for net-ssh 7.0.1.

**Comment by jaymzh** [comment]
@Stromweld - this is done now, right?

**Comment by Stromweld** [comment]
correct
