### ISSUE TITLE
Regression: Unable to run chef on windows if diffrent users perform chef runs

### ISSUE THREAD

**Issue by floh96** [chef/chef#13402]
## Description

We are runinning chef in local mode on windows with 2 diffrent users.
We are performing one chef run as system user and a second chef run with the current logged in user wich is a user without admin rights.
The problem is that chef is encrypting the client certificate with user 1 and user 2 can not decrypt the Secure-String wich was created by user 1.
This is working on chef version 17.10.0.

## Chef Version

Chef Infra Client: 18.0.185

## Platform Version

Microsoft Windows [Version 10.0.19044.2251]

## Replication Case
Run chef in local mode as user 1 on windows.
Create user 2 and try to run chef in local mode.
Chef fails to run with the stacktrace below.

## Stacktrace

```
Generated at 2022-12-06 14:16:14 +0100
ChefPowerShell::PowerShellExceptions::PowerShellCommandFailed: Unexpected exit in PowerShell command: ["ConvertTo-SecureString: Key not valid for use in specified state.\r\n\nAt line:1 char:515\r\n+ ... e340283997ac58324acb50c492e42a3242f20fec1eb\" | ConvertTo-SecureString\r\n+                                                    ~~~~~~~~~~~~~~~~~~~~~~", ": Exception calling \"SecureStringToBSTR\" with \"1\" argument(s): \"Value cannot be null.\r\nParameter name: s\"\nAt line:2 char:1\r\n+ $string = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"]
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-powershell-1.0.13/lib/chef-powershell/powershell.rb:63:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-powershell-1.0.13/lib/chef-powershell/powershell_exec.rb:128:in `powershell_exec!'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:215:in `decrypt_pfx_pass'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:177:in `block in get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:175:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:175:in `get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:222:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:98:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:140:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http/authenticator.rb:45:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:104:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/http.rb:103:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/server_api.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:393:in `rest'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185-x64-mingw-ucrt/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.0.185/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:32:in `load'
C:/opscode/chef/embedded/bin/chef-client:32:in `<main>'
```

**Comment by jaymzh** [comment]
Moving over from what I typed in #13407

---

OK this is a bit more complicated than it looks. We discussed this at length in the PR review meeting this week and this is my attempt to sum up the conclusions.

Background: We write keys to the registry instead of the filesystem now (as of 18)

It looks like from the use case that you have two runs, that share the same key. Having two seperate runs if fine, but having them hare a key is a dangerous way to have two separate runs on the same system (and probably not supportable and never intended) - I'll talk about that below, but... Even in 17 this would only work in the SYSTEM chef run ran first to create the key, and that's (I believe) true here too - if the SYSTEM run ran first, the key should be readable by the non-system users. You're failing to write, not read, and back in the 17 (filesystem) days, the non-admin user wouldn't have been able to write to the chef directory either (without permission hacking).

To have two separate runs on the same system, they should have separate `nodename`s and (presumably) separate runlists, which probably means separate config dirs. Separate `nodename`s imply separate keys. In the filesystem days throwing two separate config dirs at it, would Just Work(TM) - you'd have different places to write keys, probably different log directories, etc. But now, that doesn't work anymore... because of the registry.

Which leads to this PR. This PR isn't the right fix - at the very least it'll break existing users who will fail to find their keys. We probably need a configuration flag like `--auth-key-registry-type [MACHINE|USER]`. For system runs, you can leave it off and have it default to `MACHINE`. For user runs, you could pass in `--auth-key-registry-type USER`, and that users would get their own key in their own user key.

At that point, the supportable way to do what you're doing is to have two separate runs, one with nodename of the hostname or wahtever you use today and then one of "#{hostname}-#{username}" (`$HOSTNAME-Berater` in this case), with two separate configs, the latter of which specifies in its config file `auth_key_registry_type USER`. This would:

1. Ensure separate runlists on the server
2. Ensure separate stats on the server
3. Ensure ordering of chef runs does not matter, ever

In the short-term, it seems like making sure your system-level chef run happens first should be a temporary work around (I think, but I"m guessing a lot about your environment, and I'm not a Windows expert).

**Comment by floh96** [comment]
@jaymzh @johnmccrae thanks for discussing this issue, I have some questions regarding your proposal:

> Which leads to this PR. This PR isn't the right fix - at the very least it'll break existing users who will fail to find their keys. We probably need a configuration flag like `--auth-key-registry-type [MACHINE|USER]`. For system runs, you can leave it off and have it default to `MACHINE`. For user runs, you could pass in `--auth-key-registry-type USER`, and that users would get their own key in their own user key.

See my comment below in my opinion it is never correct to save the registry key in _HKEY_LOCAL_MACHINE_ because the key is user specific and can only be decrypted by the same user wich encrypted the key. For this reason, I think that the key should always be saved under _HKEY_CURRENT_USER_.

> In the short-term, it seems like making sure your system-level chef run happens first should be a temporary work around (I think, but I"m guessing a lot about your environment, and I'm not a Windows expert).

This is what I tried first, see issue description unfortunately this is also not working  and I'm getting the stactrace from the issue description. The relevant line is 
`ChefPowerShell::PowerShellExceptions::PowerShellCommandFailed: Unexpected exit in PowerShell command: ["ConvertTo-SecureString: Key not valid for use in specified state.`
This error occurs because strings that were encrypted with ConvertTo-SecureString can only be decrypted from the same Windows user.
About our enviroment we are using chef in local mode on the machines without a chef server.

If you have any questions or need more information just ask!

**Comment by jaymzh** [comment]
@floh96 - I hear you. However, Chef is - by default - designed to always be run by `SYSTEM`. Hence it makes sense for the key to be in `HKEY_LOCAL_MACHINE`. The `node` object makes to a _machine_, not a user.  It is assumed that Chef will always have administrative privileges. Having Chef run without admin privileges is possible with some careful work, but doing so while sharing a key with the system-level run is for sure not supported and worked only as an accident.

**Comment by floh96** [comment]
@jaymzh ok are you planing to implement the proposed solution in the next few months or would you rely on an external contribution?
Unfortunately, I am not a ruby expert and would not be able to implement it.

**Comment by jaymzh** [comment]
I'm an external maintainer, so I can't speak for the allocation of Progress resources. However, my understanding from the meeting was that given that a use-case was broken here, there was priority around getting it fixed.

**Comment by jaymzh** [comment]
@PrajaktaPurohit might be able to speak to that

**Comment by takesson** [comment]
Just want to mention the ```-o``` flag which is also quite challenging to use in Chef 18 due to this this issue.

We are using ```-o``` for some maintenance / recovery tasks. Yes, only on Windows...

**Comment by phromo** [comment]
Just want to drop a note that we hit this first thing when upgrading to chef 18. Chef runs as a privileged 'automationuser', first it start as localhost\automationuser, then it joins the domain and proceeds to run as domain\automationuser (running as o domain user simplifies access to a lot of other things). This means as soon as the machine joins the domain the key stored in the registry is now invalid => this error.

**Comment by johnmccrae** [comment]
Thanks all. We're actively working on this now. Stay tuned

**Comment by phromo** [comment]
I'm been trying to workaround this issue. Exclusively using chef-client in "solo" mode (-z) using exported chefrepos, so I really really don't care about the security when communicating with `127.0.0.1`

tried setting config options like
```
client_key               "c:/snakeoil.pem"
ssl_verify_mode          :verify_none
verify_api_cert          false
local_key_generation     false
```
but nothing seems to prevent chef client from trying to read the key from the registry anyway. Looking at https://github.com/chef/chef/blob/main/lib/chef/http/authenticator.rb#L139 I think one problem is that it ignores the user-configured key completely and always use the registry one? this seems like a strange default/non-overridable behaviour to me.

I've started deleting the generated stuff before every run:
```
reg delete HKLM\Software\Progress\Authentication /f /reg:64
```

Is a viable workaround for now. But would appreciate an easier way to turn this new behaviour off for "chef solo" runs.

**Comment by takesson** [comment]
I am also using chef zero extensively. I have reverted to Chef 17 for Windows.

**Comment by Stromweld** [comment]
This may also have implications with chef-cli in the latest chef-workstation release with chef-client 18.0.185 and this issue that has come up for windows users https://github.com/chef/chef-cli/issues/218

**Comment by floh96** [comment]
Verified that the issue was fixed with https://github.com/chef/chef/releases/tag/v18.2.7 closing
