### ISSUE TITLE
Enable roles in subdirectories for chef-zero.

### ISSUE THREAD

**Issue by mcquin** [chef/chef#1499]
Chef-solo now enables storing roles in subdirectories, we should make sure chef-zero can do the same.

Tickets for reference: https://tickets.opscode.com/browse/CHEF-4193, https://github.com/opscode/chef/pull/759

**Comment by lamont-granquist** [comment]
In light of the RFC to deprecate chef-solo with chef-client -z this is fairly important

**Comment by lamont-granquist** [comment]
Think I'm going to close this.  #759 really should not have been accepted/merged, and the problem here is that the chef-server has no notion of subdirectories of roles, so that means that an upload/download cycle will lose that information, which is going to make local-mode/chef-zero very problematic since the files in the subdirs will be uploaded to the chef-zero server and will appear in the non-subdir location.
