### ISSUE TITLE
Chef should be installable to a different directory on Windows.

### ISSUE THREAD

**Issue by sersut** [chef/chef#1512]
https://tickets.opscode.com/browse/CHEF-4857

Currently due to hardcoded paths Chef Client can not be installed to a different directory on Windows. 

This issue is somewhat unfixable at this point because installing Chef Client into a directory with spaces doesn't work some of the gems with native bindings that doesn't have the right quoting in their Makefile. Since we don't know which gems are impacted by this issue, we should make the fix on our end to make Chef installable to a different directory and then find out what are the important gems that have the native binding issue.

@adamedx / @btm I think we should prioritize this. 

Related to: https://github.com/opscode/chef-dk/issues/68

**Comment by tknerr** [comment]
Just checked. As of ChefDK 0.3.6:

 * :+1:  the paths in the `<chefdk>/bin/*` files all look good now. There's a reference to "#!C:/opscode/chefdk/embedded/bin/ruby.exe" left in the header of the ruby files, but that's not being used interpreted by `cmd` I guess
 * :-1:  in `<chefdk>/embedded/lib/ruby/gems/2.0.0/bin/*.bat` the .bat files still contain `@"C:\opscode\chefdk\embedded\bin\ruby.exe" "%~dpn0" %*`

I don't know whether the latter executables are used at all though...

**Comment by btm** [comment]
@danielsdeleo @jaym @adamedx: Can we close this as fixed by https://github.com/chef/appbundler/pull/5?

I just installed 12.7.2 to d:\opscode\chef\chef (hah!) and it seems to work fine.

neither `bin/*.bat` or `embedded/bin/*.bat` have hardcoded paths (although some of the non-bat ruby files do).

@mwrock fixed a bug where the chef-client service on Windows was hardcoded in FLOW-205 around 2016-01-15. Looks like we can close https://github.com/chef/chef/issues/3688 now.

ECO-162 + ECO-164 were both relevant and closed on 2016-01-14 and 2016-01-15 but there's no comment as to the state.

**Comment by jaym** [comment]
@btm try installing a gem that compiles a native extension. IIRC, there were issues with that

**Comment by adamedx** [comment]
@btm, what about problems resolving paths such as `/etc/funstuff` given that `/`is ambiguous on Windows because it lacks a drive leter? We wtill need to do work to force `/` to always be interpreted a particular way (e.g. as the system drive) or disallow it altogether (since it really isn't a valid path).

@jaym, I'm not aware of native gem issues with this, though there are definitely challenges if any installation directories for Chef have a space in them.

**Comment by tknerr** [comment]
Hey everybody, the hardcoded paths in the non *.bat gem binaries cause
issues if you use Cygwin / git-bash. So I usually regex-replace them with
their relative path equivalents to prevent this when installing chefdk to a
non-standard dir. Would be sweeeeeeeet if this would come fixed
out-of-the-box :)
Am 23.02.2016 1:07 vorm. schrieb "Adam Edwards" <notifications@github.com>:

**Comment by stuartpreston** [comment]
I'm going to close this out as I think the issues are well-understood.

Today it is possible to select a different target folder for Chef, ChefDK and other packages using the Windows installer, the binstubs do still hardcode the path which is something we could sort out in the packaging process I think.  Tracking this in #7459.

If you choose to install into a folder that contains a space, various tools will fail, first of all gems that require native compilation will not find the .h files correctly, the second is that our ecosystem has built tools that rely on the installation folder being on the SystemDrive under /opscode. Third, some custom script will probably fail because they need to be quoted.

RubyInstaller itself has stated not to install into ProgramFiles.  (https://github.com/oneclick/rubyinstaller/wiki/faq#q-should-i-install-to-cprogram-files)
