### ISSUE TITLE
Lazy attributes evaluation context

### ISSUE THREAD

**Issue by KrilYura** [chef/chef#1536]
### Scenario:
I'm trying to lazy evaluate branch for deployment.

### Steps to Reproduce:
```ruby
deploy path do
  repository 'git@github.com:user/repo.git'
  revision lazy { `git ls-remote --heads git@github.com:user/repo.git`.lines.first }
  user "deploy"
end
```
Only user 'deploy' has access to private repository. But I can't specify user for lazy evaluation.

### Expected Result:
Ability to provide some context(user, group, environment, etc) for lazy evaluation.

### Actual Result:
Access denied.

**Comment by lamont-granquist** [comment]
Adding user and env args to lazy doesn't make a lot of sense because it is not responsible for executing the shell command.  The backticks that are being used in this example are responsible for doing the shell command, and this is a limitation of using backticks.  To fix this, use shell_out or another library function which supports shelling out and changing the user and setting the environment.
