### ISSUE TITLE
support persistent HTTP connections in chef-client

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#1617]
This came from ChefCo's internal feature request board. I think it's a useful feature to have, and is smaller than a roadmap item, so we should do it.

Right now Chef Client frequently closes and opens HTTP connections to the Chef server. This causes performance problems for some customers, as they have some high-latency links and this overhead of establishing and tearing down HTTP connections slows down their client runs considerably.

**Comment by smurawski** [comment]
@lamont-granquist Just want to get this back on your radar.

**Comment by lamont-granquist** [comment]
yeah #1792 is still in my backlog, hopefully now after i'm moved i'll get to it soonish =)

**Comment by mfischer-zd** [comment]
+1

**Comment by mfischer-zd** [comment]
See also CHEF-4283, which is even older.

**Comment by charlesjohnson** [comment]
:+1: as this came up in a customer conversation this week.

**Comment by mbrossard** [comment]
[CHEF-4423](https://tickets.opscode.com/browse/CHEF-4423) had priority 'major'. Would it be possible to bump it here to 'Accepted Major' as well?
Cookbook synchronization is probably the number one performance issue we encounter with chef, and this is supposed to be the solution.

**Comment by coderanger** [comment]
@mbrossard "Accepted Major" means it's accepted for the next major release (i.e. Chef 13) because it would be a breaking change. We don't use priorities on here because they don't get looked at anyway.

**Comment by mbrossard** [comment]
@coderanger. Ok, thank you for pointing out the difference.

How can the priority be raised on this issue? There was an example in #3803 showing that the problem doesn't affect only high latency links. We have a similar experience where on Windows the cookbook synchronization takes about 50% of the chef-client run.

Also I don't know if this is the right issue to discuss this. I didn't want to open a duplicate issue and this one mentioned CHEF-4423, but it assumes that persistent connection is going to fix cookbook synchronization performance. Looking at #1792 it would improve things.

I'd wager that batching requests (doing many files instead of one by one) would improve things even more, but that would most likely require an API extension.

**Comment by coderanger** [comment]
@mbrossard If you are a Chef Software Inc customer you can talk to your sales rep, otherwise you can write a patch and submit a Pull Request. We don't really have priorities, just patches or not-patches. You can use the old, experimental patch as a starting point but I'm not sure that one ever really did what we wanted (which is part of why it got shelved).

**Comment by lamont-granquist** [comment]
#5151
