### ISSUE TITLE
knife commands in Windows can have unexpected results because of argument globbing

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#1687]
I ported this over from [CHEF-2486](https://tickets.opscode.com/browse/CHEF-2486)

This is enough of a delight blocker issue that I felt we should move it here. The real fix is probably in mingw and/or conversation with MSFT about the purported MSVC bug, but we would need someone from engineering to chase that down.

The problem is the quotes around the run_list are not preventing globbing of file/directory names in the current working directory.

For example, if your current working directory is a chef-repo with a subdirectory named `roles` then setting a node's run_list to `"role[webserver]"` acts as a glob which matches the name of the `roles` subdirectory.

Reference: http://sourceforge.net/p/mingw/bugs/1621/

There are a few workarounds documented in the ticket, but they are non-obvious and users will get frustrated long before they find them.

When using Powershell you have to use triple single quotes:

```
knife node run_list set test-node '''role[ssssssomething]'''
```

When using the Command prompt you have to use single quotes:

```
knife node run_list set test-node 'role[ssssssomething]'
```

**Comment by jeremiahsnapp** [comment]
Here's the workaround from CHEF-2486

When using Poweshell you have to use single quotes and escape them with backticks:

```
knife node run_list set test-node `'role[ssssssomething]`'
```

When using the Command prompt you have to use single quotes:

```
knife node run_list set test-node 'role[ssssssomething]'
```

**Comment by jeremiahsnapp** [comment]
The problem is the arguments of the knife command are seen by the shell (Powershell or command prompt) as a [string with wildcard characters](https://msdn.microsoft.com/en-us/library/aa717088%28v=vs.85%29.aspx). So the shell does its job and finds files that match the pattern. This is often referred to as [globbing](http://en.wikipedia.org/wiki/Glob_%28programming%29).

The typical way to prevent globbing is to surround the string with single quotes to prevent the shell from interpreting the string as a wildcard pattern. This works when using knife in the command prompt but it does not work when using knife in Powershell.

It seems that, for some reason, when using knife in Powershell the single quotes get eaten by knife leaving the bare string available for interpretation as a pattern internally. **The way to prevent this in Powershell is to use triple single quotes.**

Do the following to reproduce the problem and show the solution.

Create a few directories that will match the wildcard pattern `recipe[iptables]`

```
mkdir recipes
mkdir recipep
mkdir recipel
```

Run the following in the command prompt.

```
C:\Users\vagrant>knife exec -E 'puts ARGV' recipe[iptables]
WARNING: No knife configuration file found
exec
-E
puts ARGV
recipel
recipep
recipes
```

Run the same command in Powershell.

```
PS C:\Users\vagrant> knife exec -E 'puts ARGV' recipe[iptables]
WARNING: No knife configuration file found
exec
-E
puts ARGV
recipel
recipep
recipes
```

You can see how knife is not getting the `recipe[iptables]` argument the way we'd like. Instead knife is getting a list of files/directories that match the wildcard pattern `recipe[iptables]`.

To avoid this use single quotes in the command prompt.

```
C:\Users\vagrant>knife exec -E 'puts ARGV' 'recipe[iptables]'
WARNING: No knife configuration file found
exec
-E
puts ARGV
recipe[iptables]
```

And use triple single quotes in Powershell.

```
PS C:\Users\vagrant> knife exec -E 'puts ARGV' '''recipe[iptables]'''
WARNING: No knife configuration file found
exec
-E
puts ARGV
recipe[iptables]
```

**Comment by smurawski** [comment]
If you have PS 3 or greater, you can use the --% operator to tell PowerShell not to parse the arguments.

e.g. 
```
knife --% exec -E 'puts ARGV' 'recipe[iptables]'
```

**Comment by ksubrama** [comment]
I managed to track down the source of the globbing.  It's not is MSVCRT or in msys.  It's right here: https://github.com/ruby/ruby/blob/trunk/win32/win32.c#L1582

Ruby (and when built on Windows) does special command line parsing that is neither based on MSVCRT nor on CommandLineToArgvW.  It bypasses all that and applies special semantic differences to "" vs ''.  Powershell (being a shell and all) reasonably assumes that it is the one that's supposed to be interpreting quotes and handling escapes and all that good jazz.  Hence the triple '''.  That forces powershell to send a quote character on the command line so that ruby can then stop globbing on [].

One way to fix this would be to make a thin powershell cmdlet wrappers that completely defeat ruby's attempts to glob things by always quoting arguments (such as https://github.com/chef/chef/pull/3339).  This will make things "pure" but it will affect things like "knife upload cookbooks\*" which should never have worked on Windows in the first place.  If globbing is still needed, it can be done explicitly using the powershell pipeline...

ls thingsthatyouwant | %{ knife upload $_ }

**Comment by smurawski** [comment]
@ksubrama or just 
```
knife upload cookbooks
```
?

**Comment by ksubrama** [comment]
https://github.com/chef/chef/pull/3339

**Comment by juliandunn** [comment]
:cake:

**Comment by madisonjsmith** [comment]
You can also use back ticks:
``
knife exec -E `'puts ARGV`' `'recipe[iptables]`'
``

But you really should be using the ChefDK which Imports the chef module
