### ISSUE TITLE
http_request resource :get does not return body of the request.

### ISSUE THREAD

**Issue by vinyar** [chef/chef#1729]
Current implementation of http_request resource does not return the body of the request.

In LWRP or library implementation, the existing methods cant be leveraged without either monkey patching or duplicating functionality to actually get the body.

Expectation:
  action_get, and other methods, should return the body.

Simple Example (should be implemented with all resources):
  https://github.com/vinyar/chef/commit/d5d568711cef0ec27eb5951109a8ef3af5206fe3

**Comment by rthideaway** [comment]
Hi there. Does it mean, it's not possible with chef to store response of http_request to file? Or to some variable which will be then used as an input variable for template file?

**Comment by danielsdeleo** [comment]
> it's not possible with chef to store response of http_request to file

That is correct. Chef resources are only really capable of communicating with other resources via notifies/subscribes. You have to code the http request on your own, perhaps best done with a custom resource.

**Comment by rthideaway** [comment]
Well, I can write my own resource of course, but don't get me wrong (maybe I still don't get some Chef basics), what is the point of having http_request resource without having possibility of using its response. Let's say I am provisioning server based on the GET responses of some REST endpoints. Let's say one particular endpoint gives me "true" or "false" and based on this I install or uninstall some package on my server. Isn't a bit "weird" of having natural http_request resource inside Chef without possiblity to use its response? Because my resource will be very lame comparing what http_request.rb has already inside.

**Comment by danielsdeleo** [comment]
The main point of it now is that you can do a conditional GET and have that notify another resource, or you could notify it from some other resource to do a PUT/POST/DELETE. I agree your use case could be easier, though whether that is best modeled as a resource is another thing to think about.
