### ISSUE TITLE
chef-service-manager: Should it be run as Administrator?

### ISSUE THREAD

**Issue by docwhat** [chef/chef#1777]
Currently, the `chef-service-manager -a install` creates a service that runs as the LOCAL_SERVICE user.

This can cause problems with things like environment variables, etc. Especially if `chef-client` is ever run directly by the administrator.

Should the service run as Administrator? Or should chef-client refuse to run unless as LOCAL_SERVICE?

To see this you can try running `chef-client` via `cmd` as Adminstrator vs. the Service and then check it with:

```
knife search os:windows -a current_user
```

Ciao!

**Comment by eranlevinzon** [comment]
Hi adam, we have encountered the same issue now with having the local account being used by chef following to having a server bootstrapped whilst using Azure knife. Just to clarify, is there a way to pass any parameters to knife azure so that it will bootsrap using the right service account, as without it we have chef recipes failing to perform actions that require more access to the domain and things like importing certificates fail for instance.

**Comment by adamedx** [comment]
@eranlevinzon, I think to understand the relevance of this particular issue to what you're seeing, we'll need answers to some of the questions below. In general, you can configure any service, including chef-client, to run as an arbitrary account using the `service` resource. You'd need to specify that in a recipe to make it work, and potentially restart the service after the configuration.

Here are a few additional questions that might clarify things:

* What command line (minus password of course) are you using?
* What response do you get?
* What versions of knife-azure and knife-windows are on the workstation from which you are initiating the bootstrap?
* What version of chef-client is being used on the node?
