### ISSUE TITLE
'knife winrm' doesn't support hosts with underscore '_' in name

### ISSUE THREAD

**Issue by Valiev** [chef/chef#1858]
Here's the example:
$ knife winrm 'host_name.mydomain.com' hostname -m -x 'my_user'
WARNING: Could not load IOV methods. Check your GSSAPI C library for an update
WARNING: Could not load AEAD methods. Check your GSSAPI C library for an update
Enter your password:
ERROR: URI::InvalidURIError: the scheme http does not accept registry part: host_name.mydomain.com:5985 (or bad hostname?)

**Comment by Tensibai** [comment]
It's more your naming convention not compliant with RFC 2396 and windows allowing hostnames with an `_` in them (inheritance from SMB protocol) which is not allowed by RFC (alphanumeric chars and `-` only in hostnames).


For the information the root cause is in the [URI class](http://ruby-doc.org//stdlib-1.9.3/libdoc/uri/rdoc/URI/Parser.html#method-i-parse) which indeed resect the RFC.

```console
 #>URI.parse("http://host_name.mydomain.com")
URI::InvalidURIError: the scheme http does not accept registry part: host_name.mydomain.com (or bad hostname?)

RFC2396 states:
>  The host is a domain name of a network host, or its IPv4 address as a
>   set of four decimal digit groups separated by ".".  Literal IPv6
>   addresses are not supported.

And the accoding naming allowed:
>  hostname      = *( domainlabel "." ) toplabel [ "." ]
>  domainlabel   = alphanum | alphanum *( alphanum | "-" ) alphanum
>  toplabel      = alpha | alpha *( alphanum | "-" ) alphanum

[More ref here](http://tools.ietf.org/html/rfc2396#section-3)

Voting for 'not a bug'
