### ISSUE TITLE
Attributes don't Deep Merge at the same precedence level

### ISSUE THREAD

**Issue by kcd83** [chef/chef#1911]
In one recipe the merge behaves as expected

```
node.default['attribute_hash'] = {'a' => 'default','b' => 'default'}
node.override['attribute_hash'] = {'b' => 'override','c' => 'override'}
log "before #{node['attribute_hash']}"
```

But if we are foolish in another recipe
```
node.default['attribute_hash'] = {'b' => 'default_again','c' => 'default_again', 'd' => 'default_again'}
log "after #{node['attribute_hash']}"
```

We silently lose 'a' because the original recipe default has been forgotten
```
  * log[before {"a"=>"default", "b"=>"override", "c"=>"override"}] action write
  * log[after {"b"=>"override", "c"=>"override", "d"=>"default_again"}] action write
```

If this it is not easy to resolve can there be a warning added to http://docs.getchef.com/essentials_node_object_deep_merge.html

**Comment by thommay** [comment]
We're not comfortable with changing the current behaviour, but would love to accept a pull request documenting this against the chef/chef-docs project.

**Comment by dansteen** [comment]
So, an interesting effect that I have noticed is that while the above is true, that if you do this:

node.default['attribute_hash'] = {'a' => 'default','b' => 'default'}

in one cookbook/recipe, and this:

node.default['attribute_hash'] = {'b' => 'default_again','c' => 'default_again', 'd' => 'default_again'}

in another cookbook/recipe you will wind up losing 'a' out of your hash.  The same is not true if you do this in one cookbook/recipe:

node.default['attribute_hash']['a'] = 'default'
node.default['attribute_hash']['b'] = 'default'

and this in another:

node.default['attribute_hash']['b'] = 'default_again'
node.default['attribute_hash']['c'] = 'default_again'
node.default['attribute_hash']['d'] = 'default_again'

You will not lose 'a'.  This seems obvious in context, since you did not touch node['attribute_hash']['a'] at all in the other recipe.  However, if you assume that adding hashes is the same as directly adding a node element, this can be very confusing.
