### ISSUE TITLE
Reboot_pending? does not detect reboots from the windows_reboot resource

### ISSUE THREAD

**Issue by Tech356** [chef/chef#1925]
### Version:
Chef 11.14.6

### Environment:
Windows 7 x64
windows cookbook 1.34.0

### Scenario:
Detect a pending reboot requested from the `windows_reboot` resource. 

### Steps to Reproduce:
    windows_reboot 'test' do
      action :nothing
      reason 'rebooting for test'
      timeout 60
    end

    log "Is reboot pending first: #{reboot_pending?}"
    
    execute "dir" do
        notifies :request, 'windows_reboot[test]'
    end

    log "Is reboot pending second: #{reboot_pending?}"

    execute "dir" do
        notifies :request, 'windows_reboot[test]', :immediately
    end

    log "Is reboot pending third: #{reboot_pending?}"

### Expected Result:
I would expect `reboot_pending?` to return `true` after a reboot has been requested with the `windows_reboot` resource.

### Actual Result:
In a recipe, if a reboot is requested using `windows_reboot`, subsequent calls to `reboot_pending?` return `false`.

**Comment by adamedx** [comment]
This should not be an issue with Chef 12, which has reboot support built into core Chef (not a cookbook) in the following places:

[reboot_pending? DSL feature](https://docs.chef.io/dsl_recipe.html)
The [reboot resource](https://docs.chef.io/resource_reboot.html)

Closing for now since the implementation of those components should cover this scenario.
