### ISSUE TITLE
Chef Client logs expected 404 error with no details

### ISSUE THREAD

**Issue by Tech356** [chef/chef#1931]
### Version:

Chef Client 11.14.6
Chef Server 11.1.4
### Environment:

Windows 7 x64
### Scenario:

Each chef run using the open source server logs a 404 error.

```
INFO: HTTP Request Returned 404 Object Not Found: 
DEBUG: Reporting error starting run. URL: reports/nodes/node_name/runs Received 404. Disabling reporting for run.
```

This 404 is caused by `../node_name/runs` not being available on the open source server. This is an understandable way to detect if reporting should be enabled or not, but the log message should be a bit more informative.

```
INFO: Open Source Server detected. Disabling reporting for run.
```

As it currently stands, the message looks like something is going wrong and it takes some time to figure out that the 404 is expected behavior.  

Ticket CHEF-4737 talks about the same issue: https://tickets.opscode.com/browse/CHEF-4737

**Comment by jfbibeau** [comment]
@lamont-granquist Continuing #5172 over here. It turns out that the log message is not coming from here (https://github.com/chef/chef/blob/c1a389c2a8452e9b796aa1d34c4d9e51f4af30c7/lib/chef/resource_reporter.rb#L148). If you check that code path, the error is a 404, so it properly gets logged at DEBUG level.

The problem seems to be that the generic rest_client resource used to make the call appears to be the one that logs the error at INFO level. I think the `log_failed_request` method is the culprit, but I can't find it in the code... It would also be hard to change that one from INFO to DEBUG as that would impact anything using it... 

What would you suggest?

**Comment by lamont-granquist** [comment]
ah right, you just rediscovered why nobody has done anything about it yet.

log_failed_request is in chef/http.rb but that would change the log level of debugging output for all Chef::HTTP consumers.

**Comment by lamont-granquist** [comment]
maybe you could add an accessor on the Chef::HTTP for the default log level for errors and set that to :info by default in the class -- and then override that in the resource reporter only for that call?
