### ISSUE TITLE
Chef Client ignores config option when executing search

### ISSUE THREAD

**Issue by martinisoft** [chef/chef#1932]
When running chef-client and providing a `--config` option to a client configuration, the chef-client will also take up the settings from /etc/chef/client.rb and override the `--config` options when executing a search.

I was able to uncover this by using the [chef-client cookbook](https://github.com/opscode-cookbooks/chef-client) and changing the Chef Server URL. Upon executing a search, it would run the search against the Chef Server URL in the /etc/chef/client.rb instead of the provided one in /tmp/kitchen when using Test Kitchen.

**Comment by lamont-granquist** [comment]
I don't think this is actually fixable.  If you enforce in your chef-client cookbook that your chef_server_url points at hosted, then chef-client will dutifully change your chef_server_url on the host you are running on and reload its config.  That is useful behavior for settings like no_lazy_load and other client settings you might enforce with the chef-client cookbook.  When you use it to enforce your chef_server_url and you run that under test-kitchen and chef-zero then it points your chef_server_url away from the chef-zero instance and to hosted which explodes.

I don't see a solution to the problem here, and your title is misleading.  If anything the chef-client cookbook could be modified to try to detect running under chef-zero and then not drop the chef_server_url attribute.  It certainly isn't a bug in chef-client, and the fact that the subsequent search hit fails is just because its the next API request your chef-client run happened to make and the bug isn't in chef-client's search API.

So, my advice is to just not use that setting.  You can also open an issue against the chef-client cookbook, but I'm not sure we have a way to determine running under chef-zero or test-kitchen.
