### ISSUE TITLE
Validate Functionality of Providers within Group Resource

### ISSUE THREAD

**Issue by afiune** [chef/chef#1935]
There has been a concern from one of the clients I am working with, that either there is a bug or a bad documentation about the `Providers` within the `Group` Resource. 

I have opened an issue in `chef-docs` to start the conversation about this topic:

https://github.com/opscode/chef-docs/issues/329

The code that the customer is using is this:

```
            13: group node['mq-server']['group'] do
            14:   gid node['mq-server']['gid']
            15:   provider Chef::Provider::Group::Groupadd
            16:   action :create
            17: end
```

And the error he is getting is:

```
 Chef::Exceptions::Group
  -----------------------
  you must override set_members in #<Chef::Provider::Group::Groupadd:0x0000000374c9c8>
```

For more output of the error look this gist: https://gist.github.com/afiune/5e49f53f20e203df9d82

**Comment by quinn286** [comment]
has this been resolved? seeing the same thing on rhel6.7 and chef12.7.2

**Comment by lamont-granquist** [comment]
```
provider Chef::Provider::Group::Groupadd
```

that line is invalid.  the class being referenced there is only used to inherit from.  the aix, gpasswd, suse or usermod group providers are the ones that must be used.

if there's docs somewhere which still have that they are incorrect.

the `provider` line in general should never be used, since it causes errors like this.
