### ISSUE TITLE
CookBook cache on Node

### ISSUE THREAD

**Issue by avinashs433** [chef/chef#2061]
Hi

I am having an issue where there is no 'files' directory in the cookbook cache on a node, when the cookbook is downloaded from the chef server.  The chef server contains the files directory for the respective cookbooks, which is visible on the server webpage.

Chef server version: https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.1.4-1_amd64.deb

Chef client version : Chef 11.16.0

**Comment by lamont-granquist** [comment]
The files and templates in cookbooks in Chef 11 are downloaded lazily by default so that if you haven't hit a cookbook_file or template resource that actually uses the file then you won't see it in the cache.  In Chef 12 the no_lazy_load config flag is on by default so everything will by sync'd up front.

Generally you shouldn't be poking around in the cookbook cache, and should use cookbook_file resources to deploy files from cookbooks, though.

**Comment by avinashs433** [comment]
Thanks this makes sense.
