### ISSUE TITLE
Delayed notifications running after failed chef run can cause broken configuration

### ISSUE THREAD

**Issue by micmac** [chef/chef#2084]
If I generate a config file calling the template's :create action delayed after collecting all the needed parts during the chef run, calling the template after a failed chef run can cause some config parts missing, turning a mostly harmless chef breakage into a potential service outage.

I've created a proof-of-concept fix, creating an additional option :only_on_success for notifications that causes them to not run if there was an exception earlier: https://github.com/micmac/chef/pull/1

**Comment by smurawski** [comment]
@micmac You are welcome to submit a PR addressing this behavior, but this feels more like a workflow solution than a change in code.  This is not something we intend to pick up as a change.  Thanks!

**Comment by lamont-granquist** [comment]
So when you're creating a user with a resource, you should really be asserting the state that you desire, and you can therefore assert the state in the other resources.  Creating a user, then reading the pid (using a converge-time ruby block) then using a lazy attribute on a template is code smell.  In that case you should just select a pid at compile_time somewhere and assert it in both resources.  Unless you've got a more concrete example.

Also since you're using a definition to create a template resource you can hang a not_if/only_if off of the template resource that you are constructing.   In chef 12 if your definition returns the resource then it will correctly get returned in the dsl and you can use the absence of an argument to the definition to create a no-op that will return your resource so you can easily chain notifications/guards/etc off of the resource.

And again, I think the direction you're going is fighting the tool.  If you've got resources creating other resources that is going to end badly.  You want to be using definitions to iteratively create resources.
