### ISSUE TITLE
Clarify the probable cause of tempfile creation failure during cookbook sync

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2171]
Could we make the possible problem here more clear during an exception? 
https://github.com/opscode/chef/blob/master/lib/chef/http.rb#L385

This result from chef-client while trying to sync cookbook files is not very helpful and requires digging to discover the real issue

    Unexpected Error: 
    ----------------- 
    NoMethodError: undefined method `close!' for nil:NilClass

The real problem is almost always going to be

1. /tmp filesystem full/inodes used up. Presents as 

        bash-3.2# touch /tmp/chef-rest20141003-29957-1iayumf.lock 
        touch: cannot touch `/tmp/chef-rest20141003-29957-1iayumf.lock': No space left on device

2. /tmp filesystem read-only

**Comment by wjordan** [comment]
I just got bit by this today, was surprised to see that such a clear, low-risk fix for such an obvious bug has been well-known and discussed for over a year but never yet applied. Would love to see #4579 finally merged so others don't continue getting sidetracked by this. If there's anything else I can do to help, please let me know.

**Comment by lamont-granquist** [comment]
@wjordan patches need spec tests.  getting the code right is usually 5-20% of the difficulty of the problem.  writing tests so that the use case doesn't regress is the other 80-95% of the work.  the easiest way to make sure a bugfix goes into the code is to get us a PR with specs that we can just hit the merge button on.  otherwise, the time necessary to write the spec tests and the severity of the issue get triaged against all the other work that needs to get done, and the impossibility of ever getting the queue of work to get done down to zero.  since this is a bug that just changes one exception to a clearer one its a 'nice to have fix' and without a spec test it'll always be lower priority than other fixes where functionality is broken or where functionality does not exist--until someone like @thommay just gets tired of seeing it in the list of open PRs...

**Comment by wjordan** [comment]
@lamont-granquist @thommay thanks for pushing this through, very much appreciated :heart:
