### ISSUE TITLE
"knife cookbook site install" command is failed.

### ISSUE THREAD

**Issue by morou** [chef/chef#2317]
I tried to install some cookbooks by using "knife cookbook site install" command in git repository that is initialized by "git init --separate-git-dir" command.
Then I got the following error.

> ERROR: The cookbook repo /chef-repo/cookbooks is not a git repository.

Can I avoid this issue?

Reproduce steps.
1. knife solo init chef-repo
2. cd chef-repo
3. git init --separate-git-dir <some path>
4. git add .
5. git commit -a -m "initial"
6. knife cookbook site install yum

**Comment by smurawski** [comment]
I submitted a pull request to deal with a separate git directory.

**Comment by dasgoll** [comment]
I'm still getting this error. Was this fixed?

**Comment by lamont-granquist** [comment]
i'm not sure if this ever got fixed.  `knife cookbook site install` is fairly deprecated, we don't recommend anyone use it, and if its still broken its likely that command will be retired before it gets fixed.

**Comment by nebffa** [comment]
Hey @lamont-granquist , I am quite shocked to read that as your docs really don't reflect it.

https://docs.chef.io/plugin_knife_supermarket.html says `Only use knife supermarket if you are using a Chef 12.12 or earlier. If you are using Chef 12.13 or later, you should use the knife cookbook site commands.` and the https://docs.chef.io/knife_cookbook_site.html docs make no mention that it's fairly deprecated. What should we use instead of `knife cookbook site install`?
