### ISSUE TITLE
knife[:ssh_attribute] in knife.rb seems to be ignored

### ISSUE THREAD

**Issue by tas50** [chef/chef#2325]
### Version:
ChefDK 0.3.2

### Scenario:
I'm attempting to ensure that knife ssh uses fqdn on my AWS nodes by adding knife[:ssh_attribute] = 'fqdn'  to my knife.rb file.

### Steps to Reproduce:
Run knife ssh name:* 'uname' -a fqdn and watch knife use FQDN to connect to the hosts
Add knife[:ssh_attribute] = 'fqdn'  and run knife ssh name:* 'uname' and watch knife ignore the fqdn ssh attribute

### Expected Result:
Knife should SSH to the hosts using FQDN

### Actual Result:
Knife attempts to ssh to public IP on nodes using public IPs aka it ignores the fqdn attribute

**Comment by smurawski** [comment]
Thanks for your thoughts on this @Igorshp  and @willejs and @tas50.  Given @btm's response that this is as designed, I'm closing this issue.

**Comment by lamont-granquist** [comment]
Feels like we really need a smart default here that would guess some priority of IPs and names and would try them until it found one that pinged and worked.

**Comment by btm** [comment]
IIRC, the current behavior is so you can configure an attribute for your local infrastructure in your knife config, and still use cloud instances which know the best configuration option for themselves, enabling you to use multiple clouds and local infrastructure without having to remember the correct attribute for all of them.

```
knife[:ssh_attribute] = "internal_address_of_doom"
```

If you have this configuration for your internal network, we change the default so that a knife config file setting wins over cloud attributes, and you go to use a cloud, you'll have to specify -a every time. 

Another option for that case is having separate knife configs, which doesn't help you and @tas50 in your situation. Which is a valid argument for changing it.

@tas50 why fqdn? is your case like @Igorshp where something else in node[:cloud] would be more appropriate like local_hostname?
