### ISSUE TITLE
knife bootstrap - error installing git-daemon

### ISSUE THREAD

**Issue by ctippur** [chef/chef#2412]
Knife boostrap fails while installing git. Here is the error.

Appreciate any help in this regard.

Chef::Exceptions::Package
 -------------------------
 No version specified, and no candidate version available for git-daemon

 
 Resource Declaration:
---------------------
 # In /var/chef/cache/cookbooks/git/recipes/server.rb
 package 'git-daemon'

**Comment by stevendanna** [comment]
@ctippur Apologies that you never received a response on this.  This appears to be a problem with a particular cookbook you are attempting to use rather than a bug in `knife` or `chef-client`.  If you are still experiencing this problem, many in the Chef community would be happy to help, particular in our IRC channel on freenode and the mailing list.  Is this still an issue for you?  If not, I'll close this bug out.

**Comment by smurawski** [comment]
@ctippur As Steven noted above, this is more of an issue with the cookbook or recipe you are using and the Chef mailing list or IRC channel are more appropriate forums for help with that.
