### ISSUE TITLE
Configurable line ending conversion for template resource

### ISSUE THREAD

**Issue by jarig** [chef/chef#2466]
### Version:

11.12.0
### Environment:

Deployments to Windows OS
### Scenario:

Deploying SVN cached credentials under AppData from the template with UNIX style endings, however resulted template has Windows style endings, and that breaks SVN.
### Steps to Reproduce:

Create template with UNIX style endings and deploy it to the Windows machine.
### Expected Result:

UNIX style endings should be preserved
### Actual Result:

UNIX style endings converted to the Windows ones

I suggest adding additional option to the template resource which will either preserve or convert EOLs.

Related JIRA issue: https://tickets.opscode.com/browse/CHEF-4399

**Comment by lamont-granquist** [comment]
What we need to do here is reinstate an old PR of mine to add a 'binmode' flag to every file resource as part of the massive 11.6.0 file provider refactor, which was backed out in #795

**Comment by btm** [comment]
The history I've gathered:

Starting with #795 we wrote templates based on the platform they were written on, i.e. if they had CRLF in the erb file, they were written with CRLF to disk. If you didn't realize you were uploading all your files from your Windows machine with CRLF though, this caused a problem.

In #906, we were going to change that slightly to only write CRLF if we were on a Windows node, but instead in #1020 we made it always write CRLF on Windows. Which is the current state, and trigger of this bug.

**Comment by lamont-granquist** [comment]
yeah, #1020 is sane most of the time.  we need a binmode flag though so that users can override this behavior on an individual file resource, though, and basically say "look, i know i'm deploying this file to a windows box, but trust me i need unix line endings, stop being helpful..."

There's also this:

https://tickets.opscode.com/browse/CHEF-4751

That would help fix the case where we have a binary in files/ and deploy it to a windows box and the CRLF conversion mangles the binary.  But just having a `binmode true` flag to set on the file resource would ensure that the user can override the behavior in that case (if binmode defaults to 'nil' rather than true/false then we can later compute a default binmode based on inspecting the downloaded file and still let the user override).

**Comment by lamont-granquist** [comment]
closing as dump of #4662
