### ISSUE TITLE
knife wildcard search for attrs with values containing spaces doesn't work

### ISSUE THREAD

**Issue by jblaine** [chef/chef#2467]
Easy test case on any Linux node:

    knife node show mylinuxnode -a cpu.0.model_name
    => Intel(R) Xeon(R) CPU              X7560  @ 2.27GHz

    knife search 'cpu_0_model_name:"Intel\(R\) Xeon\(R\)"'
    => 290 items

Fails with wildcarding:

    knife search 'cpu_0_model_name:Intel*'
    => 0 items

    knife search 'cpu_0_model_name:"Intel*"'
    => 0 items

**Comment by stevendanna** [comment]
@jblaine Apologies that I never got back to you on this one.  The "version" you see in the header isn't updated as often as it should be.  I wasn't able to reproduce this at the time you reported it, I'll try to take another stab at it sometime this week.

**Comment by lamont-granquist** [comment]
I also can't replicate the problem against Hosted.

**Comment by lamont-granquist** [comment]
Its likely this was also a Server bug and was misclassified anyway.  Sorry we can't be more helpful about when or how it got fixed.

(I was testing with Chef 12, so its possible there was a fix applied client-side at some point, but looking at the search query I'm not aware of anything that the client would be doing that would affect that, since there's no actual spaces in the query string sent to the server).

**Comment by jblaine** [comment]
I can't replicate it anymore. We're on Chef Server 12.0.3 now.
