### ISSUE TITLE
service providers don't respect documented *_command attributes

### ISSUE THREAD

**Issue by jblaine** [chef/chef#2474]
```
  service 'foo' do
    init_command '/bin/true'
    start_command '/bin/true'
    status_command '/bin/true'
    stop_command '/bin/true'
    restart_command '/bin/true'
    action [:enable, :start]
  end
```

RHEL 5, RHEL 6: "unable to locate the init.d script!"

RHEL 7: "/bin/systemctl enable foo returned 1, expected 0"

etc...

**Comment by lamont-granquist** [comment]
I actually don't think this is really a bug. The purpose of the redhat service provider is to start/stop sysv init scripts, the purpose of the systemd provider in RHEL7 is to start/stop systemd services.  If you try to override that completely they'll blow up due to baked-in assumptions.  Writing code to work around the baked in assumptions in every provider would be the wrong thing to do.  There might be a doc bug here to document the simple provider so people can entirely roll their own, but its an edge case.  You can follow up with a doc bug against the chef-docs repo if you're interested, but triaging this one to closed.

**Comment by rehevkor5** [comment]
This combined with https://tickets.opscode.com/browse/CHEF-3511 makes it really difficult to create new services with Chef... unless there's a different way I'm not aware of?

**Comment by coderanger** [comment]
@rehevkor5 The fix is shown above. Please don't necro old closed issues.
