### ISSUE TITLE
Chef 12 errors on Windows when role_path doesn't include leading drive letter

### ISSUE THREAD

**Issue by sneal** [chef/chef#2666]
I took a working provisioned Windows box and upgraded from Chef 11 to Chef 12 (without changing anything else) and now I get a "Missing Role(s) in Run List" error. See Vagrant issue https://github.com/mitchellh/vagrant/issues/4974 for more information, but basically Chef 12 now requires that role paths include a leading drive letter which wasn't previously required.

```
==> default: Running chef-solo...
==> default: [2014-12-16T11:03:23-08:00] INFO: *** Chef 12.0.1 ***
==> default: [2014-12-16T11:03:23-08:00] INFO: Chef-client pid: 2848
==> default: [2014-12-16T11:03:49-08:00] INFO: Setting the run_list to ["role[dotnetframework]"] from CLI options
==> default: [2014-12-16T11:03:51-08:00] ERROR: Role dotnetframework (included by 'top level') is in the runlist but does not exist. Skipping expand.
==> default: 
==> default: 
==> default: ================================================================================
==> default: Error expanding the run_list:
==> default: ================================================================================
==> default: 
==> default: Missing Role(s) in Run List:
==> default: ----------------------------
==> default: * dotnetframework included by 'top level'
==> default: 
==> default: Original Run List
==> default: -----------------
==> default: * role[dotnetframework]
==> default: 
==> default: [2014-12-16T11:03:51-08:00] FATAL: Stacktrace dumped to C:/var/chef/cache/chef-stacktrace.out
==> default: [2014-12-16T11:03:51-08:00] FATAL: NoMethodError: undefined method `run_id' for nil:NilClass
```

Setting role_path to `/tmp/vagrant-chef-3/chef-solo-2/roles` doesn't work in Chef 12, but works in Chef 11.

Setting role_path to `c:/tmp/vagrant-chef-3/chef-solo-2/roles` works in Chef 11 and 12.

**Comment by shackit** [comment]
Thanks @b-dean just tested that work around and it works for me.

**Comment by Scythril** [comment]
I'm having the same issue with data_bag_path using vagrant and chef-solo; found this bug after figuring out that prepending the drive letter fixes it, but doesn't help me since Vagrant replaces the chef config on every provision.

Another note is that without the drive letter, it still verifies that the path exists, it just doesn't grab the files within that path without prepending the drive letter.

I'm currently using a combination of work-arounds from @b-dean and @lonniev (thank you both!), which is putting

```ruby
Chef::Config[:data_bag_path] = ::File.expand_path(Chef::Config[:data_bag_path])
```

in a file specified by the vagrant variable

```
chef.custom_config_path
```

**Comment by lonniev** [comment]
I should try @Scythril's patch: if I follow it, then it is simply injecting a bit of cleanup code into chef's code to get that path properly formatted for the DOS/Windows OS. My hack was to simply hard-code the known OS-specific destination path into the variable. This is hardly reliable because vagrant can shuffle the temporary folders it uses.

**Comment by lonniev** [comment]
I see: the File class for ruby on Windows will prepend the drive letter for both File.absolute_path and File.expand_path. A small ruby one-liner proves this:
```cmd
PS C:\Users\vagrant> ruby -e"puts File.absolute_path('/users/vagrant')"
C:/users/vagrant
PS C:\Users\vagrant>
```

**Comment by awithersdd** [comment]
The issue at least for data bags is that it calls Chef::Util::PathHelper.escapse_glob which returns the results above (not so helpfully turning forward slashes into backslashes). It then calls path.join to join the pattern with the path and then Dir.glob (lib/chef/data_bag.rb load() function) which fails for the now mixed slashes of \\original\\path\\data_bag_name/*.json. If esacpe_glob didn't change the dir separator it would work for most (instead of breaking for everyone).

**Comment by NickMRamirez** [comment]
I'm currently seeing this error with chef_zero. I install chef-client-12.3.0-1.msi on the Windows VM using Vagrant's shell provisioner. But then, both `add_role` and `add_recipe` in Vagrant fail. Vagrantfile contains:

```ruby
# Installs chef-client-12.3.0-1.msi"
config.vm.provision 'shell', path: 'downloadchef.ps1'

config.vm.provision 'chef_zero' do |chef|
    chef.roles_path = 'roles' 
    chef.add_role 'windowsnode'
	
    # this also fails...
    # chef.cookbooks_path = 'cookbooks'
    # chef.add_recipe 'somerecipe' 
end
```

**Comment by NickMRamirez** [comment]
Using @lonniev suggestion, adding a `File.expand_path` to the `clean_path` function in `opscode\chef\embedded\apps\chef\lib\chef\util\path_helper.rb` seems to fix this. I will submit a pull request.

```ruby
def self.cleanpath(path)
  path = Pathname.new(path).cleanpath.to_s

  # ensure all forward slashes are backslashes
  if Chef::Platform.windows?
    path = File.expand_path(path) # <--ADDING THIS LINE    
    path = path.gsub(File::SEPARATOR, path_separator)
  end
  path
end
```

Before the fix, clean_path returns:
`\tmp\vagrant-chef\b4ec99bdd1a0b235ccd6a5cd3eb84288\roles`

After the fix, clean_path returns:
`C:\tmp\vagrant-chef\b4ec99bdd1a0b235ccd6a5cd3eb84288\roles`

Incidentally, the purpose of the block that checks for Windows is to convert forward slashes to backslashes, but this didn't seem to be necessary during my testing. Windows could handle forward slashes just fine, at least during this test.

**Comment by NickMRamirez** [comment]
Submitted pull-request: [https://github.com/chef/chef/pull/3569](3569).

**Comment by NickMRamirez** [comment]
I am now wondering if this is an issue with Vagrant when using a Windows guest and not an issue with Chef. There's a Vagrant config option called provisioning_path.

[Shared Chef Options](http://docs.vagrantup.com/v2/provisioning/chef_common.html):
> provisioning_path (string) - The path on the remote machine where Vagrant will store all necessary 
> files for provisioning such as cookbooks, configurations, etc. This path must be world writable. By 
> default this is /tmp/vagrant-chef-# where "#" is replaced by a unique counter.

Given that, in my experiments, the path `/tmp/vagrant-chef` is being used on a Windows guest, maybe Vagrant should have a check for Windows and use a different path by default when on Windows?

**Comment by NickMRamirez** [comment]
Yep, this is probably a bug in Vagrant where Vagrant isn't setting the cooksbooks path correctly for Windows. The following Vagrant provisioning works, setting the provisioning_path for Windows:

```ruby
config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:\vagrant-chef'
    
    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
end
```

**Comment by lonniev** [comment]
That’s a cleaner looking workaround than what I was using.

-- 
Lonnie VanZandt
303-900-3048

On 24 June 2015 at 13:37:00, NickMRamirez (notifications@github.com) wrote:

Yep, this is probably a bug in Vagrant where Vagrant isn't setting the cooksbooks path correctly for Windows. The following Vagrant provisioning works, setting the provisioning_path for Windows:

config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:\vagrant-chef'

    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
end

**Comment by lonniev** [comment]
But, arguably, it isn’t “good” Ruby because the path shouldn’t use a drive letter and a backslash. Ruby’s supposed to handle that for us.

-- 
Lonnie VanZandt
303-900-3048

On 24 June 2015 at 13:37:00, NickMRamirez (notifications@github.com) wrote:

Yep, this is probably a bug in Vagrant where Vagrant isn't setting the cooksbooks path correctly for Windows. The following Vagrant provisioning works, setting the provisioning_path for Windows:

config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:\vagrant-chef'

    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
end

**Comment by thommay** [comment]
It sounds like this was likely a vagrant issue. If not, please feel free to reopen this ticket with more infortmation.
