### ISSUE TITLE
Error Text Could Be Improved When Chef-Client Fails to Auth on Knife Bootstrap

### ISSUE THREAD

**Issue by aronchick** [chef/chef#2693]
While bootstrapping a Node, I realized my associated key was out of sync. However, the error associated indicates something is wrong with JSON, and required running in verbose mode to dig out. Ideally, the client would detect the issue and report a move valuable error, including both the actual issue, as well as the key (on the system) being used.

```
ec2-54-149-126-230.us-west-2.compute.amazonaws.com [2014-12-20T14:53:23-05:00] INFO: HTTP Request Returned 401 Unauthorized:
ec2-54-149-126-230.us-west-2.compute.amazonaws.com
ec2-54-149-126-230.us-west-2.compute.amazonaws.com ================================================================================
ec2-54-149-126-230.us-west-2.compute.amazonaws.com Chef encountered an error attempting to create the client "da-boostrap-node"
DEBUG: received packet nr 47 type 94 len 2476
INFO: channel_data: 0 2451b
ec2-54-149-126-230.us-west-2.compute.amazonaws.com ================================================================================
ec2-54-149-126-230.us-west-2.compute.amazonaws.com
ec2-54-149-126-230.us-west-2.compute.amazonaws.com [2014-12-20T14:53:23-05:00] DEBUG: Re-raising exception: Chef::Exceptions::JSON::ParseError - parse error: premature EOF
ec2-54-149-126-230.us-west-2.compute.amazonaws.com
ec2-54-149-126-230.us-west-2.compute.amazonaws.com                      (right here) ------^
ec2-54-149-126-230.us-west-2.compute.amazonaws.com
ec2-54-149-126-230.us-west-2.compute.amazonaws.com /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:52:in `rescue in parse'
```

**Comment by Cervator** [comment]
Adding in one more user here who has encountered this quirk. In my case I was using the [Chef Identity plugin for Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/chef-identity+plugin), which prepares a job's workspace with a copy of knife.rb defined in the global settings.  Unfortunately it doesn't seem like it updates existing workspaces with changes so even after I added my org key and related config I just got this error over and over since the knife.rb in use was still missing the key info.

Eventually figured it out and found this as well as #1894 which I wanted to link to this - same issue pretty much.
