### ISSUE TITLE
Can't use --disableexcludes with yum_package or dnf_package (python helpers don't know about those options)

### ISSUE THREAD

**Issue by glasschef** [chef/chef#2728]
When using a yum_package within a recipe like:

```
yum_package "mypackage" do
options "--disableexcludes=all"
flush_cache [:before]
end
```

The flag --disableexcludes is not considered by yum-dump to get a list of packages, so some packages are not installable.
I think we need some similar functionality as provided for the options --enablerepo and --disablerepo.

https://tickets.opscode.com/browse/CHEF-5271

**Comment by neo-inuit** [comment]
+1

**Comment by jmaziarz** [comment]
+1

**Comment by jblaine** [comment]
+1

**Comment by jhmartin** [comment]
+1

**Comment by Lacaranian** [comment]
+1

It seems like other yum options could be included under this umbrella (for example `--exclude=foo`, which I ran into recently). It seems odd to enumerate a limited set of options under what is in practice a loosely typed field (since the option parameter is a string, it could be anything a string can be, not necessarily one of the "supported" options).

Would it be worth considering allowing arbitrary options to be passed through the options parameter, without vetting, before they get passed to the raw command? Or, alternatively, creating new yum_package specific parameters that enumerate the options that are actually supported (if anyone is in the mood to duplicate an API in the name of type safety)?

**Comment by pkleanthous** [comment]
Hi guys, is there a workaround for this? 
I would like to use `options '--disableexcludes=all'` inside my recipes. I'm using `Chef Development Kit Version: 1.3.43`

**Comment by saltyblu** [comment]
+1  need --disableexcludes=[all|main|repo]

**Comment by dguertin** [comment]
Since --disableexcludes hasn't ever worked and doesn't look to be implemented any time soon, we've been using a workaround with the execute resource:

`execute '<package>' do
    command 'yum --assumeyes install <package> --disableexcludes=all'
end
`
It's an ugly non-Cheffy kludge, but it's the only way we've been able to get this to work.

**Comment by saltyblu** [comment]
This is more pretty, and will not mark the install always as changed.
```
execute "install-package" do
  command "yum install --disableexcludes=main package-#{node['package']['version']}-1 -y -q"
  not_if "test \"$(rpm -qa package | awk -F'-' '{print $2}')\" = #{node['package']['version']}"
end
```
