### ISSUE TITLE
systemd provider for service resource doesn't pick up custom init scripts

### ISSUE THREAD

**Issue by dAnjou** [chef/chef#2839]
I'm currently configuring Red5 on Debian Jessie using [the init script from the Debian's repo](http://anonscm.debian.org/viewvc/pkg-flash/packages/red5/trunk/debian/red5-server.init?revision=520&view=co). Red5 however is not in Jessie and we need a newer version than in Sid anyway.

After adapting the init script and putting it on the node I wanted to enable and start Red5.
```ruby
template "/etc/init.d/red5" do
  source "red5/red5.service"
  mode "0750"
  action :create
end

service "red5" do
  supports :start => true, :stop => true, :restart => true, :status => true
  action [:enable, :start]
end
```
This failed, and after some investigation it turns out there's no unit file (e.g. `red5.service`). Running `systemctl daemon-reload` creates this unit file. So putting the following line right between the resources above makes all of this work:
```ruby
execute "systemctl daemon-reload"
```
The systemd provider for the service resource should do this.

**Comment by lamont-granquist** [comment]
run_action doesn't take an array of actions it does a single action.  you need to call it repeatedly if that is what you're trying to do.

```
r = [....resourcey stuff...]
r.run_action(:enable)
r.run_action(:start)
```

**Comment by dAnjou** [comment]
@lamont-granquist Uhm, this wasn't the actual issue. Read the title of this issue. The systemd provider is buggy if not broken in that regard.

**Comment by lamont-granquist** [comment]
After discussing this, we believe this is the way that it should work and after dropping a template you should have the template resource notify the execute resource to hit "systemctl daemon-reload".  Otherwise we have to constantly be doing daemon-reload on every service resource action.  The explicit solution is better because the template resource knows that daemon-reload actually needs to be called when it gets updated.  We can't put that kind of intelligence directly into the systemd provider.
