### ISSUE TITLE
powershell_script doesn't seem to always emit a line describing the step in output

### ISSUE THREAD

**Issue by docwhat** [chef/chef#2852]
I've notice when running test-kitchen or even chef-client on the command line (with or without `-l info`) that there isn't always a line like:

    * powershell_script[frobulate the frobinator] action run

Occasionally, for some rules, it does print this; I don't know why some do and some don't

Instead it usually prints something unhelpful like this:

      - execute "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20150203-452-3q886.ps1"

Which I assume to be the `Mixlib::ShellOut` log entry?

**Comment by lamont-granquist** [comment]
That line at the top should always exist.  We have a bug where INFO output and formatter output can get confused and make it hard to identify those lines.

The second line is normal output because powershell_script is really an execute resource which executes that command.

Without more context I wouldn't know where to look for this bug.  If you're still seeing this and can provide more context around the error message and what you're doing then please update the ticket.  Right now this doesn't seem actionable.
