### ISSUE TITLE
chef_gem doesn't account for orphaned gems

### ISSUE THREAD

**Issue by david-crowder** [chef/chef#2882]
In one of our cookbooks we install ridley as a chef_gem, ridley depends on json, chef 11 depends on different version of json. When we update the version of chef (using the omnibus installer) the installer blows away the extra version of json, but leaves ridley. This means that the chef_gem resource won't take an action because ridley is 'installed', but any attempts to use the gem fail because the dependency is missing.

Obviously there are parts of this issue that apply to how chef is being installed (using the omnibus install on redhat 6). However, it would be nice if there were a way to verify a gems install in the resource.

cc @ryancragun

**Comment by ryancragun** [comment]
I reported this upstream https://github.com/chef/omnibus/issues/427

**Comment by lamont-granquist** [comment]
Its debatable as to if this is a bug or a feature.  You're installing gems outside of the package managers knowledge so it doesn't clean those up on a re-install.  The solution would be to either patch the packages so that they'd blow away any stray files on a re-install, but that kind of violates the usual way that packages behave.  A better solution might be to patch something like the omnibus_updater so that it optionally wipes /opt/chef.

At any rate, though, I don't see the bug to fix here.  Its either in omnibus_updater or in omnibus/omnibus-chef.  I don't think we have a hook via rubygems to do the thing that you want to do.  If there is a hook you can probably also just `execute "gem magic ridley"` to fix it up.
