### ISSUE TITLE
Does open source chef server 11.0.12 support pushy?

### ISSUE THREAD

**Issue by cheyang** [chef/chef#2902]
Can it support pushy? If it can, how to install pushy server into Erchef? when I ran the following command, it reported "install is not subcommand which can be recognized"
[chefuser@autochef chef-server]$ sudo  chef-server-ctl installopscode-push-jobs-server
I don't know that command.

**Comment by lamont-granquist** [comment]
This is a better question from the mailing list / stack exchange or IRC since it isn't a bug and is a help request rather than something requiring software development.  Also this repo is only for chef-client.   There is a specific repo for server: http://github.com/chef/chef-server (pushy is smeared out over several repos, so that's probably the best place for pushy issues for now).

**Comment by mmzyk** [comment]
@cheyang I happened to see this, so I'll answer it, although in the future Lamont is right that asking on the chef server repo is probably better.

The answer is no. Push jobs needs either Enterprise Chef server or Chef 12 server, as it was built on top of the multitenant features that are not in open source Chef 11 server.

**Comment by cheyang** [comment]
Thank you very much. I will try open source Chef 12 server.
