### ISSUE TITLE
Enable suppressing delayed notifications

### ISSUE THREAD

**Issue by kbaltrinic** [chef/chef#2947]
There are several scenarios where a resource is only executed upon delayed notification but wherein under some circumstances one wishes to ultimately suppress the execution of the resource.  There are two stack overflow questions[[1]](http://stackoverflow.com/questions/26655604/chef-client-cancel-notifies-delayed)[[2]](https://stackoverflow.com/questions/27535197/stop-service-in-chef-after-it-has-been-notified-to-restart) that discuss how to do this with no good solution.  

I have a different scenario that requires the same kind of solution.  We are using the opscode Jenkins cookbook as the basis for our own cookbook.  Some actions that our cookbook might take require that Jenkins reload its configuration.  Some actions might require that the Jenkins service be restarted.  Often some of each actions will occur.  This results in the 'reload-configuration' and the 'restart' resources both being notified.  Yet, if we are restarting Jenkins there is no need to reload its configuration as well.  Thus it would be nice to configure a the reload-configuration resource to run if notified but only if the restart resource has not been notified.  

This is particularly a problem because the reload resource frequently times out because Jenkins is still starting up and slow to respond after being restarted.

**Comment by lamont-granquist** [comment]
For the linked examples its better to use a not_if kind of conditional:

```ruby
service "whatever" do
  ...
  action [ :enable, :start ]
  not_if { running_under_unit_tests }
end

other_resource "stuff" do
  [...]
  notifies, :restart, "service[whatever]", :delayed
end
```

Then if running_under_unit_tests is defined the resource will not run due to the not_if even if its a delayed notification.

And running_under_unit_tests can be an attribute or it can be a module/ruby library so that the state can bleed across multiple different cookbooks and recipes.

If the service resource is in another cookbook you can add the not if via chef-rewind-like functionality:

```ruby
resources(service: "whatever").not_if { running_under_unit_tests }
```

Although this is a reason why library cookbooks should export LWRPs like "jenkins_service" that wraps "service" and which the wrapper cookbook is explicitly supposed to call so that the not_if can be applied directly to the "jenkins_service" LWRP by the wrapper and we don't have to hack up the resource collection (but that is a bit of a digression).

The same principle can be applied here.  You want the service resource to 'restart' but `not_if { reloading_configuration }` so you just need to add that conditional and then make sure it somehow gets set correctly.
