### ISSUE TITLE
chef_gem should support options hash

### ISSUE THREAD

**Issue by pburkholder** [chef/chef#2977]
I'm trying to help a customer with the way the chef_gem uses rubygems.org, per #2867  

I'd suggested as a workaround that s/he use explicitly set the options hash. However, there's no way use the options hash with chef_gem since #1300 explicitly set the gem_binary in chef_gem.

But at https://github.com/chef/chef/blob/master/lib/chef/provider/package/rubygems.rb#L510-L527 we explicitly shell_out when gem_binary is not nil.

I'd submit a PR but I'm not sure what a reasonable fix is.

**Comment by lamont-granquist** [comment]
I don't think this is very fixable.  The `clear_sources` attr on the resource addressed the reason why you'd want to use an options hash on chef_gem.  Since we're using the gem_binary feature to implement chef_gem and that conflicts with the ability to use the options hash I don't see a good way around it.

We could:

1.  Figure out how to hack up the internal rubygems structures to point at the chef gem and and then revert after we're done, or the next time we hit a gem_package.  This will most likely require flushing the internal gem cache and all other state in the process which will be terrible for performance and memory for one thing.

2.  Do some translation from options hashes to command line options magically for the user (for both gem_package and chef_gem).

And I think right now we should support additional command line options to gem_binary which is the proper way to do this (but without `clear_sources` there was no way to remove the default command line option we were passing -- after `clear_sources` this should just work?).

So, closing this unless there's a really compelling use case we're missing where there's still no ability to get the job done.

**Comment by pburkholder** [comment]
Works for me. Thanks.

**Comment by patcon** [comment]
Possibly a compelling use-case for not failing out when a hash is set on `chef_gem`, and instead warning:
https://github.com/guilhem-cookbooks/gem_specific_install/issues/4

`specific_install` cookbook uses the "specific_install" gem to create an alternative gem_package provider that installs edge gems from git repos. The options hash was a way to pass in options for repo url and branch/tag without needing a whole new resource defined. It's now awkward as a fix involves forcing those options to come from a string now

**Comment by lamont-granquist** [comment]
Yeah the example case may be "awkward" for users, but trying to fix it will create a mess inside a provider that is already overly complicated.   We pretty much *MUST* shell out to a binary to chef_gem install.  In order to do that the options HASH is broken since it requires the rubygems internal API.   Therefore, users MUST use a string.  The only thing I'm aware of that you couldn't really do via the command line API was addressed via the addition of 'clear_sources' because we were forcing a source of rubygems.org which some people don't want.

We could support rendering an options hash into a string when the gem_binary is set, but then the options hash is going to look the similar but will support different options based on gem_binary being set or not which may be even more confusing.  Arguably the options hash and options strings should have been different resource properties to keep them separate so that it was clear that they're different in important ways.

So, mostly this argument turns on users wanting a little more sugar, but either the sugar is going to be a bit trivial (and easy for users themselves to render something like an array into a string in their own code) or else its going to be so invasive to the provider that its not worth it.
