### ISSUE TITLE
knife search exhibits surprising exit code behavior

### ISSUE THREAD

**Issue by eropple** [chef/chef#2981]
This may not be a bug depending on the intended behavior, but in at least my mental model, `knife search` is analogous to `grep`. To that end, it's odd that `knife search` returns an exit code of 0 when no matches are found; `grep` returns 1 for no-matches-found and higher codes for other fail states.

This totally might be what is intended, and in that case feel free to disregard, but returning 0 for this makes shell pipelining act unexpectedly with regard to `&&` and (particularly) `||`.

**Comment by ranjib** [comment]
`knife search ` the command itself didn't fail, hence the exit code is not 0. Its different from `grep` semantics,  and thats intended.

grep is built for shell usage, hence that behavior makes sense, but even that behavior has some consequence if you use `set -e` or if you dont have -o pipefail. But still, its very helpful. for shell scripting,

**Comment by eropple** [comment]
Your logic doesn't make sense to me. If knife isn't built for shell usage, what's the point of it being a command-line application?

**Comment by thommay** [comment]
We've been doing some work to make knife behave in a more 'shell'-y way, so I think we should make this change. However! This is a breaking change, because it will mean that people expecting 0 search results not to explode their pipes will not now get that behaviour, so we're not going to get to it for a while.
