### ISSUE TITLE
user resource: home dir recursive creation

### ISSUE THREAD

**Issue by brett-petrusek** [chef/chef#3007]
From CHEF-3725.

I consistently have user home directories that are not in /home and need to be created recursively. I know the proper way to handle this is with a directory resource, but depending on the complexity of the cookbook interactions, the ordering is not always ideal to allow for this. If the parent directory could be created with the same perms as the user home dir, the resource converge would succeed and I could later set the permissions differently, if required.

**Comment by btm** [comment]
@bp8017 could you provide an example of what that directory structure would look like?

**Comment by bp8017** [comment]
For example, an SAP instance database user for db2 has a home directory of /db2/dbSIDadm. With Oracle, the db user home could be /u001/dbinstance. If the user resource's manage_home capability recursively created the parents, I could leverage common LWRP's that manage users instead of having to recreate the wheel.

**Comment by lamont-granquist** [comment]
The recursive attribute to the directory provider is also problematic and we generally push people to not use that and to be explicit and declarative about all their directories under management.  I can see how its easier just have it be magic, but the magic has edges that we know consistently bite people on the directory resource.
