### ISSUE TITLE
Git provider fails to force update when you are already on the branch

### ISSUE THREAD

**Issue by iankronquist** [chef/chef#3025]
Consider the following invocation of the git provider:
```ruby                                            
 git '/opt/fenestra' do
  action :sync
  repository 'https://github.com/osuosl/fenestra'
  checkout_branch 'master'
end 
```
By default, git will check out the master branch. The provider will then attempt to force update to the `checkout_branch`, but will fail because you can't force checkout a branch you are on.
https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L160
An example on the command line:
```shell
$ git checkout master
$ git branch -f master
fatal: Cannot force update the current branch.
```
I'm interested in fixing this issue. What would be the best way to go about it?
Would I want to change the provider to look something vaguely like the following?

```ruby
def checkout
  sha_ref = target_revision
  converge_by("checkout ref #{sha_ref} branch #{@new_resource.revision}") do
    # checkout into a local branch rather than a detache@new_resource.checkout_branchd HEAD
    current_branch = shell_out!("git rev-parse --abbrev-ref HEAD") # I don't know what this returns, but let's pretend it just returns stdout
    if current_branch != @new_resource.checkout_branch then
        shell_out!("git branch -f #{@new_resource.checkout_branch} #{sha_ref}", run_options(:cwd => @new_resource.destination))
    end
    shell_out!("git checkout #{@new_resource.checkout_branch}", run_options(:cwd => @new_resource.destination))
    Chef::Log.info "#{@new_resource} checked out branch: #{@new_resource.revision} onto: #{@new_resource.checkout_branch} reference: #{sha_ref}"
  end
end
```

Thanks @jordane for helping me find where the issue was.

**Comment by iankronquist** [comment]
Any thoughts on this issue?

**Comment by toddmichael** [comment]
There a workaround for this?  I just ran into it as well.  Thanks.

**Comment by ddarbyson** [comment]
same issue. any ideas?

**Comment by iankronquist** [comment]
@ddarbyson You can try passing the hash which master is at to the provider. Good luck.

**Comment by bcg62** [comment]
same issue here

**Comment by phutchins** [comment]
Confirmed this issue also.

**Comment by aronwoost** [comment]
Confirmed.

**Comment by iankronquist** [comment]
Thanks for mentioning that you're having the issue too, I was beginning to wonder if I was crazy.

[Here](https://github.com/iankronquist/chef-bug-demo) is a minimal test case cookbook which demonstrates the issue. To see the bug in action just run `kitchen test`. The README has more information.

@danielsdeleo said this could be a documentation bug, as opposed to an issue with the git provider.

**Comment by danielsdeleo** [comment]
See #3289

**Comment by danielsdeleo** [comment]
https://github.com/chef/chef-docs/issues/552

**Comment by aronwoost** [comment]
Ok, I still don't get it.

When I use
```
git '/opt/fenestra' do
  action :sync
  repository 'https://github.com/osuosl/fenestra'
  revision 'master'
end
```
chef does still create a deploy branch. I want master to master. How to achieve that?

**Comment by jordane** [comment]
@aronwoost That is expected behavior. Is there a reason the deployed branch has to be `master`? If so, there isn't a great way to do this right now.

`revision` is what you change to change what the repo tracks

`checkout_branch` is the local branch that is checked out at whatever `revision` is. As @iankronquist originally mentioned, having `checkout_branch` set to master causes errors, because the underlying `git checkout` command fails.

**Comment by jordane** [comment]
@aronwoost The reason for the branch name being `deploy` is beyond me. Perhaps @danielsdeleo can shed some light on that. I agree it probably isn't the most intuitive choice for the average bear.

**Comment by danielsdeleo** [comment]
https://github.com/chef/chef-docs/issues/552#issue-90142019 explains why the behavior is the way it is. As for the name "deploy", that comes from Capistrano (as of 5ish years ago). Originally, some folks at engine yard adapted the capistrano code to make a "deploy" resource in Chef (as a gem external to Chef), which was supposed to be able to "take over" an existing capistrano deployment and just work, so you could move EC2 nodes into EY Cloud. I moved that deploy resource into Chef and extracted the git and svn code into separate resource/provider pairs so you could use them outside of the capistrano stuff, but that all was supposed to be compatible with the existing EY stuff so we wouldn't break them in the process of adding the features to core.

**Comment by pkyeck** [comment]
I did get this to work using the following snippet:

```ruby
git "/var/xxx" do
  repository "git@github.com:xxx/xxxx.git"
  user "xxx"
  group "xxx"
  revision "master"
  checkout_branch "master"
  enable_checkout false
  action :sync
end
```

Is this not the right/one way to do it? Or am I missing something?

**Comment by danielsdeleo** [comment]
Copying from the other issue ( https://github.com/chef/chef/pull/3289#issuecomment-113790597 )

The git provider is designed to work two ways:

1. You want to always sync a particular commit (which can change over time based on use of attributes, etc.). In this case you identify what commit you want from the upstream repo using the `revision` property of the git resource. The git provider will locally maintain its own branch and force it to whatever commit you want. This way, if you want to switch from one branch to another, or only deploy certain tags (maybe you set with attributes or a data bag item), you just set the `revision` and the provider will always ensure you're on the correct commit by checking `git ls-remote` on the upstream repo.

2. You want to do a one-time checkout. Usually this happens when you're maintaining developers' laptops with Chef. In this case, you set `enable_checkout` to false which prevents the git provider from attempting to checkout master to master. This usage was sort of bolted on to the git provider after use case (1), so it's a bit unwieldy, I admit.

@pkyeck that is the correct usage for use case # 2.

**Comment by pkyeck** [comment]
@danielsdeleo thanks for the detailed answer. 
(2) is exactly what I was trying to achieve - so all good :) cc @aronwoost
