### ISSUE TITLE
Core Windows resources are different from Windows cookbook resources

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#3037]
A number of Windows Chef resources are defined differently in two places, core and windows cookbook. As far as I know there isn’t any documentation that helps users understand this.

This is **very confusing and frustrating** to users who start with core resources and then add the windows cookbook to their run_list.

Here's an example related issue.
https://github.com/opscode-cookbooks/windows/issues/185

It seems that there is no solid effort to identify and attack this problem head on.

Thankfully a number of other windows pains are being worked on. It would be really nice to put some serious effort into moving the windows cookbook resources completely into core in a non-breaking way as soon as possible.

**Comment by adamedx** [comment]
I think windows_package is the worst offender. There are duplicates, but that's the only one I'm aware of that causes problems with existing recipes because of naming conflicts. That conflict might be the first one we should tackle.

**Comment by adamedx** [comment]
In general, here are resources that are duplicated in client and in cookbooks -- in all cases but windows_package, the core resource is not only preferred but better. We can probably start the deprecation process with those now:

* Registry: Use `registry_key` in core instead of `registry` from the Windows cookbook
* Batch: Use `batch` from core instead of `windows_batch` from the Windows cookbook.
* Reboot: Use `reboot` from core instead of `windows_reboot` from the Windows cookbook
* PowerShell: Use `powershell_script` instead of `powershell` from the PowerShell cookbook
* Package: Use `package` instead of `windows_package`. Note: if you try to use `windows_package`, core's Windows package wins, and this breaks cookbooks.

So today we should be able to deprecate `windows_reboot`, `windows_batch`, `registry`, and `powershell` from the Windows and powershell cookbooks now. The newer resources have more / better features.

**Comment by jeremiahsnapp** [comment]
This is great information. Thanks @adamedx !

It would be nice to see this deprecation announced in the appropriate channels as well as in the [windows cookbook](https://github.com/opscode-cookbooks/windows) itself.

Thanks!

**Comment by btm** [comment]
```Package: Use package instead of windows_package. Note: if you try to use windows_package, core's Windows package wins, and this breaks cookbooks.```

If you have the windows cookbook and you use ```windows_package``` the cookbook will win. In either case (with the windows cookbook or without) using just ```package``` on windows will use the provider in core.

**Comment by sean-horn** [comment]
The java cookbook has for some time depended on the checksum attribute being present on the windows_package/package provider. That functionality is not available currently in either set of providers. It was last spotted in version 1.34.8 of the windows cookbook 

https://github.com/opscode-cookbooks/windows/tree/v1.34.8/providers

**Comment by btm** [comment]
@sean-horn I believe you're looking for this: https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_package.rb#L208

I believe it was https://github.com/chef/chef/pull/2193 that had the side-affect of no longer allowing an LWRP to override an HWRP in core Chef. This was filed as https://github.com/opscode-cookbooks/windows/issues/150 and fixed in https://github.com/opscode-cookbooks/windows/pull/151 by moving the LWRP into a library.

**Comment by sean-horn** [comment]
@btm Yes, correct, I misspoke. The current version of the java cookbook doesn't work without the windows cookbook.

**Comment by rlaveycal** [comment]
Just to mention that the windows CB version of windows_package is superior to core when it comes to uninstalling : it looks up the package name in the registry to find the uninstall command rather than relying on the original MSI still being present and referenced in the recipe.

**Comment by adamedx** [comment]
@rlaveycal, the msi should be cached and the original msi should not be needed. Are you seeing this issue in general or with a specific msi? That sounds like something we need to open an issue for if that's the case.

**Comment by rlaveycal** [comment]
@adamedx This came up during some R+D with DataDog/dd-agent#1689. As part of that I wanted a recipe that just uninstalled the msi to aid testing.
````
windows_package 'Remove Datadog Agent' do
  action		:remove
  package_name	'Datadog Agent'
end
````
The CB wasn't referencing the windows CB and so reverted to core...and failed as I don't indicate the msi (it decided the source was D:\Remove Datadog Agent). The Windows CB implementation searches the registry for the package name and gets the uninstall command from there.

I was just commenting to indicate that the windows CB package implementation is superior to core, so if/when they're merged please take that one :)

**Comment by btm** [comment]
The issue with the registry search that the cookbook uses is that it's a text match for a non-unique field.  When I re-wrote the MSI provider in core I intentionally used the unique GUID from the MSI.

See https://github.com/opscode-cookbooks/windows/issues/192.

The thing to do would be to add an attritube to the windows_package resource in core to allow you to pass a GUID for removal without the MSI.

**Comment by adamedx** [comment]
Thanks @rlaveycal. @btm, I think in addition to the guid, we'd need good docs for how people can find the guid (maybe we should even output it in logs). I can't remember if there's a way to find the guid via add / remove programs, but certainly we could point people to a PowerShell command that would dump the guid for a given name on the computer.

@rlaveycal as @btm says, we can't rely on the package name as it isn't unique -- you could easily uninstall the wrong package. Some packages also make display names dynamic depending on the system they install on, so in some cases you'd need to figure out the name dynamically. That said, I think it's worth considering from a usability standpoint an explicitly-named attribute to allow the provider to search by name and remove the package that way. That way the user is opting-in to the risky functionality knowingly.

**Comment by btm** [comment]
In addition to some packages using the same name in the registry, others put the version in that string, which makes upgrading more trouble.

I agree we should doc both how to extract the upgrade_code GUID, and also make the debugging statements in Chef that already exist make it easier to find.

**Comment by rlaveycal** [comment]
Thanks for the feedback. I agree with @adamedx that having an attribute to opt-in to delete-by-name would be useful, and then delete all matching packages. As the title of this issue says, there are functional differences between the core and CB implementations and the CB seems richer at the moment (version numbers, non-msi support). 

Version support is another thing that relies on the package name being unique so that the current version can be read from the registry. Enforcing this assumption would at least ensure Chef failed safe rather than the current CB behaviour of last one wins.

**Comment by btm** [comment]
Other providers aren't going to have nice unique GUIDs for uninstall anyway. As we add more provideers, given the unique way we choose providers for windows_package, rather than another attribute we can probably just DWIM when resource.name/resource.source isn't a file on disk/path.

**Comment by lamont-granquist** [comment]
Having two identically named resources in core and in the cookbook also breaks foodcritic rules:

acrmp/foodcritic#393

One way or another there can be only one.  Either the core chef resource needs to stop stomping on windows_package in the DSL or else the windows_package in the cookbook needs to be removed and fully replaced by the core version.  Having identically named resources in core and in a cookbook is unsustainable.

**Comment by btm** [comment]
The rest of the package providers from the Windows cookbook are going to be moved into core this quarter.

https://github.com/chef/chef/blob/master/ROADMAP.md#2015-q4

**Comment by btm** [comment]
https://github.com/chef-cookbooks/windows/pull/389 will remove `windows_package`, `windows_batch`, `windows_reboot`, `windows_registry`, and `powershell_out` from the windows cookbook.

**Comment by lamont-granquist** [comment]
![Its Happening!](http://i.imgur.com/7drHiqr.gif?noredirect)

**Comment by tas50** [comment]
This is mostly done at this point. In April when we ship Chef 13 I'm going to remove the remaining functionality from the windows cookbook and require Chef 12.6+ in that cookbook. That that point we won't have differing resources.

**Comment by tas50** [comment]
Closing this out since we've done the deprecation in the windows cookbook. We ported windows_task and windows_path into core chef in the 13 window. Those will be removed from the windows cookbook in the future as well. There's deprecation warnings there as well.
