### ISSUE TITLE
reboot_pending_spec.rb relies on existing system state

### ISSUE THREAD

**Issue by smurawski** [chef/chef#3085]
The test should stub out responses from the various registries keys, so as not to rely on system state and allow tests to validate cross platform.

**Comment by stuartpreston** [comment]
I had a quick review of `reboot_pending_spec.rb` and whilst generally fine for CI where the original state is known it does look like it could be improvement for development.  Specifically we should not skip the test if possible, either backup/restore the state or stub out the calls into the registry. https://github.com/chef/chef/blob/master/spec/functional/dsl/reboot_pending_spec.rb

**Comment by btm** [comment]
The unit tests in `spec/unit/dsl/reboot_pending_spec.rb` current stub out the registry checks and do run on all platforms (tested on linux today).

The functional tests in `spec/functional/dsl/reboot_pending_spec.rb` will create the key and then delete it if it does not exist, to test functionality. If the key does it exist, it will test functionality but not delete it afterwards. This is correct behavior, and was fixed up way back in https://github.com/chef/chef/pull/3909 (after this ticket was created but still in 2015).

The functional test for `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootRequired` currently is marked 'pending' as permissions to modify this key are limited to the TrustedInstaller and would require modifications to permissions that are more arduous than they would be worth.

The only work left to do here that I see could be to remove the entire functional test for CBS since we can't test it.
