### ISSUE TITLE
'knife upload' does not honor dependencies in metadata.rb

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3095]
Scenario:
Metadata.rb of cookbook foo has `depends cookbook bar`

Issue:
knife upload cookbooks will upload foo w/o any issues.
knife cookbook upload foo will fail with ```missing cookbook``` error (as expected)

**Comment by lamont-granquist** [comment]
This goes under the #3368 epic.  Although I'd say that knife upload is dumb and should be dumb and the behavior there is right.  Depsolving should be handled by berkshelf/policyfile APIs.  It would take a lot more code to make sure that for every cookbook in the set that you are uploading that all the deps are satisfied either by the cookbooks on the server or the cookbooks you are uploading, and then you'd still be exposed to the command failing halfway through and having cookbooks uploaded to your server without deps.  This isn't a problem for 'knife cookbook upload' because it doesn't do bulk uploads.

**Comment by vinyar** [comment]
I've learned a lot since filing this bug.. with this newfound knowledge I agree that bulk upload should stay dumb.

Specific example - when a chef server 10 is migrated to 12, there may be cookbooks where name in the metadata doesn't match runlist name on the node. This discrepancy may stem from cookbook folder name or something else (didn't dig too hard). However, it seems to work in CS 10 but fails in 12. Depsolving during migration bulk upload would cause additional headaches for migration.

**Comment by lamont-granquist** [comment]
Agreed.
