### ISSUE TITLE
Group resource reporting deleted group still exists

### ISSUE THREAD

**Issue by tfitch** [chef/chef#3100]
Filing on behalf of a customer:

A colleague is seeing a problem using the group resource.

The Chef run is reporting that the group already exists and is up to date on the node, even though it has been deleted by using groupdel command and removing it from /etc/group.

Looking into the [provider code](https://github.com/chef/chef/blob/master/lib/chef/provider/group.rb#L46-L51) - the Ruby call to Etc.getgrnam() does return the group, even though does not appear in /etc/group.  We have ran this explicitly on the server with the odd results.

Possibly a big variable: the server does have [Centrify](https://www.centrify.com/) installed.

Have you seen anything like this before?  With or without Centrify?

**Comment by btm** [comment]
What does your /etc/nsswitch.conf look like?

**Comment by tfitch** [comment]
@btm we've got the nsswitch.conf file, but can't share all because of some sensitive data.

Is there specific settings you're interested in?

There is the following entry that is shareable:

group: centrifydc files

**Comment by btm** [comment]
It's most likely related to centrify. Have you tried to replicate with centrifydc removed from the nsswitch.conf? Because it is first in the list, libc is going to give getpwent an answer from centrify first if it gives an answer. 

You could getent to test outside of Chef what is being returned to chef, e.g. "getent group name"

http://man7.org/linux/man-pages/man1/getent.1.html

The other nsswitch.conf issue is that changes to nsswitch are not exposed to running processes. That is, chef-client has to exit after changing the nsswitch.conf.

https://tickets.opscode.com/browse/CHEF-3780

**Comment by lamont-granquist** [comment]
This is glibc caching.

There's no solution to this outside of running nscd which has the proper code to notice updates and invalidate the caches.

Someone could port the code from nscd into core ruby itself.  Otherwise, the chef-client cannot work around this issue.
