### ISSUE TITLE
Cookbook Metadata Should Allow Arbitrary Data

### ISSUE THREAD

**Issue by smurawski** [chef/chef#3104]
via @agh in https://github.com/chef/chef/issues/1776

Would it be nicer to add arbitrary metadata support?

I can think of a few cases where I might want to be able to ingest cookbook metadata from everything we run internally, and where it might be valuable to have arbitrary data available to assist that. Supermarket seems like another case where it'd be valuable, but where Chef Server maybe should not care about that data today.

Is this really much more complex than teaching Chef Server about supported values and having it ignore everything else which may be present? Feel free to say, "Yes, that would be very hard!".

via @danielsdeleo 

@agh I see arbitrary metadata as kind of orthogonal. I would prefer that any user-defined metadata live in its own keyspace like:

{
  "name": "my_cookbook",
  // etc.
  "user_data": {
    // arbitrary data here
  }
}
This way you don't have compatibility issues with stomping users' existing data if you want to add a new key to the top-level in the future.

Of course, I think that the server should at least allow unknown keys (even if it ignores them) so it can be forward compatible, but if you keep system and user-owned keyspaces separate like I've described, that's a different feature.

**Comment by lamont-granquist** [comment]
we already support arbitrary cookbook metadata on the server

**Comment by danielsdeleo** [comment]
Reopening because we still need to do something client/knife side to make this useful.

Generally I think arbitrary metadata should be allowed but it should be separate. For example, suppose you implement something like "required_chef_version" in a cookbook. Everyone likes it, and it becomes a standard feature. Suppose that we add server-side validation of the required version field so that you fail early if you have invalid data. Then you could be in a situation where you have data in a cookbook that was valid with the cookbook version of the feature but not in the final version, and now you can't upload the cookbook, which means it's a breaking change and we can't fully release the feature until the next major version.

To accomplish separation of user vs. "system" metadata, we can either squirrel user metadata away in a separate top-level field, or we can do something where we prefix user's keys with (e.g.) "x_user" so in the example from before you'd have "x_user_required_chef_version". Thoughts?

**Comment by carpnick** [comment]
Using x- is common practice in HTTP headers.  So using a variation of that should feel familiar to quite a few people.

**Comment by lamont-granquist** [comment]
Well knife upload probably needs to be able to upload any arbitrary metadata fields.  Or at least it needs to not crash and strip those fields and warn the user that they may need to upgrade.  The latter would be most likely be fairly simple, the former looks like it might be quite a bit of plumbing to the metadata class (and starts to smell like method_missing).

**Comment by anjutiwari** [comment]
so anybody working on it ?

**Comment by danielsdeleo** [comment]
I don't know of anyone working on it right now. I'm not sure if this strictly _requires_ a chef-rfc, but I would like to get everyone's perspectives on the handful of different ways we could implement this on the client side and have maximum forward and backward compatibility, so that might be a good place to start.

**Comment by lamont-granquist** [comment]
We've already created the problem because if server_url becomes widely used then it'll break knife cookbook upload on those cookbooks for any knife workstation that doesn't support it (all of 11.x probably and anything older than the commit that introduced it into the code base).

**Comment by danielsdeleo** [comment]
@lamont-granquist yeah, forward compat is hard. I could see going the method_missing+warning route, or we could do something like:

```ruby
attribute(:server_url, VALUE)
```
Where it detects if it knows about "server_url" as metadata, and if not, sets it as "user metadata" (either "x_server_url" or put it in a different hash or whatever) in the JSON version. Anyway, maybe an RFC is the best way to flesh out the pros and cons of the various approaches
