### ISSUE TITLE
Provide a way to express cookbook multiple constraints

### ISSUE THREAD

**Issue by sbuzonas** [chef/chef#3124]
This was initially reported in https://tickets.opscode.com/browse/CHEF-4727 and I couldn't tell if it was migrated or Triaged for Later.

Some cookbooks may have a very long span of compatibility across multiple versions and then a major version breaks backward compatibility as anticipated with semantic versioning.  In a scenario where a cookbook utilizes the database cookbook I have a recipe that requires 1.3.0 for the mysql recipe.  This is removed in 4.0.  Pessimistic versioning doesn't cover constraints spanning multiple versions.

I tried to declare the dependency twice `depends 'database', '>= 1.3.0'` and `depends 'database', '< 4.0'`, that appears to disregard the second declaration.  There should be some way to express these constraints.

**Comment by MikeTLive** [comment]
this may be useful. https://github.com/npm/node-semver

**Comment by b-dean** [comment]
This is super obnoxious that we can't do dependencies with more than one constraint (like is commonly done in ruby gems). It means that when we have a cookbook that is referenced by many other cookbooks we either have to

1. use optimistic version constraints and have things break when we go to a new version. (For example: `>= 9.0.1`)
2. use pessimistic version constraints and have to update them in every related cookbook each time we bump the major version. (For example: `~> 9.0` and then change it to `~> 10.0` when 10.0.0 comes out)

Both of these have problems. With optimistic versioning the risk is obviously that some new breaking change will come out and ... break things. With the pessimistic versioning, we basically are saying that the second cookbook cannot use version 9.x anymore when it maybe can just fine, depending on what the breaking change was. Often we'd be happy with `'>= 9.0.0', '< 11'`. Also, a problem with pessimistic versioning and semver is that if you want to be okay with all 9.x, because you don't mind getting new features, you do `~> 9.0` but if there is some crippling bug that wasn't fixed until 9.0.5, there's no way to say all 9.x and also at least 9.0.5 (at least not with a single constraint. The [rubygems docs talk about how to do this with multiple constrains in their section on pessimistic versioning](http://guides.rubygems.org/patterns/#pessimistic-version-constraint)).

So we've gone with pessimistic versioning but it makes it a huge pain when there's a major version change because it spreads like some sort of virus across all the cookbooks that are in the dependency graph.

Too bad you can't go back in time and just package the cookbooks as gems :wink:

**Comment by coderanger** [comment]
> Too bad you can't go back in time and just package the cookbooks as gems 

[You can](https://github.com/poise/halite).

**Comment by b-dean** [comment]
@coderanger, I don't think [halite](https://github.com/poise/halite) solves the multiple constraints problem though. Chef is still responsible for resolving dependencies, not rubygems.

**Comment by coderanger** [comment]
You can use Bundler to solve the gems, convert them all to cookbooks, and feed them to chef-solo or chef-client local mode. The actual solver issue is with Erchef, not Chef itself (though Chef does enforce the validation).

**Comment by andytson** [comment]
This is so painful to work around for all the reasons @b-dean mentions

**Comment by lamont-granquist** [comment]
I think this is a dup of some other issue which has better details.

Yep closing in favor of #2457 and #3924
