### ISSUE TITLE
remote_file Provider Issue Following Redirects

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#3134]
The aws 2.6.4+ cookbook's `aws_s3_file` provider only works when the s3 resource we want to access is local. If we are on eu-west-1 and the bucket and file are actually over on us-west-2, S3 will send a redirect and `remote_file` is unable to follow the redirect. `aws_s3_file` is implemented in terms of `remote_file`

https://github.com/opscode-cookbooks/aws/issues/119

**Comment by lamont-granquist** [comment]
It looks like AWS is/was sending back a 301 redirect with no location header, so that seems like its AWS's problem.

We have code in Chef::HTTP to handle redirects, and we test that work at the Chef::REST level here:

https://github.com/chef/chef/blob/master/spec/unit/rest_spec.rb#L433-L452

I think this should probably be closed as Not[Our]Bug.

**Comment by thommay** [comment]
Agreed, closing.
