### ISSUE TITLE
Chef client no longer handles interactive shell scripts well

### ISSUE THREAD

**Issue by glasschef** [chef/chef#3189]
This worked fine in Chef 11, but In Chef 12 it will just hang:

```
execute "outfile" do
  cwd "/tmp/"
  environment "TEMP" => "/tmp/scratch"
  command "sh -i -c 'echo hello > outputfile'"
  action :run
end
```

**Comment by bahamas10** [comment]
title says `bash` but command invokes `sh`

what was the expected result in Chef 11? did you run something that required interactive input?

**Comment by glasschef** [comment]
This was opened on the behalf of a customer, but their expected result that happens in Chef 11 was that interactive shell scripts (like package installers, for example), would just proceed and finish executing without input.

**Comment by jekriske** [comment]
Under RHEL sh is a symlink to bash. This also occurs if using the bash resource instead of execute. 

The example doesn't run anything that requires interactive input. It simply echos "hello" into a file called outputfile. Chef client does not and cannot know the commands in advance or their behavior in the child processes of those commands. The expected behavior should be as if you typed the command yourself into an interactive shell with a tty or pty available to read from and write to.

**Comment by jekriske** [comment]
Once this is fixed, it might be beneficial to add an rspec test to catch this problem on future builds. Like the previous yum silently failing issue, it makes chef client 12.x currently unusable in production (at least for our environment).

**Comment by lamont-granquist** [comment]
Fixed by https://github.com/chef/mixlib-shellout/pull/94
