### ISSUE TITLE
LWRP behaves odd when trying to set an attribute to nil

### ISSUE THREAD

**Issue by omribahumi** [chef/chef#3197]
Given the following `cookbook/resources/manage.rb`:
```ruby
attribute :users,    :kind_of => [Hash, Symbol, NilClass], :default => :admins
```

When trying to use it like this:
```ruby
cookbook_manage 'foo' do
  users nil
end
```

The provider gets `new_resource.users` set to `:admins`

After digging a bit in the code, I noticed that the [LWRP resource attribute implementation](https://github.com/chef/chef/blob/5d666b72725bb7df414e335b50a7892d5a457425/lib/chef/resource/lwrp_base.rb#L77) uses [Chef::Mixin::ParamsValidate#set_or_return](http://www.rubydoc.info/github/opscode/chef/Chef/Mixin/ParamsValidate:set_or_return), which uses `nil` instead of `NULL_ARG` like the rest of the code.

**Comment by lamont-granquist** [comment]
This is a breaking change which can only be fixed in Chef 13 and will be fixed in Chef 13.  The deprecation warnings are in there now.  We cannot fix it now because there is existing code in popular cookbooks which expects this code to retain the default value for the 'property' on the resource even if its not nil (so if the default is 'foo' then it retains 'foo', we cannot set it to nil):

```ruby
variable = nil
resource "whatever" do
  property variable
end
```

That code should all be rewritten something like:

```ruby
variable = nil
resource "whatever" do
  property variable unless variable.nil?
end
```

But until it is, that would be a breaking change.

**Comment by axos88** [comment]
@lamont-granquist may I ask how this will be fixed? I'd still  want it to work the way it works currently, so that i can avoid all the unless .nil? boilerplate when doing such as
```
modues.each_pair do |name, cfg|
  module name
    cfg[:url]
    cfg[:instances]
  end
end
```
where the values default to the default values if they are unset in the hash.
