### ISSUE TITLE
`knife bootstrap` fails if `-N` option is not passed

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#3204]
The client_builder uses the value of the `-N` option as the node name:

https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/client_builder.rb#L79-L81

if that is nil since the user didn't pass it, the user will receive a confusing HTTP 405 Method Not Allowed Error here:

https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/client_builder.rb#L157

This command should use the first argument of the bootstrap command as the node name if `-N` was not passed.

**Comment by okram999** [comment]
This is the same issue that i am going through now. Is this only for Chef-client 12.x i didn't had this with the chef-client 11.x?

**Comment by daxroc** [comment]
Second - hitting this is issue also. Chef: 12.2.1

**Comment by flacito** [comment]
Third - hitting this issue as well. But with further problems...

We also have a custom bootstrap template that fails even if you put the `-N` option on your bootstrap command.

Relevant contents of bootstrap template:
`
awk NF > /etc/chef/validation.pem <<'EOP'
<%= validation_key %>
EOP
chmod 0600 /etc/chef/validation.pem
`
if you remove the `validation_key` attribute from your knife.rb file and the validation key file from your .chef directory, the bootstrap template writes nothing to  `/etc/chef/validation.pem` on the node and the chef-client on the node fails because of a corrupted validation key. I tried removing the validation key logic from the bootstrap template, but then the chef-client on the node fails because the key cannot be found at `/etc/chef/validation.pem`.

What to do?

$ knife --version
Chef: 12.2.1
(on both my Chef workstation and my Chef node)

**Comment by LJT91** [comment]
Fourth that issue on a standard bootstrap process.
