### ISSUE TITLE
Potential issue with deprecated `command` for script resources

### ISSUE THREAD

**Issue by sethvargo** [chef/chef#3244]
Currently when specifying a script resource with a command attribute, the following error is given:

```text
WARN: Specifying command attribute on a script resource is a coding error, use the 'code' attribute, or the execute resource
WARN: This attribute is deprecated and must be fixed or this code will fail on Chef-13
```

However, the `command` attribute is also the name/identity attribute for the resource. For example, consider:

```ruby
bash 'specifying the identity attribute' do
  command 'identity_attribute'
end
```

In the resource collection, this item exists as `bash[identity_attribute]`. However, changing that to:

```ruby
bash 'specifying the identity attribute' do
  code 'identity_attribute'
end
```

causes the item to exist in the resource collection as `bash[specifying the identity attribute]`.

This causes some serious problems with ChefSpec, since ChefSpec relies on the name/identity attribute to identify resources in the collection. Furthermore, it is somewhat misleading that the "name" attribute generates a warning:

```ruby
bash "echo 'test'"
```

The above code generates that warning and it is very unintuitive to a new user what that means.

How can we work around this so that Chef 13 does not break ChefSpec? Do we really need the deprecation? What if we deprecate `code` instead of `command` since it's already the name attribute?

/cc @lamont-granquist @schisamo

**Comment by lamont-granquist** [comment]
So the problem is that internal the script resources inherit from the execute resource and scribble over the command parameter.  If a user supplies a command parameter in the DSL it will get silently overwritten and ignored and I believe a null command will succeed in running and the user will not get any indication of the error.  This isn't being done to just cosmetically change the API, the code parameter is the only one that works and the only one that can work.

And there's a deeper problem with this:

```ruby
bash "touch /tmp/foo"
```

That warning is entirely accurate:

```
No code attribute was given, ***resource does nothing***, this behavior is deprecated and will be removed in Chef-13
```

Emphasis is added.  The `touch /tmp/foo` was overridden by the bash resource and nothing was actually run, the resource is worthless, and this behavior existed prior to my patch we just didn't notice it.  The warning is now accurately warning of behavior.

The problem seems to be that we need to inherit from execute and override the name parameter to be the code parameter instead.  Kind of a mild nightmare, I'm considering that all the script resources need to inherit from some other hidden base class that is like execute but which execute can setup its command name attribute and the other ones can setup code as their name attribute.  The script resources clearly do not adhere to a strict is_a relationship with the inherited execute resource.

**Comment by lamont-granquist** [comment]
Oh hm, I'm getting a different warning, think I'm getting a different chef in my bundle...

**Comment by lamont-granquist** [comment]
Ah I see there's two warnings, one for using the command attribute an one for not having a code block.

Anyway both accurately warn and both do not do what the user intends (/tmp/foo will not be created):

```ruby
bash "touch /tmp/foo"

bash "do it" do
  command "touch /tmp/foo"
end
```

This works:

```ruby
bash "do it" do
  code "touch /tmp/foo"
end
```

**Comment by sethvargo** [comment]
Hrm... The issue is, given:

```ruby
bash "do it" do
  code "touch /tmp/foo"
end
```

The item in the resource collection is `bash[do it]`, not `bash[touch /tmp/foo]`. There's conflation around the name/identity attribute. The side effect is that a ChefSpec test for that resource will fail:

```ruby
# Fails
expect(chef_run).to run_bash("touch /tmp/foo")

# Works
expect(chef_run).to run_bash("do it")
```

However, as you can probably tell, the test that works is not very intuitive and doesn't seem like a real test.

I think, as part of this change, the identity attribute needs to be changed to `code`, but I don't know all the implications of doing that.

**Comment by stevendanna** [comment]
> Hrm... The issue is, given:
> ```ruby
bash "do it" do
  code "touch /tmp/foo"
end
```
> ```
# Fails
expect(chef_run).to run_bash("touch /tmp/foo")
# Works
expect(chef_run).to run_bash("do it")
```

This is a bit confusion to me.  The behavior you described seems correct for me.  "do it" should definitely be the name of that resource in the resource collection.  I agree that the test you need to write is confusing and can see an argument for changing it.  But, the current behavior does allow things like:

```
execute "frob the frobinator" do
   execute "Long command that would be annoying to reference in a notify or other places where you need to reference resources by name"
end
```

**Comment by sethvargo** [comment]
Maybe I'm misunderstanding the example. How would you rewrite these? https://github.com/sethvargo/chefspec/blob/master/examples/script/recipes/run_bash.rb

```ruby
bash 'default_action'

bash 'explicit_action' do
  action :run
end

bash 'with_attributes' do
  creates 'creates'
end

bash 'specifying the identity attribute' do
  command 'identity_attribute'
end
```

**Comment by stevendanna** [comment]
> Maybe I'm misunderstanding.

Or I misunderstood ;). In your original post you say:

> For example, consider:

>```
bash 'specifying the identity attribute' do
  command 'identity_attribute'
end
```

>In the resource collection, this item exists as bash[identity_attribute]

But I'm not seeing that behavior and would consider it a bug:

```
This is the chef-shell.
 Chef Version: 12.3.0.dev.0
 http://www.chef.io/
 http://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u sdanna@!
chef > recipe_mode
chef:recipe > bash 'specifying the identity attribute' do
chef:recipe >   command 'identity_attribute'
end  command 'identity_attribute'
chef:recipe ?> endend
[2015-04-21T13:45:47+01:00] WARN: Specifying command attribute on a script resource is a coding error, use the 'code' attribute, or the execute resource
[2015-04-21T13:45:47+01:00] WARN: This attribute is deprecated and must be fixed or this code will fail on Chef-13
 => <bash[specifying the identity attribute] @name: "specifying the identity attribute" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :run] @action: "run" @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @resource_name: :bash @command: "identity_attribute" @backup: 5 @creates: nil @cwd: nil @environment: nil @group: nil @path: nil @returns: 0 @timeout: nil @user: nil @umask: nil @is_guard_interpreter: false @code: nil @interpreter: "bash" @flags: nil @declared_type: :bash @cookbook_name: nil @recipe_name: nil>
chef:recipe > resources
["bash[specifying the identity attribute]"]
```

which is exactly what I would get in the resource collection, sans warning, when I change `command` to `code.

>  How would you rewrite these?

The only one that requires rewriting is the last one, to get rid of the warning. In all cases, the first argument to the `bash` Recipe DSL method should be the name of the resource in the resource collection.

**Comment by sethvargo** [comment]
@stevendanna it's warning for each of those resources though: https://travis-ci.org/sethvargo/chefspec/jobs/59390160

**Comment by lamont-granquist** [comment]
This is the only bash resource that works:

```
bash "touch file" do
  code "touch /tmp/foo"
end
```

```
expect(chef_run).to run_bash("touch file")
```

Chef itself does not, and has never supported the other forms, and has silently ignored the argument and done nothing.  So again, the warnings are accurate, you don't have to support those because they don't work.  The point of the warnings is that this can be confusing and you *must* write resources with the code attribute to make them shut up.

We might be able to fix the short form if we can inherit from the execute resource and override the name attribute.  Either its a short patch or its a major yak shave, I haven't looked at the code yet.

The `command` attribute on a script resource is wrong, and Chef 13 must be changed to raise if the user passes that because it gets overwritten internally and is useless.

**Comment by sethvargo** [comment]
Dang. That's a bad bug then. I'll update ChefSpec examples and docs. Thanks everyone!
