### ISSUE TITLE
no service provider for mac_os_x on chef 12?

### ISSUE THREAD

**Issue by nathwill** [chef/chef#3257]
we're working on upgrading from chef 11 -> 12, but hit this updating our mac_os_x cluster... 

```irb
chef > Chef::VERSION
 => "11.16.4" 
chef > Chef::Platform.find_provider_for_node node, :service
 => Chef::Provider::Service::Macosx 
```

```irb
chef > Chef::VERSION
 => "12.2.1" 
chef > Chef::Platform.find_provider_for_node node, :service
ArgumentError: Cannot find a provider for service on mac_os_x version 10.10.3
	from /opt/chef/embedded/apps/chef/lib/chef/platform/provider_mapping.rb:446:in `find_provider'
	from /opt/chef/embedded/apps/chef/lib/chef/platform/provider_mapping.rb:373:in `find_provider_for_node'
	from (irb):5
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:76:in `block in start'
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `catch'
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `start'
	from /opt/chef/embedded/apps/chef/bin/chef-shell:37:in `<top (required)>'
	from /usr/bin/chef-shell:51:in `load'
	from /usr/bin/chef-shell:51:in `<main>'
```

**Comment by btm** [comment]
@nathwill You're accessing an internal part of the old provider mapper directly. As of 12.2.0/c3552dc11831379a4b4753964451498e1340611e the OS X providers are no longer statically resolved, so the old provider mapper no longer knows about them.

I'm not sure what you're using that code for, but because resources can have unique attributes, you should look at using ```Chef::Resource.resource_for_node(:service, node)```.

**Comment by nathwill** [comment]
@btm hmmm... in my experience, it's generally used as a proxy for detecting the chef-preferred init system for the platform (e.g. https://github.com/atomic-penguin/cookbook-nfs/blob/master/attributes/default.rb#L44 or https://github.com/nathwill/chef-haproxy-ng/blob/master/recipes/install.rb#L85). being able to use that is/was a *lot* more lightweight than maintaining/duplicating an internal mapping for each cookbook that needed to support multiple init systems.

Chef::Resource#resource_for_node doesn't quite fit the bill from what i'm seeing, it seems to resolve to Chef::Resource::Service on EL6, EL7, mac_os_x, and Ubuntu 12.04. Is there anything better that can be considered a stable interface?

thanks for the help so far.

**Comment by btm** [comment]
We always had support for multiple providers for a resource (via the provider map) but as provider's started to need unique attributes (like package) we ended up having resources that took a bunch of attributes that may not even apply to chosen provider. Quite a while ago we added the initial ```provides``` code for choosing an alternate resource, but it wasn't heavily used.

This feature was refactored recently to support having multiple init systems as you described, and continues to be refactored (see #3077).

There isn't a stable interface. We discussed the need for one in the dsl over in #3071, but generally we're not good at clearly identifying the internal methods that are public and stable.

Maybe this helps:
```
chef > service_resource = Chef::Resource.resource_for_node(:service, node).new("lookup a provider")
[snip]
chef > service_provider = Chef::ProviderResolver.new(node, service_resource, :start).resolve
 => Chef::Provider::Service::Macosx 
```

**Comment by nathwill** [comment]
@btm ok, thanks. i'd definitely seen some mention of the new dynamic selection stuff, but pending some of that settling out a bit, i haven't bothered to look into it in detail.

the provided solution unfortunately only works on Chef 12, but wrapping the old way and the new way in a version check ought to be straightforward enough, so i'll try to make it work.

FWIW, a search on github seems to indicate that Chef::Platform#find_provider_for_node has been pretty broadly adopted in lieu of an official stable interface. i'm not super familiar with the code in question, but that makes me wonder if it can be made to continue working during and after the transition to the new dynamic matching system so as to minimize ecosystem disruption.

in any case, thanks again for the explanation and pointers! feel free to mark this closed if this seems a reasonable place to leave it.

**Comment by nathwill** [comment]
hmmm, a second look at the search results says nearly all of those are forks and dupes, so maybe not as disruptive as i thought, whew!

**Comment by yoshiwaan** [comment]
nfs cookbook uses it in attributes just as an FYI. I just came across this trying to run chefspec tests on OSX
```
default['nfs']['service_provider']['lock'] = Chef::Platform.find_provider_for_node node, :service
default['nfs']['service_provider']['portmap'] = Chef::Platform.find_provider_for_node node, :service
default['nfs']['service_provider']['server'] = Chef::Platform.find_provider_for_node node, :service
```

**Comment by yoshiwaan** [comment]
Are you running the suggested alternative via chef-shell or does it need a full Chef run? I get the following (on the latest ChefDK on OSX). Do I need to require something?:
```
chef > service_resource = Chef::Resource.resource_for_node(:service, node).new("lookup a provider")
 => <macosx_service[lookup a provider] @name: "lookup a provider" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :enable, :disable, :start, :stop, :restart, :reload] @action: "nothing" @updated: false @updated_by_last_action: false @supports: {:restart=>false, :reload=>false, :status=>false} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @resource_name: :macosx_service @service_name: "lookup a provider" @enabled: nil @running: nil @parameters: nil @pattern: "lookup a provider" @start_command: nil @stop_command: nil @status_command: nil @restart_command: nil @reload_command: nil @init_command: nil @priority: nil @timeout: nil @plist: nil @session_type: nil> 
chef > service_provider = Chef::ProviderResolver.new(node, service_resource, :start).resolve
NameError: uninitialized constant Chef::ProviderResolver
	from (irb):2
	from /opt/chefdk/embedded/apps/chef/lib/chef/shell.rb:76:in `block in start'
	from /opt/chefdk/embedded/apps/chef/lib/chef/shell.rb:75:in `catch'
	from /opt/chefdk/embedded/apps/chef/lib/chef/shell.rb:75:in `start'
	from /opt/chefdk/embedded/apps/chef/bin/chef-shell:37:in `<top (required)>'
	from /usr/bin/chef-shell:51:in `load'
	from /usr/bin/chef-shell:51:in `<main>'
```
@nathwill are you setting this in an attributes file or are you using it in a provider?

This is something of an annoying change when using Berkshelf and upstream cookbooks use this, the attributes are still evaluated even if you override them in a wrapper cookbook.

**Comment by yoshiwaan** [comment]
For me specifying a different platform in chefspec solved the issue. Still not sure why chef-shell wasn't working but anyway.

**Comment by lamont-granquist** [comment]
The problem is that on ubuntu 14.04 there is no concept of a uniform service since you might get sysv init scripts or might get upstart.   The proper interface to use should be:

```ruby
Chef::Resource::Service.new("ntpd").provider_for_action(:install)
```

You are guaranteed to get a service back for why-run messages, so there is the concept of a default fall-back service provider buried inside of how it looks it up:

```ruby
Chef::Resource::Service.new("doesnotmatter").provider_for_action(:install)
```

It looks like that has backcompat all the way back to 10.14.0 as well:

https://github.com/chef/minitest-chef-handler/commit/c73f308fcb6e513fc9013a0e9931f9e3f4eb95d8

And, I certainly consider that a stable interface and don't plan on changing that any time soon.  We also deprecated `Chef::Resource.resource_for_node` and replaced it with that in 12.0.  I suspect it worked up until 12.4.x-ish for some use cases because we hadn't yet fully dumped the platform map out and completed the work of migrating provider discover to the provider resolver.

**Comment by lamont-granquist** [comment]
And the default provider for Ubuntu 14.04-ish did change with 12.0 where in 11.x you used to get sysvinit, but in >=12.0 the default provider is Upstart for all upstart-enabled Ubuntus (if it detects the presence of upstart you get back upstart).  Now with Systemd taking over the world that automatically changes and if systemd is detected as the init system, then the default provider will be systemd (and since its dynamically resolved, if the user rolls back systemd back to upstart then the default provider will get rolled back to upstart, which should be comply with DWIM/DTRT).
