### ISSUE TITLE
Last Check-in is only updated on the first run of chef-client, but not on later runs 

### ISSUE THREAD

**Issue by joyalgeorge** [chef/chef#3258]
When I start chef-client, I can see the updated check-in time on chef server status page. But the following runs of chef-client do not update the check-in time anymore. I am using chef-client (chef_12.2.1-1_amd64) and server (chef-server_11.1.3-1_amd64).

**Comment by btm** [comment]
Are the subsequent runs completing successfully? That used to come from ```node[:ohai_time]``` which was only written on the ```node.save``` at the end.

**Comment by laghoule** [comment]
What's the status of this issue? I have the same problem.
chef-client is completing sucessfully and exit with code 0
chef-server 12.3.0 and chef-client 12.3.0

**Comment by joyalgeorge** [comment]
I upgraded chef server from chef-server_11.1.3-1_amd64 to chef-server-co 12.0.8-1. Now it's working fine. Sometime i need to logout and login to see the updates.

**Comment by laghoule** [comment]
When I use my old chef-client (11.8.2), it's working fine.

**Comment by laghoule** [comment]
I think it's because of this:
"[2015-06-12T17:12:54+00:00] WARN: Skipping final node save because override_runlist was given"

**Comment by laghoule** [comment]
Ok, I confirm.
If you overide the runlist on the cmdline, it will node do the node.save.

I thinks it's a little weird to not save...

**Comment by btm** [comment]
@laghoule The `-o` or `--override-runlist` option is meant to be used temporarily and doesn't save changes to the node. It is not the normal way to specify a run list. The reason it doesn't save is because if your normal run lists causes the node to be monitored (or whatever) based on its run list, the recipes that were run on it, or some dynamically generated attributes, and override run to say, just deploy an application, would likely cause that data to change on save. That would affect your search for monitoring (or whatever) until the next time you had a normal client run. [CHEF-3964](https://tickets.opscode.com/browse/CHEF-3964)

If you need a way to specify a run list from the command line for normal operation, use `-r` / `--runlist`.

**Comment by btm** [comment]
@joyalgeorge sounds like you're all set now. I'm going to close this issue.

**Comment by laghoule** [comment]
Thanks for the clarification!
