### ISSUE TITLE
Concerns about the new Chef.node API

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3275]
So I'm really worried that this new API is a line we shouldn't cross. We has so far avoided having per-run data (i.e. not truly global config et al) in globals, passing the `node` or `run_context` object through APIs as needed. This is certainly frustrating sometimes, but adding a global variable for this kind of indirection risks all the old campfire stories about global-driven spaghetti code. It is probably too late to pull this API from 12.3 but as a compromise could we mark them as explicitly internal and not subject to API compatibility? This would allow a do-over for 12.4, as I think @jkeiser is planning to majorly revamp the code that caused `Chef.node` to be added in the first place.

**Comment by ranjib** [comment]
My understanding is that Chef class static methods are intended to be a
public facing API. They are global, but they are also singleton, and this
might be fine during the chef run time, as there are only one node and
run_context(top level). Are you concerned as a raw API or from other
libraries perspective its pain? Can you give examples on how this will be
harder to maintain? Given these are methods, they can use non global
components underneath, but this enables us to access the common gears
standard way. We already discussed how the top level class based static
methods will help us maintain version specific or breaking changes etc,
hence I'm asking.

**Comment by coderanger** [comment]
It means you can never be certain if a particular method varies based on node data or not. I don't have specific examples of why global variables are bad, nor do I think specifics are really needed. It is something this field learned the hard way, keeping the values that a method has access to limited to object data (read: things passed to other methods on the same object) and method arguments allows far simpler mental modelling of how a given section of code works. I can tell you for a fact there is not a single `run_context`, for example, as `use_inline_resources` calls `dup` on it for every action that is run (and Poise/Crazytown do similar things). I would much rather see a design pattern of passing the needed data in places that need it, it adds some extra arguments in places, but it will make things far more grokkable.

**Comment by danielsdeleo** [comment]
This is only intended to be used in situations where the node isn't easily accessible otherwise, such as when library files are evaluated. Using them when not absolutely required in core code is definitely discouraged, as is already documented in the code. For example, it'd be great if we could move LWRPs inside a `Chef.lw_resource do ... end` block in libraries, which would allow you to `require` them in test code (this change would also give us a sane path to supporting subclassing). Right now, we do some magic to make node, run_context, etc. available to LWRPs at eval time, which could not be done from a top-level binding context without some form of static method. Likewise, no data can be sent to the formatters/event handlers from a top-level context, since currently these objects are directly passed to related objects. Yet another example, is Ranjib's RFC for defining event handlers in library code--we need to have access to the run context in order to add the event handler to the set.

As with any global state, there's always potential for abuse. Even in Erlang, you can screw yourself pretty good with the process dictionary if you have a mind to. That said, making these objects available as (mostly) read-only static methods goes a long way to preventing the most egregious problems with global state and gives us the option of reducing the number of specialized file evaluation contexts in the future, which I think is worthwhile.

**Comment by coderanger** [comment]
It reduces the need to build out the APIs for, say, calling Handlers by virtue of making it impossible to track what is using that data. The node object is still full of methods like `include_attribute` that can easily mutate global state. Saying "this is a huge, loaded footgun but it makes life easier" is literally the sound of tech debt being born. I agree that global state is hard to do correctly at the best of times, which is why I'm saying it is a bad idea and we shouldn't do that. As the person on the planet that has probably written the most code evaluated under `libraries/` I can say I've found better solutions to every place that a global would have allowed a lazy approach.

**Comment by danielsdeleo** [comment]
No, it's not to "make life easier," there are things we want to do that are impossible otherwise (except for `ObjectSpace`, but that's rather worse), which I listed above. That you haven't yet needed the functionality doesn't diminish the value.

**Comment by ranjib** [comment]
certain in behavior or data? currently many public facing APIs (like
resource, provider) uses these objects anyway, and they dont dupe it. Node,
run_context, events system are almost always passed on, in some way they
are already  global, this class to a great extend consolidates them. the
concern you have mentioned, is already their, you can tamper the attribute
of a node from resource, via run_context. why dont you share a concrete
example? As in a library writer would un-intentionally screw the chef run
due to this method? cause if someone is doing it intentionally i dont see
how we can stop that even without this.

on similar note, i always felt the config class was more of global state
pain, not these, cause node, run_context , events  even if global in their
essence, are implemented by pretty decent subsystems and instantiated as
object (unlike the config). Chef::Config is more prone to the problems that
you are concerned about

**Comment by coderanger** [comment]
The difference with `Chef::Config` that makes it slightly less bad is that it is immutable, but I would certainly prefer if it wasn't a magic global (perhaps a `#config` on the run context). I have not yet found a use case that ended up being impossible despite making Chef jump through some pretty serpentine hoops. That is far from an exhaustive proof, but it is a vote in the "I've not needed it" from an expert.

Due to `ObjectSpace` existing we can't ever totally prevent this, but the leap from "is possible via heap munging" to "a supported API from Chef" is a huuuuge one. This will definitely allow kinds of very clever tricks, but it does so at a huge cost to maintainability and our ability to reason about the code by looking at it locally. If this is going to be used to power some internal features, at a minimum it can be marked as a private API (in the YARD sense, not the `#private` one) which will allow for reconsideration in the future. In places where we need to zigzag through a global, we should still call to "user code" with it as an argument so they are isolated from the terribleness of globals.

**Comment by danielsdeleo** [comment]
I only brought up `ObjectSpace` because it's the only other alternative that does what we want. Of course anyone using it for anything other than memory debugging is probably misguided.

Re: `Chef::Config`, we're getting a bit off in the weeds here, but it's 100% mutable, you can change `chef_server_url`, `ssl_verify_mode`, whatever you want, at any time. I think most (all?) classes that use it should have it passed in via DI, but there's no business argument for me to spend my time refactoring all that right now.

Again, just because you've not wanted to do something that needed this API, doesn't mean it's not valuable. Registering an event handler from library code is the perfect example. You must have access to the run context (or at least the event dispatcher it owns) to do this. I'll say that what you're advocating as good OO software design is correct for the general case, which is why run context and the event dispatcher are not currently singleton classes. However, we now have use cases we want to support where these things need to be accessible from a top level binding, which is the thing you can't do with a pure-DI pattern.

**Comment by jkeiser** [comment]
Is it true that the `method_missing` and related changes will make the only use of `run_context` and `node` go away?  If so, why not privatize the API when we make those changes, and reintroduce it when we have a specific compelling use case, so that we can have a concrete discussion around that?  APIs without users are begging for trouble :)  And it *does* seem prudent to exercise caution around global APIs in particular (not a blanket disapproval, but a real note of caution).

If library event handler registration is a real potential use case (or is it an actual one?), then let's discuss that case specifically :)  Is the use case a gem that provides an event handler, and when the gem is loaded we want it to start listening to events from the run_context?

**Comment by danielsdeleo** [comment]
> Is it true that the method_missing and related changes will make the only use of run_context and node go away?

I don't see why they would. Can you explain why you think so?

> If library event handler registration is a real potential use case (or is it an actual one?), then let's discuss that case specifically :) Is the use case a gem that provides an event handler, and when the gem is loaded we want it to start listening to events from the run_context?

https://github.com/chef/chef-rfc/blob/master/rfc039-event-handler-dsl.md

These are event handlers defined in library files within cookbooks, which need to create an event handler class, instantiate it, and then register it with the event dispatch object.

**Comment by jkeiser** [comment]
> I don't see why they would. Can you explain why you think so?

I have no idea--I inferred it from @coderanger's initial comment.  Thus why I'm asking if they are true :)

**Comment by jkeiser** [comment]
> https://github.com/chef/chef-rfc/blob/master/rfc039-event-handler-dsl.md

> These are event handlers defined in library files within cookbooks, which need to create an event handler class, instantiate it, and then register it with the event dispatch object.

Ah!  So they should only attach to one run.  I grok.

Question: why not evaluate library files with a context so they can get information?  Like, instance_eval them in an object with `run_context` and `node`?  Seems like it would be generally pretty useful.

**Comment by danielsdeleo** [comment]
> Question: why not evaluate library files with a context so they can get information? Like, instance_eval them in an object with run_context and node? Seems like it would be generally pretty useful.

This makes testing pretty frustrating because there's extra magic that's not easy to find or understand happening. You can't just `require 'file_i_want_to_test'` and go, you have to set up extra magic to eval things in the right context. This also makes testing LWRPs much more difficult than necessary, since you have to figure out that you need to call the magical incantations on the relevant `LWRPBase` class.

> (This might solve the case in question, but it's actually not just about that--it feels like communicating run state to files in a cookbook/recipe as we evaluate them fits the Chef pattern pretty well.)

It may be possible to do this with terrible Binding hacks, like eval-ing library files in a specially crafted binding with the relevant things set as locals. In the case of `Chef.event_handler {}`, the event handler method would then have to grab the binding of the block and extract the locals. All of this is way more terrifying to me than just exposing some data that's pretty much exposed everywhere anyway via a static method. The binding magic is significantly more non-obvious (assuming it even works).

**Comment by jkeiser** [comment]
You can't use a `require` to correctly do it in a test anyway, unless you can guarantee a different handler load every time--in which case, there's no point in doing a require anyway, you may as well use an inline block.  Like, I don't think any test would work the way you are talking about.

As to scariness, we're already eval'ing, instance_eval'ing would be the only change.  No binding magics, just the `self` in which the library file is loaded, which is already a super typical case (`Chef::Config` for example).  No change at all to how any local variables work.

**Comment by jkeiser** [comment]
And I was about to offer that this case doesn't matter, because the library file could `require` a file from a gem that did the actual load work ... but *that* would fail on a second run in the same process because the require wouldn't even happen.  It feels like you need to pass actual context to do it right.

**Comment by jkeiser** [comment]
(To be clear, I think what @ranjib put in the RFC will totally work!  It just seems there may be a reasonable alternative that doesn't require globals.)

**Comment by danielsdeleo** [comment]
> You can't use a require to correctly do it in a test anyway, unless you can guarantee a different handler load every time--in which case, there's no point in doing a require anyway, you may as well use an inline block. Like, I don't think any test would work the way you are talking about.

You don't need to do multiple stubbed Chef runs in your test, you just need the DSL to generate the class you want to test, then you test it like you would any other class, or like we do any internal class in core chef.

> (To be clear, I think what @ranjib put in the RFC will totally work! It just seems there may be a reasonable alternative that doesn't require globals.)

I can't think of anything that isn't way worse.

**Comment by coderanger** [comment]
> I can't think of anything that isn't way worse.

I would say the better way is to use a registration pattern like we do with Resources. There is still a global, but it is hidden internally behind a method call. So `Chef.event_handler` would store the block you give it under some later time in the run (after loading the library file for example where is can instantiate the event handler and pass it the node object either via block args or an initializer. This still has a global in the mix to allow for registration, but unlike the node object it is very well defined about what state is stored and how it is manipulated. The node and run_context objects are more all over the place in what kind of data they store and how that data is mutated.

**Comment by coderanger** [comment]
As for why we don't just revisit this later, once the method hits the public API, it will be a compat break to remove it. If we mark it as internal for now, we don't have to wait for Chef 13 to finish this discussion.

**Comment by lamont-granquist** [comment]
It'd also be nice to be able to get at the CLI options from knife.rb/config.rb but that's also impossible.  The Chef class can also be extended and safely used in recipe code without worrying about the problems of injecting new methods into the recipe DSL that might clobber someone's variable names.

**Comment by lamont-granquist** [comment]
#2403 is another example of a pre-existing bug that is addressed by Chef.node and Chef.run_context

**Comment by coderanger** [comment]
@lamont-granquist Alternate solution with no global variables https://github.com/poise/poise/blob/master/lib/poise/helpers/lazy_default.rb#L20-L30
