### ISSUE TITLE
"knife status" returns incorrect time-since-last-run value if ohai_time is nil

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#3287]
If a node object's ohai_time value is "nil" then the calculated time-since-last-run value is incorrect because the "nil" gets converted to integer "0".

https://github.com/chef/chef/blob/master/lib/chef/knife/core/status_presenter.rb#L146

Please do something different to show that the node object actually doesn't have an ohai_time.

**Comment by jblaine** [comment]
Using Chef 12.3.0, I see '399189 hours' in knife status output when ohai_time is not set.

```
% knife search 'NOT ohai_time:1*' -i
14 items found
...
% knife status | grep 399189 | wc -l
   14
%
```

**Comment by cramaechi** [comment]
Perhaps we could signal a failure when a node's `ohai_time` value is nil before computing the
time-since-last-run value as illustrated by the following:

`chef/lib/chef/knife/core/status_presenter.rb `
<img width="574" alt="screen shot 2018-01-15 at 8 58 34 pm" src="https://user-images.githubusercontent.com/24444174/34969952-1eb7c9ea-fa37-11e7-9c4f-b41c6f4d259d.png">
