### ISSUE TITLE
knife bootstrap/ssh should take an --auth-methods config/cli which is passed to net-ssh-multi

### ISSUE THREAD

**Issue by sophcars** [chef/chef#3331]
Using chef-12.1.2-1, all nodes running Centos 7.

I've setup up host based ssh authentication on my nodes and can successfully ssh without passwords between them.

I start up a chef server by doing the following:
/opt/chef/bin/chef-zero -H <ip> -p 8889 -d

and try to bootstrap my nodes using knife bootstrap which takes me to a password prompt:
[root@node]# knife bootstrap <ip> -r <role>
Connecting to <ip>
Failed to authenticate root - trying password auth
Enter your password:

After doing some digging I found that knife uses the Ruby implementation of SSH, using the gem net-ssh-multi. I can't find specifically why this wouldn't work with host based authentication.

Why is it prompting me for a password and not using my host based authentication?

What would a workaround be for this if there is no solution?

Thanks in advance for the help

**Comment by jekriske** [comment]
Are you providing -i IDENTITY_FILE as in the instructions https://docs.chef.io/knife_bootstrap.html
?
I'm assuming you are issuing the knife bootstrap command from the server, not from the nodes as you posted, and I'm assuming you have the private key on the server and the pub key inside authorized keys on each of the nodes already...

**Comment by jeremiahsnapp** [comment]
I setup a host based authentication between two systems and was able to use the openssh `ssh` command to connect without a password.

I was also able to get ruby's net-ssh to use host based authentication.

```
require 'net/ssh'
Net::SSH.start("target.lxc", "ubuntu",
               :keys => [ "/etc/ssh/ssh_host_rsa_key" ],
               :auth_methods=>[ "hostbased" ]
               ) do |ssh|
  puts ssh.exec!("hostname")
end
```

However, I was not able to get `knife ssh` to use host based authentication without modifying code.

Knife uses `net/ssh/multi` to configure the ssh sessions.

https://github.com/chef/chef/blob/12.3.0/lib/chef/knife/ssh.rb#L198-L230

Knife doesn't currently give a way to set the `:auth_methods` option.

Hacking in the following line and using the `--identity-file` option to point to a host private key gets `knife ssh` working with host based authentication.

```
session_opts[:auth_methods] = ['hostbased']
```

I don't think this really qualifies as a good workaround and unfortunately I wouldn't expect this to get added as a feature soon.

I recommend implementing SSH Key Based Authentication instead since that already works with `knife ssh`.

https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Deployment_Guide/s2-ssh-configuration-keypairs.html
