### ISSUE TITLE
Knife bootstrap don't refresh vault anymore

### ISSUE THREAD

**Issue by BarthV** [chef/chef#3337]
Ohai chefs !

I'm running into a bootstrap / vault issue (probably a regression) :
* I'm using knife 12.3.0 gem install with rbenv : 
```
> knife -v
Chef: 12.3.0

> ruby -v
ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux]
```
* I'm trying to bootstrap a bare metal server who got a fresh ubuntu 12.04.5.
* I'm using my own Chef account to make the bootstrap
* bootstrap command : 
```
knife bootstrap node1.acme.org -N node1 -E prod -r 'role[uk],role[my-server],role[my-metrics-agent]' -x root
```
* I'm using a validator certificate to bootstrap the node (old fashioned way)
* My account is admin of the vault : (vault_keys content)
```
admins:
  bvessemont
  [...]
```

* my vault is configured to ```search_query:                *:*``` (yeah it's for some root password and shit ...)
* ```node1.acme.org``` is not registred in the vault (before or after the bootstrap).. not even after any other successive bootstrap operation.
* I'm using vault cookbook 1.3.0 : ``` depends 'chef-vault', '~> 1.3.0' ```
* and it __used to work__ before 12.3.0 afaik

Got this :
```
node1.acme.org   ================================================================================
node1.acme.org   Recipe Compile Error in /var/chef/cache/cookbooks/my-system/recipes/default.rb
node1.acme.org   ================================================================================
node1.acme.org   
node1.acme.org   ChefVault::Exceptions::SecretDecryption
node1.acme.org   ---------------------------------------
node1.acme.org   teamops/vault is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!
```
Classic and verbose log available here (I changed node/role/server/... name before putting it on gist): 
https://gist.github.com/BarthV/a2e960e228392f719d67

__As a workaround, I must refresh the vault after the first bootstrap attempt (so client cert is created and available in Chef server). So the vault can be loaded  using the node private cert and the bootstrap operation can go on.__

**Comment by lamont-granquist** [comment]
well this isn't the same issue as #3121 since you're not using the new bootstrapping code.  you might try using the new bootstrapping code and pass in the --chef-vault-item's that you want to grant to the client on the command line and that might actually work better.  the old workflow didn't change though.  are you sure you're getting the old workflow?  gist of the full output might be useful since there's nothing here which looks incorrect.

**Comment by BarthV** [comment]
It works with ```--bootstrap-vault-item teamops:vault``` , it is somewhat more restrictive since I've put vault search especially for this kind of job...

Now i've to specify all the needed vault item in my bootstrap, or bootstrap an empty node (if it works)

**Comment by lamont-granquist** [comment]
Only thing I can think of is the problem with the old bootstrapper uploading a blank client.pem now.

**Comment by lamont-granquist** [comment]
So ^^^ that statement is incorrect.  The problem is with the new bootstrapper, when -N is not passed, it uploads a blank client.pem.  As far as I can tell the code in the template is correctly protected for the old bootstrapper to not have changed.  Still have no idea what is going on with your issue.  Would still be useful to get a gist of the full output.

**Comment by BarthV** [comment]
I will make a simple vault test next week :)

**Comment by lamont-granquist** [comment]
Closing due to lack of response
