### ISSUE TITLE
Chef sets LC_ALL=C on restarted services

### ISSUE THREAD

**Issue by danfruehauf** [chef/chef#3367]
### Version:
 * Chef 12.2.1

### Environment
 * Ubuntu 12.04

### Scenario:
 * Trying to get a service restarted with no injected locale or other unexpected variables. In my case it completely messes up a tomcat service restart by setting a wrong locale to it (`LC_ALL=C`).

### Steps to Reproduce:
 * Run chef on a node (I'm using chef-solo)
 * Have `LC_ALL` unset
 * Make sure it restarts a service (such as apache), but anything will do

### Expected Result:
 * `LC_ALL` is not injected to restarted service
 * Verify by looking at `/proc/$pid/environ` with:
```
# set $pid to the service that was restarted
cat /proc/$pid/environ | tr "\0" "\n" | grep LC
```

### Actual Result:
 * `LC_ALL=C` in all restarted services. This is a result of those lines I believe (https://github.com/chef/chef/blob/master/lib/chef/mixin/command/unix.rb#L56):
```
unless args[:environment].has_key?("LC_ALL")
  args[:environment]["LC_ALL"] = "C"
end
```

**Comment by coderanger** [comment]
This is very intentional. To be more specific, Chef sets LC_ALL on external commands if no locale is otherwise specified because of how many programs fail to start if all locale settings are unset (a common case with Chef when run as a system service itself). With the sysvinit service provider in particular, the service process inherits from the environment of the start command (not the case with any other system I'm aware of) so if the init script itself doesn't correctly set the locale env vars, this would happen. The correct fix is to update your init script or stop using sysvinit as it is now deprecated on all major distros.

**Comment by danfruehauf** [comment]
Overriding `LC_ALL=C` is wrong behaviour. Difficult to convince me about this. If this is intentional, it's wrong.

What about the case where I have LC_CTYPE set properly but don't want LC_ALL to override it?

Sysvinit is still a reality on many supported Linux distributions (CentOS 6, Ubuntu 12.04). I think chef is supposed to support those too.

**Comment by coderanger** [comment]
(this was discussed on IRC, explained how things like locale settings generally don't apply to Chef due to shell init files not applying to services on most service frameworks)

**Comment by danfruehauf** [comment]
Discussed further more on IRC indeed. I think this behaviour is still broken. For instance this warning is also in place:
https://wiki.debian.org/Locale

```
Warning!

Using LC_ALL is strongly discouraged as it overrides everything. Please use it only when testing and never set it in a startup file.
```

I'm struggling to find an example of a decent application that will just set `LC_ALL=C` because it's convenient.

**Comment by danfruehauf** [comment]
Talking more to @coderanger he pointed out that the locale is now guessed:
https://github.com/chef/chef/blob/28b0b58a7bb4e79c9684250199a9df1ed5e3880d/lib/chef/config.rb#L693-L727

That satisfies me.
