### ISSUE TITLE
ChefDK 0.5.1 knife Needs STDERR Redirection for Cookbook Version Selection Deletion

### ISSUE THREAD

**Issue by danielsdeleo** [chef/chef#3379]
@sean-horn I moved this here, looks like a knife issue.

Zendesk 4209

Windows 7
ChefDK 0.5.1 / Chef Client 12.3.0

As a customer using Windows 7, I need the choice among deletion of multiple cookbook versions to work correctly.

Workaround: I can redirect STDERR to a file and input the correct numeric selection and the desired cookbook is deleted.

**Comment by lamont-granquist** [comment]
Oh this is a repeat of the ruby 2.1.x segfault in knife-ui bug

**Comment by adamedx** [comment]
The issue was a seg fault in the command

`knife cookbook delete cookbookname`

where `cookbookname` is a cookbook uploaded to your Chef Server with more than one version. With the latest Chef Client + ChefDK (Chef Client 12.4.1 and Chef DK 0.7.0) on Windows, this no longer reproduces and I can successfully delete cookbooks without a segmentation fault
