### ISSUE TITLE
chef-server-ctl org-show whitespace issues

### ISSUE THREAD

**Issue by sdarwin** [chef/chef#3414]
1. create a new org:
chef-server-ctl org-create test1 "Test1 Corporation" --association_user user1 --filename /files/test1-validator.pem

2. view the org:
chef-server-ctl org-show test1

full_name: Test1
guid:      622a3c511ae9345da7476bd4113218
name:      test1

Notice the full_name is not "Test1 Corporation" ?

**Comment by stevendanna** [comment]
This bug is actually in the create command and not the show command.  `chef-server-ctl org-create` wraps `knife-opc`.  It isn't quoting "Test1 Corporation" when it passes it through, so it isn't seen as one argument by knife-opc.  The `chef-server-ctl org-show` output is correct based on what actually got created.

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/fdfd8786523627cc71d12d6f57b99e795ce28903

**Comment by thommay** [comment]
I'm gonna close this. If you're still seeing this in recent versions of chef-server please open a new bug at https://github.com/chef/chef-server/issues . Thanks!
