### ISSUE TITLE
Windows service ignores interval setting

### ISSUE THREAD

**Issue by echohack** [chef/chef#3432]
Windows won't respect the interval/splay set on the node.

To quoth the documentation:

```
node["chef_client"]["interval"] - Sets Chef::Config[:interval] via command-line option for number of seconds between chef-client daemon runs. Default 1800.
node["chef_client"]["splay"] - Sets Chef::Config[:splay] via command-line option for a random amount of seconds to add to interval. Default 300.
```

Since Windows doesn't respect the above settings, it leads to the "workaround" of wanting to set it in the client.rb using ['chef_client']['config']['interval'] and ['chef_client']['config']['splay'], but this makes manual runs impossible to instantly execute. Windows WILL respect the settings for regular check-in runs in the client.rb.

Personally we think it's more painful to have to wait for manual runs (if we do a manual run, we want it to go NOW), so we choose just to use the default built in 30 minutes interval and 5 minute splay... but we'd like to be able to set this so it can be in accordance with our policy in our base cookbook.

See: https://github.com/opscode-cookbooks/chef-client/issues/235 for a full discussion of this issue.

**Comment by lamont-granquist** [comment]
That description of the problem sounds like a simple problem with the cookbook.  The actual problems according to julian, however, do involve core chef bugs:

>That detail aside, it sounds like there are two distinct issues described in this issue that need further investigation/triage:

>Manually running Chef Client on Windows causes an unnecessary delay, because interval and/or splay sleep is read from client.rb and that wait time is prepended to the run.

>The interval, ironically, is ignored when setting up the Chef Windows service, because chef-service-manager doesn't understand interval and there isn't a delightful way to teach it to do so.

>Is that a decent summary of what's going on here? Neither of these seem to be problems with the cookbook, just problems in core Chef.

**Comment by lamont-granquist** [comment]
There's already a bug somewhere about the interval and sleep (can't find it right now but I know its there), so the first half of this bug seems to be a dup of that.  Changing the title to reflect the second thing.

**Comment by lamont-granquist** [comment]
And if julian is right and there's "no delightful way to teach it to do so" then this is simply a dup of the other issue about interval/sleep and should be closed.

**Comment by jeremiahsnapp** [comment]
@lamont-granquist and @juliandunn I just added a [large comment](https://github.com/opscode-cookbooks/chef-client/issues/235#issuecomment-116989556) that should give a better explanation of this problem.

Here is the summary of the direction I'm suggesting for a fix.

The Windows service can be configured in a manner similar to the Linux service. The interval and splay can be set in the following registry key which defines the command that starts the Windows service.

```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\chef-client\ImagePath
```

Currently the default value for ImagePath is `"C:\opscode\chef\embedded\bin\ruby" "C:\opscode\chef\bin\chef-windows-service" -c C:\chef\client.rb -L C:\chef\log\client.log`. Simply appending ` -i 700 -s 30` to that value and restarting the service correctly sets the interval and splay for the service while still allowing for manually running chef-client immediately.

Some work needs to be done to both the `chef-client` cookbook as well as the Chef Client code in order to really fix this but it doesn't look very complicated.

The following link shows the `chef-service-manager` command that the `chef-client` cookbook uses to install chef as a service. This is where the chef-client cookbook needs to append new options for the interval and splay.

https://github.com/opscode-cookbooks/chef-client/blob/v4.3.0/recipes/windows_service.rb#L33

The following links show where the new interval and splay options would need to be defined in the `chef-service-manager` code.

https://github.com/chef/chef/blob/12.4.0/lib/chef/application/windows_service_manager.rb#L45-L55
https://github.com/chef/chef/blob/12.4.0/lib/chef/application/windows_service_manager.rb#L107-L109

**Comment by thommay** [comment]
ping @chef/client-windows

**Comment by echohack** [comment]
Closing due to being so long since I originally opened the issue.
