### ISSUE TITLE
Chef::REST api does not say what types of objects are returned

### ISSUE THREAD

**Issue by Tech356** [chef/chef#3453]
I recently wrote some code to generate new certs for some clients. I ran into an issue where the api call to reregister a client returns `#<Chef::ApiClient>` but the call to register a new client returns a `#<Hash>`. I would assume they would return the same type of thing. I couldn't find any [documentation](http://www.rubydoc.info/github/opscode/chef/Chef/REST) telling me what type of objects to expect. Everything I found just says returns `Object` so I had to figure it out through guess and check. 

I included my code below. The two lines of note are `private_key = r.private_key` and `private_key = r['private_key']`
    
    api = Chef::REST.new(
        chef_server_url,
        client_name=cert_name,
        signing_key_filename=cert_path
    )

    if api.get('clients').key?(my_name)
        # re-registering returns #<Chef::ApiClient>
        json = { :name => my_name, :private_key => true, :admin => false }
        r = api.put("clients/#{my_name}", json)
        private_key = r.private_key
    else
        # registering returns #<Hash>
        json = { :name => my_name, :admin => false }
        r = api.post('clients', json)
        private_key = r['private_key']
    end

    File.open(client_key_path, "w") do |f|
        f.print(private_key)
    end

**Comment by lamont-granquist** [comment]
So our documentation sucks on various levels, it'd be better to either open a PR against the chef-docs repo:

https://github.com/chef/chef-docs/issues/new

Or to issue a PR against this repo to add YARD documentation to the code.  Otherwise this issue isn't very useful for prioritization and we know that we need better documentation and we're trying to work on it (e.g. a261c2c6954a6e3c682ff40a4c82d30ed994bdd8, 320aa0fe43158c8c89bfab7f1494271eb9da7cd).
