### ISSUE TITLE
Implement RFC-040 and solve the oft requested recursive library loading problem

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#3494]
https://github.com/chef/chef-rfc/blob/master/rfc040-on-demand-cookbook-libraries.md

**Comment by kamaradclimber** [comment]
I would be really interested by having this one.
Our use case is the following:

we often add a libraries/kitchen_patch.rb file to override attributes values or library code for kitchen/chefspec.
The idea is that a cookbook should not require any modification by users when used in kitchen/chefspec. It allows us to mock interaction with some external api to avoid every user to rewrite the same mocking code in cookbooks depending on this one.

However, because of library loading (instead of require) and alphabetical loading of files, this technique is harder to implement.

We are either forced to move the file to zz_kitchen_patch (very unelegant) or patch the original libraries to detect they've already been loaded once and skip other loading (reimplementing require logic).

**Comment by lamont-granquist** [comment]
john left the company and its not on anyone's radar at all.

i don't know why i put it high priority, its certainly not being treated that way.

**Comment by kamaradclimber** [comment]
ok thx for the update @lamont-granquist
