### ISSUE TITLE
Windows service 'run_as_user' param does not work and clobbers existing permissions

### ISSUE THREAD

**Issue by tadrinth** [chef/chef#3521]
The changes made in be28ba9 introduced support for running a windows service as a specific user by passing 'run_as_user' and 'run_as_password'.

I can't find any documentation of this feature other than the ticket which added it.

This feature first assigns the service to run as the specified user using the specified password.  This part works, although I needed to specify HOSTNAME/username, not just username.  You cannot specify the SID when using Win32::Service.configure.

The second part attempts to grant the user the right to log on as a service.  This part does not work.  First, the method it uses appears to require the SID of the user, but the code just passes the username.   I believe the correct fix is to look up the SID for the provided username and pass that:
wmic useraccount where name='USERNAME' get sid

A far worse issue is that it does not look up the existing permissions.  It just applies a permissions file.  This will completely clobber any existing users that have the right to logon as a service.  I believe it should pull the current list, then append the provided user as necessary.

**Comment by GregAndo** [comment]
I personally feel that this is two issues, one being the complete failure of "run_as_user" to work at all which I think is major - the functionality doesn't work at all and breaks the chef run.

The first issue is in my opinion a show-stopper.  What tadrinth failed to mention which I think is the key to getting this issue escalated, is that the chef-client run dies the moment the cookbook specifies run_as_user credentials.  This is more than not working as expected.  Tadrinth is also correct, documentations is not great here.  I was able to find doco but it doesn't specify that the server/domain name (or ".\" in place of server name) is required in front of the username to make the configuration for run_as_user take effect.

But even if you do this, the chef-client run will still die.  Digging into the code, I find that in windows.rb on line ~244, an explicit "\\" is inserted in front of the user name before it is added tot the text file being sent to scedit.exe - which ironically would work if there was no need to specify the server name and \ in front of the user name.  Removing these two slashes (technically \\\\ as they need to be escaped) will allow the chef-client run to successfully complete if you do correctly specify either ".\" or "SERVERNAME\" or "DOMAINNAME\" in front of the username.  This is a very simple fix and I hope someone can make this urgently to at least get chef-client to complete, and restore functionality for users only using a single service account to start service(s) on a server.

The second issue would be the clobbering problem.  I have confirmed this is the case through testing:
 - Manually restarting any service configured with run_as_user (except the last one chef configured) will fail, and the service will generally never start again.
 - The same happens upon rebooting the server.
 - This means the same will happen if the service fails.
 - The only workaround is to reconfigure (and effectively restart) the service every chef run, which is not a solution for many reasons I think are obvious and won't cover here.
 - Everything I have specified here is only an issue if you can work around the first issue above, as realistically the service won't actually ever start in the real world in the first place.

Maybe the resolution for the second issue would be to require log on as a service to be configured separately from the service credentials?

For us, the issue is going to prevent us running chef in our enterprise, and is a show stopper for our proof of concept.

**Comment by GregAndo** [comment]
Also tadrinth, I am not aware of a way to configure a service to run as a user via SID.  Do you know of a way to do this?  The Microsoft methods used by the code do not seem to support SID...

**Comment by GregAndo** [comment]
An update on the clobber issue, if you correctly specify the run_as_user credentials before all service start/restart resources, the services will actually start upon the next chef run correctly after all.  If you leave them out the chef run will fail.  There is no built in way that I can find to configure windows_service to detect the service name has changed and take action (IE run_as_user is ignored on :configure_startup) so I had to spend the time detecting this myself and coding in a not_if.  I had not been specifying the run_as_user credentials in the :start action as a result.  After doing this, the chef-client run will start the services, but if they fall over or the OS is rebooted, the services will not start automatically on boot or via manual intervention.  This means either waiting for the chef-client to run automatically (making automatic start a moot point) or by logging in and manually starting a chef-client run.  Not really ideal, but at least it actually works - but again - only if you hack windows.rb with my fix mentioned earlier.

**Comment by mwrock** [comment]
For part 2 we need to add the ruby FFI equivilent of https://github.com/mwrock/chef-minecraft/blob/master/templates/default/LsaWrapper.ps1.erb to our the win32 code
