### ISSUE TITLE
Add attribute blacklisting to complement `automatic_attribute_whitelist`

### ISSUE THREAD

**Issue by patcon** [chef/chef#3533]
Heyo! I'm working with a tool called `knife-zero`, which allows provisioning of remote machines with chef-zero running in localmode, such that the node objects are written to local disk. This is great, except that there is tons of noise in that automatic attributes that get saved, and it can be confusing for version controlling the node objects sensibly.

I was hopeful that it might be simple to add blacklisting capabilities to `client.rb`. This makes me think it's close, but I'm not sure how this connects with the `automatic_attribute_whitelist` config key:
https://github.com/chef/chef/blob/59da09f64b72dbd712c890f999322493a4bc9ec4/lib/chef/node_map.rb#L157

Any thoughts?

Ref: https://github.com/higanworks/knife-zero/issues/39
cc: @mcquin (saw in another issue that this is your handiwork :)

**Comment by rmoriz** [comment]
Had the same problem, but learned that when you use `knife node edit <nodename>` you get a very clean view of node object, all automatic attributes wont get displayed.

I've experimented with empty "_whitelist" options in `client.rb` because I was editing the plain json files directly in an editor but in the end I decided, that I want to have persisted attributes, so I can finally use search in a "non-server" setup (coming from knife-solo/chef-solo).

The same "issue" also occur when running `chef-provisioning` as it creates a local node object (e.g. your mac) on the fly when provisioning remote nodes. Luckily with OSX and Zeroconf, my local host name(s) end in ".local" so It was easy to add a .gitignore entry in this case.

**Comment by patcon** [comment]
Interesting. Thanks for the use-case story.

I agree that I want local searching, but I just never search on the things that change constantly (counters, filesystem size, timestamps, etc.) so I think I could pretty safely reel that in with a blacklist :)

**Comment by rmoriz** [comment]
yes, but IMHO it is cumbersome to black/whitelist specified parts of ohai data. That said, there is a community project at https://github.com/irccloud/blacklist-node-attrs which may help, if you really, really don't want to sync the data…

**Comment by sawanoboly** [comment]
:+1:

**Comment by patcon** [comment]
Nice! Thanks! fwiw this one seems a bit better: https://github.com/hpcloud/blacklist_node_attrs

**Comment by rmoriz** [comment]
@patcon nice. looks indeed better and it's available on supermarket, too.

**Comment by lamont-granquist** [comment]
This seems to:

- Clearly have a demand for the feature
- Is not easy to search for
- Is named inconsistently (automatic_attributes_whitelist vs blacklist_node_attrs)

It seems like we should pull this into core and make it consistent and document it and make it easy to use.

**Comment by robmul** [comment]
a method of node attribute blacklisting that is consistent with whitelisting has been added.
maybe this should be closed?
https://github.com/chef/chef/pull/5868
