### ISSUE TITLE
Cannot bootstrap node when using --bootstrap-vault-item

### ISSUE THREAD

**Issue by shoekstra** [chef/chef#3537]
Hi,

I'm experiencing a problem when trying to bootstrap a node using the `--bootstrap-vault-item` option.  The bootstrap process runs as normal: it connects to the host, downloads and installs Chef client, but fails on the first run:

```
$ knife bootstrap node1 -N node1 --sudo -r 'recipe[baseline_role::default]' --bootstrap-vault-item 'some_vault:some_item'
Creating new client for node1
Creating new node for node1
WARNING: No clients were returned from search, you may not have got what you expected!!
Connecting to node1
node1 Starting first Chef Client run...
node1 Starting Chef Client, version 12.2.1
node1 Creating a new client identity for node1 using the validator key.
node1
node1 ================================================================================
node1 Chef encountered an error attempting to create the client "node1"
node1 ================================================================================
node1
node1 Authorization Error:
node1 --------------------
node1 Your validation client is not authorized to create the client for this node (HTTP 403).
node1
node1 Possible Causes:
node1 ----------------
node1 * There may already be a client named "node1"
node1 * Your validation client (corpit-validator) may have misconfigured authorization permissions.
node1
node1 [2015-06-15T19:31:10+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
node1 Chef Client failed. 0 resources updated in 2.309109113 seconds
node1 [2015-06-15T19:31:10+02:00] ERROR: 403 "Forbidden"
node1 [2015-06-15T19:31:10+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

I am able to bootstrap nodes without the `--bootstrap-vault-item` option, so that negates the `Your validation client is not authorized to create the client for this node` line.

I believe the problem relates to the line `There may already be a client named "node1"`, as before my workstation connects to the node I see the lines `Creating new client for node1` and `Creating new node for node1`; this makes me think the problem is that because the client already exists on the Chef server, when the node tries to generate/request a certificate it cannot as there is already a client with that name (running `knife client list` after a failed bootstrap shows the node name):

I'm not sure where to go from here and am looking for some pointers as to what to look at next.  Any pointers where to look next would be greatly appreciated as for now I'm bootstrapping, manually updating the chef vault and running chef-client again.

Stephen

**Comment by lamont-granquist** [comment]
That doesn't make a lot of sense.  If you had a client or node it would have prompted you when it was creating them at first.  Then it fails to find them from search, which indicates the client being 'published' through the rabbitmq to solr took a long time.  Then you got a validation key uploaded to the client, and it seems to have failed to find the client again, and tried to create it with the validator and then failed because it found the client and couldn't create it.

First thing is that the chef-vault stuff always uses validatorless bootstraps so you can delete your validation key and stop uploading that to servers.  It looks like there's a slight usability bug there in that when we wind up on the chef-vault path we will upload a validation key even though we shouldn't be using it and it can only go wrong in this way.  You can fix that though by deleting/renaming it or unsetting the knife config var for it.

Then it looks like you've got very slow solr ingestion.  If you're not on Chef Server 12 you should really get onto it since the solr4 in it drops typical ingestion times from around 1 minute to 1 second.  If you're on hosted or hitting a Chef 12 server then that'd be weird, and maybe your hitting the server with so many writes per second that your rabbitmq queues are very long (e.g. you have thousands of servers all firing of chef-client runs at the top of the hour and creating a thundering herd and this run happened to hit then, or something else is misconfigured and causing long search backups).

**Comment by shoekstra** [comment]
After discussing with a colleague earlier we came to a similar conclusion: the client key is not being copied to the client, so it tries to register itself again using the validator key (like in the standard bootstrap process) and because a client with the same name exists, it fails.

Good point re solr, I hadn't dug into that much as I wanted to resolve bootstrapping a node first. We are using Chef 11 and are in the process of upgrading to Chef 12 - definitely a good reason to put more effort into making it happen.

And yes, we do indeed use a custom bootstrap template, I'll compare it with a recent Chef provided template and get back to you after some testing tomorrow. Thanks for the pointer!

**Comment by lamont-granquist** [comment]
Yeah, I'm not sure how to catch the fact that someone is using an old bootstrap template that doesn't do the correct work and at least warn them somehow.  I think this is the first instance where old templates become kind of broken with new bootstrapper behavior (its not really a backcompat bug since the chef-vault stuff and validatorless bootstrapping is new) and I'm not sure if its possible to 'catch' that in any way.  Ideally we'd do something to make bootstrapping a bit more composable so that if you wanted to modify the process you could still 'inherit' most of the behavior that ships in the client and then just override or add what you like.

But yeah, if you fix your templates it should mostly start working.  Chef Server 12 will completely fix the search ingestion delays via solr4.

**Comment by lamont-granquist** [comment]
So closing this as we're unlikely to spend the resources to try to work around the search delays on Chef Server 11, and I can't think of a good way to help people out who have old templates that don't work with the validatorless bootstraps, so its not actionable.  Can be re-opened or a new ticket cut if someone comes up with thoughts on how to provide a better UX.
