### ISSUE TITLE
chef-client for network device?

### ISSUE THREAD

**Issue by ensean** [chef/chef#3583]
From the doc https://docs.chef.io/nodes.html#manage-nodes, chef can manage network nodes
But I can not find the chef-client for network device, can anyone help? 

Thanks a lot

**Comment by rmoriz** [comment]
depends on your network-device/vendor…

e.g.  http://www.juniper.net/techpubs/en_US/release-independent/junos-chef/information-products/pathway-pages/

**Comment by ensean** [comment]
so, network chef client is released by device vendors?

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
