### ISSUE TITLE
Knife does not detect winrm when called from Jenkins.

### ISSUE THREAD

**Issue by Infydevops** [chef/chef#3601]
I have a jenkins setup where my Chef workstation is a jenkins slave. I need to invoke "Knife Winrm" from my chef workstation (jenkins slave) to run chef client on few machines. 
When I run "Knife Winrm" from the command prompt from of my workstation everything works fine but when I run the jenkins job - knife does not detect winrm. I have ensured that there are no two knife/ruby installs on the machine. 

More details are available on this page :
http://stackoverflow.com/questions/31053333/knife-does-not-detect-winrm-when-called-from-jenkins

Thanks,
Sandeep.

**Comment by lamont-granquist** [comment]
This is bug tracker, not a general purpose help list.  Your Stack Overflow question is a more appropriate place to ask this question, as is IRC or E-Mail (and since the same set of people typically monitor all four locations it is generally polite not to spam all those locations with the same question).
