### ISSUE TITLE
Chef 12.4.0 changed the interface of Chef::User

### ISSUE THREAD

**Issue by jaym** [chef/chef#3628]
This breaks things, for example chef-vault:
https://github.com/Nordstrom/chef-vault/issues/175

**Comment by jaym** [comment]
The plan for this:
- Default to V0 of the rest api. 
- `Chef::User` becomes `Chef::UserV1` 
- `Chef::OscUser` will become `Chef::User` preserving the old ruby api

cc @chef/client-maintainers @stevendanna @tylercloke

**Comment by tylercloke** [comment]
Actually, the one thing I disagree with is rest defaulting to V0. This will mean that once V0 is out of date, a client that otherwise supports V1 will not work, even though V1 vs V0 only affects users and clients. What we should do is default Chef::User (currently Chef::OscUser) to use V0. That will fix all current bugs related to which version of the API is used, but everything else should default to V1 as they are not affected by changes between those versions of the API and shouldn't fail due to api versioning.

**Comment by tylercloke** [comment]
Other than that :+1:

**Comment by tylercloke** [comment]
https://github.com/chef/chef/pull/3630
