### ISSUE TITLE
Can we automate Appliances like DataPower using chef

### ISSUE THREAD

**Issue by Dhananjaiah** [chef/chef#3653]
Hi,

I am working to automate DataPower using chef.
As DataPower is an appliance Am unable to  automate anytasks using bootstrap.

Is there any way that we can automate DataPower or have a cookbook for the same using chef.

Please help me.

Regards,
Dhananjaiah Maroju.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
