### ISSUE TITLE
Apt provider can't install packages from different default release

### ISSUE THREAD

**Issue by mconigliaro** [chef/chef#3694]
I'm running into a problem on 12.4.0 that was supposedly fixed in 0.10 via [CHEF-1547](https://tickets.opscode.com/browse/CHEF-1547). 

Consider the following:

```
package 'haproxy' do
  options "-t #{node['lsb']['codename']}-backports"
end
```

Chef runs this command:

```
apt-get -q -y -t trusty-backports install haproxy=1.4.24-2ubuntu0.1
```

Somehow the version from the default release is being appended there, and I believe that's preventing the version from backports from being installed.

Running the command manually (without specifying a version) does the right thing:

```
# apt-get install haproxy -t trusty-backports
# haproxy --version
HA-Proxy version 1.5.3 2014/07/25
```

**Comment by congaframe** [comment]
Same here, install it manually work fine.
But Chef couldn't install the right version.
```
apt_repository 'jessie-backports' do
  uri        'http://http.debian.net/debian'
  distribution 'jessie-backports'
  components ['main']

end

package 'haproxy' do
    
    options "-t jessie-backports"
    action :install
end
```

**Comment by sandervanburken** [comment]
Setting the `default_release` property resolved this issue for me.

My package resource is managed by a community cookbook. So I had to use this work around to set this property in my wrapper cookbook:
<pre>
r = resources(package: 'haproxy')
r.default_release('trusty-backports')
</pre>

**Comment by lamont-granquist** [comment]
Setting the default_release is the correct way to do this otherwise the apt-cache command to find the available versions only searches apt cache for the current version.

I would consider merging a PR which added a property which set set both the `-t` option to apt-get install and the appropriate default_release to the apt-cache command.  But that would need to be a new property and not do silly new_resource.options parsing to determine if -t was being passed -- that would be a hard not-accepted patch.  Care would need to be taken though to consider the edge cases of if the new property was given in conjunction with the default_release property (probably fail if both are given -- i wouldn't care what happens if the user passes -t in the options string since that is on them).

As there's a functional workaround and this is an edge case, this is so low of a priority though that we aren't going to do the work so I'm going to close this.
