### ISSUE TITLE
knife ssh with an SSH private key that's not a file (gpg-agent)

### ISSUE THREAD

**Issue by gregkare** [chef/chef#3814]
### Version:

12.4.1

### Environment:

Client machine is OS X, Linux servers

### Scenario:

I started using a GPG smartcard as an SSH key a few months ago and never realised I can't use `knife ssh` anymore. It looks like net-ssh-multi is ignoring the gpg-agent I'm using as `SSH_AUTH_SOCK`. If I copy a public key from a private file and pass it as the identity it will work. At first I thought it was an issue with an SSH gateway but I have the same issue with a simpler case:

### Steps to Reproduce:

This might be hard to reproduce since my issue is caused by using gpg-agent as my ssh agent

```
knife ssh "name:server_name" "hostname" -x user -VVV
[snip]
DEBUG: received packet nr 6 type 51 len 28
DEBUG: allowed methods: publickey
ERROR: all authorization methods failed (tried none, publickey)
WARNING: Failed to connect to server_name -- Net::SSH::AuthenticationFailed: Authentication failed for user user@server_name@server_name
DEBUG: ~/chef/vendor/gems/ruby/2.2.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:194:in `rescue in new_session'
DEBUG: ~/chef/vendor/gems/ruby/2.2.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:183:in `new_session'
DEBUG: ~/chef/vendor/gems/ruby/2.2.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
DEBUG: ~/chef/vendor/gems/ruby/2.2.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
DEBUG: ~/chef/vendor/gems/ruby/2.2.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
```

Is that a known issue? Should it be filled to net-ssh-multi (or some other dependency) instead?

**Comment by ranjib** [comment]
i think you have to check this with net-ssh & net-ssh-multi ,  it will be considerably harder for us to test this out.

**Comment by lamont-granquist** [comment]
Yeah, we'd need to know if this is a bug in net-ssh/net-ssh-multi or if there's something we need to fix.  Generally, these kinds of bugs have been in net-ssh in the past (like ecsda key support, etc.).  Closing this since its unlikely that we're going to do the legwork to research the problem, and i'm betting it eventually just gets fixed upstream and we wind up pulling from that.

If there is a bug to fix in our code, whoever finds it can open a PR with the fix (this is low priority so without a PR contribution its unlikely to get fixed).
