### ISSUE TITLE
CVE-2015-8559: knife bootstrap leaks validator.pem private key into system logs

### ISSUE THREAD

**Issue by jschauma** [chef/chef#3871]
When you 'knife bootstrap' a node, the validator.pem private RSA key is leaked into the system logs /var/log/messages.

The reason is that 'knife bootstrap' constructs a shell command to run on the node from a template, filling the private key in as a here-doc (see https://github.com/chef/chef/blob/81419cc617091461b8a78c93276e00a7276484df/lib/chef/knife/bootstrap/templates/chef-full.erb#L193). This command is invoked via (more or less):

ssh node 'sudo sh -c full-command-goes-here'

As a result, the private key ends up on the command-line, in the process table, and, by way of sudo command logging on most reasonable systems, in the system logs. The logs may also be forwarded to other places (possibly in clear text), and possible stored on other systems, making the private validator key not quite so private any more.

**Comment by lamont-granquist** [comment]
I can't recall but I suspect this is also a problem with the validatorless bootstrapping as well, which copies client.pem up to the node instead validation.pem.

It would be very good not to tactically patch this but to pull more of dan's boostrapper code into knife bootstrap.  The big shell command is shitty for so many other reasons as well...

**Comment by bdangit** [comment]
:+1: any traction on this?

**Comment by lamont-granquist** [comment]
Its being worked on internally, no ETA right now.  Since we need to support unix and windows bootstraps, we need a transport abstraction over at least winrm and ssh.  That already exists in several places (test-kitchen/chef-provisioning) but needs to get extracted out into its own library.  Then mixlib-install and that "mixlib-transport" need to be glued together in knife bootstrap (then those mixlibs need to be patched into test-kichen/chef-provisioning in order to DRY up the code across all the projects).  So, its highish priority, but we're trying to engineer it right.

**Comment by jschauma** [comment]
Possible quick band-aid solution:

Instead of

ssh node 'sudo sh -c 'shell script with here-docs'

use

echo 'shell script with here-docs' | ssh node "sudo sh"

This allows the shell on the remote system to read and execute commands from stdin, without having everything on the command-line.  This also has the benefit of only using a single ssh connection (compared to the possibility of creating the script as a file and scp(1)'ing the file to the remote side for execution).

Either way, please do note that this issue does not only affect the validator key, but other materials as well (for example, the 'encrypted_data_bag_secret').  Also note the race condition noted in https://github.com/chef/chef/issues/3872.

**Comment by lamont-granquist** [comment]
Yeah we've noted all the other issues with it, that's a large part of why we want to not do any quick fixes, its already a large enough collection of band-aids.

**Comment by jschauma** [comment]
FYI: MITRE has assigned CVE-2015-8559 for this issue.

**Comment by Purple90** [comment]
Is there any progress on this?

**Comment by pfsmorigo** [comment]
Any update?

**Comment by btm** [comment]
The big portion of this that was ending up in system logs was fixed in Chef 15 by replacing the internal mechanisms for running commands with the train transport library. Rather than running one large heredoc, train allows us to copy a file over and run The initial work was done in #8253 and #8419 primarily. 

There's still an issue with the `ps` output that should be an easy fix that will tackle soon.

**Comment by vsingh-msys** [comment]
Fixed in #8885 

I think we can close it?
