### ISSUE TITLE
knife bootstrap has a race condition between file creation and chmod(1)

### ISSUE THREAD

**Issue by jschauma** [chef/chef#3872]
The knife bootstrap command in https://github.com/chef/chef/blob/81419cc617091461b8a78c93276e00a7276484df/lib/chef/knife/bootstrap/templates/chef-full.erb creates private files via here-doc cat(1)ing followed by running chmod(1) and setting the permissions.

This is a race condition if the default umask creates files world- or group-readable (as is almost universally the case).

Fix: set 'umask 077' at the beginning of the script instead of chmod(1)ing after creation. (Care must be taken to create all other resources with the appropriate explicit permissions as needed, e.g. 'mkdir -m 0755 -p /whatever' etc.)

**Comment by btm** [comment]
The bootstrap script does [set umask in a subshell](https://github.com/chef/chef/blob/81419cc617091461b8a78c93276e00a7276484df/lib/chef/knife/bootstrap/templates/chef-full.erb#L12) when creating the temp directory

We could probably wrap the three `cat` commands that we subsequently `chmod` in a subshell as well with `umask 077` first instead of the chmod.

https://github.com/chef/chef/blob/81419cc617091461b8a78c93276e00a7276484df/lib/chef/knife/bootstrap/templates/chef-full.erb#L184-L203

**Comment by Nimesh-Msys** [comment]
Fixed in #8895
