### ISSUE TITLE
ERROR: RuntimeError: Please set EDITOR environment variable on GitBash (Windows)

### ISSUE THREAD

**Issue by satinrichu** [chef/chef#3922]
Hello
Can someone please guide me on how to fix this error "ERROR: RuntimeError: Please set EDITOR environment variable". I have tried to set environment variable for this editor path as well as updated in knife.rb and still continue to see this. Please advise

**Comment by lamont-granquist** [comment]
You're going to have to include more context like what command you are running and a copy-paste of the output or we're unlikely to be able to help you at all.  You may also be better off asking usage questions on stackoverflow, the mailing list, and/or the IRC channel.  Right now this does not look like an actionable bug report.

**Comment by satinrichu** [comment]
Thanks lamont. I was able to fix this today. I would require assistance now on fixing knife vault update . I am getting an error message stating that "can not find sub command" when i am trying to update vault for one of my pre prod environments thru local git bash. Please advise what i could be missing here. I have gone thru stackoverflow page and nothing concrete about it and i am on Windows machine.

**Comment by lamont-granquist** [comment]
Sorry, this is a bugtracker, not a support channel or stackoverflow...

Our boilerplate support answer:

Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
