### ISSUE TITLE
Implement zap-like functionality in chef core resources and LWRPs

### ISSUE THREAD

**Issue by patcon** [chef/chef#3956]
Ref: https://github.com/nvwls/zap

I assume there's been some discussion about it somewhere, since the concept seemed well-presented at ChefConf, but didn't see an issue for it :)

Anyone have any thoughts or things to share on the general premise?

cc: @nvwls @svanharmelen @helgi @damm
cc: @ranjib (curious about your internal library: https://github.com/chef/chef/issues/3616#issuecomment-116914334)

**Comment by lamont-granquist** [comment]
I don't quite like the implementation of zap since it has issues with resources in sub-resource collections inside of resources and providers.   It probably needs to hook the event system to watch for resources running, and then collect a list of the ones that ran, then register an event_handler to do the cleanup at the very end of the run.  It might actually be cleaner to do it in core chef, but I'd like to see an implementation in a cookbook that tried to get it more correct first.

**Comment by lamont-granquist** [comment]
Zap's issues:

1.  use_inline_resource resources inside of providers are missed (PR #1415 attempted to address this)
2.  partial runs (override run_lists) can wind up zapping files that are referenced in recipes not running (i.e. zap should not zap files with override run lists)
3.  aborted runs can wind up with the same problem as files which were not yet managed at the time chef aborts will not be seen on the resource collection, but the delayed notification to the zap cleanup resource will fire and will clean resources it should not (i.e. zap should not zap files if chef client aborts)

In core chef we should also consider a way of incorporating this into existing resources.  For example, the directory resource could take a 'zap true' property instead of having a new zap resource.  Or at any rate the shape of the API should be considered.

**Comment by damm** [comment]
I suspect handling case 2 and 3 would be difficult without storing all the resources somewhere (node seems overloaded; this would hyperoverload it)

**Comment by lamont-granquist** [comment]
Well 2 is pretty easy -- when the run_list is overridden just never zap -- similar to node.save being a no-op when that happens.

3 would also be fairly easy if zap-cleanup was implemented as a custom handler rather than a delayed notification (since we're talking about incorporating into core chef, it could look like the reboot handler).

1 is the hard problem that requires tracking all the resources in the run completely.  One way to solve this would be to add pointers to the sub-resource collection hanging off of parent resource collections or hanging off of the run_context in some way so that they wouldn't get garbage collected and could be iterated at the end.  Another possibility is hooking the events system when resources fire and building a parallel container with all the resources that have been evaluated in converge mode.

**Comment by lamont-granquist** [comment]
#8063 exposes the Chef::ActionCollection which is the thing which can be used to address nvwls/zap#35 sub-resource collection concerns.  Not only that but it also captures e.g. manually created file resources from someone just going to town with Chef::Resource::File.new like its still Chef 0.10.8...
