### ISSUE TITLE
Add ability to notify from inside LWRP to wrapping resource_collections

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4017]
This has wound up finally irritating me.

In the case where you've got multiple statements to manage config files (e.g plugins) but the underlying system correctly supports conf.d style management, there's no need to use an accumulator and no need to use a definition.  I'd like to be able to easily use an LWRP to get all the resource goodness out of that.

But if we break up our resources into service and plugin LWRPs then our recipe code looks like this:

```ruby
foo_plugin "bar1" do
  # stuff
  notifies :restart, "foo_service[instance]"
end

foo_plugin "bar2" do
  # stuff
  notifies :restart, "foo_service[instance]"
end

[...repeated for all the plugins...]

foo_service "instance" do
  action [ :enable, :start ]
end
```

I'd prefer to wrap that repeated notification into the LWRP to keep it DRY and so the user doesn't need to remember it and doesn't forget it.  While the code could be simplified by a loop in the trivial case, if the `#stuff` varies in each plugin then you can't easily use looping constructs to build the plugin resources.  We also *could* use a definition here instead to avoid building another run_context/resource_collection, but I'd prefer not to.

So, I'd like the ability to bubble up the notifications.

cc: @jkeiser @coderanger @danielsdeleo

**Comment by lamont-granquist** [comment]
Can we do this just via having run_context's have a :parent accessor to maintain a tree structure back up to the root run_context, then make a change to notifications so that if they don't find a resource in the current resource_collection they'll follow that parent point back up to the root looking for resources?

**Comment by lamont-granquist** [comment]
I don't think this is breaking, but if it is breaking then make the argument and we can bump it to Chef 13.

**Comment by lamont-granquist** [comment]
(We can also just have a use_inline_resources-style directive for 12.x and then make it the default in 13.x)

**Comment by coderanger** [comment]
Am obviously :+1: on this, my implementations have always behaved this way :) The biggest issue is how it interacts with resource cloning. My solution on that front was to just disable it (and I think John did the same), so this might have to wait until we nuke that to turn on globally.

**Comment by lamont-granquist** [comment]
For 12.x can we pick some heuristic like it selects the last-cloned resource in the resource collection, with the qualification that it also requires a directive to turn the feature on?  And is it sufficient to stop cloning or do you mean we also need to make the names in the resource collection unique and enforce that (i.e. `package "zlib-devel"` twice in the same resource_collection would be a hard error?)

**Comment by coderanger** [comment]
So the specific implementation that I've used for the past few years is to override `ResourceCollection#lookup` to check parent contexts on error. That results in both notifications mostly JFWing (give or take some decision about when delayed notifications happen, end of sub-converge or end of the overall converge). The downside is that it means a resource in a sub-converge can clone something from an outer context. That can end up being really confusing.

**Comment by nathwill** [comment]
i'm generally :+1: on the idea, but a little meh as well, as there's some really weird edge cases.

 - why not just flatten the run_contexts?
 - obvious concern about impact on existing cookbooks with resource cloning.
 - what if the LWRP is used without including the recipe providing the external resource? iirc, notifying a non-existent resource explodes the converge.
 - i *like* that providers have to contain everything required to provide a resource. it feels clean and right.
 - letting provider resources reach outside the provider feels like a net loss for reusability, since most cookbook authors aren't very good about modularizing their recipes. better i think to encourage resources that can stand alone.

it's also already pretty easy to determine if an action needs to be run in the parent run_context due to changes in LWRPs already, using [this kind of pattern](https://raw.githubusercontent.com/nathwill/chef-systemd/master/recipes/daemon_reload.rb).

**Comment by lamont-granquist** [comment]
What do you mean by "flatten the run_contexts"?  And how do you maintain the encapsulation you like in your fourth point if you do that?

Resource cloning we already know needs to to be removed, so that's not a huge objection in my eyes, and we can just adopt a heuristic.

I just don't see the possibility that the resource might not have been created in the parent context to be a compelling reason to not do this.

With the ability of providers to walk the resource collection this can be used as a way to eliminate the pattern of implementing accumulators using definitions and then providers can be responsible for asserting that their parent resource collection contains the resource they want to target.  This makes them self-contained again so that they manage all their concerns and completely eliminates the problem of notifying resources that don't exist.

That pattern looks like its only going to be useful to gather requests and run them late, which doesn't address the multipackage cookbook case of wanting to accumulate packages and install them early so that other cookbooks can depend on them (or the iptables or sysctl where you want to do those accumulated actions early so that later recipes can depend on their state being setup).

**Comment by nathwill** [comment]
> how do you maintain the encapsulation you like in your fourth point if you do that?

sorry, i don't brain too good late at night apparently, but your summation is exactly the point i meant to convey. "if there's no encapsulation, why bother separating them in the first place."

> I just don't see the possibility that the resource might not have been created in the parent context to be a compelling reason to not do this.

OK.

> That pattern looks like its only going to be useful to gather requests and run them late

Yes, as written (with the :converge_complete subscription), but there are of course other events you can subscribe to if you don't mind drinking from the fire-hose (`:resource_*` events look promising for this).

Another interesting idea for the described use case (conf.d type stuff) would be an enhancement to the current subscribes mechanism to support subscription to a particular resource *type* (maybe expressed as `subscribes :reload, "my_resource[*]", :immediately`?), which i think handily addresses the conf.d use-case as well.

> the iptables or sysctl where you want to do those accumulated actions early

i get your point (that timing is tricky, though i think applying iptables early is a Bad Idea, and sysctl are easily addressed via `sysctl -w`), but i think the use case (sub-configs triggering action in a "parent") described is best addressed through subscription rather than notification.

the core issue seems to be the pain of notifying the sub-config consuming resource (most likely a service) when a resource for a sub-config is altered, without relying on the users to have to attach notifications to every instance of the sub-config resource, which i've definitely griped about before. i just found out about event_handlers, but i'm pretty excited about 'em, specifically because of the fact that they can help address this conf.d use-case.

to get a little more tangible about what i mean, here's a contrived example using monit:

```ruby
# pretend this is the install recipe in the monit cookbook
package 'monit'

# pretend this is the service recipe in the monit cookbook
service 'monit' do
  action [:enable, :start]
end

Chef.event_handler do
  on :resource_updated do |resource, action|
    if resource.is_a?(Chef::Resource::MonitCheck)
      Chef.run_context.resource_collection.select do |r|
        r.to_s == 'service[monit]'
      end.first.run_action(:reload)
    end
  end
end

# pretend this is in a wrapper cookbook
monit_check 'sshd' do
  check_id '/var/run/sshd.pid'
  tests [
    {
      'condition' => 'failed port 22 proto ssh',
      'action' => 'unmonitor'
    }
  ]
end
```

and the run log:

```
       Converging 3 resources
       Recipe: lwrp-sub-v-notify::default
         * apt_package[monit] action install
           - install version 1:5.6-2 of package monit
        (up to date)
         * service[monit] action start (up to date)
         * monit_check[sshd] action create
           * template[/etc/monit/conf.d/sshd.conf] action create
             - create new file /etc/monit/conf.d/sshd.conf
             - update content in file /etc/monit/conf.d/sshd.conf from none to 9f63c5
             --- /etc/monit/conf.d/sshd.conf	2015-11-13 20:09:25.151174767 +0000
             +++ /etc/monit/conf.d/.sshd.conf20151113-1479-muhokr	2015-11-13 20:09:25.151174767 +0000
             @@ -1 +1,6 @@
             +# sshd check generated by Chef
             +check process sshd
             +  with pidfile /var/run/sshd.pid
             +  if failed port 22 proto ssh
       
         
         * service[monit] action reload
           - reload service service[monit]
       
       Running handlers:
       Running handlers complete
```

we achieve the same effect i think, but without tying the existence of the resource in the parent run context to being able to use the LWRP.

also, i may be nuts, but at first glance it appears https://github.com/chef/chef/blob/master/lib/chef/run_context.rb#L85 may even actually already make it possible to reach up a level anyways (albeit not via notifies)?

anyways, i've got no real objection to chef providing support for doing it like you describe, i just think it would be something of an anti-pattern to use, since it makes it *really* easy to too-tightly integrate your recipe and provider code, making your provider unnecessarily difficult to consume.

**Comment by lamont-granquist** [comment]
lol, that hook didn't exist the last time i checked.  thank you @jkeiser.

anyway, the rest of the discussion gets into style issues.  I find the way that code inserts an event handler which walks the resource collection a lot grosser than code which "could" be misused to create tight coupling...  the potential for shooting yourself in the foot with that event handling and resource walking seems a lot worse to me.  we'll have to agree to disagree on this though.

**Comment by nathwill** [comment]
yeah, i agree it's ugly as sin :cry:. i'm sure there's simpler ways to write it, but quick and dirty is... dirty...

e.g. a slightly more reasonable looking version of the same:

```
Chef.event_handler do
  on :resource_updated do |resource, action|
    if resource.is_a?(Chef::Resource::MonitCheck)
      Chef.run_context.resource_collection
        .find(service: 'monit')
        .run_action(:reload)
    end
  end
end
```

and i'm sure there's half a dozen other ways to clean it up further still.

> we'll have to agree to disagree on this though.

:+1:

**Comment by lamont-granquist** [comment]
Yeah, if you want to do that some thought should go into a better primitive to use there -- it does smell like a different kind of notifies/subscribes syntax could cover the use case cleaner.

Of course my first cut at a resource-driven-accumulator is going to look ugly as hell and could probably use an additional primitive or two added at least...
