### ISSUE TITLE
remote_file resource needs to support sftp

### ISSUE THREAD

**Issue by adeconsulting** [chef/chef#4043]
I'm attempting to bootstrap an Ubuntu 12.04 LTS node using Chef 11.10.4.  The remote_file resource is failing because it does not support sftp.

**Comment by coderanger** [comment]
This seems out of scope for a ticket. If someone makes a provider in a gem/cookbook we could talk about integrating it to core.

**Comment by jkerry** [comment]
Attempting to answer this here.  feedback / pull requests are welcome
https://github.com/jkerry/sftp_provider

**Comment by btm** [comment]
@jkerry any interest in submitting a PR to merge that into core?

**Comment by yoshiwaan** [comment]
@coderanger I think this is something that is worth adding to core under the remote_file resource instead of a separate resource/provider. I feel that ideally the remote_file resource would be an abstraction over multiple drivers for different sources (like the service resource abstracts over different init systems).
It already supports http, https and ftp, why not scp, ftps and sftp also? It's certainly the most user friendly and they're commonly used protocols. There's also easy determination of type as prefixes are already used in the source attribute (i.e. http/https/ftp/file, so scp/ftps/sftp could be added).

**Comment by coderanger** [comment]
@yoshiwaan Supporting it in `remote_file` is :+1: but that can be done in an external gem/cookbook for the initial development and to prove out that this is something people want enough to include in core.

**Comment by jkerry** [comment]
Sorry for leaving you folks hanging.  I'm back on this now and a PR for core will be provided shortly.  working on getting test coverage of the code first.
