### ISSUE TITLE
Cant Converge CentOS 6.6 

### ISSUE THREAD

**Issue by ArneCoder** [chef/chef#4063]
Our Scripts are failing because Download of install.sh currently not working (Centos 6.6) in Azure Cloud,
```

 78:          url = build_url(url_or_node)
 79:          node = url_or_node
 80:        else
 81:          url = url_or_node
 82:          raise "Node instance is required for Omnitruck.url!" unless node
 83:        end
 84:        request = Chef::REST::RESTRequest.new(:head, URI.parse(url), nil)
 85>>       result = request.call
 86:        if(result.kind_of?(Net::HTTPRedirection))
 87:          result['location']
 88:        end
 89:      end
 90:
 91:    end
 92:  end
 93:
```
wget https://www.opscode.com/chef/install.sh does not work.

**Comment by lamont-granquist** [comment]
So install.sh tickets need to get filed in https://github.com/chef/omnitruck/issues/new rather than here in the client since that code is completely different.

Right now that URL works for me both from the office and from servers colo'd in California.

Can only speculate that either Azure was having issues, or transit between Azure and AWS were having issues or AWS was having issues, or we had some transient problems with omnitruck 11 hours ago which have resolved or been fixed.
