### ISSUE TITLE
Performance Issue with Chef::Provider::Package hitting candidate_version when action is :install and the package is already installed

### ISSUE THREAD

**Issue by chilicheech** [chef/chef#4122]
folks, i’m wondering if there’s a bug with the chef_gem resource.
if i don’t specify a version and the gem is already installed i get this:
```
DEBUG: chef_gem[knife-lastrun] found installed gem knife-lastrun version 0.0.5 matching knife-lastrun (>= 0)
DEBUG:  found gem knife-lastrun version 0.0.5 for platform ruby from #<Gem::Source:0x00000004cfcd18>
DEBUG: chef_gem[knife-lastrun] knife-lastrun 0.0.5 already installed
DEBUG: chef_gem[knife-lastrun] is already installed - nothing to do (up to date)
```
if i do specify the version and it’s already installed i get this:
```
DEBUG: chef_gem[knife-lastrun] found installed gem knife-lastrun version 0.0.5 matching knife-lastrun (= 0.0.5)
DEBUG: chef_gem[knife-lastrun] knife-lastrun 0.0.5 satisifies 0.0.5 requirement
DEBUG: chef_gem[knife-lastrun] is already installed - nothing to do (up to date)
```
the key thing to notice here is the `found gem knife-lastrun version 0.0.5 for platform ruby from #<Gem::Source:0x00000004cfcd18>`. when i don’t specify a version it seems it always searches for the gem even though the gem is already installed. is this the intended behavior for action install? it seems like this should be the behavior for action upgrade to always search for the latest gem...

the declared resource is as follows:
```
  chef_gem 'knife-lastrun' do
    version '0.0.5'
    clear_sources true if respond_to?(:clear_sources)
    source 'http://my.awesome.private.rubygems.cool'
    compile_time true if respond_to?(:compile_time)
  end
```

here's what i expected to see:
chef_gem action install with no version specified:
- install the latest gem if it's not already installed. this requires to search for the gem
- do nothing, not even search for the gem, if it's already installed

**Comment by lamont-granquist** [comment]
So, its doing the right thing, but the debug output looks odd because when you specify a version it prioritizes the new_resource.version-vs-current_resource.version check and shortcuts the computation early.  When you don't specify a version in an ideal world it would shortcut the check that current_resource.version is not nil while new_resource.version is.  Instead something hits candidate_version (quite possibly via define_resource_requirements which comes before the idempotency check in action_install) and you see that debug message.  That causes it to fetch the available version out of the gem cache in memory.  That doesn't seem like a very large issue.

Could try to fix that in an ideal world, but its not really a 'bug' and if it makes the code less readable then its not worth fixing at all because those package providers need to prioritize reading cleaner over perfect behavior.

Probably going to close this unless you figure out a more compelling argument (either behavior or code) that this is truly undesirable.

**Comment by chilicheech** [comment]
Are you sure it hits the gem cache in memory? That would be acceptable behavior. We have a rubygems mirror that we use and it seemed to be hit every time the node converged, even when the gem was already installed.

**Comment by chilicheech** [comment]
ok, so, i did some further investigation. when i set the version of chef_gem to install and the gem is already installed it makes no requests to my rubygems mirror. when i don't set the version and the gem is installed it makes a call to my rubygems mirror requesting this path: `/latest_specs.4.8.gz`. the way i proved it is i modified my nodes' /etc/hosts file to have the rubygems mirror point to 127.0.0.1. then i had netcat listen on the node. i then ran the recipe and netcat caught the connection attempt. so, it looks to me like it's not hitting a local gem cache in memory, but instead is making requests to the rubygems mirror.

Here's the recipe:
```
chef_gem 'knife-lastrun' do
  clear_sources true if respond_to?(:clear_sources)
  source 'http://rubygems.mirror:10000'
  compile_time true if respond_to?(:compile_time)
end
```
Here's the log output:
```
 * chef_gem[knife-lastrun] action install[2015-10-30T18:10:13+00:00] WARN:  failed to find gem knife-lastrun (>= 0) from [http://rubygems.mirror:10000] (up to date)
```
Here's the netcat output:
```
[chilicheech@my_node ~]$ nc -l 10000
GET /latest_specs.4.8.gz HTTP/1.1
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
Accept: */*
User-Agent: Ruby, RubyGems/2.4.8 x86_64-linux Ruby/2.1.6 (2015-04-13 patchlevel 336)
Connection: keep-alive
Keep-Alive: 30
If-Modified-Since: Thu, 29 Oct 2015 16:44:20 GMT
Host: rubygems.mirror:10000

[chilicheech@my_node ~]$
```

i think it's fine to hit a local gem cache in memory, but it shouldn't be hitting the remote source to find gems. this is causing unnecessary load on our rubygems mirror. this is probably also causing unnecessary extra load on rubygems.org.

**Comment by lamont-granquist** [comment]
forced_packages_missing_candidates walks through the 4 main arrays in tandem:

```ruby
      # Returns an array of all forced packages which are missing candidate versions
      #
      # @return [Array] names of packages missing candidates
      def forced_packages_missing_candidates
        @forced_packages_missing_candidates ||=
          begin
            missing = []
            each_package do |package_name, new_version, current_version, candidate_version|
              next if new_version.nil? || current_version.nil?
              if candidate_version.nil? && !target_version_already_installed?(current_version, new_version)
                missing.push(package_name)
              end
            end
            missing
          end
      end
```

The conditional should probably get reversed with `candidate_version.nil?` appearing at the end, but it doesn't matter since we iterate through all 4 arrays in lockstep and therefore with always create the candidate_version array, and will always kick off the lazy initializer which downloads the sources.

In general this is likely an issue with each_package walking the arrays in tandem, but that is fairly critical to the correctness of the multipackage design.  We could make each_package take arguments about what arrays to walk, but that doesn't help because we do in fact need the candidate_version array.

The alternative is to refactor and go back to just using the index and accessing all the arrays via index so that in that case it would never hit the lazy initializer.

Specs for this will be interesting to write.

**Comment by lamont-granquist** [comment]
This would be worthwhile to fix, since if we're fully converged we can just check that current_version is not nil and never hit candidate_version and never slurp all the rubygems data into memory which would significantly drop the memory utilization of already-converged chef clients.

But refactoring all the multipackage code to remove each_package and make candidate_version access more lazy will be a bit delicate and needs to be done **cleanly** and not make a mess out of the provider.
