### ISSUE TITLE
chef-client init script broken on ubuntu 14.04 with latest chef-client.deb 

### ISSUE THREAD

**Issue by mbassett** [chef/chef#4145]
There is a problem in the init script of chef-client from the 12.5.1-1 amd64 build.

It has

```
running_pid() {
  pid=$1
  name=$2
  [ -z "$pid" ] && return 1
  [ ! -d /proc/$pid ] && return 1
  cmd=`awk '/Name:/ {print $2}' /proc/$pid/status`
  [ "$cmd" != "$name" ] && return 1
  return 0
}

running() {
  [ ! -f "$PIDFILE" ] && return 1
  pid=`cat $PIDFILE`
  running_pid $pid ruby || return 1
  return 0
}
```

`awk '/Name:/ {print $2}' /proc/$pid/status` always returns chef-client, not ruby.

changing `running()` to read

```
running_pid $pid chef-client || return 1
```

solves the issue.

**Comment by josb** [comment]
I don't get why people use pidfiles. The kernel is perfectly capable of keeping track of processes.

On this platform, chef-client should use Upstart. This would also make transitioning to systemd easier since the configuration models are similar.

**Comment by lamont-granquist** [comment]
this repo doesn't have any init script in it.  you're most likely using the chef-client cookbook?  and that cookbook has the ability to switch all kinds of different service management models.  you could submit a PR against that repo in order to change the default on upstart-supporting ubuntu distributions to use upstart.

**Comment by lamont-granquist** [comment]
closing due to no response.   issue most likely needs to be cut against http://github.com/chef-cookbooks/chef-client/issues/new
