### ISSUE TITLE
One node/client multiple Chef servers.

### ISSUE THREAD

**Issue by kumhera** [chef/chef#4184]
Hi there,

We are running multiple environments, whereas few configurations run from one Chef server and few needs to be run from another Chef server ( Eg -We want to install Apache from one Chef environment and Jboss from another Chef environment and both on a single node/server).

Is it possble? If yes how we may configure this configuration?

Many thanks
Nitin

**Comment by btm** [comment]
You should be able to do that by having separate client config files with different server URLs and client key locations. You'll probably want/need to also specify different cache paths. I don't know off the top of my head which paths are based off each other, it would take a little testing. All of those configurations can be changed here:

https://docs.chef.io/config_rb_client.html

Remember that the last client run is going to be the one that specifies the current state of the system. Just like if you have two cookbook managing the same files or services, having two servers means it is harder to have a complete view of the changes planned for the system.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
