### ISSUE TITLE
Error 404 on creating admin user on chef server

### ISSUE THREAD

**Issue by mgattelli** [chef/chef#4190]
Hi there,

I am trying to create a new admin user, following the (fantastic) guide on the chef web site that helps to install and configure chef server using a cloud provider (GCE).

Now when I run chef-server-ctl user-create command the response is the following:

*ERROR: The object you are looking for could not be found
Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /users/ was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at 127.0.0.1 Port 443</address>
</body></html>*

Can anyone help me figure out which is the problem?

**Comment by btm** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Issues with the Chef Server should be filed aagainst the [chef-server](https://github.com/chef/chef-server) project. Questions like "How do I .... with Chef?" are better answered by our awesome community on the [Chef mailing lists](https://discourse.chef.io/), or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
