### ISSUE TITLE
Using Chef with Private Gem Server

### ISSUE THREAD

**Issue by st-isidore-de-seville** [chef/chef#4220]
Ohai Chefs!  I apologize in advance as this is probably more of a question than an issue that I cannot find the answer to.  I am currently using Chef behind a firewall and run a private gem server.  I would like to be able to use community cookbooks from the Supermarket without modification but the issue I am having is that I cannot figure out how to configure the Chef Client to pull gems from my private gem server and not rubygems.org when community cookbooks install gems via the chef_gem resource.  

Any help is greatly appreciated as I have searched high and low but could not find an answer.  Thanks!

**Comment by justanshulsharma** [comment]
@st-isidore-de-seville how is your private gem server designed can you please provide more input on this.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue.

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists here. On StackOverflow, please tag your question with the "chef" label so that it shows up in this list.

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
