### ISSUE TITLE
Can't glob using Chef::Config[:file_cache_path] on Windows

### ISSUE THREAD

**Issue by shoekstra** [chef/chef#4221]
Ohai,

It seems one can't use `Dir.glob` on Windows paths that use the `::File::ALT_SEPARATOR`.  I can across this when trying to do `Dir.glob(File.join(Chef::Config[:file_cache_path], '*'))` in a recipe.

When looking into this, I found the following:

```
chef (12.4.3)> Chef::Config[:file_cache_path]
 => "C:\\chef\\cache"
chef (12.4.3)> Dir.glob(File.join(Chef::Config[:file_cache_path], '*'))
 => []
chef (12.4.3)> Dir.glob("C:\\chef\\cache\\*")
 => []
chef (12.4.3)> Dir.glob("C:/chef/cache/*")
 => ["C:/chef/cache/7z922-x64.msi", "C:/chef/cache/ActivePerl-5.16.3.1603-MSWin32-x64-296746.msi", "some other files..."]
chef (12.4.3)> ::File::SEPARATOR
 => "/"
chef (12.4.3)> ::File::ALT_SEPARATOR
 => "\\"
chef (12.4.3)> Dir.glob(File.join(Chef::Config[:file_cache_path].gsub(::File::ALT_SEPARATOR, ::File::SEPARATOR), '*'))
 => ["C:/chef/cache/7z922-x64.msi", "C:/chef/cache/ActivePerl-5.16.3.1603-MSWin32-x64-296746.msi", "some other files..."]
```

I'm not sure what the best solution is here as the problem seems to be with Ruby and not Chef, but it seems sensible to change `Chef::Config[:file_cache_path]` (and any other paths in `Chef::Config`) to use `::File::SEPARATOR` instead of `::File::ALT_SEPARATOR` in order to fix this sooner rather than later.

**Comment by coderanger** [comment]
If changed that would have the reverse problem in other places. I don't think this is fixable directly.

**Comment by jaym** [comment]
`Dir.glob` on Windows does not work with `\` most of the time. http://ruby-doc.org/core-2.1.1/Dir.html#method-c-glob says don't do it. We still do it in places by accident. It might be worth us creating another glob function in `PathHelpers`

**Comment by lamont-granquist** [comment]
So you should be using escape_glob which will backwhack-escape the File::ALT_SEPARATORs in the path, and will also catch other glob escaping issues.  But while that seems to work most of the time, it appears based on #4194 that it doesn't work all the time.

We may need some kind of escape_glob2() API that converts backwhacks to forward slashes and then goes through and escapes the glob patterns.  Then the caller would be responsible for calling that before calling `Dir.glob` and then would be responsible for calling `cleanpath` on the resultant paths if they need to.

However, I'm kinda :-1: on trying to solve this through trying to fix all the paths.  This is a problem in how `Dir.glob` must be used on windows, and it looks like the caller must do before and after sanitization around this library call.  And while we could consider writing a wrapper around `Dir.glob` the problem is that actual globs need to not be fed into escape_glob makes the shape of that wrapper API a little inconsistent -- if you just make it take a `*path` argument then it'll escape_glob all your actual globs and break it completely.

**Comment by shoekstra** [comment]
Totally agree that the problem is with `Dir.glob` and Windows, but the intention wasn't to fix all possible paths, just paths in `Chef::Config`. It would be nice to be able to use `Dir.glob` on a value that comes from `Chef::Config` without jumping through hoops; if someone is using backslashes in a path they supply and then try to use `Dir.glob` (or some other method that breaks) then it's up to them to fix.

The idea was to use ::File::SEPARATOR on Windows systems and people can make them into Windows friendly paths when the need arises (either with gsub, or the win_friendly_path helper in the windows cookbook).  I reached this idea because when using `File.join` on Windows, ::File::SEPARATOR is used so this seems to be the preferred separator.

Is there any value in using ::File::ALT_SEPARATOR over ::File::SEPARATOR for "Chef generated" values on Windows?  If there is, or there is the potential to break many things, I'll stick to replacing ::File::ALT_SEPARATOR with ::File::SEPARATOR (must be a limited use case if there aren't other people aren't experiencing this), I just spotted this and thought perhaps not too hard to remedy.

**Comment by lamont-granquist** [comment]
Yeah there's edge conditions which is why the `#cleanpath` API to convert everything to ::File::ALT_SEPARATOR was written.  Assuming we correctly filter all the Chef::Config values through cleanpath when its necessary you could do this fine, but I'd bet large sums of money that we do not and you'll cause bugs and its not that simple.

**Comment by shoekstra** [comment]
Fair enough, issue was created to see if it was simple to fix, so closing this one - it doesn't seem to be a common issue and, to be fair, it's the first time I've come across it so will use gsub if ever globbing paths with `\\`.

Thanks for the prompt response.
