### ISSUE TITLE
Chef workstation error

### ISSUE THREAD

**Issue by rchennuri** [chef/chef#4230]
Hi Team,

please provide solution to below error.
I have used two ec2 ubuntu 14.4 installation for chef server and workstation.

I have used knife ssl fetch command also to place the valid certificate under .chef/trusted_certs

Use `knife ssl check` to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
`knife ssl fetch` to make knife trust the server's certificates.

Original Exception: OpenSSL::SSL::SSLError: hostname "ec2-52-74-246-20.ap-south
east-1.compute.amazonaws.com" does not match the server certificate
root@ip-172-31:/home/ubuntu/chef-repo# knife ssl check
Connecting to host ec2-52-74-246-20.ap-southeast-1.compute.amazonaws.com:443
ERROR: The SSL cert is signed by a trusted authority but is not valid for the gi
ven hostname
ERROR: You are attempting to connect to:   'ec2-52-74-246-20.ap-southeast-1.com
pute.amazonaws.com'
ERROR: The server's certificate belongs to 'ip-172-31-30-179.ap-southeast-1.comp
ute.internal'

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue.

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://discourse.chef.io). On StackOverflow, please tag your question with the "chef" label so that it shows up in this list.

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
