### ISSUE TITLE
knife ssh with multiple commands & sudo hangs

### ISSUE THREAD

**Issue by ryanl-ee** [chef/chef#4274]
Hi, I noticed this problem:

`knife ssh 'environment:exampleenv' 'wget http://example.com/script.sh; sudo script.sh'` shows the `wget` output, then hangs indefinitely without asking for the password.

`knife ssh 'environment:exampleenv' 'sudo wget http://example.com/script.sh; sudo script.sh'` prompts for the sudo password, shows the `wget` output, and then executes the script. So, if I execute `knife ssh` with multiple commands & one requires elevated privileges, I have to preface the first one with `sudo` whether it needs it or not.

**Comment by arnaud036** [comment]
Same problem here

**Comment by lamont-granquist** [comment]
So the logic which looks at the first characters of the string for 'sudo' needs to be extended so that you can pass it a flag to force this behavior.

In retrospect we never should have included the magic because writing our own bash parser to determine if the command might run sudo on the remote system is not something we'll ever do or be able to get correct.

**Comment by lamont-granquist** [comment]
I suppose we could look for the sudo password prompt and then always feed the password but that feels like a whack-a-mole as well since the sudo prompt is customizable and other things may output strings that look like password prompts as well...

**Comment by atheiman** [comment]
Ive logged a related issue, #4783
