### ISSUE TITLE
MvUnix not actually atomic

### ISSUE THREAD

**Issue by john-karp** [chef/chef#4313]
There is no fsync of file content after it is written before the mv operation. Generally, the kernel can perform IO in any order, so it is possible for the directory to be updated before the file content is written, leading to the target file being empty or incomplete if there is an interruption. This can be avoided by adding a fsync of the file's content after writing is complete but before the mv.

Also, mv itself isn't actually atomic unless source and destination files are on the same filesystem. If we can't create the tempfile on the same filesystem as the destination, there should be an error if `atomic_update` attribute is true.

Background material: http://danluu.com/file-consistency/ At the end he discusses the tempfile/mv approach specifically.

**Comment by lamont-granquist** [comment]
The problem here is that `atomic_update` is kind of a lie and it should be `strategy :mv` or `strategy cp`

We also now set  Chef::Config[:file_staging_uses_destdir] to true so that mv should not ever cross filesystems (thats one of several bugs that flipping the default to true changed).

Agreed that it should fsync, but I don't think there's an fsync lib in core ruby, last time I looked there wasn't a good one in rubygems either.

**Comment by lamont-granquist** [comment]
Hmmm, IO::fsync exists back to ruby 1.8.7 so I'm not sure what I'm thinking about.

This may have performance effects it should probably be possible to turn this off (yes even when atomic_updates is 'true' this should be able to be turned off -- badly named property)

**Comment by lamont-granquist** [comment]
Also note that this pattern of not calling fsync is extremely common and caused major issues with ext4 which originally did not support it:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/317781

The resolution of that was the ext4 was patched to support not calling fsync and avoiding corrupting the target file.

Any halfway modern linux filesystem (not old async ext2 which corrupts everything when it crashes) will ensure that the metadata write to rename the file will never come before the contents of the tempfile have been flushed to disk.  That means that you will not corrupt the file.   Of course you'll return and be able to proceed before the file has been flushed to disk.  In the event of a crash its possible that files have been written out of order.

However, with idempotent and convergent config management software like Chef its not even clear that this is a concern.  Most of the time you should never be updating file system state as Chef runs as the resources should be convergent and idempotent.  If you crash in the middle of a chef-client run, then the only way to fix that is running chef-client again, and a properly written recipe with declarative resources will find the half-state and repair it.  Badly written Chef recipes may not be able to fix arbitrarily mangled partial-states, but well written recipes should always be able to fix them (otherwise you're vulnerable to admins doing typey-typey keyboard attacks as root on the server and putting the node into a state that Chef can't fix).

Danluu's paper also is not about this use case, and he explicitly recommends against the tempfile-and-mv approach for the use case he's trying to solve (which is more about using the filesystem as a transactional database).  He also notes the large performance penalty for fsync'ing large files.

We don't have a single bug report on this currently where users have been affected by corrupted files, and its not clear to me that the edge conditions (which necessarily involve the node crashing) require a solution more complicated than "run chef-client again" or "always run chef-client on boot".

About the only thing that gives me a little pause is that in the ext4 bug report Ted Ts'o mentions AFS as another filesystem that may have issues.

So, I think if this gets implemented it should probably be off by default, not on, because the performance hit vastly outweighs any benefits in consistency.  There should most likely be a global switch in Chef::Config so that users can turn it on, and needs to be a property in the file resources so that it can be turned back off again on a case-by-case basis.

Dropping this down to Help Wanted priority, it can be bumped up again if we encounter actual corruption problems on AFS or something like that.

**Comment by lamont-granquist** [comment]
I can't see a practical consistency issue here, and the performance cost of fsync() will be an issue.

There is a cultural naval gazing issue here where the POSIX standard technically doesn't mandate filesystem authors to follow semantics where avoiding the fsync is safe.  But the fallout from the ext4 issue shows that if filesystem authors break that unwritten rule that the Unix ecosystem largely falls apart and they will lose.

If someone wants to submit a PR to include an `fsync` and/or `fdatasync` property on individual resources (with tests), that would probably be accepted, but is not worth keeping this issue open.  Without a concrete use case (a "one of my servers exploded this weekend;  this is what happened;  i really need an fsync property" kind of bug report) this issue seems academic at best.
