### ISSUE TITLE
Migrate off of Merb / Help update Debian

### ISSUE THREAD

**Issue by sodabrew** [chef/chef#4326]
Hi, I'm trying to sort out why Debian won't remove its ancient Merb packages, and they say it's because Chef needs them. (I received that information in a personal reply.) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794904

Would you consider migrating Chef 10. off of Merb? https://packages.debian.org/sid/chef-server-api _[this is a rhetorical question]_

Does someone on the Chef side of things have a contact in Debian to try and get them to update their package to Chef 12. so that the Merb dependency can be removed and thus Merb removed?

**Comment by coderanger** [comment]
Chef 10 was EOL'd years ago and is no longer supported. Chef Server 11 and 12 don't use Merb that I'm aware of (for the API components). We are not involved in the Debian packaging, nor do we directly support the use of their packages. The Chef Software omnibus builds are the supported way to install Chef and Chef Server.

**Comment by sodabrew** [comment]
I'm aware that Debian is packaging an ancient version of Chef. I'm hoping to find a contact to get them to ship something less ancient or nothing at all. Any leads at all would be greatly appreciated to help chase this down.

**Comment by coderanger** [comment]
@btm Appears to have maintainer access still. Is that enough to implode their packages?

**Comment by sodabrew** [comment]
Also weird, it's just the `chef-server-api` package that is still in Sid as version 10... the main Chef package is in the 12. series: https://packages.debian.org/sid/chef

**Comment by coderanger** [comment]
Probably because we never technically released another version of `chef-server-api`, that gem/package/software thingy stopped with Chef Server 10 and was replaced by Erchef.

**Comment by btm** [comment]
@sodabrew Chef Server 11+ was rewritten in erlang and would have needed a fresh packaging start. We had done a ton of work adding rubygems dependencies as debian packages for Chef 10, and keeping them updated. We weren't much interested in doing that again for Erlang given that experience.

We wouldn't make upstream packages again that meet policy. We are working with Canonical on alternatives. We have in the past worked with Canonical to pull the old packages and would be happy to sign off on that with Debian.

Mostly, the shelf life of distributions is far too long to include Chef in typical form. We release significant new features on a regular basis. While I understand and appreciate the intentions, Debian policy requires us to go through rigorous process to backport and required us to do so as patches that only fixed bugs. The benefit of the time it would take to make those custom patches for each Debian release is not worthwhile. Further, since we've moved to Omnibus packaging we've created a world where we don't have to test against everyone's version of Ruby and other dependencies, which allows us to spend significantly more time testing against a single set of dependencies, which produces a higher quality build.

**Comment by sodabrew** [comment]
Sadly, yes, those were bad times for Ruby packages in Debian. I filed a ticket! https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808348

**Comment by sodabrew** [comment]
Thank you! https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808362 This is now resolved - the Chef 10 packages and its Merb dependency are now removed from Debian Sid. Let's also be sure to bug Canonical not to ship old Chef and old Merb in the Ubuntu Xenial April 2016 LTS release.
