### ISSUE TITLE
Chef::Search::Query getting stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by fmonserrat** [chef/chef#4329]
Hi guys,
we currently have 4500 nodes in our fleet all managed by Chef (which is awesome :) ) and we have a script that runs a  query to get the last time a node has reported to the chef server so we can get all those nodes that have not called home in more than 24 hours and report this through email and we can check what is going on with them. 
This script used to run ok but it is now throwing the following error:
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.1/lib/chef/http.rb:153: stack level too deep (SystemStackError)

any ideas what could be causing it? 
Thanks in advance

**Comment by lamont-granquist** [comment]
probably would need the full stacktrace.out along with the rest of the output to even guess.

that line in the code is just re-raising the exception so its a bit worthless other to suggest its down below the http code someplace.

if you're not already using the partial search api to filter the attributes returned by the search, that is likely one thing you need to do -- it may solve this problem and it'll be massively kinder to your RAM usage.

**Comment by stevendanna** [comment]
The search method is recursive and there have been some changes in it to try to addresses cases where it won't make progress:

https://github.com/chef/chef/blob/master/lib/chef/search/query.rb#L106

**Comment by stevendanna** [comment]
If we could get full debug output (-l debug for chef-client or -VV for knife) that would be very helpful.

**Comment by fmonserrat** [comment]
hi guys, sorry for the delay replying to my issue, I've been trying to get some debug info using knife but i had no success. just in case i'm pasting here the query i'm using in my script and how i'm using it

query = "*:*"
missing_query = "-run_list:*"

opts = {
  filter_result:
    {
      hostname: ["hostname"],
      domain: ["domain"],
      ohai_time: ["ohai_time"],
      ipaddress: ["ipaddress"],
      tags: ["tags"],
      run_list: ["run_list"]
    }
}


# use Solr query as much as possible
q.search(:node, query, opts) do |item|
  next unless item[:ohai_time].to_i < time_threshold.to_i
  delay = (time_now - item[:ohai_time].to_i)
  host_list.push([item[:hostname], item[:domain], item[:tags], item[:ipaddress], delay])
end

q.search(:node, missing_query) do |item|
  missing_host_list.push([item[:hostname], item[:domain]])
end


hope it helps. Thanks in advance for the support and effort you put here :)

**Comment by lamont-granquist** [comment]
@stevendanna by default rows is nil so shouldn't we get all the results back and not paginate at all?

**Comment by thommay** [comment]
@fmonserrat can you try putting `Chef::Log.level = :debug` at the top of your script and then rerunning it? We really can't do much without some error output. If there's information you'd consider private in the output, please mail it to me at thom@chef.io and I'll take a look.

**Comment by jstange** [comment]
One of my Chef servers (`chef-server-core-12.15.7-1.el6.x86_64` with a client running `chef-12.20.3-1.el6.x86_64`) just started doing this on searches against a particular data bag. I stuck a debug statement of my own into `/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/search/query.rb`.

The problematic search is from the Nagios community cookbook, and it's roughly `Chef::Search::Query.new.search("nagios_users", "groups:sysadmin NOT action:remove")`.

The first response looks more or less sane:

```
CALL TO: response = call_rest_service(type, query: query, **args_h)
RESPONSE: {"total"=>2,
 "start"=>0,
 "rows"=>
  [{"data_bag_item('nagios_users', 'mu')"=>
     {"id"=>"mu",
      "groups"=>"sysadmin",
      "htpasswd"=>"*",
      "openid"=>"http://nagiosadmin.myopenid.com/",
      "nagios"=>
       {"pager"=>"john.stange@eglobaltech.com",
        "email"=>"john.stange@eglobaltech.com"},
      "chef_type"=>"data_bag_item",
      "data_bag"=>"nagios_users"}}]}
```

...then it recurses because that `total` is less than the number of rows, which I assume is some kind of pager functionality. But all subsequent calls give me:

```
CALL TO: response = call_rest_service(type, query: query, **args_h)
RESPONSE: {"total"=>2, "start"=>1, "rows"=>[]}
```

...until it runs out of stack.

The client search method should probably handle this in some other way that recursing infinitely, for a start. I'm monkey-hacking it by hand for now so I can get a complete Chef run on this node.

Additionally, that single entry in the original result is the only item in that data bag, so I don't know where `"total"=>2` could be coming from. Deleting the data bag and recreating it doesn't help; if I remove the single item, I just get the same behavior but with `{"total"=>1, "start"=>0, "rows"=>[]}`.

**Comment by coderanger** [comment]
@jstange That's only marginally valid. What you means what probably `groups:sysadmin AND NOT action:remove`, but `NOT` queries in Chef can have real weird behavior because of the nesting expansion so be careful.

**Comment by jstange** [comment]
I can't speak for the query, since it's from a popular community cookbook, rather than something of mine. Were it mine I'd suggest that if the syntax doesn't have meaning, it should probably throw an error instead of returning nonsensical results.

**Comment by coderanger** [comment]
Being in a community cookbook doesn't make it any more valid, and yes the server should better reject parse errors but this is not that ticket or project.

**Comment by stevendanna** [comment]
> groups:sysadmin AND NOT action:remove

The original query was correct.  `AND NOT` is counter-intuitively not valid lucene IIRC.

The reason we are running out of stack is that we've gotten a document count from Solr/ES that says there are two document but then erchef is filtering out both documents (likely because it is no longer in the database).  If the calling code didn't explicitly pass a rows parameters, we try to advance by the number of rows, which in the case of a completely empty page leads up to spin forever:

https://github.com/chef/chef/blob/master/lib/chef/search/query.rb#L90

> @stevendanna by default rows is nil so shouldn't we get all the results back and not paginate at all?

No, there is no way to definitely get all results with the current API.  If the client doesn't pass a row size, the default row size of 1000 is used.

**Comment by stevendanna** [comment]
If this is a chef-server you manage yourself you might be able to resolve the issue with `chef-server-ctl reindex`.
