### ISSUE TITLE
knife bootstrap named_run_list not supported

### ISSUE THREAD

**Issue by scopenco** [chef/chef#4365]
Hello,

```
$ knife -v
Chef: 12.6.0
```

Test Kitchen already supports named_run_list but knife does not. This doesn't allow to do `knife bootstrap` based on Policyfile with `named_run_list`.

**Comment by danielsdeleo** [comment]
What is the expected behavior here? Do you think chef-client would run the named run list once, and then run the default run list after that? Or do you think that chef-client would run that named run list indefinitely until you made a config change on the host?

This isn't as clear as the test kitchen case because for kitchen, the main driver of the named run list use case is to run different suites with different run lists. For example, if a cookbook (say, mysql) has both a client and server "mode," you would need to test those independently, so you'd use a different named run list for each one. In a more "production-y" use case, the idea is that the named run list replaces the `--override-runlist` feature from non-policyfile chef-client, where you want to run a subset of your run list to do something like update an application without running the "base" cookbooks. So we never planned for named run lists to be used indefinitely, but instead just for "one-shot" use cases. But if there's a compelling case, we can revisit that.

**Comment by scopenco** [comment]
I think chef-client should run the named_run_list or run_list but not together, because this lead to unclear converge. On Chef Server in node run_list should be recipe that is set in named_run_list in knife bootstrap. It will look like intuitive and clear behavior.

**Comment by scopenco** [comment]
In addition, if i try to run
```
sc:env-reports $ knife bootstrap --policy-name myname --policy-group mygroup  --run-list mycookbook::myrecipe <NODE>
```
i get
```
ERROR: Policyfile options and --run-list are exclusive
```
in
```
$ knife -v
Chef: 12.6.0
```

**Comment by danielsdeleo** [comment]
I'm talking about the next chef-client run after you bootstrap. E.g., you run `knife bootstrap ETC`, it runs successfully, then you ssh into that box and type `chef-client <enter>`. What do you expect to happen?

**Comment by scopenco** [comment]
Of course chef-client should run recipe from named_run_list, because it was bootstraped  with this named_run_list.

**Comment by danielsdeleo** [comment]
Can you explain a bit more how you're using named run lists? What you're asking for is a bit contrary to what they were designed to do so this would require some extra work beyond just modifying `knife bootstrap`.

**Comment by legal90** [comment]
@danielsdeleo Me and @scopenco are co-workers, so I'll try to explain our use case:
We have a big wrapper cookbook (former "environment cookbook") designed to manage a single project, consisting of several components (say, web backend nodes, load balancer and database node). Each node (e.q. component) is converged by some specific recipes, so they have different run lists.
Since this is a single project, all the nodes have the same cookbook dependencies and we use a single Policyfile in order to manage them.

We've found that `named_run_list` is a good way to manage component-specific run lists and it works fine with test-kitchen, as you've described above. But when we tried to bootstrap production nodes with `knife bootstrap` we've got an error.

What do we expect:
```
$ knife bootstrap --policy-name myname --policy-group mygroup --named-run-list database <...>
```
Being bootstrapped with this command, the node should indefinitely have a run list which is defined as `database` in Policyfile. If we edit the value of `database` named run list in Policyfile and then push it to the Chef Server, then the next run of Chef Client should use the new run list.

At the moment we have to bootstrap the node with a fake empty recipe and then edit it's `/etc/client.rb` and set `named_run_list` there. And the next Chef Client run gives us what we want :)

**Comment by danielsdeleo** [comment]
The way policyfiles are designed to be used is that you'd have a separate policy for each kind of node that makes up the application, e.g., myapp-lb, myapp-web, myapp-db. If it makes it easier, you don't have to name the files `Policyfile.rb`; all of the policy commands accept an optional argument for the relative path to the ruby policyfile, so you can have a policies directory with `policies/myapp-lb.rb`, `policies/myapp-web.rb`, etc.

There are a few downsides to this:

* It's a double-edged sword, but each policy locks dependencies independently. In the good case, this means that, for example, if you're using the postgres and nginx cookbooks from supermarket, that you won't get stuck if the postgres and nginx cookbooks require a different major version of the apt or yum cookbook(s). In the bad case, you might want to use the same version of an in-house "base" cookbook everywhere, but forget to update a particular policy or not notice if the newest version has a dependency conflict with something else.
* Stuff that you want to share between the policies, such as attributes, have to be repeated, or you have to "roll you own" sharing mechanism by putting ruby code in the policies. Eventually, we'll have some kind of "snippet" mechanism built-in where you can include "snippets" of policyfiles into other ones, but we don't have that now.
* You have to promote your policies through the lifecycle separately.

I think the 1st and 3rd problems can be handled pretty easily with a simple Ci system or just a script that you run instead of running the `chef` commands directly.

Are there any other things that would be deal-breakers for you using separate policies instead of named run lists here?

**Comment by legal90** [comment]
Well... It is too big overhead to split policies in order just to keeping different run-lists. And it makes the workflow too complicated. We want to manage cookbook dependencies in the single Policyfile and `named_run_list` feature allows us to set run lists per each node (component).
The only problem is that we have to set `named_run_list` in client.rb

Why don't just to allow to set it during `knife bootstrap`?

**Comment by danielsdeleo** [comment]
What exactly causes the overhead?

**Comment by legal90** [comment]
By the overhead I mean the necessity to keep and manage separated policies even though we need only different run lists.
We have pretty much projects (15-20) with different count on node types (up to 8), so instead of using obvious commands like `chef update`, `chef push`, `git add` , `git commit` we will have to wrap them on custom scripts, which will run slower. 
Also, we don't use "chef-repo", so we'll have to store all these policyfiles, their locks and scripts in the cookbook repo. It might be OK, but... sounds weird.

Actually, we are using Berkshelf with "Environment Cookbook Pattern" ([link](http://blog.vialstudios.com/the-environment-cookbook-pattern/)) at the moment, but a brand-new Policyfile feature solves some important problems of this pattern, so we'd like to use it instead. 
And seems like this issue of `knife bootstrap` is a deal-breaker for us.

**Comment by danielsdeleo** [comment]
I think this should become supported via https://github.com/chef/chef/pull/4529 though my preference would be to make it easier to manipulate policies in batches, perhaps by supporting commands like `chef update policies/*`.

**Comment by legal90** [comment]
> I think this should become supported via #4529

Thanks. But as I've understood, #4529 allows to upload config presets form the workstation to the node.
Such presets should exist on workstation and they should be common for all nodes which we are going to bootstrap.
So, this approach doesn't allow to set node-specific options like `named_run_list`, do it?

**Comment by aespinosa** [comment]
Hello,

Here's my use case for a named_run_list in bootstrap:

1.  I have a node that I want to bootstrap with an initial base configuration.  Like let's say having chef-client running as a service
2.  Once I have a set of nodes bootstrap, I want to apply the actual runlist (like the default run_list) in that policy.

That way we can have a fast bootstrap process for bootstrapping multiple machines without being blocked by the main runlist of my nodes.

**Comment by salsa-dev** [comment]
@legal90 I'm also looking into using global policy file with named_runlists for the nodes. Have you overcome this issue with knife bootstrap ?

**Comment by legal90** [comment]
@salsa-dev Unfortunately, not. We gave up and used a separate policyfile for every node type :(

**Comment by SolverDude** [comment]
Hi.  I just encountered a similar roadblock.  The utility of named run_lists are that they initialize something and then you don't need to do that any more.  So It would be helpful in this scenario to supply a named_run_list on bootstrap.  Future converges I'd expect to run the default run list of the policy.  At the moment, we'd need to:
* Bootstrap with no run list
* Edit node and set the policy group and name
* Manually converge with named run list.

Adding a parm to bootstrap to supply an optional named run list would eliminate that noise.

Any love for that idea @danielsdeleo ?
