### ISSUE TITLE
Allow 'single digit'/'browser' style cookbook versions

### ISSUE THREAD

**Issue by kemra102** [chef/chef#4454]
Currently all cookbook versions have to be a semantic like x.y.z or x.y and this enforced by the Chef Server.

However it would be advantageous in that it could simply our CI process by allowing version like in the Chrome & Firefox browsers, e.g. 23 -> 24 -> 25 (integer)

This would simply our CI system incrementing our version numbers for us in a situation where we really don't care about semantic versioning, we just want a higher version number.

**Comment by lamont-granquist** [comment]
you probably want to use policyfiles and pin to the sha.  at any rate since this is the chef-client repo and the server would need changes, this is in the wrong repo, and should be at a minimum should be cut against http://github.com/chef/chef-server instead.  it also could probably use an RFC at http://github.com/chef/chef-rfc.  i think its fairly unlikely any work will be done on this, or that there will be support for an rfc, unless heavy users of policyfiles report that policyfiles do not solve their problems.
