### ISSUE TITLE
directory resource chown recursively

### ISSUE THREAD

**Issue by philipmeadows** [chef/chef#4468]
Are there any plans to update the resource directory https://docs.chef.io/resource_directory.html to have the option to set ownership and mode recursively when run on a pre-existing directory? 

So something equivalent to chown -R.

**Comment by lamont-granquist** [comment]
So if we start chown'ing parent directories when should we stop, because ultimately you wind up chown'ing root and before that there's all kinds of awful directories like '/etc' and '/var' and '/var/tmp' that you could hose.

This is a dup of https://tickets.opscode.com/browse/CHEF-1621

We've also documented the current correct approach at:

https://docs.chef.io/resource_directory.html

Which is simply being explicit:

```ruby
%w[ /foo /foo/bar /foo/bar/baz ].each do |path|
  directory path do
    owner 'root'
    group 'root'
    mode '0755'
  end
end
```

I think I mentioned in CHEF-1621 or some other related ticket that a DSL helper method or resource/definition could be written to wrap this pattern with a bit of sugar to generate all the subdirs in between the two endpoints.  Nobody has ever been bothered by this enough to code anything up.
