### ISSUE TITLE
Duplicate gems in chef 12.7

### ISSUE THREAD

**Issue by chefsalim** [chef/chef#4540]
Chef 12.7 current builds have two versions of rake and json:
rake (10.50.0, 10.4.2)
json (1.8.3, 1.8.1)

Need to determine root cause and determine how/if we can use only a single version.

**Comment by lamont-granquist** [comment]
cabin, which comes in through fpm, pins a dev gem dependency on rake ~> 10.4.2, so won't pick up 10.5.0, and we install the dev gems because of [good] $REASONS.
json-1.8.1 comes in through the base ruby, while 1.8.3 gets installed by gems that depsolve for the the latest.

none of those are problems, imo, or worth spending a lot of time on.
