### ISSUE TITLE
Use of platform_family?('linux') with RHEL or CentOS

### ISSUE THREAD

**Issue by monkey1016** [chef/chef#4555]
Hi,
I'm writing a recipe that I want to do one thing for all Linux variants and something else for Windows variants.  But the behavior I expect for `platform_family?('linux')` is not actually what I'm seeing.  Looking at the [Chef docs for platform_family](https://docs.chef.io/release/12-5/dsl_recipe.html#platform-family), I would expect this
```ruby
if platform_family?('linux')
  include_recipe '::linux'
elsif platform_family?('windows')
  include_recipe '::windows'
end
```
To include the `::linux` recipe when running on RHEL 6.5, however `platform_family?('linux')` returns false.
Should it be more specific?
In what instances (or OS) would it return true?

Thanks

**Comment by lamont-granquist** [comment]
That line in the docs is completely wrong and needs to be deleted.  Nodes can only have one platform_family.  We have platform_families for 'rhel', 'arch', 'suse', etc.  We can't have a platform_family of 'linux' since that would mean we either couldn't have 'rhel' or that platform_family would be multi-valued.  If you want to check for all-linux, you need to use 'os' like `node["os"] == "linux"`.

**Comment by lamont-granquist** [comment]
doc fix should be in the pipeline to go out right now.

**Comment by monkey1016** [comment]
Sounds good.  Thanks for the clarification.

**Comment by monkey1016** [comment]
Just a heads up, 'linux' shows up under the description for `platform?` as well.

**Comment by monkey1016** [comment]
Never mind.  I was mistaken about `platform?`

**Comment by lamont-granquist** [comment]
yeah, although it looks like the text under platform is the same as the text under platform_family which is also wrong though...  'rhel' isn't a valid platform value...

**Comment by monkey1016** [comment]
Ok, that explains why I remembered seeing it there.  Thanks again for the clarification.
