### ISSUE TITLE
SIGHUP kills chef-client when loading library in client.rb

### ISSUE THREAD

**Issue by rdoorn** [chef/chef#4578]
Hello,

When loading a library in the /etc/chef/client.rb (using the attributes) we get the following code in the client.rb

```
["sbp_nagios_chefclient_handler/sbp_nagios_chefclient_handler"].each do |lib|
  begin
    require lib
  rescue LoadError
    Chef::Log.warn "Failed to load #{lib}. This should be resolved after a chef run."
  end
end
```

when sending a SIGHUP (kill -1) to the chef-client to reload the configuration, the chef-service client dies

```
[2016-02-15T15:13:33+01:00] FATAL: Configuration error ThreadError: can't be called from trap context
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:3:in `block in from_string'
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:1:in `each'
[2016-02-15T15:13:33+01:00] FATAL:   /etc/chef/client.rb:1:in `from_string'
[2016-02-15T15:13:33+01:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

This only happens when loading the library, for the second time due to the sighup.
Tested with a empty library, to exclude code issues:

```
require 'chef/handler'
require 'chef/config'

class SBP
  class Nagios
    class Chefclient
      class Handler < ::Chef::Handler
        def initialize
        end
      end
    end
  end
end
```

Tested on RHEL7 with Chef-client 12.4.3 and 12.7.2
This is especially important because the SIGHUP signal gets sent every sunday in the default logrotate configuration on linux, and this crashing chef-client every week when using libraries.

Temporary workarround is doing a restart instead of reload in logrotate for rhel7 and systemd alike, but it would be better if chef-client handles this correctly.

```
override['chef_client']['log_rotation']['postrotate'] = 'systemctl restart chef-client.service >/dev/null || :'
```

Kind Regards,

**Comment by xTNTx** [comment]
I'm getting same errors but on Centos 6.x while on Centos 7.x it works fine. Chef client version is `12.19.36`.

**Comment by NimishaS** [comment]
@rdoorn , @xTNTx , I have tried the following steps on Centos 6.9 and Rhel 7.2:
a) Configured node with default chef-client cookbook (to start service) using chef-client 12.19.36.
b) Modified client.rb to load a library, such as this empty lib for testing:
```
#client.rb
chef_server_url  "https://chef-tier.lxc/organizations/demo"
validation_client_name "demo-validator"
log_location   "/tmp/cheflogs"
# Using default node name (fqdn)
trusted_certs_dir "/etc/chef/trusted_certs"

require 'chef/handler'
require 'chef/config'

class SBP
  class Nagios
    class Chefclient
      class Handler < ::Chef::Handler
        def initialize
        end
      end
    end
  end
end
```
c) Sent SIGHUP (kill -1) to chef-client process

**– Observations for Centos 6.9:**
```
# service chef-client status
chef-client (pid  27697) is running...

# kill -1 27697

# service chef-client status
chef-client dead but pid file exists

# service chef-client start
```
Here, `kill -1` command runs successfully. The issue says `This only happens when loading the library, for the second time due to the sighup`. So I started the service again and then ran `kill -1` again. It ran successfully.

**– Observations for RHEL 7.2**
```
# service chef-client status

Redirecting to /bin/systemctl status  chef-client.service
● chef-client.service - Chef Client daemon
   Loaded: loaded (/etc/systemd/system/chef-client.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-04-28 10:55:21 UTC; 1h 8min ago
 Main PID: 10100 (chef-client)
   CGroup: /system.slice/chef-client.service
           └─10100 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-c...

Apr 28 12:00:02 nimrhel chef-client[10100]: [2017-04-28T12:00:02+00:00] INFO...)
Apr 28 12:00:02 nimrhel chef-client[10100]: [2017-04-28T12:00:02+00:00] INFO...)
Apr 28 12:00:02 nimrhel chef-client[10100]: [2017-04-28T12:00:02+00:00] INFO...)
Apr 28 12:00:02 nimrhel chef-client[10100]: [2017-04-28T12:00:02+00:00] INFO...)
Apr 28 12:00:02 nimrhel chef-client[10100]: [2017-04-28T12:00:02+00:00] INFO...)
Apr 28 12:00:02 nimrhel chef-client[10100]: [2017-04-28T12:00:02+00:00] INFO...)
Apr 28 12:00:03 nimrhel chef-client[10100]: [2017-04-28T12:00:03+00:00] INFO...s
Apr 28 12:00:03 nimrhel chef-client[10100]: [2017-04-28T12:00:03+00:00] INFO...s
Apr 28 12:00:03 nimrhel chef-client[10100]: [2017-04-28T12:00:03+00:00] INFO...e
Apr 28 12:00:03 nimrhel chef-client[10100]: [2017-04-28T12:00:03+00:00] INFO...)
Hint: Some lines were ellipsized, use -l to show in full.

# kill -1 10100

# service chef-client status
It shows a running service, but with a different process ID.
```

@rdoorn, @xTNTx,  in both cases I am not able ro reproduce the issue. Can you please point out if I am missing anything?

I have also verified by keeping the library that I am loading in a separate file rather than in `client.rb`, but then also `kill -1 <pid>` works successfully.

**Comment by btm** [comment]
I searched for `sbp_nagios_chefclient_handler and found the related code that @rdoorn was originally indicating wasn't the source of the issue because they tested with an empty class and were still able to reproduce. 

https://github.com/schubergphilis/NagiosChefclientHandler

I am able to reproduce a similar error by putting `Mutex.new.lock` in my `client.rb` and sending a HUP signal to a daemonized chef-client service.

```
[2017-05-03T00:00:38-04:00] FATAL: Configuration error ThreadError: can't be called from trap context
[2017-05-03T00:00:38-04:00] FATAL:   /etc/chef/client.rb:7:in `lock'
[2017-05-03T00:00:38-04:00] FATAL:   /etc/chef/client.rb:7:in `from_string'
[2017-05-03T00:00:38-04:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

When I move that from the end of my `client.rb` to the first line, the indicated line number in the exception changes to 1, indicating that in the original poster's failure, it is related to `require 'chef/handler'`. Indeed, I was able to reproduce the error by putting that at the top of my client.rb.

It looks like it's the require itself, not the code in the library that is being required. Requiring `uri` or `json` here also raise this exception:

```
[2017-05-03T00:11:02-04:00] FATAL: Configuration error ThreadError: can't be called from trap context
[2017-05-03T00:11:02-04:00] FATAL:   /etc/chef/client.rb:1:in `from_string'
[2017-05-03T00:11:02-04:00] FATAL: Aborting due to error in '/etc/chef/client.rb'
```

@NimishaS in both your cases you might be reproducing the error but a process supervisor is restarting chef-client when it fails. I can see the fatal errors in `/var/log/chef/client.log` on my system.

It looks like Ruby 2.0+ prevents you from performing a lot of actions inside a `trap` and previously it would allow it but risked deadlocking if the `trap` interfered with resources the main thread was using.

The solution is probably to have `trap("HUP")` in `application.rb` not immediately run `reconfigure` but to set a variable and have #interval_run_chef_client check that variable between runs and reconfigure from the main thread.

**Comment by xTNTx** [comment]
@NimishaS For `Centos 6.9` the log you've pasted indicates that you were able to reproduce the issue. Service status says `chef-client dead but pid file exists` after the reload. It means that client service is crashed. And we can't just manually execute `service chef-client start` because reload happens during chef-client run.
