### ISSUE TITLE
Node method_missing symbol matching incorrectly matches `:>=` into a setter like `:foo=`

### ISSUE THREAD

**Issue by oker1** [chef/chef#4619]
## Description

If you dereference a non-existing key in node.default, and try to compare it's value with >= it writes the right side of the comparison under the key under another ">" key.

I've traced the problem back to the infix invocation of the missing_method (">=") on Node, supporting the accessor method way of using attributes, so the behaviour can be explained, but I think it's still a pitfall.
## Chef Version

12.5.1
## Platform Version

Mac OS 10.11.3
## Replication Case

See https://github.com/oker1/mash-problem for an example cookbook
## Client Output

```
[2016-02-24T10:42:32+01:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.5.1
[2016-02-24T10:42:35+01:00] WARN: Run List override has been provided.
[2016-02-24T10:42:35+01:00] WARN: Original Run List: []
[2016-02-24T10:42:35+01:00] WARN: Overridden Run List: [recipe[example::default]]
resolving cookbooks for run list: ["example::default"]
Synchronizing Cookbooks:
  - example (0.1.0)
Compiling Cookbooks...
{">"=>8000}
Converging 0 resources
[2016-02-24T10:42:35+01:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 02 seconds
```

**Comment by lamont-granquist** [comment]
You mean this line of code?

```
          key_to_set = symbol.to_s[/^(.+)=$/, 1]
```

**Comment by coderanger** [comment]
We should probably error if the first character isn't a letter. I think that's the same rule Ruby uses for method naming, so maybe backwards compatible? Or we could just ignore it until Attributes 2.0 when this whole syntax gets nuked.

**Comment by lamont-granquist** [comment]
Yeah, I'd like to deprecate method_missing in v1.99 as well, it causes so much lolwut...

**Comment by oker1** [comment]
@lamont-granquist yes, that line.

Great to hear we all agree. Is there any public writeup of Attributes 2.0?

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef-rfc/pull/77

**Comment by Tyrael** [comment]
any update on this?

**Comment by lamont-granquist** [comment]
I think the end result of this is actually "don't do that"

The problem here is that this line:

```
if node.default['not_existing']['not_existing2'] >= 8000
```

Needs to be rewritten like:

```
if node['not_existing']['not_existing2'] >= 8000
```

If that means that you need to protect it like this because you lose autovivification:

```
if node['not_existing] && node['not_existing']['not_existing2'] && node['not_existing']['not_existing2'] >= 8000
```

then that is really getting at the crux of the matter, that you're relying on autovivification to not trainwreck and you're getting that value inflated to a hash and then calling the operator on it and we're getting into a trainwreck when method_missing hits autovivification.

the solution here is just to remove all the method_missing handling which will then remove the attempt to set `[:>] = 8000` when method_missing is nuked, which I think will then result in a NoMethodError.

but ultimately i think the problem here is attempting to write shorthand code and rely on too much magic.

**Comment by lamont-granquist** [comment]
Also:

```
if node.default.read('not_existing', 'not_existing2') >= 8000
```

should be both safe (returns nil if the values do not exist) and avoids autovivifying anything and does not trainwreck.

**Comment by lamont-granquist** [comment]
Here's another bad example of this:

```
chef (12.13.16)> node.automatic[:not_present].to_i >= 1000017
 => 1000017
chef (12.13.16)> node.debug_value('not_present')
 => [["default", :not_present], ["env_default", :not_present], ["role_default", :not_present], ["force_default", :not_present], ["normal", :not_present], ["override", :not_present], ["role_override", :not_present], ["env_override", :not_present], ["force_override", :not_present], ["automatic", {"to_i"=>{">"=>1000017}}]]
```

if `node.automatic[:not_present]` were actually present and an integer or a string-representation-of-integer then it would call `#to_i` on it and it would work.  since its not, though, it autovivifies a VividMash (which is basically a Hash) which has no `#to_i` on it.  the `#to_i` then falls into method_missing and autovivifies the hash which then calls `:>=` on the VividMash which then hits method_missing again.

the `#to_i` example here shows how a simple regexp fix just kicks this can down the road though, and this is more than just a problem with the infix `:>=` operator, but its a more general problem with trying to treat VividMashes as Hashes and really calling invalid methods on them and expecting autovivification to be magical and to know that `#to_i` isn't a hash key but its a method to call and that you expected to see a String there but autovivification can only give you a VividMash.

the solution to this is that method_missing access to attributes goes away so that NoMethodError is NoMethodError -- but that doesn't really fix what people are trying to do.

```
node.automatic.read("not_present").to_i >= 1000017
```

that is safe and unambiguous, will not trainwreck, returns nil if the attribute isn't there, and does not autovivify strange keys.

**Comment by lamont-granquist** [comment]
method_missing access to the node object is gone as of (if i recall correctly) Chef 13.0 so this is no longer relevant:

```
chef (15.0.33)> node.automatic[:not_present].to_i >= 1000017
Traceback (most recent call last):
       16: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
       15: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
       14: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
       13: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
       12: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
       11: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
       10: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
        9: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
        8: from /Users/lamont/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
        7: from /Users/lamont/.rvm/gems/ruby-2.5.1/bin/chef-shell:23:in `<top (required)>'
        6: from /Users/lamont/.rvm/gems/ruby-2.5.1/bin/chef-shell:23:in `load'
        5: from /Users/lamont/oc/chef4/bin/chef-shell:31:in `<top (required)>'
        4: from /Users/lamont/oc/chef4/lib/chef/shell.rb:80:in `start'
        3: from /Users/lamont/oc/chef4/lib/chef/shell.rb:80:in `catch'
        2: from /Users/lamont/oc/chef4/lib/chef/shell.rb:81:in `block in start'
        1: from (irb):1
NoMethodError (undefined method `to_i' for {}:Chef::Node::VividMash)
Did you mean?  to_s
               to_a
               to_h
chef (15.0.33)>
```

That is the correct error code because `:not_present` gets autovivified into an empty VividMash (because it has to, because autovivification) and then calling `.to_i` on that throws NoMethodError.
