### ISSUE TITLE
Mount Resource for bind mounts is not idempotent

### ISSUE THREAD

**Issue by pollosp** [chef/chef#4660]
## Description

Mount Resource for bind mounts is not idempotent
Here https://tickets.opscode.com/browse/CHEF-5254 is a similar bug opened with version 11.12.2 and fixed in version 11.14.0
## Chef Version

12.7.2 + Opscode server version
## Platform Version

Debian Jessie 8.3
## Replication Case

This is the provider code.

```
mount '/mnt' do
  device '/tmp'
  fstype 'ext4'
  options %w(bind rw)
  action [:mount, :enable]
end
```

Bind mountpoints in fstab file are mounted again in every chef-run, if you run chef-client four times you are going to have the resource mounted four times.

Fstab file is ok just one line per mount. 

Now mounted binds in jessie are not displaying the word bind as in squeeze with the mount command and using cat /proc/mounts  
## Client Output

``` shell
sudo chef-apply mount.rb

Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * mount[/mnt] action mount
    - mount /tmp to /mnt
  * mount[/mnt] action enable
    - enable /tmp
vagrant:~/code$
vagrant:~/code$ sudo chef-apply mount.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * mount[/mnt] action mount
    - mount /tmp to /mnt
  * mount[/mnt] action enable (up to date)
vagrant:~/code$ mount
/dev/sda1 on /mnt type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/sda1 on /mnt type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by josacar** [comment]
Fix in ansible: https://github.com/ansible/ansible-modules-core/issues/1942

**Comment by josacar** [comment]
This patch seems to work it out:

```diff
diff --git a/lib/chef/provider/mount/mount.rb b/lib/chef/provider/mount/mount.rb
index f8b8684..9cf8ee3 100644
--- a/lib/chef/provider/mount/mount.rb
+++ b/lib/chef/provider/mount/mount.rb
@@ -85,14 +85,17 @@ class Chef
                                @new_resource.mount_point
                              end

-          shell_out!("mount").stdout.each_line do |line|
+          shell_out!("findmnt -rn").stdout.each_line do |line|
             case line
-            when /^#{device_mount_regex}\s+on\s+#{Regexp.escape(real_mount_point)}\s/
+            when /\A#{Regexp.escape(real_mount_point)}\s+#{device_mount_regex}\s/
               mounted = true
               Chef::Log.debug("Special device #{device_logstring} mounted as #{real_mount_point}")
-            when /^([\/\w])+\son\s#{Regexp.escape(real_mount_point)}\s+/
+            when /\A#{Regexp.escape(real_mount_point)}\s+([\/\w])+\s/
               mounted = false
               Chef::Log.debug("Special device #{$~[1]} mounted as #{real_mount_point}")
+            when /\A#{Regexp.escape(real_mount_point)}\s+([\/\w])+\[#{device_mount_regex}\]\s/
+              mounted = true
+              Chef::Log.debug("Bind device #{device_logstring} mounted as #{real_mount_point}")
             end
           end
           @current_resource.mounted(mounted)
```

**Comment by thommay** [comment]
@josacar can you submit that as a pull request please?

**Comment by lamont-granquist** [comment]
that is going to also be the default mount provider for BSD and other operating systems (although not solaris/aix/windows that have their own).   

yeah and findmnt is not in centos 5.x so there's no way we can take that patch.

**Comment by josacar** [comment]
yes, I supposed that. I'll try to look for another solution. Also a warning or error should be raised in these scenarios.

**Comment by tgagor** [comment]
I could confirm this bug on CentOS 7.x with chef-client 12.1.2. In my case effect of this bug was quite impressive: after every chef-client run mount doubled amount of mounts. After about 12h machine end up with about 1mln of mount points and oomkiller enters party killing processes one by one :-)

When do you plan to fix this bug? Could it be possible to backport this fix also for older releases like mine (I can't currently safely upgrade to newer versions because of some cookbooks incompatibility problems with chef-client above 12.1)?

**Comment by josacar** [comment]
I just removed the `:mount` with a `mount -a`. Another posibility is use automounter like in opsworks cookbooks.

**Comment by karcaw** [comment]
I am Experiencing this issue as well. please fix.

**Comment by moll** [comment]
Seeing the same thing in Chef v12.16.42. Quite a bug given I too ended up with a million mountpoints on Ubuntu 16.04 LTS.

**Comment by thommay** [comment]
this has come up in regard parsing remote mount points on ubuntu 16.04…

**Comment by lamont-granquist** [comment]
I doubt we have any functional testing of the mount provider on FreeBSD, but its important that any patch to this not totally break FreeBSD (and any other operating systems which might use this as the default mount provider).  Ideally testing for that would be added.  If this can be patched by obvious and simple extensions that should be portable across Unix-like operating systems that would be acceptable.  Another possible solution is to write a more linux-focused mount provider that used findmnt and keep that totally separate (we don't support rhel5 any more so that isn't a concern, but rhel-vs-ubuntu-vs-<other> linux gentoo, arch, and whatever else is).

**Comment by antima-gupta** [comment]
@lamont-granquist @tas50 If we run `mount` command to list all the mount points, it gives us following output:

```
/dev/sda1 on /mnt type ext4 (rw,relatime,errors=remount-ro)
/var/lib/snapd/snaps/core18_1668.snap on /snap/core18/1668 type squashfs (ro,nodev,relatime,x-gdu.hide)
/var/lib/snapd/snaps/gnome-3-34-1804_36.snap on /snap/gnome-3-34-1804/36 type squashfs (ro,nodev,relatime,x-gdu.hide)
configfs on /sys/kernel/config type configfs (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/var/lib/snapd/snaps/gnome-3-28-1804_128.snap on /snap/gnome-3-28-1804/128 type squashfs (ro,nodev,relatime,x-gdu.hide)
vmware-vmblock on /run/vmblock-fuse type fuse.vmware-vmblock (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other)
tmpfs on /run/user/121 type tmpfs (rw,nosuid,nodev,relatime,size=400224k,mode=700,uid=121,gid=125)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=400224k,mode=700,uid=1000,gid=1000)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)

```
In this [code](https://github.com/chef/chef/blob/3e9e6d41a31bd1ac932f7f4100102466b4fdfe05/lib/chef/provider/mount/mount.rb#L94), 
first when condition is not satisfying and it is going into next when block [here](https://github.com/chef/chef/blob/3e9e6d41a31bd1ac932f7f4100102466b4fdfe05/lib/chef/provider/mount/mount.rb#L99).

As per `mount` command output, that second case regular expression will always satisfy and it will make `mounted = false` .
So It will run command to create a new mount point again, that is the cause of this issue.

[when condition](https://github.com/chef/chef/blob/3e9e6d41a31bd1ac932f7f4100102466b4fdfe05/lib/chef/provider/mount/mount.rb#L99) is written to make provider work ,when there are multiple devices mounted to the same mount point.

But without this also it works fine.

To list the mount points there is some commands: `mount`,  `df -Th #device`, ` findmnt`, `cat /proc/mounts`,`cat /proc/self/mounts`, `cat /proc/self/mountinfo`.

Only ` findmnt` and `cat /proc/self/mountinfo` provide the mount points along with device. 

Can we use `cat /proc/self/mountinfo` command to find the existing mount point instead of using `mount`?

Or please suggest better way to fix this issue.
