### ISSUE TITLE
Include unzip.exe in bin folder

### ISSUE THREAD

**Issue by kaltokri** [chef/chef#4679]
## Description

tar.exe is included in bin folder of chefdk and chef-client which enables unzip of tar.gz files with the same command line on Windows and Linux. If unzip.exe will be added we have the same advantage for unzip, too.

## Chef Version

Chef Development Kit Version: 0.9.0

## Platform Version

Windows 8.1 & CentOS 7.1.

## Replication Case

Add a execution resource to a sample cookbook to use the unzip command line tool. On Linux add package unzip, too. Run it on Windows. If you have installed 'git for Windows' or Oracle db it will work, because both includes unzip.exe and change the PATH environment variable. But when the cookbook is executed on staging area (where no Oracle and git is installed) the cookbook will fail.

**Comment by lamont-granquist** [comment]
Couple issues:  this is the wrong repo, this is for client bugs only and this is chef-dk and would need to be filed over in http://github.com/chef/chef-dk/issues/new.  We're also not trying to install a complete development environment with chef-dk.  The unzip program is there because we need it in order to build it and it winds up getting shipping with the package.  We're actually more likely to remove unzip from the windows package than we are to include unzip in the Unix package.

**Comment by coderanger** [comment]
For bonus points, if you want platform-agnostic unzipping from Chef cookbooks you can use RubyZip as it is pure Ruby.
