### ISSUE TITLE
All knife plugin are loaded automatically when running without `knife rehash`.

### ISSUE THREAD

**Issue by sawanoboly** [chef/chef#4758]
## Description

All knife plugin are loaded automatically when running without `knife rehash`. It causes override of unexpected options. This is different from the previous behavior?

## Chef Version

Chef 12.6.0〜

## Platform Version

- OSX 10.11.4
- Ruby 2.2.4

## Replication Case

https://github.com/chef/chef/issues/4756
https://github.com/higanworks/knife-zero/issues/92

**Comment by lamont-granquist** [comment]
Hows it supposed to work?  We need to parse all the files to know what the commands in them are.  So if I type `knife foo bar baz` there's no inherent way to know if its in some gem's `lib/knife/foo.rb` or `lib/knife/foo_bar.rb` or `lib/knife/foo/bar.rb` or in `lib/knife/arglebargle.rb`

Changing that at this point would most likely be way too disruptive of an API change.

**Comment by sawanoboly** [comment]
@lamont-granquist 

If I remember correctly, the plugins of Chef in the non-interference in each other, had been loaded only option when use previously.

I seem that this behavior has changed ?

**Comment by sawanoboly** [comment]
For example, knife rehash and without rehash.

without knife rehash, chef v12.6〜

`knife bootstrap` includes `knife zero bootstrap` options. It causes overrides default parameter of policy-group.

with knife rehash, chef v12.6〜

`knife bootstrap` ignores `knife zero bootstrap` options. It doesn't overrides default parameter of policy-group.


There is change the behavior before and after the  `knife rehash`. I think that knife command should ignores options which come from other plugins without `knife rehash` in the same way after knife rehash.

**Comment by lamont-granquist** [comment]
is that just an accident of which way the knife subcommand loader loads up the classes and `knife rehash` changes the ordering?

**Comment by lamont-granquist** [comment]
heh, okay i see what knife-rehash does now and why this 'fixes' it...

the knife subcommand loader has always behaved this way, and you need to fix the code in knife-zero.

what you're saying here:

`I think that knife command should ignores options which come from other plugins without knife rehash in the same way after knife rehash.`

the way that you want knife commands to work /is/ `knife rehash`.

the default way knife commands load up without knife-rehash is to load all the classes from all the files.  knife-rehash is fast because it has a static mapping of the subcommand you want to run to the ruby file to Kernel.load so that it doesn't have to load them all up.

**Comment by sawanoboly** [comment]
Thanks, I see.
