### ISSUE TITLE
If a password is provided on the command line, sudo commands should not prompt for a password

### ISSUE THREAD

**Issue by atheiman** [chef/chef#4783]
When I run a sudo command using `knife ssh`, I am prompted for a password [(`Enter your password`)](https://github.com/chef/chef/blob/master/lib/chef/knife/ssh.rb#L337). If I logged into the node with the password argument to the `-P` flag rather than using an ssh key, the utility should already know my password and it should be passed into the sudo prompt automatically.

I dont know of a situation where a user's sudo password would be different than a password used to login to via ssh, so I think sudo should never prompt for a password when its provided at the command line.

Current state:
```shell
$ knife ssh name:mynode 'hostname' -P mypassword
mynode mynode.mydomain.com
$ knife ssh name:mynode 'sudo hostname' -P mypassword
mynode knife sudo password:
Enter your password:
mynode
mynode mynode.mydomain.com
```

Desired state:
```shell
$ knife ssh name:mynode 'hostname' -P mypassword
mynode mynode.mydomain.com
$ knife ssh name:mynode 'sudo hostname' -P mypassword
mynode knife sudo password:
using sudo password provided at command line...
mynode
mynode mynode.mydomain.com
```

I will take a look at implementing this, if I did not explain the problem clear enough, please tag me in a comment and I will try to clarify

**Comment by lamont-granquist** [comment]
If you look at implementing this keep in mind that *any* scanning you do of the command line to determine "does this command run sudo" is going to have edge conditions which must fail one way or the other and will be inherently brittle (i.e.  you go down the road of needing to determine 'sudo foo' from 'echo "sudo"') 

sudo prompts are also customizable and the "Enter your password:" prompt is not going to necessarily be universal -- and Chef doesn't just run on recent Ubuntu and RHEL but AIX6, Solaris 10, FreeBSD, RHEL5 from 10+ years ago, etc that have wildly divergent codebases.    Also words like "password" may enter the output stream just from cat'ing a file on the remote which has the word "password" in it and it may be inappropriate to respond with the users password in response to any text in the output that seems to match a sudo password prompt.

any solution needs to not be brittle, and definitely needs to be customizable, so that users can override it.

**Comment by atheiman** [comment]
playing around with this a little more, I discovered there is a `-S, --stdin` flag for sudo that reads the sudo password from stdin:

```
$ knife ssh name:mynode "echo 'password' | sudo -S whoami" -P password
mynode [sudo] password for someuser: root
```

Since `sudo` still shows a prompt when reading the password from stdin (strange), it looks a bit better with specifying an empty prompt:

```
$ knife ssh name:mynode "echo 'password' | sudo -S -p '' whoami" -P password
mynode root
```

**Comment by abajracharya** [comment]
but isn't that a bad practise to actualy echo your passwork while running knife command, assuming you are not in a local machine. if you are in local machine it should be fine.
