### ISSUE TITLE
Unable to create Windows Chef Workstation for VMware CentOS Chef Server

### ISSUE THREAD

**Issue by Shawn-Mathew** [chef/chef#4794]
## Description

I am following the tutorial for manually configuring an onsite chef-server. I was able to accomplish this on a CentOS VM created in VMware Vsphere ESXi and can access the Chef-Server Web UI within the Chef-Server Web browser.

I am now attempting to create a chef-workstation directly on my local Windows 7 machine. I have installed the chef-development kit as well as GitBash and made a directory ~/learn-chef.

The directions in the tutorial state to now access the on the workstation browser "https:<chef-server-ip-address>" and download the starter kit.

Problem is that when I attempt this, browser returns "Connection has timed out" and so I am unable to proceed further.

It should be noted that the IP address of my Chef Server VM is in my local network: 10.1.10.37 with my workstation ip being 10.1.10.49.

As I understand it the problem seems to be that I cannot remotely connect to the chef-server web UI perhaps due to some firewall issue. 

On my Windows workstation I attempted disabling my windows firewall and trying to connect but it still says "Connection timed out".

I have heard that VMware has its own firewall and that may be blocking the connection but I am not sure how to resolve this. 

Any help would be very much appreciated.
  
## Chef Version

Chef Server: Version 12.4.1
Chef Workstation:
    Chef Development Kit: 0.11.2
    chef-client version:12.7.2
    berks version: 4.2.0
    kitchen version: 1.5.0

## Platform Version
Chef Server: VMware Vsphere ESXi VM ---> CentOS 7x86_64 DVD ISO
Chef Workstation: Windows 7

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
