### ISSUE TITLE
How to get audit result by report handler without Chef Analytics server

### ISSUE THREAD

**Issue by cawamata** [chef/chef#4800]
## Description

I'd like to get audit result by report handler without Chef Analytics.
I confirmed run_status output, however some audit attributes are private
 - audit total counts can be gotten from total_audits (https://github.com/chef/chef/blob/master/lib/chef/formatters/doc.rb)

## Chef Version

12.8.1

## Platform Version

CentOS6 and 7

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
