### ISSUE TITLE
Powershell not_if fails when powershell_out works

### ISSUE THREAD

**Issue by youngjl1** [chef/chef#4803]
## Description

A certain line of powershell code "import-module webadministration; Get-WebConfiguration –filter system.applicationhost/sites/sitedefaults/logfile" is failing when it is used inside a not_if. When that same line of code is executed in powershell_out it works fine. Incidentally it's a line of code that works in 64bit powershell and fails in 32bit powershell.
## Chef Version

12.8.1
## Platform Version

Microsoft Windows Server 2008 R2 Standard
## Replication Case

In the below case the guard_interpreter runs successfully, returning true and skipping normal execution

``` Ruby
guard_script = <<-EOH
        import-module webadministration
        $log_fields = Get-WebConfiguration –filter system.applicationhost/sites/sitedefaults/logfile | Select-Object -ExpandProperty logExtFileFlags
        ($True)
EOH

powershell_script "set iis logging fields" do
  guard_interpreter :powershell_script
  code <<-EOH
    # do something
  EOH
  #Script fails if I just use not_if. Suspect the reason is 32-bit powershell
  not_if powershell_out(guard_script).stdout
end
```

The below however uses the exact same code but the guard_interpreter doesn't work and the main is not skipped

``` Ruby
powershell_script "set iis logging fields" do
  guard_interpreter :powershell_script
  code <<-EOH
    # do something...
  EOH
  #Script fails if I just use not_if. Suspect the reason is 32-bit powershell
  not_if <<-EOH
        import-module webadministration
        Get-WebConfiguration –filter system.applicationhost/sites/sitedefaults/logfile 
        ($True)
  EOH
end
```

Furthermore I can get the above to work by commenting out the Get-WebConfiguration line e.g.

``` Ruby
powershell_script "set iis logging fields" do
  guard_interpreter :powershell_script
  code <<-EOH
    # do something...
  EOH
  #Script fails if I just use not_if. Suspect the reason is 32-bit powershell
  not_if <<-EOH
        import-module webadministration
        #Get-WebConfiguration –filter system.applicationhost/sites/sitedefaults/logfile 
        ($True)
  EOH
end
```
### NOTE: CHEF CLIENT BUGS ONLY

This is definitely a chef client issue as I am not using any other cookbooks

**Comment by lamont-granquist** [comment]
well i know why they're not the same.

your first example you are:

- calling `powershell_out(guard_script).stdout` and getting back a string
- invoking the powershell guard on the stdout return from that command

the second example you are:

- invoking the powershell guard on the `guard_script` string.

two make the two examples similar you'd need to do this:

```ruby
powershell_script "set iis logging fields" do
  code <<-EOH
    # do something
  EOH
  #Script fails if I just use not_if. Suspect the reason is 32-bit powershell
  not_if { powershell_out!(guard_script).error? }
end
```

i think...   my actual knowledge of powershell is nearly zero and i'm not certain that `error?` is the correct way to get the return truthy or falsey return value out of the powershell script (which i think you're trying to do but IDK).

anyway the point here is that now you're using the ruby guard interpreter to invoke powershell once through powershell_out and avoiding the double powershell-out.

IDK if that helps at all.

i'm also quite suspicious that you were actually getting "correct" behavior out of the first example -- or if you were getting correct behavior it was via a fairly tortured route and you definitely shouldn't be using that code.

**Comment by lamont-granquist** [comment]
To maybe be clearer, this:

```ruby
powershell_script "set iis logging fields" do
  guard_interpreter :powershell_script
  not_if powershell_out(guard_script).stdout
end
```

is roughly equivalent to this:

```ruby
powershell_script "set iis logging fields" do
  guard_interpreter :ruby # being explicit but if you change the not_if to have a block this is what you'll get
  not_if { powershell_out!(powershell_out(guard_script).stdout).exit? }
end
```

**Comment by lamont-granquist** [comment]
(again modulo that the implementation of the powershell guard and powershell_out evolved separately so that there might be differences in implementation and i'm taking a bit of a stab in the dark at how the powershell guard is written without actually burning a couple hours studying the code -- but the overall point i'm trying to make there is that you're invoking powershell twice)

**Comment by btm** [comment]
@lamont-granquist raises the most important point, `not_if powershell_out(guard_script).stdout` isn't actually doing what you want. It is skipping the execution of the script but only because you're passing a string which will (almost?) always be true and skip execution.

You shouldn't need to specify to specify `guard_interpreter :powershell_script`, that's been the default for quite a while (before 12.8.1, looks like 12.4.0).

The guard is run using 64bit powershell, which you can verify with:
```
powershell_script "test 64bit guard" do
  code "fail"
  not_if '[Environment]::Is64BitProcess'
end
```

That will skip because it's returning true for the guard.

You need to be sure that your guards are working as expected by reviewing the debug output. Someone else was debugging this ticket recently and was finding that `Import-Module webadministration` was failing for them, not the later `Get-WebConfiguration` command:

```
#<Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -Exe
cutionPolicy Bypass -InputFormat None -File "C:/Users/azure/AppData/Local/Temp/2/chef-script20161206-1864-3ncdxm.ps1" --
--
STDOUT:
STDERR: The specified module 'webadministration' was not loaded because no valid module file was found in any module dir
ectory.
---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -Execu
tionPolicy Bypass -InputFormat None -File "C:/Users/azure/AppData/Local/Temp/2/chef-script20161206-1864-3ncdxm.ps1" ----

Ran "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypa
ss -InputFormat None -File "C:/Users/azure/AppData/Local/Temp/2/chef-script20161206-1864-3ncdxm.ps1" returned 1>
```

For more assurance in your recipe, you might add a powershell_script resource earlier that runs `Get-WebConfiguration` but is a noop and always returns true, such that it would fail if `Get-WebConfiguration` couldn't run successfully which would raise an exception and end your Chef run.

This is an old ticket, hopefully you solved you problem already. I'm going to close this up. In the future you might start over at https://discourse.chef.io/, where you'll get more help on recipe issues, before opening a bug. Thanks for running Chef on Windows!
