### ISSUE TITLE
Improve knife presenter for arrays attribute

### ISSUE THREAD

**Issue by kamaradclimber** [chef/chef#4808]
## Description

When node attributes are arrays, it is impossible to write a knife command to access them easily.
## Chef Version

Any version
## Replication Case

node attributes are:

```
{ 
  'foo' => [
    { 'bar' => true },
    { 'bar' => false }
  ]
}
```

It is impossible to access the value of bar in the second element of foo.
One could expect to call: `knife node show xxx -a foo.1.bar` and gets `false`.

Currently it fails with an exception.

**Comment by kamaradclimber** [comment]
A simple patch in `Chef::Node::ImmutableArray` would solve the issue:
```
def has_key?(i)
  integer = i.to_i
  integer.to_s == i.to_s && (0...self.size).include?(integer)
end

def [](i)
  super(i.to_i)
end
```

**Comment by kamaradclimber** [comment]
if you think the issue is interesting, tell me and I'll submit a PR.

**Comment by lamont-granquist** [comment]
Arrays don't support has_key? so I don't think we should be patching Chef::Node::ImmutableArray this way.

The code in knife that calls has_key? really needs to be changed to not call has_key?  it may be better to just trainwreck and rescue, and the code in knife should probably look a bit more like the code that claire is writing here:

https://github.com/chef/ohai/pull/796

Since its Immutable its very pointless to worry about trainwrecking since you don't autovivify on access.
