### ISSUE TITLE
chef access to os package info mangled > 12.8.1

### ISSUE THREAD

**Issue by rljohnsn** [chef/chef#4849]
## Description
Omnibus install using latest 12.9 started throwing errors on unchanged cookbooks. Github link to original issue thought to be in the cookbook https://github.com/dev-sec/chef-os-hardening/issues/112

## Chef Version
chef-solo: 12.9.38
ohai: 8.14.0

## Platform Versions
OS image: Amazon Linux AMI release 2015.09 (ami-f0091d91)
OS Image: Centos 6.7

## Replication Case
Include [os-hardening](https://github.com/dev-sec/chef-os-hardening) cookbook in your chef run with 12.9.x client install.

## Client Output
chef-solo log: https://gist.github.com/rljohnsn/36cdf0e8525f5113a56afd8a69c85cfc
ohai output: https://gist.github.com/rljohnsn/8cd4b428e73c3d465376b072183787ba

**Comment by lamont-granquist** [comment]
You need to be a bit clearer about what you're seeing in ohai output and what you are expecting.  Your ohai output looks fine to me, so what do I need to be looking at?

AFAIK, we added the packages plugin to ohai sometime around 12.8.1 timeframe, but we were supposed to be adding it disabled:

https://github.com/chef/ohai/pull/717

If you are expecting a different format,then its likely that you were pulling in a custom plugin that was not in core which the new core plugin overrode.  We also might have a bug since the new core plugin was supposed to be disabled by default.  On the other hand, we're going to make the core plugin enabled by default and it'd be better to migrate to using it anyway.

**Comment by lamont-granquist** [comment]
This is also an ohai issue and should really get opened against https://github.com/chef/ohai/issues/new

**Comment by lamont-granquist** [comment]
Yeah this is solidly a bug in the cookbook:

https://github.com/dev-sec/chef-os-hardening/pull/88
