### ISSUE TITLE
Mount provider should support sensitive property

### ISSUE THREAD

**Issue by timbrown5** [chef/chef#4850]
## Description

I am using Chef-vault to try and keep my passwords secure. I am currently using one of the vault Items to try and mount a share. 

My problem is that the error output from chef printed the RAW password, not the encrypted or hashed out version, meaning anyone can circumvent the chef-vault by creating a bad mount recipe!

Would it not be better to hash out ALL 'password' attributes/fields in when printing them so that they are not shown to users (who might not be intended to see them!) or stored in log files?
## Chef Version

Chef: 12.6.0
## Platform Version

Windows 10
## Replication Case

  mount 'O:' do
    device '\\myShare\myFolder'
    action :mount
    domain 'myDomain'
    username testUser['username']
    password testUser['password']
  end
## Client Output

Error output:
    mount("O:") do
      action [:mount]
      supports {:remount=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      mount_point "O:"
      device "'\\myShare\myFolder'"
      device_type :device
      fsck_device "-"
      fstype "auto"
      options ["defaults"]
      dump 0
      pass 2
      username "muUser"
      password "myPassword"
      domain "myDomain"
      declared_type :mount
      cookbook_name "sn_users"
      recipe_name "test_user"
    end

**Comment by lamont-granquist** [comment]
You should actually be able to pass it `sensitive true` and it may prevent that debug logging, I'm not sure if any changes to the provider are necessary.

**Comment by thommay** [comment]
It probably should do that by default when a password is passed to it, just to avoid this outcome.

**Comment by lamont-granquist** [comment]
so, ultimately though, this isn't much of a practical security issue.  the assumption here is that "anyone can create a bad mount resource".  under that threat model if you give me the ability to inject resources intoa chef-client run i can open up remote root access to the box and steal the client credentials.  i can also probably just use the mountpoint directly on the server since i have enough leverage to be able to break into it, so the password itself is probably moot anyway.  i can therefore always recover the password, or just inject logging commands to give myself the password.  chef-vault does nothing to protect credentials that the chef-client run can use against compromise from an attacker that can compromise the server at the root level or inject chef-client config or otherwise steal the chef client credentials.

OTOH, certainly wouldn't stand in the way of someone submitting a PR to set `sensitive true` if a `password` property was set on the resource (globally, for all resources most likely).

**Comment by tas50** [comment]
This was already fixed so I'm going to close it out.
