### ISSUE TITLE
chocolatey_package should build candidates one at a time

### ISSUE THREAD

**Issue by ferventcoder** [chef/chef#5040]
## Description

https://github.com/chef/chef/blob/de78e3902a6b1743f0d69bbac073c274ed85cb80/lib/chef/provider/package/chocolatey.rb#L229-L239

The above code on first glance looks like it would be more efficient because it is just one call to choco, but it actually is less efficient. Caching strategies are prepped already for `choco list package1`, `choco list package2` versus `choco list package1 package2 packageN`. We can't effectively cache the latter, it ends up using much more memory and increases load on https://chocolatey.org.

Further, I think we are going to need to flip our filter here to move to an "AND" instead of an "OR" to handle future cases (once of course you all fix it in this provider) because of the increased load we've been seeing against the site.
## Chef Version

Any current
## Platform Version

Windows

**Comment by ferventcoder** [comment]
It could be a design decision, but I'm not fully aware of why an updates list needs to be built for all packages installed.

**Comment by lamont-granquist** [comment]
so chef needs to do its own idempotency checks.  e.g. we don't run `choco upgrade <package>` and then parse the output to see if something got upgraded, we need to know what is installed and what is available and be able to make our own decisions.  that is very baked into the way that actions are implemented inside of chef and highly baked into the way that the package superclass behaves.

**Comment by lamont-granquist** [comment]
one thing to consider here is that all the other major package managers that chef targets provide their own client-side caching baked into them.   e.g. we generally expect to have to run `apt-get update` at the start of a chef-client run.  then we later basically do `apt-cache search lsof` to see the available versions of lsof which does not do a network connection and only hits the local cache of all the apt packages.

if there were some kind of `choco cache update` and `choco cache search git 7zip` then we could use the same approach and only have to hit chocolatey.org once for metadata every run (and slurp down the whole cache of available packages -- but you can optimize the crap out of that query -- and for the apt_update resource we have default throttling around that so that it only runs once per day per server instead of once per run).

**Comment by ferventcoder** [comment]
@lamont-granquist I understand that. 

I will step back for a moment and provide a Puppet sense to try to get an understanding of Chef's provider.

`ensure => installed`
`ensure => latest`
`ensure => 1.0.0`
`ensure => held`

If Chef has the same concept, you are still building checks for all of these scenarios and really only need it for ensure latest.

**Comment by ferventcoder** [comment]
@lamont-granquist Oh we definitely have plans for client-side caching (package indexes). We really have to provide that. 

The command we are looking to do this through is `choco update` (that's why we moved upgrades to upgrade and deprecated the update command).

If we could find a way to not crush the server in the here and now until we can provide the local indexing option, I think that would be most desirable.

**Comment by ferventcoder** [comment]
I believe that option is to call out several times in `available_upgrades` to `choco search package1`, `choco search package2`, instead of `choco search package1 package2 packageN`, so the calls use the cached queries and return near instantaneously, instead of attempting to build and provide a cache for each different computer's installed packages. It's impossible to optimize for that without local package indexes.

**Comment by lamont-granquist** [comment]
so one question is if you're getting the benefits of lazy evaluation or not.  in the common case users should be using ":install" as an action (ensure => installed in puppetsense?) and then we should only check the installed version.  because of multipackage-code $REASONS we were hammering on candidate_version though even though we didn't need to.  that was fixed in the superclass in #4869 but the subclass can still have code bugs that cause that to happen anyway.  if that is the case then we can just fix it.

#4122 is an example of this kind of bug in the chef_gem provider.

**Comment by lamont-granquist** [comment]
Hrm, so just looking through the code in the chocolatey provider I don't see that kind of bug, candidate_version/build_candidate_version/available_packages don't have any other code paths that would hit them.

So you may be seeing *very* high load from clients before v12.10.32 (and after v12.7.2 when the chocolatey provider was added).   It looks like that missed the 12.10.24 release window as well, so its only the latest 12.11.18 release where this perf bug would have been fixed.

**Comment by mwrock** [comment]
Yes my guess is the 12.11.18 install base is on the small side right now. Also, my non-scientific guess is that windows nodes are one of the slower groups to upgrade.

**Comment by ferventcoder** [comment]
Great, that's good to know. 

I believe there is still a potential issue in caching and server load in the way you ask the remote server if there are updates and pass all candidates at once. My understanding of the filter is that it was an AND, but what we are seeing is that it is an OR, which is allowing the multiple packages passed to work.

**Comment by lamont-granquist** [comment]
yeah so if multiple requests for single packages is better, that'd be fine to do, its kind of up to you...

**Comment by ferventcoder** [comment]
That's how we are optimized now. 👍

**Comment by ferventcoder** [comment]
Once we have local indexes we can explore that route.

**Comment by stuartpreston** [comment]
I'm going to close this as it's a very old issue and the desired behavior appears to be our documented path right now (i.e. oriented around individual chocolatey_package resources and calling choco.exe for each one).
