### ISSUE TITLE
Don't discourage the chef-dk gem

### ISSUE THREAD

**Issue by mcandre** [chef/chef#5043]
Many people would prefer to install chef-dk via RubyGems, especially for RVM support. So please don't show a banner insisting that we use an OS-specific ChefDK package that can't be managed by RVM.

**Comment by coderanger** [comment]
The banner is there to make it clear that while gem installs get you the `chef` command line tool, it's very much not the same thing as "installing ChefDK". Especially for people that already are used to Ruby development workflows, they may not be expecting to install an alternate package but this is the only way we can keep user support manageable. If you are enough of an advanced user to take responsibility for your own errors, then you can ignore the warning (which is why `chef-dk` continues to be distributed as a gem too).

**Comment by lamont-granquist** [comment]
Yep, this is both the wrong repo to cut this against, and we're not going to remove the banner, it remains discouraged.

I regularly swim past signs like this, up to 3,000 feet (60 minutes of swimming) so far past them:

![grim reaper](http://www.lovethesepics.com/wp-content/uploads/2012/06/Nothing-in-this-cave-worth-dying-for-Vortex-Spring-grim-reaper.jpg)

Those warnings serve their purpose, and I have the training and understand the risks of swimming past them...
