### ISSUE TITLE
knife status show "minutes" instead of "seconds"

### ISSUE THREAD

**Issue by arielrolfo** [chef/chef#5055]
## Description

When a node.save operation is executed and a "knife status" is immediately executed I get "xx minutes" instead of "xx seconds".
## Chef Version

v12.11
## Platform Version

rhel 7
## Replication Case

In order to replicate this issue a node has to run the ohai recipe and "knife status | grep the-node" has to be executed immediately after that and you will notice:

`59 minutes ago, the-node-here, redhat 7.1.`

**Comment by cramaechi** [comment]
Hi everyone,

I am a new chef-client contributor and would like to handle this ticket.

I believe the underlying problem is that the code behind `knife status` is only considering hours and minutes as the options to use in constructing the output message. My proposed change would be to modify `summarize()` in `chef/lib/chef/knife/core/status_presenter.rb `  as shown in the following screenshot:

<img width="504" alt="screen shot 2018-01-08 at 2 36 22 pm" src="https://user-images.githubusercontent.com/24444174/34695599-1abcc5bc-f491-11e7-9d0b-e90f3512e95e.png">

The same exact changes would also have to be applied to 
`chef/pkg/chef-13.7.5/lib/chef/knife/core/status_presenter.rb` and `chef/pkg/chef-13.7.5-universal-mingw32/lib/chef/knife/core/status_presenter.rb`.

Please share your thoughts.

Best Regards,
Chibuikem Amaechi

**Comment by coderanger** [comment]
@cramaechi Welcome. We use Pull Requests here to share and review patches. https://help.github.com/articles/about-pull-requests/ covers the basic process but it looks like you've made a few before, so you can just follow the same process as you did before. Just mention this ticket number in the description for your new Pull Request and it will link the issue. The fix looks good, though you may need to update some of our unit and functional tests. https://github.com/chef/chef#testing shows how to run our tests once you have a local fork. Thanks for helping out!

**Comment by cramaechi** [comment]
Hi coderanger,

Thank you for the warm welcome!

I will go ahead and open a pull request. I don't believe any unit or functional tests need updating seeing as how the method I modified is a member of a private class, which makes me suspect that another unit of the public interface is already exercising the method. Additionally, there doesn't seem to be a corresponding _spec file for the `chef/lib/chef/knife/core/status_presenter.rb` file. 

Please share your thoughts.

- Chibuikem. A

**Comment by tas50** [comment]
We fixed this back in 15.1
