### ISSUE TITLE
how to pass attribute override in json for chef-client local mode and chef-solo

### ISSUE THREAD

**Issue by kuberkaul** [chef/chef#5135]
I have a cookbook and roles.son and environment.json file available. I run them through both chef-solo and chef-client -z (local mode).

Both give the ability to add -j flag to pass the roles.json but doesn't provide any easy way of attribute overriding using environment.json. I am not using a server so not pushing it any where.

Am I missing something ?

I have something like this :

cookbooks  environment.json  file.txt  local-mode-cache  nodes  roles.json
and I'm running the following

1 : chef-client local mode with client.rb:

log_level               :info
log_location            "/var/log/chef/client.log"
node_name       "ip-10-201-38-78"
cookbook_path           "/tmp/cookbooks/"
json_attribs        "/tmp/roles.json" 
chef-client -z -c client.rb -j roles.json

chef-solo -c client.rb -j roles.json

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
