### ISSUE TITLE
Backport Poise's shell_out helper?

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5169]
Opening this for discussion as to if this belongs in Chef or Mixlib-ShellOut.

In Poise I wrote a helper (https://github.com/poise/poise/blob/master/lib/poise/utils/shell_out.rb) for Chef's `shell_out[!]` which makes sure to populate the `$HOME`, `$USER` and `$LOGNAME` environment variables, as well as on Unix setting the group if a user if given (and a group isn't). All of these are overwhelmingly the expected behavior for `execute` and its subclasses, and I would say should be the standard behavior for Mixlib-ShellOut in general but that might be a bridge too far. What say we all?

**Comment by coderanger** [comment]
I should also mention that shellout already has similar env var behavior when you pass `login: true` as a flag, except that also overwrites `$PATH` and some other misc stuff. Also to complicate this further is how to handle things when Chef is being used to change nsswitch.conf, which can cause `Etc.getpw*` to fail for the remainder of the current run.

**Comment by lamont-granquist** [comment]
Well we should definitely do something about it...   Since its the kind of behavior people expect by default, I'd like to see it on by default with a flag to turn it off ideally...

IDK what to do about Etc.getpw-stuff...  I don't think there's a convenient pure-ruby NSS library to monkeypatch on top of all that.

**Comment by coderanger** [comment]
I don't know of one, and writing something that can support all the weird nsldap integrations sounds painful :-(

**Comment by stevendanna** [comment]
@coderanger Is the PATH munging the main issue you've run into with the login option?  The login option in ShellOut tries to match what su(1) would do [0], including things like setting the secondary/supplementary groups for the user.  I definitely think we should consider changing the default behavior to something that matches user expectations, but I worry about adding a helper that puts the behavior somewhere "in-between" `su` and simply setting the process EUID.

Re the nsswitch.conf stuff, would it be possible to do all username lookups via a helper process that could be restarted between calls? The last time I investigated this, I didn't find many solutions other than (1) restart, (2) use nscd.  Re (1) it would potentially be interesting to rework parts of Chef such that we cold serialize our state and restart; however, making that work for user-code seems like it would be very hard.

[0] Notably we tend to mean su(1) on Linux here, which is another sad complication.

**Comment by thommay** [comment]
We should also look to see what we can rob from https://github.com/berkshelf/buff-shell_out and replace all the uses everywhere with mixlib-shellout.

**Comment by lamont-granquist** [comment]
I think I'm going to wind up extracting a shell_out_internal() which injects the LC stuff and the PATH sanity stuff in prep for removing that from Chef 13.  That'll isolate the 'screw with the environment for internal reasons' use case.  We also still have shell_out_with_systems_locale() that mostly isolates the internal use case of removing the LC mangling stuff.

We probably need to figure out how these should behave:

- shell_out used alone
- bash/script/execute resources
- not_if/only_if uses

Users probably want one API which touches *nothing* -- no PATH, no LC stuff, and is just purely a fancier system() call.

Then there's the API where we need to support touching *everything* -- USER, HOME, LOGNAME, all the su-similar stuff.

Should also probably consider the proliferation of shell_out_yadda_yadda functions and maybe use options instead of making so many different methods.

**Comment by lamont-granquist** [comment]
So i think we need APIs for:

- mangle nothing
- mangle PATH and LC for internal use
- mangle USER, HOME, LOGNAME and behave like su to a user (does this also mangle PATH and LC?  or only optionally?  or only PATH and not LC?)

And I think I'm leaning towards these should be feature flags and we should fold shell_out_compact into shell_out and try to get back to one shell_out/shell_out! API.

**Comment by lamont-granquist** [comment]
i think the way it should probably work is:

```
# does no mangling at all -- no PATH, english, or any user stuff
shell_out!("foo")
# should do proper stuff with mixlib-shellout along with the group and environment stuff from poise_shell_out
shell_out!("foo", user: "testuser1")
# unsets all the mangling
shell_out!("foo", user: "testuser1", usermangling: false)
# does path and english locale mangling (alias for path_sanity: true, force_english: true)
shell_out!("foo", internal: true)
# does path sanity only
shell_out!("foo", path_sanity: true)
# does english forcing only
shell_out!("foo", force_english: true)
```

then also have the api support flatten/compact of *args while making sure to support single strings as well.

the user: flag on macosx should also un-fuck the TMPDIR by default.

i don't think there's any reason to have the user mangling stuff on for root, but `shell_out!("foo", user: "root")` or `shell_out!("foo", usermangling: true)` should turn on all the user mangling.

the major API break here would be dropping path sanity + english forcing from `shell_out!()` which i think is the thing that would need to be chef 13.

the user mangling changes being turned on when the user flag is given /might/ change behavior but i think its at least 95% fixing people rather than breaking them.

**Comment by coderanger** [comment]
The `$HOME` setting for root can still matter as its possible to end up with a different homedir (usually the user that started chef-client). Also are you including setting the group automatically as part of user mangling? Other than that :+1: The only thing left downstream at that point would be my reparse and escape handling for Windows, not sure how we feel about upstreaming that. The goal there is twofold, to support array arguments (i.e. `shell_out(['foo', '--bar', 'one two'])`) on Windows and to try to make things written expecting Bash-ish parsing (such as the `ShellWords` library and things using it) to JFW. The former seems like a solid win because currently arrays just error on Windows, the latter is more opinionated.

**Comment by lamont-granquist** [comment]
yep, auto setting the group plus the env settings seem fine, i see all that stuff in cookbooks and it pains me.

probably have it turned off by default but setting the user flag should turn it all on, then it could be all turned off again with a flag in case someone doesn't want it.

i want to support array args in windows, i need to look closer at what you're doing there.

**Comment by lamont-granquist** [comment]
so as far as:

> The $HOME setting for root can still matter as its possible to end up with a different homedir (usually the user that started chef-client).

is it good enough that if you care about that you should do `shell_out!("foo", user: "root")` instead of `shell_out!("foo")`?  and we could do the same thing with the execute/script/etc resources so that setting a user of "root" would be different than the nil default in that it would enable all the magic.

**Comment by coderanger** [comment]
https://github.com/poise/poise/blob/master/lib/poise/utils/win32.rb#L59-L123 is the relevant Windows command parser and generator. Basically parse using Bash rules (if not already an array), run `argv_quote` on each item, and then if converting back to an array use `^` escaping for cmd.exe if needed to shut off its interpolations and whatnot. Technically the `argv_quote` port in there only works for programs that parse `lpCmdStr` using the `CommandLineToArgvW` rules which is technically optional but everything I found that I could check uses `CommandLineToArgvW` (Python, Ruby, Node, and Java all do).

I'm 👍 on requiring `user: "root"` since that handles my use cases 99% of the time (`shell_out(cmd, user: new_resource.user)`). We should just be vigilant for cases where it matters.

Also another thing to ponder that I've done in a few places in my ecosystem: auto-translating root to the localized Administrator name on Windows. That would allow leaving `"root"` hardcoded in a lot of places we currently have nil (otherwise would explode on Windows by default).

**Comment by lamont-granquist** [comment]
yeah there was that PR to add the admin user to ohai.  i'm not opposed to that in principle, mostly that PR didn't seem to handle all the use cases.  also not necessarily opposed to magic, although maybe we should use `admin: true` to translate to `user: "root"` or `user: "Adminstrator"` or the correct localized windows string.

i will have to digest the parser-generator, i haven't dug that deeply into windows yet...  wonder if that fixes outstanding bugs that we have tho...

**Comment by coderanger** [comment]
Making it a separate option works for shell_out but makes it harder to piece in to a complex system like a bunch of nested custom resources where you want a single `user` property and to have it just work. Or at least that's why I went this way (specifically I translate `property(:user, default: 'root')` to `default: admin_username` on Windows rather than do it in shell_out itself).

**Comment by lamont-granquist** [comment]
Okay, I can see that, the only thing is that there'd still need to be another flag to disable the magic, even if its very unlikely to be needed...

**Comment by coderanger** [comment]
Yeah, my solution was the somewhat roundabout of `default: lazy { "root" }` is not mucked with but that wouldn't work here. A possible workaround is `user: 0` but that feels too arcane. Or we could just use `usermangling: false` for this too.

**Comment by lamont-granquist** [comment]
So 1/2 or 2/3rd of this has gotten done:

- the shell_out API cleanup got done that had nothing to do directly with this PR
- the *argv style of array passing into mixlib-shellout got done so quotes happen correctly in mixlib-shellout and so chef's shell_out now supports array passing on windows.

What remains is the additional default ENV mangling on windows similarly to how we mangle the environment on *nix for convenience.  I suspect we've got additional bugs somewhere that would be fixed by that.
