### ISSUE TITLE
got clone chef-repo 

### ISSUE THREAD

**Issue by minasys** [chef/chef#5198]
I tried to chone the chef-repo on the administration workstation as it used to be with the following command : 
git clone https://github.com/opscode/chef-repo.git
but it shows me that the following address is not exist.

after some searching, I found the following page explains how to do it:
https://docs.chef.io/chef_repo.html

which tell me to use this command instead
$ git clone git@github.com:yourgithubusername/chef.git

and it succeeded to clone it with git

but the issue is that I noticed that the old chef-repo folder has different contents thatn the contents of the new chef folder

I should have the following contents:

.chef/	                   A hidden directory that is used to store validation key files and the knife.rb file.
cookbooks/	           Contains cookbooks that have been downloaded from the           
                                   https://supermarket.chef.io or created locally.
data_bags/	           Stores data bags (and data bag items) in JSON (.json).
environments/	           Stores environment in Ruby (.rb) or JSON (.json).
roles/	                    Stores roles in Ruby (.rb) or JSON (.json).

how can I get it, then finish my chef installation

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
