### ISSUE TITLE
Make systemd_unit verify it's unit file content

### ISSUE THREAD

**Issue by mal** [chef/chef#5200]
# Feature Suggestion

The `systemd_unit` resource has the potential to be improved by utilising the `verify` functionality in it's [`file` block](https://github.com/chef/chef/blob/ba819110a6643d1f65e6b20650e5c8905b083aa8/lib/chef/provider/systemd_unit.rb#L191-L196). For example, using: `systemd-analyze verify %{path}`.

**Comment by ccope** [comment]
I think this should be reopened, since this change was reverted in #5362 
I just shot myself in the foot while trying to install a systemd mount unit, and had to work out how to run the systemd verify tool myself to figure out what I did wrong. I *think* that simply writing the unit file into /etc/systemd isn't enough to enable it, it then has to be symlinked when you run `systemctl enable`? So maybe Chef can just write it there, verify, and delete it if it fails? (disclaimer: i'm a systemd noob)

**Comment by mal** [comment]
@thommay please could you reopen this issue? The original solution had to be reverted but [subsequent discussion](https://github.com/chef/chef/issues/5362#issuecomment-248715590) agreed that the feature in theory still had merit?

**Comment by nathwill** [comment]
@thommay i think we can close this one now, as the fix is merged in #5765

**Comment by thommay** [comment]
Thanks!
