### ISSUE TITLE
:manage_home in linux_user resource should force rm_rf or chown -R homedirs owned by other uids

### ISSUE THREAD

**Issue by structurefall** [chef/chef#5207]
## Description

If a home directory exists on a host, but is owned by the wrong user, :manage_home should correct it- at least optionally. The use case here is hosts that have users temporarily. In my case, human users may exist on production hosts for emergencies, but must then be removed. If the users are re-added later with different UIDs (which may happen because people leave/join the company and the UIDs aren't being directly managed,) ownership gets all screwy.
## Chef Version

Chef: 12.11.18
## Platform Version

Amazon Linux AMI release 2016.03
## Replication Case

Create a user on a host with the "user" resource and :manage_home. Delete the user (and remove the role or recipe that adds it.) Create a new user with the same UID as the old one, then recreate the user with the "user" resource again.
## Client Output

(not relevant)
## Stacktrace

(not relevant) 
### NOTE: CHEF CLIENT BUGS ONLY

(not relevant)

**Comment by lamont-granquist** [comment]
the workaround here is for the cookbook to manually delete the homedir -- the 'bug' here isn't with the user provider implementation but that utils like `userdel -r` will flat out refuse to remove the homedir if its not owned by the user.   it seems like this could also be avoided by consistently using manage_home on all the resources that remove/add users.

not a high priority since there's a workaround.

i can see where this is a 'gotcha' with the user resource and that the underlying userdel/usermod/useradd utilities are annoyingly non-declarative.
