### ISSUE TITLE
SUSE 12 group provider

### ISSUE THREAD

**Issue by wildufo** [chef/chef#5226]
## Description

groupmod: invalid option -- 'A'

lib/chef/provider/group/suse.rb

Line 54:  shell_out!("groupmod -A #{member}....
## Chef Version

chef-client -v
Chef: 12.5.1

Server: 
chef-11.16.4
chef-server-core-12.0.1-1
## Platform Version

SUSE Linux Enterprise Server 12 SP1  (x86_64)
## Replication Case

Run basically any group-related task
## Client Output

STDOUT:
STDERR: groupmod: invalid option -- 'A'
Usage: groupmod [options] GROUP

**Comment by lamont-granquist** [comment]
welp, this was supposedly fixed in b7fff7dbcf4f6afd8ffd8d463093c68a114afa22

it looks like this line is not working:

https://github.com/chef/chef/blob/23de6b876497a1a881d836700513eda3e85a1b59/lib/chef/provider/group/suse.rb#L26

although we claim to have tests around it:

https://github.com/chef/chef/blob/f769d7eba17b3f5aa9e0561126bd9f6801c1bac2/spec/unit/provider_resolver_spec.rb#L676-L695

is it possible that this is only broken in 12.5.1 and works in 12-latest?

**Comment by tas50** [comment]
Closing this based on lamont's comment
