### ISSUE TITLE
Reversion in user resource mapping

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5242]
`Chef::Exceptions::NoSuchResourceType: Cannot find a resource for user on chefspec version 0.6.1`

Ping @lamont-granquist probably something in the user changes?

**Comment by coderanger** [comment]
From my Travis logs, it started happening between 3 and 4 days ago.

**Comment by tas50** [comment]
You need to specify an actual platform and version in your specs. Without that you get the 0.6.1 chefspec fauxhai data, which doesn't work with the user changes. The chefspec example for user has been updated. We probably still need to cut a PR to chefspec to throw a warning in this sort of situation since users should *always* specify what platform and version they want to mock.

**Comment by coderanger** [comment]
@tas50 We can fix it on either side, but as written this is a reversion and will make tests fail. I would be fine if ChefSpec defaulted to simulating Ubuntu or somesuch :) That said, having the _resource_ unmapped on an unknown platform is weird, I would expect the resource to work and then throw a provider not found error.

**Comment by tas50** [comment]
See https://github.com/customink/fauxhai/pull/249 for some more context

**Comment by coderanger** [comment]
Yep, again no argument that this is terrible behavior, but it's a compat break in Chef and thus not allowed under our current rules.

**Comment by lamont-granquist** [comment]
as far as the real actual functioning of the chef-client though this is not a compat break.  its possible that users on hpux who were previously getting the linux code for adduser are now getting exceptions from the resolver code, but that's kind of the point.

and i agreed that this would cause a mess in chefspec land which is why i cut the fauxhai ticket, which unfortunately descended into some pedantic bikeshed painting.

fauxhai setting a platform of 'chefspec 0.6.1' is definite nonsense that the provider resolver doesn't know what to do with.  imo the platform + version should have been required ages ago.  that ship sailed, so i think we should a version for the user that isn't nonsense.

**Comment by coderanger** [comment]
@lamont-granquist It's not the provider resolver, that would be fine because providers are all stubbed. It's the resource resolver.

**Comment by thommay** [comment]
Yeah, this is not a compat break for chef. I disagree that getting users to specify the platform in chefspec is a ship that's sailed - we should just ensure that this happens, and properly deprecate and then disallow having no platform set through a couple of major chefspec versions.

**Comment by coderanger** [comment]
@thommay How would you feel about a special case in the resolver/provider lookup error message that is platform == chefspec, add something about "please set a platform and version"? Might also be a good time to port over the https://github.com/poise/poise-spec/blob/master/lib/poise_spec/fauxhai.rb#L34 logic into either ChefSpec or Fauxhai.

**Comment by thommay** [comment]
Right, so we're now providing a warning in fauxhai, and I think at this point we're not going to change chef, so closing. 
The logic to select the newest version would probably be good in chefspec, yes.
