### ISSUE TITLE
Allow bootstrap to use HTTP so we can proxy it

### ISSUE THREAD

**Issue by amontalban** [chef/chef#5271]
## Description

Would be great if we can use a flag to bootstrap Chef using HTTP for downloading packages so we can cache all remote links with Polipo Proxy as shown in https://gist.github.com/fnichol/7551540 for test-kitchen.

This will also be a good thing for your servers so you can save bandwidth and resources.

Thanks!

**Comment by coderanger** [comment]
We already have `--bootstrap-url`, which you can make HTTP at your own risk :)

**Comment by amontalban** [comment]
I'm not sure if I have to open the ticket here or in [chef/omnitruck](https://github.com/chef/omnitruck) but here is what I see:

```

**Comment by coderanger** [comment]
You'll have to re-host it yourself if you want to compromise your own security. I can't speak authoritatively for Chef Software so I won't close this out but I'm 99% sure they will agree with me that this is not a footgun we'll support directly.

**Comment by coderanger** [comment]
If you're just looking for faster Kitchen tests, check out kitchen-dokken, it caches all this out of the box via Docker-y magic.

**Comment by lamont-granquist** [comment]
actually we used to support this for installs on solaris 9 which were so old they didn't even have SSL, much less updated ca-certs.

it looks like that got lost in the translation to mixlib-install -- but that's where this bug would need to go since that code isn't in this repo:  http://github.com/chef/mixlib-install/issues/new
