### ISSUE TITLE
execute resource doesn't raise an exception for a code block passed to the creates attribute

### ISSUE THREAD

**Issue by patcox** [chef/chef#5293]
## Description

An `execute` resource has the `creates` attribute which accepts a filename as a String. If you set this attribute to a code block, Chef does not raise an exception, but it should.

https://github.com/chef/chef/blob/master/lib/chef/resource/execute.rb#L71-L77

## Chef Version

12.13.37

## Platform Version

CentOS 7

## Replication Case
```
execute 'touch a file' do
  creates { '/foo' }
  command 'touch /foo'
  action :run
end
```
## Client Output
```
[2016-09-07T13:03:33-07:00] INFO: Processing execute[touch a file] action run
[2016-09-07T13:03:33-07:00] INFO: execute[touch a file] ran successfully
```
(same output on a subsequent run when the file exists; I validated that `creates` is **nil** at the provider level.)

## Counter-example Replication
Note that the input validation **does** work if we set `creates` to an Integer.
```
execute 'touch a file' do
  creates 1
  command 'touch 1'
  action :run
end
```

## Counter-example Client Output
```
==================================================================
Recipe Compile Error
==================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option creates must be a kind of [String]!  You passed 1.
```

**Comment by patcox** [comment]
My _guess_ is that something weird is happening with compile-time and then the ParamsValidate mixin: https://github.com/chef/chef/blob/c1a389c2a8452e9b796aa1d34c4d9e51f4af30c7/lib/chef/mixin/params_validate.rb#L180

**Comment by lamont-granquist** [comment]
that needs to be converted to a property and not use set_or_return directly.

its a bug, but its a bug in basically an abandoned API that has been replaced.

there's a task here to rewrite all of the set_or_return calls in all the of the chef-client core resources as properties, and we've done some work against that, but its a very large task that isn't completed yet.  every single set_or_return call you see in the execute resource is a bug, along with every single one of the other calls in other resources, which is currently 233 of them:

```
% cd lib/chef/resource
% egrep set_or_return * | wc -l
egrep: file: Is a directory
     233
```

i don't think this bug reports adds a lot of value towards us getting that work done.  at some point this will get fixed.  its very unlikely that the person fixing that will be fixing this issue, they'll just be converting resources over to use properties.  since this ticket won't provide input into getting the work done and won't get closed when it gets fixed, and then at some later date we'll have to spend time closing it as part of closing bugs en mass, i'm going to close this one now.
