### ISSUE TITLE
Chef::Node.load(node_name) giving configuration errors while interacting with chef server unless Chef::Knife.run() is run first

### ISSUE THREAD

**Issue by mbhavya** [chef/chef#5305]
## Description
Before starting my app, I am running in command line - `knife ssl fetch`, since I have a self-signed certificate. If I try to run `Chef::Node.load("node_name")`, the command fails with error
<pre>
[2016-09-10T12:08:49+00:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/chef/client.pem>
Chef::Exceptions::PrivateKeyMissing: I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
.
.
</pre>

I have to run any knife command like`Chef::Knife.run(%w(node list), options = {})` first and then run `Chef::Node.load("node_name")` to make it work
## Chef Version
chef (12.1.2)

## Platform Version
<pre>root@a8f2e0b96f36:/app# uname -a
Linux a8f2e0b96f36 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 GNU/Linux
root@a8f2e0b96f36:/app# cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian</pre>

## Replication Case
1) run knife ssl fetch from command line from pwd 
Certificates are successfully fetched.
2) Enter irb console (from same dir) with require chef done (and self-signed chef server certificates, config etc. all present in appropriate directory `.chef/trusted_certs` and `.chef/knife.rb`)
3) Run command Chef::Node.load("some-valid-node-name", options = {})
Command will FAIL with output:
<pre>
[2016-09-10T12:19:32+00:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/chef/client.pem>
Chef::Exceptions::PrivateKeyMissing: I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
</pre> and some stacktrace is also present here - attached in gist link https://gist.github.ibm.com/bhavya-maheshwari/6e4597dbe0e7c0980dbad7c40b4604cb
4) Run command `Chef::Knife.run(%w(node list), options = {})` and now same command in Step 3.
Command will SUCCEED with obj details dumped into stdout.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one: https://gist.github.ibm.com/bhavya-maheshwari/6e4597dbe0e7c0980dbad7c40b4604cb

## Stacktrace
https://gist.github.ibm.com/bhavya-maheshwari/6e4597dbe0e7c0980dbad7c40b4604cb

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

It looks like you've not configured Chef with its configuration file before you've tried to use it. You should do this by using Chef::WorkstationConfigLoader or similar. have a look at https://github.com/chef/chef/blob/master/lib/chef/knife.rb#L406 for how knife does it. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
