### ISSUE TITLE
prevent not to schedule chef-client in root user using Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000

### ISSUE THREAD

**Issue by dharanivasan** [chef/chef#5334]
## Description

   We have bootstrapped azure redhat server using Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000 plugin. Using this plugin it automatically schedule chef-client to root user on every 30 minutes. 

    Since we have os format recipe in runlist, it automatically trigger chef-client and format disk every 30 minutes. 

## Chef Version

12.8.1

## Platform Version

Redhat 7.2 

## Replication Case

User same this plugin to create new instance and bootstrap to chef server. 

## Expectation 

   1. How to disable chef-client command is not scheduled to root user using Chef.Bootstrap.WindowsAzure.LinuxChefClient-1210.12.102.1000 plugin.

   2. Can we disable flag autoUpdateClient to not to schedule in root crontab. 

   3. Need to understand by disabling autoUpdateClient will not cause any issues heartbeat or other part of recipes.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
