### ISSUE TITLE
Finish ProviderResolver changes for Chef-13

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5373]
1.   provides lines need to be mandatory
2.  resource_name lines need to be mandatory
   - guessing of the provides/resource_name based on the class name needs to be removed from the ProviderResolver and ResourceResolver
   - all the core chef resources need to comply with these if they do not
   - base classes that should never be created (ie.  Chef::Resource::Package) need to not be wired up to the DSL at all
   - magical naming of providers after the cookbook needs to be removed
3.  all of the back-compat and deprecation warnings that were added with 12.5 resources need to be removed and the resultant code needs to be simplified
- this is for all providers -- custom resources, old style LWRPS, library providers that inherit from LWRPBase, core resources, etc.

**Comment by lamont-granquist** [comment]
this still causes /incredibly/ difficult to debug issues where something like `MyProviders::MysqlService < Chef::Resource::LWRPBase` gets wired up to `mysql_service` by default in the DSL even though it might only be a base class that other classes that have explicit `provides :mysql_service` lines inherit from.

pretty certain that the company only has a bus factor of 1 (me) for debugging these issues now.

before i leave the company / get splattered by a bus / drown in a cave we should remove all the hidden magic sauce.

**Comment by tas50** [comment]
Lamont can you comment on what would be necessary to change from an end user perspective in LWRPs and custom resources?

**Comment by lamont-granquist** [comment]
- always use provides
- always use resource_name

**Comment by tas50** [comment]
So we break every existing cookbook hard or we throw a warning?

**Comment by lamont-granquist** [comment]
lots of cookbooks already do both of those

**Comment by tas50** [comment]
Most of ours don't even do that

**Comment by lamont-granquist** [comment]
so we need to start doing it now then

**Comment by tas50** [comment]
I'd completely support updating our docs and our cookbooks to do both of those things and then adding deprecation warnings so we start go get people to upgrade their cookbooks. I don't support removing this in the Chef 13 timeline. That's a change that breaks everyone who depends on 3rd party cookbooks since the timeline for community cookbook updates is often very long. We'd probably want to actually actively comb the supermarket for code that didn't comply and contact authors. Otherwise that sort of change would keep people from upgrading since the remediation step has to occur in code they potentially don't own.

**Comment by lamont-granquist** [comment]
I think I'm going to consider this done.

we've simplified properties and resources a lot in Chef-13 now with all the removed deprecated code.
