### ISSUE TITLE
Chef encountered an error attempting to create the client WITH [[Scalr]]

### ISSUE THREAD

**Issue by amittakyan** [chef/chef#5435]
## Description

Briefly describe the issue

I have configured the Java cookbook with RunList ["recipe[java]"] chef-solo configuration in Scalr UI of Refer Image 1 (Scalr is Cloud Management Platform). I have download cook book from [URL ](https://supermarket.chef.io/cookbooks/java#knife)and upload in S3 Bucket to use it as HTTP in Scalr ( Refer below image )

![image 1](https://cloud.githubusercontent.com/assets/22348272/19215748/79945ddc-8d74-11e6-996a-62a95b9e79ba.JPG)

When Scalr launch AWS instance (Ubuntu 14 trusty version) successfully
Desire Expected Service from Chef in AWS Instance:
1.Chef should install the Java in my newly created AWS instance (Ubuntu 14 trusty version ) but there no java installed (Refer Image)

![image2](https://cloud.githubusercontent.com/assets/22348272/19215687/d525dbe6-8d72-11e6-936f-feaca73d42ce.JPG)

2. Chef client should install in AWS Instance but it throw error (Refer Image3) 
![image3](https://cloud.githubusercontent.com/assets/22348272/19215689/e3abdfa8-8d72-11e6-9f0d-5df8d66efab3.JPG)

Cloud you please help why Java and Chef client not installed....????

## Chef Version

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

Chef Client, version 11.18.0

Tell us which Operating System distribution and version chef-client is running on.

Ubuntu 14 trusty

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
