### ISSUE TITLE
chef 12.15 breaks mutability of the node object

### ISSUE THREAD

**Issue by ayanich** [chef/chef#5447]
## Chef Version

12.15.19

## Platform Version

ubuntu 12.04

## Replication Case

our converges break

## Client Output

Chef::Exceptions::ImmutableAttributeModification
       ------------------------------------------------
       Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

   26:    current[:src] = params[:src]
        27:    current[:not_src] = params[:not_src]
        28:    current[:jump] = params[:jump]
        29:    current[:public] = params[:public]
        30:    current[:dport] = params[:dport]
        31:    current[:sport] = params[:sport]
        32:    current[:proto] = params[:proto]
        33>>   node['iptables'] << current
        34:  end
        35:  
       
       Platform:
       ---------
       x86_64-linux
       
       [2016-10-12T18:32:01+00:00] ERROR: Running exception handlers
       [2016-10-12T18:32:01+00:00] ERROR: Exception handlers complete
       chef client failed. 3 resources updated

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
The node object was never supposed to be mutable ever since Chef 11.0.0

Since its a deep merged representation of the underlying precedence levels, there's no way to know which precedence level to merge in order to save it back to the chef server, and since there's no way to pick which precedence to pick to write that to, and a subsequent write which invalidated the deep merge cache would cause that write to be lost when the data is re-deep-merged.

If you're upgrading from 10.x this was a deliberate change in 11.0.0

If this "worked" for you in prior 12.x versions then that was a side effect of other bugs we had in the node object, which were fixed, and the current behavior is the correct and documented behavior of how the node object should work.

If you want to mutate attributes you must always go in through a precedence level.

```
node.default['iptables'] << current
```

**Comment by coderanger** [comment]
:+1: for closing as WORKSASINTENDED. I gave Sean as bunch of workaround options on IRC.

**Comment by lamont-granquist** [comment]
Yeah, this worked right in 11.18.12:

```
git:chef4:11.18.12 rvm:ruby-2.3.1
14:25 coredump oc/chef4 % ./foo.rb
/Users/lamont/oc/chef4/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag
[2016-10-12T14:25:16-07:00] FATAL: Stacktrace dumped to /Users/lamont/.chef/cache/chef-stacktrace.out
[2016-10-12T14:25:16-07:00] FATAL: Chef::Exceptions::ImmutableAttributeModification: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
git:chef4:v12.14.89✗ rvm:ruby-2.3.1
14:26 coredump oc/chef4 % cat ./foo.rb
#!/usr/bin/env chef-apply

node.default['iptables'] = []
node['iptables'] << [ "stuff" ]
```

I seem to have accidentally broken this behavior in 12.0.0 but this is just a 'symptom' of that bug finally getting fixed.

**Comment by lamont-granquist** [comment]
Yeah got broken way back here:

https://github.com/chef/chef/pull/2462/files

It looks like I commented out these lines for debugging purposes:

https://github.com/chef/chef/blob/68dd5f42273f19bc5975c0dc8ed46ee592764eec/lib/chef/node/attribute.rb#L424-L428

I suspect that was temporarily for proof of concept before I implemented this public-not-public method to allow the deep merge algorithm to update otherwise-immutable attributes:

https://github.com/chef/chef/blob/68dd5f42273f19bc5975c0dc8ed46ee592764eec/lib/chef/node/immutable_collections.rb#L158-L160

Welp...

If you hit this bug, I'm terribly sorry for the inconvenience, mea culpa, all that...

But no, we're not going back to the pre-12.15 behavior, it was never, ever supposed to work that way.

**Comment by lamont-granquist** [comment]
Doing the spec tests in #5481 turned up that it was only Array immutability that was broken in 12.0 and that Hash immutability has worked all along (explaining why we both didn't have specs to catch this and why it went uncaught for so long).

```
git:chef3:v12.13.37 rvm:ruby-2.3.1
14:54 coredump oc/chef3 % bundle exec pry
[1] pry(main)> require 'chef/node'
=> true
[2] pry(main)> n = Chef::Node.new
=> #<Chef::Node:0x007fdd60c37db0 @attributes={}, @chef_environment="_default", @chef_server_rest=nil, @name=nil, @override_runlist=#<Chef::RunList:0x007fdd60c37ce8 @run_list_items=[]>, @policy_group=nil, @policy_name=nil, @primary_runlist=#<Chef::RunList:0x007fdd60c37d60 @run_list_items=[]>, @run_state={}>
[3] pry(main)> n.default['array'] = []
=> []
[4] pry(main)> n['array'].class
=> Array
[5] pry(main)> n['array'] << "foo"
=> ["foo"]
[6] pry(main)> n.default['hash'] = { foo: "bar" }
=> {:foo=>"bar"}
[7] pry(main)> n['hash'].class
=> Chef::Node::ImmutableMash
[8] pry(main)> n['hash'].delete("foo")
Chef::Exceptions::ImmutableAttributeModification: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
from /Users/lamont/oc/chef3/lib/chef/node/immutable_collections.rb:188:in `block (2 levels) in <class:ImmutableMash>'
[9] pry(main)>
```

That at least puts the argument that this is a bugfix on more solid ground since we just made the behavior of Arrays match the behavior of Hashes, and match the old behavior that was consistent throughout 11.x
