### ISSUE TITLE
no implicit conversion of Chef::DelayedEvaluator into String

### ISSUE THREAD

**Issue by martinb3** [chef/chef#5490]
## Description

We've had reports downstream in https://github.com/rackspace-cookbooks/chef-slack_handler/issues/37 that releases of Chef > 12.6.x have broken some functionality in the `cookbook_file` provider.  It looks like this [same issue](https://github.com/chef/chef/pull/1361) cropped up in [CHEF-5162](https://tickets.opscode.com/browse/CHEF-5162) and some other places, but I'm not specifically aware of the fix for cookbook file.
## Chef Version

```
➜  ~ chef --version
Chef Development Kit Version: 0.18.30
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.2
```
## Platform Version

Mac OS 10.x
## Replication Case

I'm actually not sure how to replicate it. I'm passing the bug upstream, but I haven't directly encountered it.
## Client Output

```
  * cookbook_file[/var/chef/handlers/slack_handler_util.rb] action create

    ================================================================================
    Error executing action `create` on resource 'cookbook_file[/var/chef/handlers/slack_handler_util.rb]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of Chef::DelayedEvaluator into String

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:42:in `from_file'
    /var/chef/cache/cookbooks/moxi-slack/recipes/default.rb:14:in `from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/slack_handler/recipes/default.rb

     37: cookbook_file "#{node['chef_handler']['handler_path']}/slack_handler_util.rb" do
     38:   source 'slack_handler_util.rb'
     39:   mode "0600"
     40:   action :nothing
     41:   # end
     42: end.run_action(:create)

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:37:in `from_file'

    cookbook_file("/var/chef/handlers/slack_handler_util.rb") do
      provider Chef::Provider::CookbookFile
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      source "slack_handler_util.rb"
      declared_type "cookbook_file"
      cookbook_name "slack_handler"
      recipe_name "default"
      mode "0600"
      atomic_update #<Chef::DelayedEvaluator:0x00000001d8ce98@/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/resource/file.rb:53>
      path #<Chef::DelayedEvaluator:0x00000001d8df78@/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/property.rb:180>
    end

    Platform:
    ---------
    x86_64-linux
```

**Comment by lamont-granquist** [comment]
the full stacktrace.out would be useful.

it looks like its this line in the file provider might be the issue:

```
      property :atomic_update, [ true, false ], desired_state: false, default: lazy { |r| r.docker? && r.special_docker_files?(r.path) ? false : Chef::Config[:file_atomic_update] }
```

although it seems to be indirect, in that its probably the `r.path` reference which is blowing up a `lazy {}` that the user passed to the resource as the path.

that doesn't entirely make sense though because that reference itself has been lazied, and shouldn't be hit until the provider runs.

this is not the same issue as CHEF-5162 or any of the other lazy bugs, they're just kind of a plague because lazy is a fairly bad feature which people who hit compile-converge problems tend to abuse and tends to create a "...and now you have two problems..." kind of solution.  the flip side of the race-to-compile-time is the race-to-lazy-everything, and a better approach is to rewrite recipes as resources.

anyway the use of the lazy default there might be overly clever and it might be better to move that code directly into the provider?  or else i need to take a look at the implementation of LazyEvaluator and see if we could use the Chef::Decorator::Lazy class to implement it more transparently, but i don't know how much surgery would be required to core chef.

the stacktrace.out could help with the specifics of this one, though, otherwise i'm only guessing -- looking at the code it looks like there might be a bug in using lazy defaults with properties which seems wrong...

**Comment by lamont-granquist** [comment]
BTW since your cookbook doesn't appear to use `lazy {}` it appears to not have much to do with the chef-slack_handler cookbook although if you shipped a resource in that cookbook instead of a recipe it would probably go away?

**Comment by joerocklin** [comment]
I'm not sure if the issue I'm seeing is related to this or not (if not I can submit a new issue). I've got the same output from `chef --version`, but on a windows host and converging in a Windows 2012r2 VM. 

I'm trying to use a lazy evaluator in the `source` property of a `gem_package` resource (I'm downloading an archive and unpacking it in a previous resource from an artifact server and the filename changes, so I'm trying to do a `Dir.glob` to get the actual filename). With the lazy evaluation, gem_package tries to download from rubygems and the error output shows that the source is `Chef::DelayedEvaluator` instance. With a static string, all works as expected - but I have to update the cookbook every time the gem is updated.

**Comment by lamont-granquist** [comment]
that is _almost_ certainly a different bug.  it is possible there's a common underlying issue with a bug in properties, but generally DelayedEvaluator bugs are all one class of problems with a common bug pattern, but all are different bugs.  generally you're better off not using lazy and instead computing the value earlier (you can either lazy the use, or more eagerly compute the value -- the latter is actually the better path if you can take it).

**Comment by lamont-granquist** [comment]
Also I tried replicating this file provider failure with a simple `path lazy {}` to a file provider and that failed, so without a stacktrace.out or a better replication case I'm a bit stuck on debugging it.

**Comment by lamont-granquist** [comment]
My suspicion is that this only happens on docker guests where `docker?` is true, which is why i couldn't replicate it.
