### ISSUE TITLE
OpenSSLError: This version of OpenSSL does not support FIPS mode - ChefDK 0.9.6-1 for Windows

### ISSUE THREAD

**Issue by JHBoricua** [chef/chef#5506]
## Description

Clean install of Chef DK 0.9.6-1 on a Windows 10 workstation.  I'm stuck on step 3 of https://learn.chef.io/tutorials/manage-a-node/ubuntu/bring-your-own-system/set-up-your-chef-server/ which involves fetching and validating the SSL certificate from the chef server.

I've downloaded my starter kit and placed the files in a directory called learn-chef per tutorial.
I've verified the knife.rb file exist and its correct inside the .chef directory in learn-chef.
I've verified the .pem file exist in the .chef directory in learn-chef

When performing the command 'knife ssl check' or 'knife ssl fetch' inside my learn-chef directory I'm getting the following error:

ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode

Thus I'm stuck on this part of the tutorial.

## Chef Version

Chef Development Kit Version: 0.19.6
chef-client version: 12.15.19
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.1.0
kitchen version: 1.13.2

## Platform Version

Microsoft Windows 10 workstation chef-client 12.15.19 installed from chefdk-0.19.6-1-x86.msi package.

## Replication Case

1. Install Chef DK on windows 10 workstation to default path
2. Download starter kit from Chef Server and extract it
3. launch Chef DK
4. cd to directory where starter kit files where extracted to.
5. perform either 'knife ssl check' or 'knife ssl fetch'

## Client Output

PS G:\Git\learn-chef> knife ssl fetch
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode
PS G:\Git\learn-chef> knife ssl check
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by JHBoricua** [comment]
Thom, did you read the issue before closing it? It seems to me you did not. This is not a "How do I...?" question. This is clearly an issue with the chef-client/knife/OpenSSL package installed by the latest Chef Development Kit for Windows.

**Comment by jblaine** [comment]
@thommay The heck? You appear to have read the first paragraph or two and not the whole report. This isn't a "how to" request.

**Comment by shortdudey123** [comment]
@jbence it was a "how to" due to non-standard system config ... see https://github.com/chef/chef/issues/5507
