### ISSUE TITLE
Unable to bootstrap a new node

### ISSUE THREAD

**Issue by kumarprd** [chef/chef#5528]
## Description

I am trying to bootstrap a node which is reachable in network but during bootstrap its throwing error : 
knife bootstrap node 10.245.178.202 -x root -P welcome1 -N node2
Node node2 exists, overwrite it? (Y/N) Y
Client node2 exists, overwrite it? (Y/N) Y
Creating new client for node2
Creating new node for node2
Connecting to node
ERROR: Network Error: getaddrinfo: Name or service not known
Check your knife configuration and network settings

## Chef Version

12.4.1

## Platform Version

OEL 6.4

## Replication Case

The node was bootstraped and later removed from node and client list. Again tried to bootstrap it.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
