### ISSUE TITLE
User unlock not working and chef-run is not failing

### ISSUE THREAD

**Issue by tilman** [chef/chef#5573]
## Description

I use the user unlock (user 'iris' do action :unlock...) in my cookbook, but the user is not unlocked.
In the Chef-client Output the unlock is displayed green and succesfull, but when i request the status of the user lock, it is still locked:
```
passwd -S iris
iris LK 2016-11-22 0 99999 7 -1 (Password locked.)
```

I think the Problem is the file 'chef/lib/chef/provider/user/linux.rb' uses "usermod -U iris" to unlock an user. But this failes if the user have no password. And because usermod -U fails with the return value 0, i think it display the chef-run as a success:
```
[root@iris-logstash1 ~]# usermod -U iris
usermod: unlocking the user's password would result in a passwordless account.
You should set a password with usermod -p to unlock this user's password.
[root@iris-logstash1 ~]# echo $?
0
```
Propaply a better Command would be "passwd -u -f iris", wich also works if the user have no password.

## Chef Version
```
Installed Packages
Name        : chef-server-core
Arch        : x86_64
Version     : 12.8.0
Release     : 1.el7
Size        : 1.4 G
Repo        : installed
Summary     : The full stack of chef-server
URL         : https://www.chef.io
License     : Apache-2.0
Description : The full stack of chef-server
```
## Platform Version
```
Oracle Linux 7.2
Chef-client: 12.15.19
```
## Replication Case

create new cookbook with following default.rb:
```ruby
group 'iris' do
  action :create
  gid 4444
end

user 'iris' do
  action :create
  comment 'Application User IRIS'
  uid 4444
  gid 4444
  home '/home/users/iris'
  shell '/bin/bash'
end

user 'iris' do
  action :unlock
end
```

## Client Output
````
...
Recipe: iris-base::users
  * group[iris] action create (up to date)
  * linux_user[iris] action create (up to date)
  * linux_user[iris] action unlock
    - unlock user iris
...
Chef Client finished, 1/38 resources updated in 11 seconds
````

**Comment by lamont-granquist** [comment]
that error message is there for a reason, and it would be EXTREMELY poor form for chef to override that and force the behavior.  there's another ticket somewhere to allow passing arbitrary options to any useradd command which would allow the user to go ahead and shoot themselves in the foot if they want to, which would be acceptable, but would require the user to add `options "-f"`.

parsing either stdout or stderr to find the error message and then cause chef to throw an exception would also be acceptable -- but this is pretty obviously a bug in the command which is failing and then returning success.  i expect that will get fixed in the upstream utility -- although if you want to submit a PR to handle this case and throw an exception, we'd accept it.

**Comment by lamont-granquist** [comment]
since this will be fixed when a clear bug gets fixed in RHEL and the other concerns are addressed elsewhere, leaving this issue open won't be useful to track work, so closing...
