### ISSUE TITLE
Question about defaulting lwrp properties

### ISSUE THREAD

**Issue by atheiman** [chef/chef#5611]
Is there a way to define complex defaults for lwrp properties that are derived from other properties? Something like this where `app_root` is derived from `app_name`:

```ruby
property :app_name, String, required: true, name_attribute: true
property :app_root, String, required: true, default: ::File.join('opt', new_resource.app_name)
```

This code raises

```
      NameError:
        undefined local variable or method `new_resource' for #<Class:0x007f9e2d5b4b90>
```

The default needs to be evaluated later (in the compile phase I guess it would be?).

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by atheiman** [comment]
If anyone finds this, I think this can be accomplished with https://docs.chef.io/custom_resources.html#action-class and a library
