### ISSUE TITLE
Yaml support for chef config objects

### ISSUE THREAD

**Issue by atheiman** [chef/chef#5620]
Chef already allows environments and roles as ruby, could there be support for yaml in addition to JSON for environments, roles, and data bags?

`knife <environment|role|data bag> from file <whatever>.y(a?)ml`

Im gonna take a shot at this. Just from a quick scan through the source, I think this is where I would start https://github.com/chef/chef/blob/master/lib/chef/knife/core/object_loader.rb#L63-L78

**Comment by coderanger** [comment]
So this issue has a long history. The last time it was discussed was as part of the Dialects RFC which was later accepted, but part of that was a condition that all new formats (explictly including Yaml) live outside of chef core.

**Comment by atheiman** [comment]
hmm you must be referring to https://github.com/chef/chef-rfc/blob/master/rfc036-dialects.md

is there a knife plugin you know of that already provides this functionality? I didnt find anything after searching for a short time. Doesnt seem like it would be too difficult to add in a plugin.

**Comment by coderanger** [comment]
@atheiman There was a patch for Chef long ago but it has been so long that it would require starting over. `chef-funnel` also still exist but I've neither updated it nor tried using it in years.

**Comment by coderanger** [comment]
Basically I fully endorse the feature and Chef has already accepted a design (disclaimer: I wrote the RFC as well as the original versions of this) to get it in via a plugins system, but it's going to be a lot more work than your patch unfortunately. If your company is interested in making this happen sooner, I'm happy to talk about sponsorship opportunities.

**Comment by atheiman** [comment]
We just want to be able write data bags, roles, and environments in yaml.
At the moment we have a simple chef repo upload script that converts yaml
to json before upload that is doing just fine for us, I only opened this to
see if there was interest from others.

I think we can get the functionality in the knife command we want with a
pretty simple plugin gem. If I make that I will post it back here in case
others want the functionality.

The logic in that rfc makes sense to me, so I think its fine to close this
issue if this functionality still belongs outside chef core.

**Comment by coderanger** [comment]
It's also been a few years, I certainly wouldn't object if the other maintainers had changed theirs minds since I wanted Yaml in core from the start :) But I'm also happy to abide by the previous discussions and do see the argument that putting more formats in core risks new-user confusion.

**Comment by thommay** [comment]
I'm pretty strongly against doing this in core. One of Chef's biggest problems for users is TIMTOWTDI, and dialects in general make that worse.

**Comment by lamont-granquist** [comment]
I'm fairly against doing this simply on a code quality basis.  I don't want to see a PR that litters dozens of classes with if statements.  We already have enough really bad code which is an aggregation of the shortest path to implementing a feature/bugfix.

**Comment by lamont-granquist** [comment]
So yeah, I think I'm just going to vote straight up "no" on this.

We don't have the resources to bugfix it, or to inevitably refactor it, and I don't want to accept more features into ChefFS (which is another thing that probably needs fewer features and a rewrite), so I don't think we have the resources to even accept a PR that does the work, because there's an implied contract there that we will support the feature in the future.

So yeah, not in core -- the code needs to live somewhere else -- when I look at all the stalled RFCs and other problems that I don't have any time for that come ahead of this feature, I definitely don't have time for this feature.

There's also the TIMTOWTDI issues and the fact that I think its entirely debatable if this makes Chef better or worse.   Regardless of which side you fall on that argument, things like the DNF provider, and ohai segments and the desired/current state split, and even getting postgres and mysql client libs baked into the build are all things which are more clearcut wins for the community.  So if you stack rank the oustanding work, IMO, this feature is something that really needs to take zero of mine and thom's time.

Sorry to be a party pooper, but most of my job is dealing with decisions like this that were made years ago and figuring out how to refactor the code because its difficult to undo saying yes to things ("Yes is forever, no is temporary"), so I definitely see this through the lens of writing a check on my future time, of which I can't see where I have any for this (and don't see where other resources are going to come from).

**Comment by lamont-granquist** [comment]
Refactoring core chef to make it more amenable to plugging external code into it would certainly be fine tho.

**Comment by coderanger** [comment]
Yeah, the design in the RFC was to basically bounce all file loading through a plugins framework, and then bundle the JSON and `.rb` (depending on the object type) plugins in Chef core. Extending knife stuff would then just mean adding a `require` in your knife config.

**Comment by coderanger** [comment]
Going to close this out as it sounds like we're sticking with the previous plan that we don't want this in core but do want to see it supportable "easily" in a gem. Sorry to be spoilsports, it is a nice feature, and I really hope we can make this doable.
