### ISSUE TITLE
Feature Request - more granular dependency definitions

### ISSUE THREAD

**Issue by axos88** [chef/chef#5641]
As suggest was never implemented correctly according to @tas50, and is going away, I would love to see the"depends" functionality expanded with conditionals, such as operating system, platform, etc, so that I don't pull in a plethora of cookbooks that are completely irrelevant to my environment.

That way I could define dependencies such as:
```
depends 'windows', os: 'windows'
depends 'systemd', platform_family: 'debian'
depends 'ubuntu_hacks', platform: 'ubuntu',
```
etc. 

Now I know this is probably not trivial to implement, but surely it is something that would reduce required bandwith on the chef server.

**Comment by thommay** [comment]
Here's the thing. Most of the time, the cookbooks people reference when they talk about conditional dependencies are `windows`, `apt`, and `yum`. By Chef 13 in April, all of those cookbooks will be completely shipped in core chef. Even without that, cookbooks are tiny - the apt cookbook is 33KB on disk, and is only shipped when it's not in cache or when one does something like a partial run_list. 

So the amount of bandwidth (and disc) we'd be saving is trivial, but at the same time we're putting a lot more load on the chef server's dependency solver (which is already one of the slowest and most fragile bits of the server), making it harder to predict what the solution would look like and committing a lot of engineering time to making this all work.

I'm going to close this since I would be very hesitant to accept a patch to implement this as things stand.
