### ISSUE TITLE
chef-server and chef-client 's version must match?

### ISSUE THREAD

**Issue by zhaoxiaoke** [chef/chef#5691]
for example ,if my chef-server version is 12.11.1, and my chef-client is  11.12.8. they will work ok ?

**Comment by zhaoxiaoke** [comment]
Can someone help me?  thank you very much。because the debian 8 (cpu is powerpc)internal 's  chef-client is 11.12.8.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
