### ISSUE TITLE
[Enhancement] Add sensitive to registry_key 

### ISSUE THREAD

**Issue by dhoer** [chef/chef#5695]
## Description

Windows registry_key resource doesn't support sensitive.  While it does write to Windows registry that is not very secure, it would be nice to suppress stdout and stderr output. Here is an example of output when setting autologin username and password:

```
* windows_autologin[set rdp_local] action enable
             * registry_key[set AutoAdminLogon for rdp_local] action create
        - set value {:name=>"DefaultUsername", :type=>:string, :data=>"rdp_local"}
        - set value {:name=>"DefaultPassword", :type=>:string, :data=>"%2wNrk6z%Y-eJrv"}
```

It would be nice to be able to hide this from the logs.

https://ci.appveyor.com/project/dhoer/chef-windows-screenresolution/build/build-28#L375

**Comment by gregersen12** [comment]
Trying to find my way about contributing to a major open source project, but it's always difficult to get thrown into a big file structure with no prior exposure.
Is this issue linked to any file(s) in particular? 

In case that Github is somehow tracking this, I have missed it!

**Comment by thommay** [comment]
Hi @gregersen12 we'd love to help you contribute.

Chef resources are composed of a resource, in this case https://github.com/chef/chef/blob/master/lib/chef/resource/registry_key.rb and a provider, https://github.com/chef/chef/blob/master/lib/chef/provider/registry_key.rb

An example of something implementing sensitive is the execute resource, https://github.com/chef/chef/blob/master/lib/chef/resource/execute.rb#L133 and the associated provider. You'll notice that execute is "new style" - it uses properties, rather than the `set_or_return` pattern in registry_key. You can selectively change things over to properties, similarly to https://github.com/chef/chef/pull/5471/files .

Hope this gets you on the right track, but feel free to ask more questions or drop in #chef-dev in the chef community slack.
