### ISSUE TITLE
Knife editor variable error message is not useful

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef#5696]
## Description

Some knife operations, like `knife data bag create bag-name item-name` requires an `EDITOR` environment variable to be set. Furthermore, it must be without spaces or quoted, which is quite undocumented, but can be seen here: https://tickets.opscode.com/browse/CHEF-4503

If the variable is set, but invalid, there is just one error message, which is not very helpful:
`ERROR: RuntimeError: Please set EDITOR environment variable`

Could we at least detect that the variable *is* actually set and report to the user that it is invalid?
We might even detect that the value is unquoted and contains spaces and report a more specific error. Or if the OS is Windows, it seems fair to tell the user to avoid spaces.

## Chef Version

```sh
> knife version
Chef: 12.13.37
```

## Platform Version

Windows Server 2012 R2

## Replication Case

- Open Windows GUI to set environment variable EDITOR with a value that contains a space, for example something in `C:\Program Files`. This usually works well.
- Run a command that requires the variable, like the one above.

## Client Output

See above.

**Comment by RichardBronosky** [comment]
## Description

The general terribleness of the error messaging is not limited to Windows. All platforms are affected by the brevity of the error checking in https://github.com/chef/chef/blob/5f998d4e2b9d4c88bf1e58d1f1c19dc4d17ffeff/lib/chef/knife/core/ui.rb#L175

Any kind of error from the `system()` command results in the message `Please set EDITOR environment variable`

A complete list of shortcomings would include:
1. Messaging should not mislead the user to believe that `config[:editor]` can be set via the "EDITOR environment variable" when it is being set via the `$CHEF_REPO/.chef/knife.rb`
1. Messaging should distinguish between "editor is not set" and "call to editor returned non-zero"
1. If editor is set but results in an error, display the command and exit code.
1. Chef's subcommand APIs (with anti-footgun provisions) should be used instead of `system`

## Chef Version

```
$ chef --version
Chef Development Kit Version: 2.1.11
chef-client version: 13.2.20
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.0
kitchen version: 1.17.0
inspec version: 1.33.1
```

## Platform Version

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

$ uname -a
Darwin Bruno.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

## Replication Case

1. Set your editor to vim (because that's how I know to reproduce this)
1. Edit an existing data_bag
1. Write your changes using `:w`
1. Exit the editor producing a non-zero status code `:cq` (NOTE: This is an effective way to abort git commit amendments)
1. OBSERVE: the data bag is not updated, and the error message is `ERROR: RuntimeError: Please set EDITOR environment variable`

**Comment by thommay** [comment]
We'd happily take PRs to fix this.

**Comment by tas50** [comment]
I've improved the knife error message here with a link to knife docs. I also refactored a lot of the knife documentation on the docs site so make it more useful for first time users. This is probably the first error the every Chef user sees and hopefully this will ease that pain a bit. Thanks for the report.
