### ISSUE TITLE
Cannot load such file -- mongo

### ISSUE THREAD

**Issue by abhishekdoshi** [chef/chef#5770]
## Description

I have multiple cookbooks for installing my entire web application built on liferay, and for CMDB i have used mongo db server, i have one separate cookbook named mongo_chef_gem to install and connect mongo server from local server, but while compiling of cookbooks chef-client throws error cannot load such file --mongo.

## Chef Version

latest
 

 

## Client Output

  LoadError
                      ---------
                      cannot load such file -- mongo

                      Cookbook Trace:
                      ---------------
                        /var/chef/cache/cookbooks/liferaybuild/attributes/default.rb:1:in `from_file'

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
