### ISSUE TITLE
Race condition between vixie-cron and cron resource

### ISSUE THREAD

**Issue by ssabo** [chef/chef#5815]
## Description

**Background**

On vixie cron, when you update a user's crontab file, vixie-cron (ubuntu default) will only parse the sub-files when the folder `/var/spool/cron/crontabs` mtime is updated from last time it checked. Normally, the directory mtime is updated on the directory when an inode is either introduced or removed from that directory path, not when a file inside changes it's own mtime. 

**Issue**

There exists an instant where if the last two cron resources of a chef run get added in the same second as when cron parses that users crontab, but one before the file descriptor is opened and one after, the last cron resource will never be read by the cron daemon unless it is restarted or the directory is touched. 

## Chef Version

Chef: 12.4.3

## Platform Version

Ubuntu 14.04.5 LTS and Ubuntu 16.04.2 LTS

## Replication Case

Have not figured out how to replicate this reliably yet since chef needs to time 2x updates at the exact second vixie-cron checks for updates. We have about 1-2 servers every day hitting this case though

## Client Output

N/A

## Stacktrace

N/A

**Comment by ssabo** [comment]
Possible workaround to force crontab to reload database after a chef run.

```
execute "make-cron-spooldir-update-delayed" do
  command 'echo "touch /var/spool/cron/crontabs" | at now + 1 minute'
  action :nothing
end

execute "dummy-crontab-fix-caller" do
  command ":"
  action :run
  notifies  :run, "execute[make-cron-spooldir-update-delayed]", :delayed
end
```

**Comment by lamont-granquist** [comment]
so that's a bit weird because all the cron resource seems to be doing is using `crontab -u` to update the crontab.

kind of feels like a bug between the crontab command and vixie cron.

i was sort of suspecting that i'd find a bit of horrible code in the cron provider (it is very unloved) that did some old non-atomic manual file mangling and that the fix would be to have it construct a real file sub-resource to do the work, but having the provider call `crontab -u` seems to make sense and avoids us having to know where the crontabs are kept on different operating systems...

so i'm not sure what to change here...

i'm legitimately pretty puzzled.  the existing code looks a lot better than i feared and i don't see any of the obvious bugs that i was suspecting would be the root cause (doesn't mean there's no bug, but i don't see it right now).

**Comment by ssabo** [comment]
my understanding of how crontab command works is it will create a copy of the current file, modify it, then copy it into place. This results in two very fast sequential updates on the same second updating directory mtime to the same value when the second one copied in. 

The thinking I had was that cron resources could create one atomic update at the end of a run instead of many small updates throughout. This is a rather large change though to deal with a very small race condition.

**Comment by lamont-granquist** [comment]
yeah that would mean writing an accumulator to spool it up and run it at the end.  that is probably better done as an accumulator resource in a cookbook wrapping the cron resource.

so far we don't have any accumulated resources added to chef core, it'd definitely be intrusive to modify how the cron provider worked.

and it seems like any process which does rapid-fire updating of crontabs through `crontab -u` would trigger the same bug...

**Comment by ssabo** [comment]
Agreed. Our workaround above is functional for the time being. I'll look into an accumulator wrapper though. Thanks for the suggestion 😀

**Comment by lamont-granquist** [comment]
if you want to do that the iptables_rule resource in the iptables cookbook is probably the only accumulator example that i'd recommend right now

**Comment by lamont-granquist** [comment]
so there's the substantially better workaround:

drop individual files into `/etc/crond.d/whatever` and make them completely idempotent.  you can have one-file-per-task that way you never have to mangle the same file.  the `/etc/cron.d` directory acts as the 'accumulator'.

generally we'd recommend using `/etc/cron.d` over using the cron resource in chef.  i think there's a cookbook out there with a cron_d resource, but i typically never bother with that since it boils down to just managing files, and i don't really need that abstraction layer.

if i understand the problem correctly that this is due to two updates to the same user's crontab file (and not two updates to two different crontab files) i think this would work around the problem (and might really be the recommended solution for numerous reasons that boil down to trying to avoid line based file editing wherever possible (and since the cron resource inherently does line based file editing, its a good thing to avoid).

**Comment by ssabo** [comment]
That is indeed a substantially better solution that should be immune to this race condition. Ty for the follow up 😄

**Comment by lamont-granquist** [comment]
yeah i don't see any good way to fix cron.d barring turning it into an accumulator which isn't something we really want to do, and /etc/cron.d solves the whole problem a lot better.

still think this sounds like an upstream bug in vixie-cron though and should really get reported.  i *think* this is an identical problem to identifying "You have new mail" like BSD /usr/bin/mail does as new messages arrive in /var/spool/mail/user, which also has to deal with the problem of multiple messages arriving at the same time -- i'm sure there are $REASONS why its more complicated than i think though...
