### ISSUE TITLE
Chef client install gem include paths differ from ChefDK install when using require "gem-name" in attribute file

### ISSUE THREAD

**Issue by eric-tucker** [chef/chef#5837]
## Description

I require a third party gem (aws-sdk) in my attribute files in my cookbooks.  When I run chef-client against the cookbook using a ChefDK based install, things work.

When I run chef-client using a chef-client based install, it does not work and complains it cannot find the gem.

## Chef Version

ChefDK 1.2.22
Chef-client 12.18.31

## Platform Version

Amazon Linux

## Replication Case

Make a cookbook with an attributes file that tries to include "aws-sdk" via a require statement.

```
require "aws-sdk"
```

Execute `gem install aws-sdk`

Run chef against the cookbook with the [chef-client install](https://downloads.chef.io/chef) vs [ChefDK install](https://downloads.chef.io/chefdk).

## Client Output

When running via Chef installed through Chef-client 
```
LoadError
---------
cannot load such file -- aws-sdk
```

When run via Chef installed through ChefDK it works fine.

There must be a difference in how the Ruby include paths for gems are setup between the two installations.

**Comment by cheeseplus** [comment]
This is because ChefDK bundles the aws-sdk gem so it is already available for use. You'll want to install the gem either as part of you bootstrapping process (via a custom bootstrap template), install it via a recipe/library like the [aws cookbook](https://github.com/chef-cookbooks/aws/blob/master/libraries/aws.rb#L27-L31), or have the cookbook install it using the `gem` keyword in metadata.rb (presuming a recentish Chef 12) like:

```
## rest of metadata

gem 'aws-sdk'
```

**Comment by eric-tucker** [comment]
Can you please provide links on how to do 1? 

3 might be the best choice though.  You're saying that specifying gem keywords in a metadata.rb results in installation of those gems in Chef's gem path?
