### ISSUE TITLE
Bundled Ruby in Chef-client should be recompiled on FreeBSD 10.3

### ISSUE THREAD

**Issue by sekrett** [chef/chef#5891]
## Description

I am getting a segmentation fault on FreeBSD 10.3. It was working a few months ago but I don't know what happened. I am running my old cookbooks which did not change on fresh vagrant bento/freebsd machines. I think you should recompile bundled Ruby on FreeBSD 10.3, now it is compiled on 10.2 which has reached EOL on 01-JAN-2017. Not sure it will help but it's time for upgrade anyway. You may also want to bundle newer Ruby 2.3.3.

## Chef Version

Have this problem on 12.16.42 and 12.19.36.

## Platform Version

FreeBSD 10.3

## Client Output

/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mysql2-0.4.5/lib/mysql2/mysql2.so: [BUG] Segmentation fault at 0x00000812970f4f
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-freebsd10.2]

## Stacktrace

https://gist.github.com/sekrett/290f927ca0dccfee00f50ff353b621c5

**Comment by thommay** [comment]
We don't ship the mysql2 gem in chef; this is something you've installed yourself. Are the mysql client libraries still on your system? Have they changed recently? I'd recommend cleaning out the gems you've installed on your system and retrying.

**Comment by sekrett** [comment]
Of course `mysql2` I install myself, I know that. As I told already it is a fresh Vagrant machine, so no need to cleanup. MySQL is version 5.6.35 now, and the same cookbook worked well on a production server which has MySQL 5.6.34, and gem mysql2-0.4.5 is the same on both machines. What I am trying to say you should support latest versions of FreeBSD. If you compiled binaries on 10.2 and they work on 10.3 - it should be considered a coincidence. BTW older 10.2 is so bad that it does not install packages without tricky hacks, I don't want to downgrade OS, sorry. :) I don't ask you to fix a bug, please just upgrade or recompile your binaries.

**Comment by lamont-granquist** [comment]
FreeBSD supports binary compatibility back a long ways.  FreeBSD 4.x binaries can run on FreeBSD 10.x with port support, and there's even kernel modules for running 20-year old a.out binaries on FreeBSD 10.x.  It isn't a coincidence that binaries on 10.2 run on 10.3, that is a design goal of the FreeBSD project.

Not saying you don't have a problem, but theoretically it should all work.  It is also burdensome to support building multiple different versions because that increases the node count for builders and testers, and increases the frequency of transient issues which causes more build failures and more friction in the whole pipeline for building artifacts.

And I don't think you've shown that recompiling on 10.3 is the solution to the problem.  It could be that ruby 2.3.1 has an incompatibility with 10.3 and that ruby is buggy, or that FreeBSD 10.3 itself is buggy.

So, in order to help you we're going to need to know more information about what you're doing.  The best thing you can do is construct a test-kitchen case that fires up either a freebsd 10.2 or 10.3 bento image and then shows that it works on 10.2 and replicates the segfault on 10.3

**Comment by sekrett** [comment]
Ok, I agree about binary compatibility on FreeBSD, older binaries should work. In fact everything worked 3 months ago on 10.3. So it does not make sense to test on 10.2, even if it success it proves nothing. The problem is with packages installed. So the only thing Chef can do is upgrade the bundled Ruby version to 2.3.3 or 2.4.0. This way I will be able to report bugs to Ruby team.

**Comment by lamont-granquist** [comment]
#5902 now that we can start bumping the ruby version again.

**Comment by sekrett** [comment]
Super thanks!

**Comment by lamont-granquist** [comment]
you won't see that, even in the current channel until we've repaired our CI infrastructure, and at this point it'll be the Chef 13.0 release in April before it gets released to stable

**Comment by lamont-granquist** [comment]
since we've done everything which is currently actionable i'm going to close this.  we'll also be upgrading to 2.4.1 whenever that gets released.  if the issue persists, then it would probably be good to open a new bug if there's some other action we can take.  i suspect that ultimately chef is caught in the middle of a bug between ruby and freebsd 10.3 though.

**Comment by mawatech** [comment]
btw: https://www.ruby-lang.org/en/news/2017/03/22/ruby-2-4-1-released/ :)

**Comment by lamont-granquist** [comment]
yeah, we're on it, waiting for it to show up in travis:  #5936

**Comment by mawatech** [comment]
Already seen it, seems that there are no binary packages yet...
