### ISSUE TITLE
yum_package: multipackage sees "downgrade" on a mix of missing and installed packages as mixing upgrade/downgrade

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#5935]
## Description

Multipackage prevents both upgrading and downgrading in the same transaction for good reasons. It throws an error akin to:

```
Chef::Exceptions::Package: Multipackage rule ["libguestfs", "libguestfs-tools", "libguestfs-tools-c", "perl-Sys-Guestfs"] has a mix of upgrade and downgrade packages. Cannot proceed.
```

However, if only half of those packages are already installed and need to be downgraded and the other half are not yet installed, this can work in a single transaction safely, and we should probably allow that.

## Chef Version

12.13.37 (I know, old, but the latest version doesn't support it either afaict)

## Platform Version

CentOS 7

## Replication Case

See above.

## Client Output

See above.

## Stacktrace

N/A

**Comment by lamont-granquist** [comment]
this is yum only right because i think yum is the only one that cares about allow_downgrade?

i think this goes away with dnf?

i certainly don't see most of the point of allow_downgrade -- if its installed we're already idempotent and won't downgrade, unless you specify a specific lower version.

the dnf provider also supports `tcdump >= 1.2.3` or whatever correctly, which is a better api for setting a floor on a version but allowing later packages to be installed/pre-installed/externally upgraded/whatevs.

**Comment by lamont-granquist** [comment]
can i start ignoring allow_downgrade in a minor release of say 13.2 -- provided that the yum provider is fixed so that users can specify a version comparison floor?  is it actually useful in its current form?  doesn't it simply explode if you try to pin to a version but have a later version installed which causes needless fussiness?  do any useful use cases break if we ignore it and basically treat it as being set to true?

**Comment by jaymzh** [comment]
You wanna just always assume allow_downgrade true?

Last I checked yum doesn't work that way. Unless you specify "downgrade" to yum, it doesn't downgrade when requesting a specific version... `allow_downgrade` is what will let chef run `yum downgrade foo-1.2.3-1` isn't it? I don't feel like digging through the code right now so I could be wrong, but that was my recollection and the whole reason I recall requiring this grouping in multipackage.

**Comment by lamont-granquist** [comment]
Yeah but internally can we just fix that for the user and always provide allow_downgrade when its appropriate or just always pass in allow_downgrade?  Make it go away from the perspective of the chef user?

**Comment by jaymzh** [comment]
Yes, we can... but in multipackage (not the cookbook, but a `package` rule with multiple packages) if 2 of the 4 are going down and 1 is not installed and 1 is being upgraded, there's no easy way to do that. multipackage says we'll do it all in one transaction, and the upgrade and the downgrade can't easily be done that way (well, you can `echo install foo-X\ndowngrade bar-X\nupgrade baz-Z\nrun\n | yum-shell -y`, but that's a bit hacky).

**Comment by lamont-granquist** [comment]
We're never gonna fix this so yum_package is smart enough to do all the magical things for multipackage with mixed upgrade+downgrade.  Pretty sure dnf does away with this problem.
