### ISSUE TITLE
powershell_out stdout contains '\r\n' at the end of the output

### ISSUE THREAD

**Issue by Jakauppila** [chef/chef#5947]
## Description

I am using powershell_out for some data processing and am sensitive to the returning value from stdout as I inject the resulting contents into a JSON document for further consumption later in my Chef run.

## Chef Version

12.19.36

## Platform Version

Windows 10, this was encountered prototyping with 'chef/mixin/powershell_out' in a library.

## Replication Case

```
require 'json'
require "chef/mixin/powershell_out"
include Chef::Mixin::PowershellOut

script = <<-EOH
  "Hello World."
EOH

result = powershell_out(script)

puts result.stdout.to_json
```

## Client Output

"Hello World.\r\n"

## Expected Output

"Hello World."

## Additional Thoughts

If this is just expected behavior, can I expect '\r\n' to always to be present and just strip it off the end of the resulting output?

**Comment by smurawski** [comment]
@Jakauppila If the output ends in a newline, yes.  In your case, writing a string to stdout includes the newline.

Some methods do not though, so you'll have to code defensively.  (Chomping the `\r\n`, should be pretty safe though.)

For example, 

```
require 'json'
require "chef/mixin/powershell_out"
include Chef::Mixin::PowershellOut

script = <<-EOH
  $host.UI.Write("Hello World")
EOH

result = powershell_out(script)

puts result.stdout.to_json
```

`powershell_out` is a convenience around `shell_out` for those that want to call PowerShell rather than just using the default file handler for the target file.  With `powershell_out` you are getting the raw stdout from the powershell process.  There is no output sanitization.

Your example basically ran

```
powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command  "Hello World."
```
