### ISSUE TITLE
Cannot set force_override via knife node edit

### ISSUE THREAD

**Issue by jeunito** [chef/chef#6034]
## Description

From the[ code](https://github.com/chef/chef/blob/master/lib/chef/knife/core/node_editor.rb#L60-L70), it seems like one cannot edit force_override properties via knife. Is there a reason for this? 

## Chef Version

12.19.36

## Platform Version

OS X 10.12.3

## Replication Case

Add a force_override object via ```knife node edit -a nodename``` alongside other precedences like default. The following should be the output:  

> Node not updated, skipping node save

**Comment by coderanger** [comment]
As explained on StackOverflow, all levels other than normal are wiped and rebuilt every run so this is not possible.

**Comment by jeunito** [comment]
@coderanger Do you think it would be good to remove the other precedence levels other than normal from https://github.com/chef/chef/blob/master/lib/chef/knife/core/node_editor.rb#L60-L70? I could work on a PR for that.

**Comment by coderanger** [comment]
So this is kind of an awkward intersection between low-level API tooling and "what the user actually wants". The `knife * edit` commands are all intended to be pretty direct mappings to the API. You can actually edit other levels, and it would get saved back up to the server, but then `chef-client` would happily ignore it. We've tried to find a balance in `node edit` specifically because it is the most commonly used (indeed, the only one that should even be used in a non-emergency situation). I don't have a good answer this, but yes we should probably think more holistically about the UX of that command and either let you edit all levels even if some don't work, or otherwise don't even bother presenting the others in the editor.

**Comment by jeunito** [comment]
> or otherwise don't even bother presenting the others in the editor.

@coderanger What do you think about removing the -a option when editing: 
```bash
$ knife node edit
USAGE: knife node edit NODE (options)
    -a, --all                        Display all attributes when editing
...
```
