### ISSUE TITLE
Impossible to install GEMs with chef-client 13.0.113 on Windows

### ISSUE THREAD

**Issue by thpert** [chef/chef#6049]
## Description

Impossible to install GEMs with chef-client 13.0.113 on Windows

## Chef Version

chef-client 13.0.113

## Platform Version

Windows 2008 R2 x64

## Replication Case

> c:\opscode\chef\embedded\bin\gem.bat install tiny_tds

> c:\opscode\chef\embedded\bin\ruby.exe: No such file or directory -- c:/opscode/chef/embedded/bin/gem (LoadError)

In chef-client 12.X, in C:\opscode\chef\embedded\bin, there was 3 files to manage gem:
* gem.bat
* gem.cmd
* gem

In chef-client 13.0.113, the file "gem" is missing. Is this choice deliberate?

**Comment by goodrum** [comment]
I just ran into this exact issue (Windows 2012R2).  I had to rollback to v12.19.36 because the push-jobs cookbook fails due to a dependency on chef_ingredient which uses this call.  I found that if I manually remove the gem.bat file the process works as expected and calling gem.cmd directly will work.

Based on my tests, the issue is with the gem.bat file which contains really nothing

> @ECHO OFF
"%~dp0ruby.exe" "%~dpn0" %*

This compares to the gem.cmd file

>` :""||{ ""=> %q<-*- ruby -*-
@"%~dp0ruby" -x "%~f0" %*
@exit /b %ERRORLEVEL%
};{ #
bindir="${0%/*}" #
exec "$bindir/ruby" -x "$0" "$@" #
>, #
} #
#!C:/opscode/chef/embedded/bin/ruby
#--
#Copyright 2006 by Chad Fowler, Rich Kilmer, Jim Weirich and others.
#All rights reserved.
#See LICENSE.txt for permissions.
#++
>
>require 'rubygems'
require 'rubygems/gem_runner'
require 'rubygems/exceptions'
>
>required_version = Gem::Requirement.new ">= 1.8.7"
>
>unless required_version.satisfied_by? Gem.ruby_version then
  abort "Expected Ruby Version #{required_version}, is #{Gem.ruby_version}"
end
>
>args = ARGV.clone
>
>begin
  Gem::GemRunner.new.run args
rescue Gem::SystemExitException => e
  exit e.exit_code
end`


FWIW, the original gem file referenced by OP contains just about the same information as gem.cmd when looking at the v12.x version of this file

**Comment by pklanka** [comment]
Having the same problem for all my Windows servers. Please help

**Comment by coderanger** [comment]
Thank you all for reporting this issue, we are aware of it and are working on a solution. If this is a blocker issue for you, please don't upgrade to Chef 13 yet. We'll post more information when it becomes available.
