### ISSUE TITLE
How to silence install chef?

### ISSUE THREAD

**Issue by liwbj** [chef/chef#6090]
I am a new guy for chef, and I am trying to silence install chef in B-shell tools.
When use command of _sudo apt-get -y install chef_, the panel of **Configuring chef** alway pops up, and I need to input the _URL of Chef server_ and type Enter to continue the installation process.
How can I silently install chef by one command or how can use parameters or options to pass the a URL to installation process? 
Any comments will be appreciated. The panel format is as below.
┌───────────────────────────────────────────────────┤ Configuring chef ├───────────────────────────────────────────────────┐
│ Please choose the full URI that clients will use to connect to the server (for instance: http://chef.example.com:4000).  │ 
│                                                                                                                          │ 
│ This setting will be stored in /etc/chef/client.rb as "chef_server_url".                                                 │ 
│                                                                                                                          │ 
│ URL of Chef server:                                                                                                      │ 
│                                                                                                                          │ 
│ ________________________________________________________________________________________________________________________ │ 
│                                                                                                                          │

**Comment by ranjib** [comment]
You have to instruct apt/deb to not work in non-interactive mode. Read about deb-set-selection and DEBIAN_FRONTEND=noninteractive environment variable.

As a side note, chef is distributed as [omnibus debian package](https://downloads.chef.io/chef/13.0.118), which does not show this behavior afaict. Are you using stock chef package from ubuntu or debian main repo?

**Comment by whonow** [comment]
im trying to fix ny old laptop real windows 7!! original!!!!!! i thought it
was tabs r tabs r!or alt r¿

On Apr 26, 2017 1:58 AM, "Ranjib Dey" <notifications@github.com> wrote:

You have to instruct apt/deb to not work in non-interactive mode. Read
about deb-set-selection and DEBIAN_FRONTEND=noninteractive environment
variable.

As a side note, chef is distributed as omnibus debian package
<https://downloads.chef.io/chef/13.0.118>, which does not show this
behavior afaict. Are you using stock chef package from ubuntu or debian
main repo?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chef/chef/issues/6090#issuecomment-297245984>, or mute
the thread

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
