### ISSUE TITLE
Chef13 windows_task resource is not idempotent when specifying start_time

### ISSUE THREAD

**Issue by jeffj254** [chef/chef#6093]
## Description

The new windows_task resource in Chef13 is not idempotent when specifying start_time.  The resource will always execute during a chef-client run even if it has not been changed in any way.

Unfortunately I have not tried to use the older windows_task resource from the Chef Windows cookbook.  I am not aware if this behavior existed in that cookbook.

## Chef Version

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

## Platform Version

Windows 2012R2 Chef 13.0.118

## Replication Case

Create a windows_task resource and specify a start time.  Run chef-client twice and note that the resource executes each time.

windows_task 'test task' do
  command "echo test"
  cwd "c:/windows"
  start_time "02:00"
  frequency :daily
end
  

## Client Output

-----> Converging <default-windows-2012r2-D5GB>...
       Preparing files for transfer
       Preparing dna.json
       Preparing current project directory as a cookbook
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-windows-2012r2-D5GB>
       Starting Chef Client, version 13.0.118
       resolving cookbooks for run list: ["Perforce-ProxySetup::default"]
       Synchronizing Cookbooks:
         - Perforce-ProxySetup (2015.2.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       ...
       windows_task[test task] action create
       ...
Running handlers:
Running handlers complete
Chef Client finished, 1/98 resources updated in 06 seconds
Finished converging <default-windows-2012r2-D5GB> (0m13.07s).

**Comment by NimishaS** [comment]
@jeffj254 , the idempotency issue exists in case of `start_time` because `schtask.exe` sets the default `start_time` of any task as the current time, even if the user doesn't pass it.
Suppose the user runs this recipe:
```
windows_task 'chef-client' do  
  cwd 'C:\\chef\\bin'
  command 'chef-client'
  frequency :minute
  frequency_modifier 20
end
```
In this recipe, `start_time` is not passed, but internally `schtask.exe` sets the start time as current time.
Now if I run this recipe again, ideally it should not converge as I haven't modified any of the attributes. In order to do the idempotency check for all attributes, we fetch the details of the existing task using `schtasks /Query` command which returns the `start_time` for this task.
If I add a check to verify change in `start_time`, this recipe will converge again. Hence in order to maintain idempotency for all other attributes, it was required to skip this attribute.

**Comment by jeffj254** [comment]
I have a couple thoughts on how this could be improved as I feel creating a task that runs at a certain time every day/week is a common use case and breaking idempotency in these situations could be a frustrating burden on cookbook authors.

First, what about adding the ability to pass a scheduled task xml file to the windows_task resource?  schtasks.exe can accept an xml file as the configuration for a task and will create the task exactly as specified in the xml.  This is how I created my scheduled tasks in Chef before this new resource was added to core chef.

Otherwise, what about adding a boolean parameter to tell the resource that I want to use a fixed start time and to only check for a change in start_time if fixed_start_time is set to true?
