### ISSUE TITLE
Support allow_downgrade in apt_package

### ISSUE THREAD

**Issue by whiteley** [chef/chef#6095]
## Description

The package resource has an `allow_downgrade` property that is supported for dnf/rpm/yum. Newer versions of Apt (1.1+) support this functionality along with a couple of others.

```
       --allow-downgrades
           This is a dangerous option that will cause apt to continue without prompting if it is doing downgrades. It should not be used except in very special situations. Using it can potentially destroy your system! Configuration Item:
           APT::Get::allow-downgrades. Introduced in APT 1.1.

       --allow-remove-essential
           Force yes; this is a dangerous option that will cause apt to continue without prompting if it is removing essentials. It should not be used except in very special situations. Using it can potentially destroy your system! Configuration Item:
           APT::Get::allow-remove-essential. Introduced in APT 1.1.

       --allow-change-held-packages
           Force yes; this is a dangerous option that will cause apt to continue without prompting if it is changing held packages. It should not be used except in very special situations. Using it can potentially destroy your system! Configuration Item:
           APT::Get::allow-change-held-packages. Introduced in APT 1.1.
```

I'm not sure if this can be done without causing backwards compatibility issues. I'll contribute a PR for this if I could be pointed towards a workable method to do it. Thanks!

## Chef Version

13.0.118

## Platform Version

Ubuntu 16.04

**Comment by thommay** [comment]
I think supporting the allow_downgrade property for apt makes sense now, and would be relatively straightforward. I don't think we should go near `allow-remove-essential` or `allow-change-held-packages`, since clearly the system at that point is in a state that is way out of normality.

The best example of how to do this is probably the rpm provider: https://github.com/chef/chef/blob/master/lib/chef/provider/package/rpm.rb#L90-L91

Probably just add the relevant bit to the options array if needed.

Make sense?

**Comment by lamont-granquist** [comment]
dnf doesn't need this any more.

i actually thought apt allowed explicit downgrades by default.

and if the user wants to pin to an explicit version can we simply always add `--allow-downgrade`?  it seems like overly fussy protection.  we've also got syntax like `version "> 1.2.3"` which we support for yum that we should support for apt so that users can "set a floor, but allow later"

**Comment by curiositycasualty** [comment]
I, too, expected `--allow-downgrades` to just be there out of the box when pinning to a specific version. It seems like a user's intentions are pretty clear when they explicitly pin, regardless of whether or not that implicitly includes an up,down,sideways-grade.

**Comment by thomas88** [comment]
For other people who are looking for an intermediate solution, you can simply pass `--allow-downgrades` as `options` like this:

```rb
package 'libkrb5support0' do
  version '1.13.2+dfsg-5'
  options '--allow-downgrades'
end
```

**Comment by lamont-granquist** [comment]
I would probably be okay with a PR to add `--allow-downgrade` to every apt command by default

**Comment by leshik** [comment]
@thomas88 the solution isn't working for me.
```
WARN: apt_package[netplan.io] netplan.io has installed version 0.36.3, which is newer than available version 0.36.1. Skipping...)
```
Any ideas?

**Comment by thomas88** [comment]
@leshik Unfortunately no idea.

**Comment by jaininshah9** [comment]
@leshik Getting the same warning and not being downgraded. Were you able to find a solution?

**Comment by leshik** [comment]
@jaininshah9 The solution might be to write a library that adds custom package resource, then copy apt class code there and change the shell_out command line according to your requirements.

**Comment by lamont-granquist** [comment]
14.04 does not have `--allow-downgrade` since it has apt 1.0.x and not apt >= 1.1.0

**Comment by jaymzh** [comment]
FYI for those here - there was still bugs in downgrades, fixed here: https://github.com/chef/chef/pull/10993
