### ISSUE TITLE
Chef-client run making unwanted backup copy of file in  file_edit.rb

### ISSUE THREAD

**Issue by rickc007** [chef/chef#6123]
## Description
Trying to use file_edit.rb
https://github.com/chef/chef/blob/master/lib/chef/util/file_edit.rb

Line 87
FileUtils.cp(original_pathname, backup_pathname, :preserve => true)
And don't want it to make a backup.
I am working in this directory  ->   /etc/sysconfig/network-scripts
and the .old file will be read in and used.

Please advise if there is way around this 

## Chef Version
Chef: 12.11.18

 
## Platform Version
Oracle Linux Server release 6.6

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
