### ISSUE TITLE
How to run multiple chef-client processes in parallel

### ISSUE THREAD

**Issue by ttsharma** [chef/chef#6134]
## Description

I have a requirement to create multiple environments in parallel.
An environment for me consists of 1 DB, 1 WLS server, 1 OHS
I have written cookbooks to do installation and configuration and it works fine.

Now I have been provided with a big and powerful machine (36 core with TBs of storage) to create multiple such environments.

I want to re-use my cookbooks earlier developed but I am unable to do so because at a given point in time only one process of chef-client can be running.
I get below message.
[2017-05-09T04:26:05-04:00] WARN: Chef client 9578 is running, will wait for it to finish and then run.

What is the way forward to this problem?

Can I make use of lockfile attribute to achieve this? Something like below:
Run the below listed process in parallel where 'one' and 'two' are respective Chef environment names

sudo chef-client --config /etc/chef/one/client.rb --environment one --client_key /etc/chef/one/client.pem --validation_key /etc/chef/one/validation.pem --lockfile /etc/chef/one/lockfile -r 'role[utils:database]'

sudo chef-client --config /etc/chef/two/client.rb --environment two --client_key /etc/chef/two/client.pem --validation_key /etc/chef/two/validation.pem --lockfile /etc/chef/two/lockfile -r 'role[utils:database]'

## Chef Version

-bash-4.1$ chef -v
Chef Development Kit Version: 1.0.3
chef-client version: 12.16.42
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.13.2

## Platform Version

-bash-4.1$ uname -a
Linux ttsorchvm 3.8.13-118.15.1.el6uek.x86_64 #2 SMP Fri Dec 2 09:07:34 PST 2016 x86_64 x86_64 x86_64 GNU/Linux

## Replication Case

Execute 2 chef-client processes in parallel

## Client Output

[2017-05-09T05:14:38-04:00] INFO: Forking chef instance to converge...
[2017-05-09T05:14:38-04:00] DEBUG: Fork successful. Waiting for new chef pid: 10262
[2017-05-09T05:14:38-04:00] DEBUG: Forked instance now converging
[2017-05-09T05:14:38-04:00] WARN: Chef client 10162 is running, will wait for it to finish and then run.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
