### ISSUE TITLE
knife softlayer command throws ERROR: Excon::Error::Socket: Connection reset by peer (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by DixonJoseph93** [chef/chef#6163]
## Description

knife softlayer command throws ERROR: Excon::Error::Socket: Connection reset by peer (Errno::ECONNRESET)

## Chef Version
Chef Server Version : chef-server 12.11.1

knife softlayer server create \
	--image-id ${image_id} \
	--ssh-keys ${ssh_keys} \
	--hostname $node_name \
	--network-interface-speed 100 \
	--domain $domain_name \
	--cores ${cores} \
	--ram ${ram} \
	--datacenter ${datacenter} \
	--node-name $node_name \
	--vlan $public_vlan \
	--private-vlan $private_vlan \
	--use-private-network \
	-x root \
	-i $USER_HOME/.ssh/id_rsa

## Client Output
 ERROR: Excon::Error::Socket: Connection reset by peer (Errno::ECONNRESET)

**Comment by thommay** [comment]
Hi, the softlayer plugin is supported by softlayer and not by chef, and you should report bugs to them directly: https://github.com/softlayer/knife-softlayer . I'd recommend running the command with `-VV` to get diagnostic information from knife.
I'll be closing this ticket now since it's not a chef problem.
