### ISSUE TITLE
chef-client init script functionality broken

### ISSUE THREAD

**Issue by jeunito** [chef/chef#6179]
## Description

chef-client init script functionality doesn't work properly. 

## Chef Version

```bash
$ chef-client -v
Chef: 13.0.118
```
## Platform Version

Ubuntu 12.04

## Replication Case

1.  Bootstrap Ubuntu 12.04 node.
```
$ ps -C chef-client
PID TTY          TIME CMD 
```

### Case A
- Start chef-client via ```/etc/init.d/chef-client start```
Output shows ```fail``` but chef-client starts
```bash
$ sudo /etc/init.d/chef-client start
 * Starting chef-client  chef-client      [fail]                                                                                                                       [fail]
$ ps -C chef-client
  PID TTY          TIME CMD
14067 ?        00:00:00 chef-client
```

### Case B
- Stop chef-client via ```/etc/init.d/chef-client stop```
Output shows ```OK``` but chef-client isn't stopped
```bash
$ sudo /etc/init.d/chef-client stop
 * Stopping chef-client chef-client   [ OK ]                                                                                                                         
$ ps -C chef-client
  PID TTY          TIME CMD
14067 ?        00:00:00 chef-client
```

Upon spot checking, I see this functionality is working on the following 12.xx versions: 

12.16.42
12.17.44

So it must probably have broken somewhere along the way to 13

**Comment by coderanger** [comment]
I don't think we ship any init scripts in the omnibus installers, maybe you're using the `chef-client` cookbook?

**Comment by lamont-granquist** [comment]
unless we know the providence of the init script (where it comes from, what is in it, etc) its going to be difficult to guess the issue here.

**Comment by jeunito** [comment]
I ll look into this today. It could be coming from the chef-client cookbook
that we also use.

**Comment by lamont-granquist** [comment]
the version of chef-client cookbook being used would be most useful, along with trying out upgrading the cookbook to see if a newer version fixes the problem.  also would need to know what attributes are being set against that cookbook and what init system is being used.

i suppose this might be the upstart-vs-systemd bug that we fixed, but in that case it would definitely be the chef-client cookbook itself that was buggy since that fix in core is the correct thing to do, and i can't quite imagine how the cookbook could have worked around that problem so that the fix broke the cookbook -- but i've seen stranger things...

**Comment by jeunito** [comment]
> the version of chef-client cookbook being used would be most useful

It's not working on chef-client 6.0.0 

> along with trying out upgrading the cookbook to see if a newer version fixes the problem.

Upgrade to 8.1.2 fixes the issue.
