### ISSUE TITLE
IDE for Chef development

### ISSUE THREAD

**Issue by mshahat** [chef/chef#6211]
Hi, 

I've been doing some Chef work for sometime, and i've tried to work with few tools like IntelliJ Ultimate, RubyMine, VS Code and else as IDE for doing Chef work. None was near to optimal. 

I am seeking recommendations to tooling to help with doing Chef coding ? 

Thanks, 
/Mo

**Comment by coderanger** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
