### ISSUE TITLE
/opt/embedded/chef/bin in PATH causes scripts to fail

### ISSUE THREAD

**Issue by benthorner** [chef/chef#6239]
## Description

Since Chef 13, the `/opt/embedded/chef/bin` path is now injected at the beginning of PATH, giving it higher priority. In previous versions, it was injected at the end. This now causes problems when running pkg-config and probably other things as well. Is there a fix (or am I doing something wrong ;-)?

## Chef Version

Chef 13.1.31

## Platform Version

RHEL 6.4

## Replication Case

    execute 'test' do
      command 'env'
      live_stream true
    end

## Client Output

    # running with chef 13.1.31
    PATH=/opt/chef/embedded/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

    # running with chef 12.21.1  
  
  PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin

**Comment by lamont-granquist** [comment]
well, that's annoying.

so that behavior change to the `shell_out` API was entirely deliberate and intended.

the problem here is that execute should have been using `shell_out_with_systems_locale` which does none of the environmental mangling (doesn't manage the PATH, doesn't inject LC_ variables, etc).  so, in chef 13.0 it looks like we should have also switched the execute provider to use `shell_out_with_systems_locale` but i had no idea that this bug existed.

**Comment by lamont-granquist** [comment]
and so yes, i agree that `execute "pkg-config"` should never pick up the `/opt/chef/embedded/bin/pkg-config` executable and that was not ever intended.  but at the same time it was very deliberately intended that `shell_out!("pkg-config")` would always pick up the `/opt/chef/embedded/bin/pkg-config` executable.

we've probably got other bugs somewhere in this bugtracker where `execute("whatever")` behaves differently from `whatever` on the command line because the locale variables get scribbled over, and people who aren't in English/UTF-8 locales are likely annoyed at this behavior...

**Comment by benthorner** [comment]
Thanks for verifying the issue exists. Apart from keeping to Chef 12, is there anything we can do as a workaround?

**Comment by lamont-granquist** [comment]
explicitly passing the ENV['PATH'] in the environment of the execute resource?

we no longer mangle that globally so it should work.

i've also gotten the go-ahead to treat this like a bugfix and i'm working on it.

**Comment by benthorner** [comment]
That's a good idea - we'll do that for the time being. Good to know it's being fixed :-)
