### ISSUE TITLE
converge_if_changed does not check desired_state of property with default that has not been accessed

### ISSUE THREAD

**Issue by jakauppila** [chef/chef#6300]
## Description

When using `converge_if_changed`, Chef will not detect a change if a property is configured with a `default` and is `desired_state` if it is not explicitly defined in the resource usage.

The following line defines which properties to watch the desired state: 
- https://github.com/chef/chef/blob/264e3c5c12e1f8c15ed37aea3964957585c23601/lib/chef/provider.rb#L247

And ultimately utilizes the `is_set?` method which returns true if `The user explicitly set the value` and `The property has a default, and the value was retrieved.`
- https://github.com/chef/chef/blob/master/lib/chef/property.rb#L400

So in the event that a property has a default value, but the user has not retrieve the value, it will not be checked against the desired state.

A workaround is to simply access the value prior to `converge_if_changed` was executed, but leads to unnecessary code.

## Chef Version

Chef 12.21.3

## Platform Version

CentOS 7.2

## Replication Case

To replicate:
1. `git clone https://github.com/jakauppila/myTestCookbook`
2. `kitchen converge`
3. `kitchen exec -c "echo 'Goodbye World.' >> /home/vagrant/myfile.txt"`
4. `kitchen converge`

## Client Output

```
  [2017-07-31T03:09:40+00:00] DEBUG: Converging node default-centos-72
  Recipe: test::default_value
    * my_provider[/home/vagrant/myfile.txt] action add[2017-07-31T03:09:40+00:00] INFO: Processing my_provider[/home/vagrant/myfile.txt] action add (test::default_value line 1)
  [2017-07-31T03:09:40+00:00] INFO: my_provider[/home/vagrant/myfile.txt] already installed - nothing to do.
  (up to date)
    * my_provider[/home/vagrant/myfile.txt] action config[2017-07-31T03:09:40+00:00] INFO: Processing my_provider[/home/vagrant/myfile.txt] action config (test::default_value line 1)
  [2017-07-31T03:09:40+00:00] DEBUG: Skipping update of my_provider[/home/vagrant/myfile.txt]: has not changed any of the specified properties .
  (up to date)
```

## Expected Output

```
  [2017-07-31T03:12:37+00:00] DEBUG: Converging node default-centos-72
  Recipe: test::default_value
    * my_provider[/home/vagrant/myfile.txt] action add[2017-07-31T03:12:37+00:00] INFO: Processing my_provider[/home/vagrant/myfile.txt] action add (test::default_value line 1)
  [2017-07-31T03:12:37+00:00] INFO: my_provider[/home/vagrant/myfile.txt] already installed - nothing to do.
  (up to date)
    * my_provider[/home/vagrant/myfile.txt] action config[2017-07-31T03:12:37+00:00] INFO: Processing my_provider[/home/vagrant/myfile.txt] action config (test::default_value line 1)
  [2017-07-31T03:12:37+00:00] DEBUG: Resources for generic file resource enabled on node include: [Chef::Resource::File]
  [2017-07-31T03:12:37+00:00] DEBUG: Resource for file is Chef::Resource::File

      - update /home/vagrant/myfile.txt
      -   set contents to "Hello World." (was "Hello World.Goodbye World.\n")
      * file[/home/vagrant/myfile.txt] action create[2017-07-31T03:12:37+00:00] INFO: Processing file[/home/vagrant/myfile.txt] action create (/tmp/kitchen/cache/cookbooks/myTestCookbook/providers/my_provider.rb line 23)
```

**Comment by coderanger** [comment]
We probably can't change this until Chef 14, but the fix would be to check either `is_set || has_default` or something like that when filtering the properties list.

**Comment by lamont-granquist** [comment]
spiritual dup of #5992 at least?  also tagging #6036 for me to take a look at it whenever i get some time for that.

**Comment by jakauppila** [comment]
Any thoughts on this getting addressed for Chef 14?

**Comment by mattlqx** [comment]
The silent nature of this is significant IMO. If you remove setting the attribute when using the resource, you'd expect the value to go back to the default but it doesn't and since the run doesn't fail, you assume the resource converges as you'd expect. This leads to the configuration of whatever the resource is to be different than if the exact same code is brought up on a new host. The divergent behavior is not what I've come to expect from Chef resources.

Hope this gets fix up soon! This really breaks dynamic resources that are taking configuration from node attributes and applying those keys that exist to the resource. Removing a key won't actually remove it from already applied resources!

**Comment by EasyAsABC123** [comment]
This definitely effects the `iis` cookbook.

**Comment by jasonwbarnett** [comment]
I was trying to implement `windows_service` create/delete/configure actions and ran into this missing functionality causing problems. In my specific use case, if a user is specifying a user the service should be running as and then removes it later, it won't revert back to the default (`SystemLocal`).

Is there anyway that you can think of forcing this functionality in a resource prior to Chef 14? I guess I could hard code the specific test case in the action and then use `converge_by` instead of `converge_if_changed`

**Comment by Annih** [comment]
I encountered this issue with the properties tagged as `name_property` too - which is a subset of the described issue. IMHO think @coderanger suggestion would do the trick.

@lamont-granquist & @coderanger now that we are living in the Chef 14 era, maybe we could consider fixing this issue? :D

**Comment by jakauppila** [comment]
Any thoughts on this getting addressed for Chef 15?

**Comment by jasonwbarnett** [comment]
So I had a coming full circle moment last night while re-working the `windows_service` provider. I actually am flip flopping on my thoughts on this. I think it _may_ make more for `#converge_if_changed` to __not__ include properties from the `new_resource` which weren't explicitly set, assuming that you're mindset is: "If someone didn't explicitly set property x, I don't need/want to be concerned about it." -- Obviously this statement is not always true for every resource provider, so maybe adding some additional flag for specific properties that indicates, "include me, even if I wasn't explicitly because my default value should always be compared against the current value." I imagine this could be something like:

```ruby
property ":x, default: 'my default', converge_default: true
```

**Comment by jakauppila** [comment]
That sounds like that's an excellent compromise to me.

**Comment by lamont-granquist** [comment]
re: "If someone didn't explicitly set property x, I don't need/want to be concerned about it."

that sounds to me like a case for not having a default though and setting it to `nil`?

i just pushed a PR that fixes this issue but i'm somewhat worried it is a breaking change for existing code, and i'm not entirely clear on edge conditions like that.

**Comment by jasonwbarnett** [comment]
@lamont-granquist ha! that totally makes sense. Hindsight I should have been able to connect the dots, but didn't. I think removing defaults from properties which shouldn't converge back to a "default" makes the most sense.

Originally I mostly wanted to keep a default value because some resources require defaults for certain actions (e.g. `:create`) but I didn't want those same defaults for others (e.g. `:update`). I think the solution would be to have hidden defaults that only the provider is aware about, but the actual property default is set to nil.

Woohoo!

**Comment by lamont-granquist** [comment]
Yeah it feels weird to have a property default that wouldn't be enforced on `:update` and was create-only and was excluded from converge_if_changed.  That sounds to me like that's more of a bug, and usually oversight.
