### ISSUE TITLE
i have installed chef version 13.3.42 and i have completed configure a resource and configure a package and service but while creating cookbook i am getting error "The program 'chef' is currently not installed.

### ISSUE THREAD

**Issue by amitechno** [chef/chef#6342]
## Description

unable to create cookbook using command:
chef generate cookbook cookbooks/learn_chef_apache2

## Chef Version

13.3.42

## Platform Version

Ubuntu 14.04

## Replication Case

i have installed chef version 13.3.42 and i have completed 'configure a resource' and 'configure a package and service' but while creating cookbook i am getting error "The program 'chef' is currently not installed.

**Comment by jugatsu** [comment]
You should install chefdk https://downloads.chef.io/chefdk to use `chef` command. Also, use slack channel or mailing list to ask questions.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
