### ISSUE TITLE
How to install an older prerelease version?

### ISSUE THREAD

**Issue by CodingSpiderFox** [chef/chef#6512]
Yesterday, 13.5.22 was the latest prerelease of chef-client.

I installed it using the following parameters during knife bootstrap

`--bootstrap-version 13.5.22 --prerelease`

However. today when I wanted to bootstrap 13.5.22 using the same parameters, chef installed the chef-client 13.5.25.

Removing the `--prerelease` caused a download failure, it could not find v. 13.5.22 that way.

How can I still install 13.5.22 during bootstrap?

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by CodingSpiderFox** [comment]
Ok
