### ISSUE TITLE
Set Chef version constraint for a cookbook like ('>= 12.15.19', '<= 12.21.10') || '= 13.4.19'

### ISSUE THREAD

**Issue by daxgames** [chef/chef#6543]
## Description

I need to set a complex chef_version constraint for a cookbook.

Example: 
('12.15.19' <> '12.21.10') || '= 13.4.19'

This is due to an embedded Ruby version issue.
See: https://bugs.ruby-lang.org/issues/14071

## Chef Version

('12.15.19' <> '12.21.10') || '= 13.4.19'
Older than '12.15.19' does not work
12.21.12 thru 13.3.42 Does not work
\> 13.4.19 does not work.

## Platform Version

Linux and WIndows

## Replication Case

https://bugs.ruby-lang.org/issues/14071

**Comment by coderanger** [comment]
You do this like so:

```ruby
chef_version '>12.15.19', '<12.21.10'
chef_version '=13.4.19'
```

Keep in mind this is only used for checking on the runtime side, it doesn't actually affect version solving so this may be less useful than you hope.

**Comment by lamont-granquist** [comment]
Yeah I think our support also followed up directly to this internally, and @tas50 added a more complicated use case to the docs.

The TL;DR is that multiple constraints on a given `chef_version` line are AND'd and multiple lines are OR'd so there should be a way to express any arbitrary version constraint range.

This is also a HOWTO question instead of a bug report and should have gone to support / slack / discord / stackoverflow instead...
