### ISSUE TITLE
dpkg_package doesn't do version comparisons on upgrade

### ISSUE THREAD

**Issue by tas50** [chef/chef#6562]
dpkg_package just installs every time when you use the upgrade action even if the package is older than the currently installed package.

This results in scenarios like this:

```
       Recipe: apt_test::default
         * apt_package[pollinate] action upgrade (up to date)
         * dpkg_package[wget_1.13.4-2ubuntu1.4_amd64.deb] action upgrade
           - upgrade package wget_1.13.4-2ubuntu1.4_amd64.deb from 1.17.1-1ubuntu1.3 to 1.13.4-2ubuntu1.4
```

**Comment by lamont-granquist** [comment]
so the problem here is just that doing a downgrade by default is unexpected and dpkg_package doesn't support allow_downgrade and forces it to true?

that's common behavior across all the package providers.

the fix would be to add the ability to specify allow_downgrade, although the default value needs to not be modified.

**Comment by snehaldwivedi** [comment]
PR merged
