### ISSUE TITLE
Req: Option to prefix with node names rather than SSH attribute in knife ssh

### ISSUE THREAD

**Issue by mal** [chef/chef#6573]
## Description

The output of `knife ssh` is really useful when running a command over multiple servers, but it can be frustrating to have to convert public hostnames, or IPs back to a recognisable server name. It'd be nice to have a flag to switch out the SSH attribute value with the corresponding node name instead for these situations and a matching `knife.rb` setting to facilitate setting it as default behavior.

Possible extensions might be allowing an arbitrary attribute to be used, configurable in `knife.rb`.

## Chef Version

13.4.19

## Platform Version

Linux

## Replication Case

**Current:**
```
$ knife ssh 'name:test-server' 'echo hello'
ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com hello
```

**Desired:**
```
$ knife ssh -n 'name:test-server' 'echo hello'
test-server hello
```

**Comment by joegoggins** [comment]
👍  !

I'm really glad I found this GH issue. When I Googled "knife ssh show node name in output", I was taken to this ticket from 2013 asking for exactly this [CHEF-4618 Jira issue](https://tickets.opscode.com/browse/CHEF-4618).


Since I imagine MANY `knife ssh` users have integrations that expect the output of current `knife ssh` to prefix with hostnames as it currently does, I'd like to propose a slightly usage syntax. I propose that a `--prefix-with` flag is introduced that defaults to `fqdn` to keep default behavior like it is by default. The usage to make @mal's proposal work as desired would be:

## Desired:

```
knife ssh -n 'name:test-server' --prefix-attribute name 'echo hello'
test-server hello
```

**Comment by joegoggins** [comment]
Woooooo! Glad to see this feature req be conquered. Thanks!
