### ISSUE TITLE
Question about running chef-client during knife upload / knife role from file

### ISSUE THREAD

**Issue by antoniogomezalvarado** [chef/chef#6713]
Hi everyone, 

I apologize if this isn't the right place for putting out a question but I couldn't find any answer to this:

What happens if during a chef-client run someone is altering the chef server using knife upload cookbooks, knife environment from file or knife role from file ? Is it possible that the node will remain in an uncertain state if these commands are being run sequently and the chef-client is being executed in between ? Or does the Chef server have any lock mechanism that prevents this issue ?

Thanks in advance,
Antonio

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by antoniogomezalvarado** [comment]
Thanks @thommay will do! Posted here in case anyone is interested
https://stackoverflow.com/questions/47978436/chef-running-chef-client-during-knife-upload-knife-role-from-file
