### ISSUE TITLE
Pass attributes or json to chef-client command line

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef#6721]
## Description

I would like to run chef-client with some modified attribute values on a Windows command line, but without a JSON file.

Use case is that a build pipeline has just produced a binary artifact and I want to specify the URL and checksum of this artifact dynamically. This works for me:

```
echo { "my_product": { "url": "http://my-artifact-server/...", "checksum": "some-sha256" }} > my-attributes.json
chef-client -j my-attributes.json
del my-attributes.json
``` 

But is this the preferred way to specify dynamic attribute values?
I looked at these suggestions, but cannot make them work in a Windows command prompt:

- https://stackoverflow.com/questions/21986477/how-to-pass-attributes-in-chef-client-without-json-file
- https://serverfault.com/questions/480179/is-there-a-way-to-pass-parameters-at-run-time-in-chef

I also filed ticket number 17538 in the Chef ticket system, which holds a bit more background.

## Chef Version

Chef v12

## Platform Version

Windows Server 2012R2

## Client Output

```

```

**Comment by martinmosegaard** [comment]
I tried this approach, which looks right and allows me to position the input:

```
>for %i in ('{ "my_product": { "url": "http://my-artifact-server/...", "checksum": "some-sha256" }}') do chef-client -j %i
```

so it becomes:

```
chef-client -j '{ "my_product": { "url": "http://my-artifact-server/...", "checksum": "some-sha256" }}'
```

Alas, it throws an `rb_sysopen` exception, probably because `-j` will only accept a filename.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by martinmosegaard** [comment]
Thanks for the quick reply. It may be a stretch to label this as a feature request. I will look into the community links.

If you do find any information here that could lead to better documentation, please let me know and I will be happy to contribute. I just don't know the semantics of `-j` yet.
