### ISSUE TITLE
Windows chef-client security vulnerability

### ISSUE THREAD

**Issue by rkotecki** [chef/chef#6727]
## Description
My Windows Engineering team performed a vulnerability scan and Chef Client came back with the following vulnerability - "Windows Unquoted/Trusted Service Paths Privilege Escalation Security Issue". They have tried installing several different versions of client ranging from 13.1.31 and newer with the same vulnerability showing up. I have attached a screenshot of the log at the bottom of the issue.

## Chef Version
13.1.31

## Platform Version
Windows Server 2012

## Screenshot
![chef_vuln](https://user-images.githubusercontent.com/35108134/34570926-d03c618e-f132-11e7-8277-922f87a6b342.png)

**Comment by thommay** [comment]
Thanks for the report. Unfortunately, your vulnerability scan appears to be showing a false positive - it's detecting:
`C:\opscode\chef\embedded\bin\ruby.exe C:\opscode\chef\bin\chef-windows-service` as one long path with a space in, rather than two separate paths.

I'll be closing this issue since it's clearly not a bug in chef.
