### ISSUE TITLE
Obtain the Chef::Client instance in a running recipe

### ISSUE THREAD

**Issue by sll552** [chef/chef#6831]
## Description
Is it possible to obtain the Chef::Client instance in a running recipe?

What I want to achieve is a chef-server switch during the chef-client run. 
Scenario is that I am installing a VM with chef-zero. During the run a chef server is installed and the cookbooks/nodes/data bags/etc. are uploaded to the fresh server. Then I want the running client to report its results to the server.
What I did is creating the required files (org-val cert, client.rb, etc.) and then trigger a  `Chef::Config.from_file('/etc/chef/client.rb')` and the running client would contact the chef-server to report at the end of the current run. 
While reporting it receives `Net::HTTPServerException: 401 "Unauthorized"` because there is no client on the server, just the node. 
So I tried to do a `node.save` in the hope it would create a client and then downloading the acl with knife, fixing it and uploading it again. Unfortunately `node.save` does not seem to try and create a client if it doesn't exist.
What I would like to do now is invoke `Chef::Client.register()` instead of `node.save` but it seems that there is no way for a recipe to get the instance of the running chef-client.

## Chef Version
```
chef-server-core-12.12.0-1.el7.x86_64
chef-12.21.4-1.el7.x86_64
```
## Platform Version
CentOS 7 (7.3/7.4)

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by sll552** [comment]
Thanks, I posted on the mailing list, here is the [Mailing List Post](https://discourse.chef.io/t/obtaining-the-chef-client-instance-in-a-running-recipe/12545) for anyone who gets here from google 😉
