### ISSUE TITLE
RFE: `ignore_update` metaproperty

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#6863]
## Description

Add an `ignore_update` property that one could add to never fire notifications.. The upshot of this is in a custom resource you could have a resource that doesn't cause the parent to notify which could be useful in several scenarios:

1. a template to a temp location that you then analyze to determine *if* you want to do something
2. a resource such as a whyrun_safe_ruby_block that has no effect on the sytem

**Comment by lamont-granquist** [comment]
To capture rationale for my future self long after I've forgotten today's conversation...  The goal is to build a custom resource which uses a template to write out a temporary file and then do complicated comparisons with the existing file (beyond just md5sum equality) to drop it into place.  An extension could be made to the File provider base class itself here to allow injecting a block to do the comparison before moving it into place, but I gather that subsequent mangling may happen as well, so you'd have to build a bit chain of actions which might happen within the file provider.  Simpler solution is to just render the template file and then mess around with it in a custom resource -- but this causes the custom resource to alway be updated and always fire notifications because a sub-resource fired.  This brings up the point that there are ways to use chef resources which don't affect running state and only scribble over temporary state, and we have no way to make exceptions to the rule that sub-resources that are updated bubble up.  Trying to do this with manual hackery runs into compile-converge problems (and using a ruby_block or whyrun_safe_ruby_block to lazy the setting of `updated_by_last_action = false` will fail because that resource will fire and update it (lol).

This can be accomplished now by using `build_resource(:template, "thingy") do ... end.run_action(:whatever)` which is fairly ugly and must run compile time (i think?), and sort of abuses not creating the resource on the resource collection to avoid updating the outer resource (note: this is `build_resource` not `declare_resource`).

Having `Chef::Resource#ignore_update(bool)` which caused (i think) `Chef::Provider#resource_updated?` to always return false would be a cheap way to avoid having to think about things so deeply to do something this simple.

**Comment by jaymzh** [comment]
You could, if you then wanted to do track whether you notify for everything else. But if you have a long and complicated provider and in the middle of it you wanna write a template out to tmp, compare it to the original, and then decide, oh only comments changed, mv the tmp over the original and move on without notifying... but the entire rest of the body of the action should work as expected. This is a simple example, but it can get more complicated, obviously.

Given all that it seems really nice to be able to say:

```
action :dostuff do
  # some prepwork here
  f = mktmp
  template f do
    ...
    ignore_update true
    action :nothing
  end.run_action(:create)
  if is_only_comments_different(f, "/etc/myconfig")
    FileUtil.move(f, "/etc/myconfig")
  end
  template "/etc/myconfig" do
    ...
  end
  # some other stuff
end
```

This is a contrived and yet simple example, there are wider more complicated examples where this pattern can be useful and having this feature would require people to venture less far off the beaten path.

**Comment by coderanger** [comment]
Sure, understandable use cases exist, just the kind of thing I would want to see prototyped out of core if possible. Can we come up with a way to do it externally?

**Comment by lamont-granquist** [comment]
This would also help with:

```
log "whatever" do
  ignore_update true
end
```

Which could then be flipped to being the default for the log provider.

**Comment by lamont-granquist** [comment]
related to #3426 and the log resource.

**Comment by tas50** [comment]
Thanks for submitting this issue. After review by the team, we've decided that this isn't something that we're going to work on ourselves. We receive dozens of new issues a month, which is more than our team can possibly work on. This means we must prioritize work and be honest about what we're able to get done as a team.  That doesn't mean that we think this is a bad idea or isn't a necessary change. It's just not something we'll likely get to given competing priorities. I've applied our `Design Proposal: Accepted. PRs Welcome` label to this issue and closed it out. If you or someone else would like to work on this issue we're open to pull requests. If you'd like to chat further about what that design might look reach out to us in our [#chef-infra-dev](https://chefcommunity.slack.com/archives/C55FCUGBS) slack channel.
