### ISSUE TITLE
Failed to authenticate to the chef server (http 401)

### ISSUE THREAD

**Issue by Skynot** [chef/chef#6866]
Description
Hi guys, I'm new in Chef and I'm French (sorry for my english). I installed a chef-server and a chef workstation. I try to run chef-client on a windows node, I got an error.

Chef Version
16.3.4

Platform Version
Chef-server = CentOS7
Chef-workstation = CentOS7
Windows Node = Windows Server 2012R2

Client Output
``
[root@workstation .chef]# chef-client -N serveur-windowsStarting Chef Client, version 13.6.4

Chef encountered an error attempting to load the node data for "serveur-windows"

Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).

Server Response:
----------------
Invalid signature for user or client 'serveur-windows'

Relevant Config Settings:
-------------------------
chef_server_url   "https://chef-server/organizations/testorg"
node_name         "serveur-windows"
client_key        "/etc/chef/client.pem"

If these settings are correct, your client_key may be invalid, or
you may have a chef user with the same client name as this node.

System Info:
------------
chef_version=13.6.4
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
program_name=chef-client worker: ppid=30912;start=11:31:16;
executable=/opt/chefdk/bin/chef-client

Running handlers:
[2018-02-19T11:31:21+01:00] ERROR: Running exception handlers
Running handlers complete
[2018-02-19T11:31:21+01:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 04 seconds
[2018-02-19T11:31:21+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-02-19T11:31:21+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-02-19T11:31:21+01:00] ERROR: 401 "Unauthorized"
[2018-02-19T11:31:21+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[root@workstation .chef]# chef-client -N serveur-windowsStarting Chef Client, version 13.6.4

Chef encountered an error attempting to load the node data for "serveur-windows"

Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).

Server Response:
----------------
Invalid signature for user or client 'serveur-windows'

Relevant Config Settings:
-------------------------
chef_server_url   "https://chef-server/organizations/testorg"
node_name         "serveur-windows"
client_key        "/etc/chef/client.pem"

If these settings are correct, your client_key may be invalid, or
you may have a chef user with the same client name as this node.

System Info:
------------
chef_version=13.6.4
ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
program_name=chef-client worker: ppid=31378;start=11:34:07;
executable=/opt/chefdk/bin/chef-client

Running handlers:
[2018-02-19T11:34:11+01:00] ERROR: Running exception handlers
Running handlers complete
[2018-02-19T11:34:11+01:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 04 seconds
[2018-02-19T11:34:11+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-02-19T11:34:11+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-02-19T11:34:11+01:00] ERROR: 401 "Unauthorized"
[2018-02-19T11:34:11+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[root@workstation .chef]# 

Thanks for your help, be kind

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

In this case, you don't say how you created the workstation client.pem. Have you followed https://learn.chef.io/modules/manage-a-node-chef-server#/ ?

**Comment by Skynot** [comment]
My chef-client was installed when i bootstrap my node. So in my opinion all certificate and key are good isn't it ?

**Comment by vsingh-msys** [comment]
Hey @Skynot In order to bootstrap a node you should hit
```
knife bootstrap IP_ADRESS -N node-name
```
After a node is bootstraped you can hit the `chef-client` on the node if required with the desired option
use `chef-client --help` to check available option.

For knife setup, you can look into https://docs.chef.io/config_rb.html.

If still, you have any issue/concern let know further otherwise close the issue?

Thanks!

**Comment by cdflint** [comment]
Ran into this problem when I rebuilt my chef-server sandbox.  On the windows node:

Remove-Item "C:\chef\client.pem"

Enjoy.

**Comment by vsingh-msys** [comment]
Okay, the closing issue for now. Thanks!
