### ISSUE TITLE
windows task  modify changes the trigger type

### ISSUE THREAD

**Issue by spuder** [chef/chef#6887]
In chef 13, If you attempt to modify an existing scheduled task with chef, and you change the start_day or start_time, chef will alter the trigger type from 'at startup' to 'on schedule'

```ruby
# schdtask.exe /Create /TN 'chef ad-join' /RU 'SYSTEM' /TR echo 'chef-client' /RL HIGHEST /SC ONSTART 
windows_task 'foo' do
   task_name 'chef ad-join'
   user 'SYSTEM'
   command 'chef-client'
   run_level :highest
   frequency :onstart
   action :create
 end

# schdtask.exe /Change /TN 'chef ad-join' /SD '06/09/2016' /ST '01:00'
 windows_task 'bar' do
   task_name 'chef ad-join'
   start_day '06/09/2016'
   start_time '01:00'
   # Chef 12 uses :change, Chef 13.4.19 uses :create to modify existing tasks http://bit.ly/2wbDTzP
   action :create
 end
```

<img width="608" alt="screenshot 2018-02-20 22 03 37" src="https://user-images.githubusercontent.com/242382/36464240-f6ab40f0-168b-11e8-8b1b-b2240af265fb.png">

<img width="612" alt="screenshot 2018-02-20 22 20 32" src="https://user-images.githubusercontent.com/242382/36464299-4fe735d4-168c-11e8-8855-99b974098210.png">

The expected behavior is that the modify resource should act the same way as the windows_task on chef 12. 

The resource should effectively run this powershell command `schdtask.exe /Change /TN 'chef ad-join' /SD '06/09/2016' /ST '01:00'`
```
# schdtask.exe /Change /TN 'chef ad-join' /SD '06/09/2016' /ST '01:00'
windows_task 'bar' do
   task_name 'chef ad-join'
   start_day '06/09/2016'
   start_time '01:00'
   # Chef 12 uses :change, Chef 13.4.19 uses :create to modify existing tasks http://bit.ly/2wbDTzP
   action :create
 end
```

It looks like the task is created with schtasks.exe arguments, then on the 'modify' it deletes the scheduled task and recreates it with a new xml file

```
[2018-02-21T05:32:44+00:00] DEBUG:     schtasks /CREATE /TN "chef ad-join" /F /SC "hourly" /MO "1" /SD "06/09/2016" /ST "01:00" /TR "chef-client -L C:\chef\chef-ad-join.log" /RU "SYSTEM"
       [2018-02-21T05:32:44+00:00] DEBUG: looking for existing tasks
       [2018-02-21T05:32:44+00:00] DEBUG: Removing former #{option} if any
       [2018-02-21T05:32:44+00:00] DEBUG: Setting #option as #option_value
       [2018-02-21T05:32:44+00:00] DEBUG: running:
       [2018-02-21T05:32:44+00:00] DEBUG:     schtasks /DELETE /TN "chef ad-join" /F
       [2018-02-21T05:32:44+00:00] DEBUG: running:
       [2018-02-21T05:32:44+00:00] DEBUG:     schtasks /CREATE /TN "chef ad-join" /RU "SYSTEM" /XML "C:\Users\vagrant\AppData\Local\Temp/windows_task.xml"
       [2018-02-21T05:32:44+00:00] INFO: windows_task[modify sched task start time] task created
```

**Comment by spuder** [comment]
Work around is to use a powershell script and schtasks.exe to get the old behavior that chef 12 had

```ruby
windows_task 'foo' do
   task_name 'chef ad-join'
   user 'SYSTEM'
   command 'chef-client'
   run_level :highest
   frequency :onstart
   action :create
 end

  powershell_script 'ad-join sched task modify start date' do
    code <<-EOH
    schtasks.exe /Change /TN 'chef ad-join' /SD '06/09/2016' /ST '01:00'
    EOH
    only_if "schtasks.exe /Query /TN 'chef ad-join'"
  end
```

**Comment by Vasu1105** [comment]
@spuder it changes :onstart to :hourly since you have not provided the :frequency property while update/change so it picks up default frequency as :hourly.

If you want to update the task make sure you are defining all resource properties that you used while create so your recipe will look like  i.e.
windows_task 'foo' do
   task_name 'chef ad-join'
   user 'SYSTEM'
   command 'chef-client'
   run_level :highest
   frequency :onstart
   action :create
   start_day '06/09/2016'
   start_time '01:00'
 end

Above recipe still will throw validation error in chef 13 since there is validation that start_day is not valid with frequeny :onstart as option /SD is not applicable with :onstart Ref: https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx.

In #6815 we are now not using schtask.exe so there won't be case that we are deleting the task and recreating it with new task xml. But for update you have to provide :frequency otherwise it will updated to default frequency :hourly. We have also removed the validation so that user is able to change the start_day for frequency :on_logon, :onstart, :on_idle in #6815
