### ISSUE TITLE
Cannot override attributes after upgrading from Chef Client 13.7.16 to 13.8.0

### ISSUE THREAD

**Issue by infertux** [chef/chef#6928]
## Description

Cannot override attributes after upgrading from Chef Client 13.7.16 to 13.8.0.

## Chef Version

13.8.0

## Platform Version

Debian 9

## Replication Case

- I'm using the [resolver](https://github.com/chef-cookbooks/resolver) cookbook version 2.0.1 (latest).
- I've set `node.normal['resolver']['search'] = nil` in [one of my cookbooks](https://github.com/infertux/chef-sanity/blob/master/recipes/resolver.rb#L9).
- After upgrading, [this line](https://github.com/chef-cookbooks/resolver/blob/master/templates/default/resolv.conf.erb#L8) is no longer respecting my `nil` value and instead is picking up `node['domain']` as per https://github.com/chef-cookbooks/resolver/blob/master/attributes/default.rb#L19 (same issue when I use `override` instead of `normal`).

**Comment by lamont-granquist** [comment]
Setting nil has never worked to override attributes.  The deep merge cache code uses nil for "not present" rather than being an actual nil value to merge.  This has been consistent behavior since at least Chef-11.0

The use of node.normal is also highly discouraged since it persists on the node object in the database rather than being wiped at the start of every run like default and override are.  This probably does not have anything to do with whatever issue you're seeing though.

`node.rm_default("resolver", "search")` can be used to remove the default level setting from the cookbook.

**Comment by infertux** [comment]
Thank you. This happened on an odd setup using `chef-client -z`. Changing `node.normal` to `node.default` fixed the issue. Closing.
