### ISSUE TITLE
Why is there still a "knife upload cookbook" AND a "knife cookbook upload"

### ISSUE THREAD

**Issue by red8888** [chef/chef#7099]
I just updated to the latest version of Chef DK 2.5.3 and this is still there.

Is there a serious backwards compatibility issue here? I forget which is which like every time and its maddening. Can there be like a warning adding to the one that is deprecated or something at least?

**Comment by lamont-granquist** [comment]
They're different and neither is deprecated.  We've had #3368 open for awhile but that issue is not to deprecate either command but to implement `knife cookbook upload` using cheffs which is the backend behind `knife upload cookbook`.  I don't think we've discussed deprecation of `knife cookbook upload`. 

`knife upload` is better for raw access and treating the repo like a filesystem and upload/download of the entire repo for backups and synchronization.  Parity is better now that (IIRC) `knife upload` works with ruby files.  We likely really don't want to tell everyone who is happily using `knife cookbook upload` in scripts that we're going to break everything since that disruption would be large (most likely stranding people on old version before the break happened and creating more legacy support issues and driving more users away who don't keep on top of those changes).  Offhand I don't see a good solution here that keeps everyone happy other than just some kind of documentation (and I'm not sure what kind of documentation, since we document those commands, but it certainly may not be easily consumable, but I'm simply at a loss for good ideas because its not remotely a thing that I'm good at -- and its obvious to me that the verb-noun form is the cheffs implementation, so its just not confusing to me).

**Comment by tas50** [comment]
I'm closing this in favor of #7368 now. Previous we removed the old supermarket plugin code and made the plugins simple aliases for the cookbook site plugins.  In 14.4 all the code was moved from cookbook site to supermarket. In 15 we'll kill the cookbook site plugins off entirely.

**Comment by tas50** [comment]
Closing this since they both perform different things and we're not yet ready to deprecate either of them.
