### ISSUE TITLE
Chef Handler DSL does not pass run_status correctly in :run_failed event

### ISSUE THREAD

**Issue by martinisoft** [chef/chef#7101]
## Description

The new Chef Handler DSL does not hand off the `run_status` correctly at least to the `:run_failed` handler as it is supposed to given the code. In the example code below, it receives nil and there is no way to access things like the cookbook collection, exception messages, etc. Only the exception is actually passed to the block resulting in a nil object error.

## Chef Version

Tested in Chef Client 13.8

## Platform Version
Ubuntu 14.04 and 16.04

## Replication Case

Here is the example `client.d` file from our chef-client which demonstrates this problem:

```ruby
begin
  require 'bugsnag'
  Bugsnag.configure do |config|
    config.api_key = 'secrets'
  end
rescue LoadError
  Chef::Log.warn('Could not load bugsnag gem. If this is the first run, it will resolve itself. If not, then something has gone horribly wrong.')
end

Chef.event_handler do
  on :run_failed do |exception, run_status|
    cookbook_list = run_status.run_context.cookbook_collection
    Bugsnag.notify(exception) do |report|
      report.ignore! if ENV['TEST_KITCHEN']
      report.release_stage = run_status.node.chef_environment
      report.add_tab(:chef,
                     node_name: run_status.node.name,
                     cookbooks: cookbook_list.keys.map { |x| cookbooks[x].name.to_s + ' ' + cookbooks[x].version })
    end
  end
end
```

The rescue blocks are related to #7088 to solve that problem which revealed this issue. In the above example the `run_status` being passed to the `:run_failed` handler is nil and thus will cause a NilClass exception. I'll also note here that I could not debug this issue via pry using `chef-shell -z` and the current documentation does not talk about any of the objects passed to the handler blocks. I had to go digging into the code with the assistance of @coderanger to find the method signature. Had to do the same for the `run_status` object as well. Some explanation would be very, very helpful here. It seems the only object I am able to access in this handler is `Chef` which is how I paired down the above example to this code which is running now in production, but does not provide very useful, actionable exceptions:

```ruby
begin
  require 'bugsnag'
  Bugsnag.configure do |config|
    config.api_key = 'secret'
  end
rescue LoadError
  Chef::Log.warn('Could not load bugsnag gem. If this is the first run, it will resolve itself. If not, then something has gone horribly wrong.')
end

Chef.event_handler do
  on :run_failed do |exception|
    Bugsnag.notify(exception) do |report|
      report.ignore! if ENV['TEST_KITCHEN']
      report.release_stage = Chef.node.chef_environment
      report.add_tab(:chef, node_name: Chef.node.name)
    end
  end
end
``` 

## Client Output
```
Running handlers:
[2018-03-30T02:10:51+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-03-30T02:10:51+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2018-03-30T02:10:51+00:00] ERROR: undefined method `run_context' for nil:NilClass
[2018-03-30T02:10:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

## Stacktrace
There was no stacktrace written when this crash occured.

**Comment by lamont-granquist** [comment]
I can't figure out how this bug happens.

The run_status is created in the initializer of the Client object.  The run_failed notification only happens in the exception handler in the main loop in the run method in the Client object.  I can't see any way that value could be nil.

The lack of a stacktrace is expected since the run_failed event is fired from the exception handler which aborts the run method when it is called so the stacktrace is not written, that is expected.

You have to be in the main block inside the run method though in order for any of this to actually fire, and so that run_status object must be there.  So I've just proven this bug is impossible?  I certainly don't understand how it happens.

If it ever gets repod, then actually getting a stacktrace out of the handler just by doing a `puts caller` would be necessary to see where in the client it is actually throwing from originally in order to wind up in the exception handler.

**Comment by lamont-granquist** [comment]
So the related issue is around an exception that seems to be being thrown from the client.rb parsing logic, which is nowhere near the `Chef::Client#run` method.  It is expected that message would not get fired due to failures parsing client.rb (which happens way over in `Chef::Application::Client`).  Both the parent and the supervisor process should be failing in the Application class which should never fire that exception.

We have issues around capturing exceptions in the client.rb (the automate data collector can't gather those exceptions either, but that is a huge meta-issue that would require refactoring a lot of the Chef::Client -vs- Chef::Application::Client code.

I don't know that this is the best ticket to address those issues though and doesn't seem to be very helpful to anyone for being actionable work at this point, so I rather than drop it down to lowest priority I think it needs to get cleared off the board.
