### ISSUE TITLE
manage.chef.io account verification mail

### ISSUE THREAD

**Issue by shesshunuthi** [chef/chef#7220]
Hi everyone, I am very new to this platform even in writing a issue.

I tried to create an account in manage.chef.io it has displayed a message verification mail has sent to proceed. But I did not got any mail 

Regards I Have sent mail to support team, I got mail from getchef.zendesk team. Unfortunately I=it is also asking me to create and account to raise ticket. I have signup for the same as requested, and the verification mail for the zendesk also did not appeared in my mail box. 

Any experts please share some tips how to solve this. 

My expectation : create account in manage.chef.io

**Comment by Zorrom** [comment]
The email its referring to is the one which you used during account creation. The verification mail contains the account activation link. Considering the fact that you haven't received any mails then it could be either be because you provided a wrong email during signup. So try creating an signing up once again with the correct email,which might solve the problem.

**Comment by stuartpreston** [comment]
Closing this issue, please email support@chef.io if you continue to have account problems.
