### ISSUE TITLE
windows_task resource doesn't properly handle commands with arguments in chef-client 14.1.1

### ISSUE THREAD

**Issue by bmiller08** [chef/chef#7238]
## Description
Previously when using the `windows_task` resource with a `command` such as `powershell.exe -ExecutionPolicy Bypass -File "c:\chef\cache\update_windows.ps1"` the `windows_task` resource would properly enter `powershell.exe` as the **Program/script** and the remaining arguments would be entered in to **Add arguments (optional)** in the resulting task. Now the full contents of the `command` property are entered in **Program/script**. This causes the resulting task to fail with `The system cannot find the file specified. (0x80070002)` or `The parameter is incorrect. (0x80070057)`.

If you try to reproduce this manually the Task Scheduler won't even let you input the values this way and automatically detects you mistakenly put arguments in **Program/script**

## Chef Version
14.1.1

## Platform Version
Windows Server 2012 R2

## Replication Case
- Attempt to created a windows task where the command has arguments. A minimal example would be:
```
windows_task 'chef ami builder task' do
  task_name 'chef-ami-builder'
  command "chef-client -W"
  frequency :none
  action :create
end
```
- Attempt to run the task and note the failure.
- Edit the **Action** in the Task Scheduler. It will return:
```
It appears as though arguments have been included in the Program text box. Do you want to run the following program:
    chef-client

With the following arguments:
    -W
```
- Clicking **yes** will fix the task, **no** will wrap the whole command in quotes like `"chef-client -W"`. This indicates the way Chef is setting up a task isn't valid to the Task Scheduler.

## Client Output
I don't think this is needed. As far as chef-client is concerned this task was created as expected.

**Comment by bmiller08** [comment]
The ruby interface for task scheduling, [win32-taskscheduler](https://github.com/chef/win32-taskscheduler), supports both a `application_name` and `parameters`. The [provider for the chef resource](https://github.com/chef/chef/blob/master/lib/chef/provider/windows_task.rb) for `windows_task` only ever calls `task.application_name` when dealing with the `command` property of the resource. The `command` property is never broken up and arguments sent to `task.parameters`.

**Comment by bmiller08** [comment]
@mitom Once this is fixed, re-running chef-client should resolve the issue. The resulting new provider (in the above PR) flags the task for updating if anything doesn't match (command, arguments, etc). In the case of your example it would flag for needing an update because the `command` portion does not match the desired command.

**Comment by bmiller08** [comment]
Additionally @mitom this wasn't an issue in `14.0.202`. You can revert and run your windows clients and it will correct the resource depending on how urgent your issue is.

**Comment by mitom** [comment]
I understand that this can be fixed by running chef client on a version that is either fixed or before the change was applied. The issue I'm trying to point out is that the `windows_task` resource is used by the chef-client cookbook which I expect is very widely used to set up chef running periodically. This bug affects it and to fix it a chef-run needs to be triggered on each instance *manually* on a working chef version (unless I am missing something).

While I understand that the chef-client cookbook is not an "official" cookbook, I think as this bug directly influences chef's ability to run on windows systems that were set up based on it (which is [recommended](https://learn.chef.io/modules/manage-a-node-chef-server/windows/hosted/run-chef-client-periodically#/)) and require manual intervention (as in manually running chef on the instance with a fixed version) to fix it once it gets applied warrants this being high priority? It doesn't really matter to my environment as our instances are already affected by it, I'm trying to raise this to ensure others' environments don't suffer from this.

**Comment by bmiller08** [comment]
@mitom Fair point. I misunderstood.
