### ISSUE TITLE
Knife search misinterprets queries in the form `<expr1> AND (NOT expr2)`

### ISSUE THREAD

**Issue by saveriomiroddi** [chef/chef#7607]
## Description

Knife search doesn't interpret queries with parentheses and NOT, for example `<expr1> AND (NOT expr2)`

## Chef Version

```sh
$ knife --version
Chef: 14.4.56
```

## Platform Version

```sh
$ lsb_release -d
Description:	Ubuntu 16.04.5 LTS
```

## Replication Case

Create a setup with a positive number of nodes. I'll call one of the nodes `testnode`. Now run a query in the form `<expr1> AND (NOT expr2)`, with and without parentheses:

```sh
$ knife search 'name:* AND NOT name:anynontestnode'
$ knife search 'name:* AND (NOT name:anynontestnode)'
```

Although the queries are semantically equivalent:

- the version without parentheses will include `testnode` in the result
- the version with parentheses will not return anything at all

## Client Output

```
0 items found
```

## Stacktrace

(no stack traces)

**Comment by lamont-granquist** [comment]
This is just due to search syntax originally being implemented using solr:

https://tickets.opscode.com/browse/CHEF-2334

It is a dup of many similar issues.  Its not good, but at the same time its been around as a thing since 2011, so its not going to ever get worked as a ticket (its a problem between breaking every existing customer who has figured out how to deal with solr syntax vs implementing something cleaner for new users vs just having vastly simpler issues to fix...)
