### ISSUE TITLE
Mount resources shouldn't track mounted status in a property

### ISSUE THREAD

**Issue by tas50** [chef/chef#7621]
We're tracking state in a property here. The user could potentially set this property and break the world. Properties are a bad place to track state.

**Comment by snehaldwivedi** [comment]
@tas50 Could you please elaborate on the ticket details for my understanding.

**Comment by tas50** [comment]
The resource property here is used to track state in the provider and needs to be refactored away: https://github.com/chef/chef/blob/master/lib/chef/resource/mount.rb#L57

**Comment by snehaldwivedi** [comment]
@tas50 I have done some analysis as per it if we removed chef/resource/mount.rb#L57 then some of the methods will break like https://github.com/chef/chef/blob/master/lib/chef/provider/mount.rb#L39 
All of these are dependent on mounted property. So maybe we can add a system-level check if the device is mounted or not or if you have any other suggestions?

**Comment by lamont-granquist** [comment]
This is probably not the right way to fix this now.

What should happen now is that either load_after_resource should be written or load_current_resource should be converted to load_current_value so that the mounted property was correctly being populated as reporting state both before and after the resource runs.

**Comment by tas50** [comment]
Based on the convo in our issue triage, I think we should hold off on this one until we figure out exactly how to structure these resources for proper reporting.
