### ISSUE TITLE
Could not find cookbook standard in your cookbook path: output cookbook paths

### ISSUE THREAD

**Issue by moorichardmoo** [chef/chef#8001]
### Describe the Enhancement:
I want to see if knife is looking where I'm expecting it to when trying to find cookbooks.

### Describe the Need:
Someone trying to diagnose why cookbooks aren't being found, perhaps due to a misconfigured config.rb or missing metadata, or a typo.

### Current Alternative
Nothing that I'm aware of.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
