### ISSUE TITLE
Child run contexts

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#8044]
### Describe the Enhancement:

Please give access to children runcontext from parent runcontexts.

In a report handler, when walking `run_context.resources` - given how CustomResources now work (with inline resource)  it's currently a lie and you lose a ton of data.

### Describe the Need:
We want to be able to log and report on what resources were fired during a run, their timing, etc. but currently we only get that for the root context.

### Current Alternative
A potential work around (thanks to @jonlives) WOULD be enabling file-based datacollector, then later parsing that file, and later parsing that file, except the DataCollector is littered with `unless nested_resource?(resource)`. :( See https://github.com/chef/chef/issues/8049

### Can We Help You Implement This?:
Please.

**Comment by lamont-granquist** [comment]
so is easy enough to shove all the child run_contexts into an array off of the run_context.

the next step though is that what you really want is to iterate recursively through all the resource_collections to find resources.  there really needs to be a stable API to iterate through the meta-resource_collection and visit every resource, or find every file resource, etc... 

i almost wonder if we should wire up the resource collections with parent and child pointers and put the API there.  i'm not sure jamming it into the run_context is the best place (because then there's a duplication of concerns), and not sure creating a meta resource_collection object or module is the best idea (again, duplication of concerns).  i don't entirely like wiring up pointers across the run_context and the resource_collection because that feels like some duplication as well.  i need to noodle on it a bit more...

**Comment by lamont-granquist** [comment]
I think we need another ticket.

"We want to be able to log and report on what resources were fired during a run, their timing, etc. but currently we only get that for the root context."

That task I now think boils down to "fix and generalize the code in the ResourceReporter (and rip out half of the DataCollector as well)" which now looks like it has nothing to do with child run_contexts and is all about hooking the event API.

**Comment by jaymzh** [comment]
per Slack chat, this will be for the generic "wanna walk child contexts" and your other PR will be for the resources specifically.

**Comment by lamont-granquist** [comment]
Closing this because I think the action_collection is the right way to go about doing this and its been shipped.

The resource collection is a dynamic object that misses actions that were fired off of resources that were never put in any resource collection, and which forgets prior actions that were called on resource objects in the collection.  It can never be a correct record of all the actions that were taken.  The action_collection gets all that right.

The example of looking for queued notifications wouldn't be helped by child contexts.  The child contexts that we could keep around would have already run all their notifications (and you could find those in the action_collection).  The child contexts that are in the future haven't been created yet.  The only queued notifications waiting to run are in the current or parent contexts of the running code.
