### ISSUE TITLE
erro syntax error, unexpected end-of-input, expecting keyword_end

### ISSUE THREAD

**Issue by ClaytonOSouza** [chef/chef#8320]
case node[:platform_family]
when 'debian'
  include_recipe 'apt'
  apt_repository 'npm pm2' do
    uri "https://pm2.io/doc/#{node['platform']}"
    distribution node['lsb']['codename']
    components ["pm2-#{node['pm2']['version']}"]
    key "https://pm2.io/doc/#{node['platform']}/GPG-key.txt"
    deb_src true
    notifies 'nothing', 'execute[apt-get update]', 'immediately'
    package ['npm pm2'] do
    action :install
  end

 case node[:platform_family]
 when 'rhel'
  yum_repository 'pm2' do
    description "pm2-wrapper #{node['pm2-wrapper']['version']} repo (#{node['platform_version']} - $basearch)"
    url "https://pm2.io/doc/pm2-#{node['pm2']['version']}/el#{node['platform_version'].to_i}/"
    gpgcheck false
    gpgkey 'https://pm2.io/doc/debian/GPG-key.txt'
    package ['npm pm2'] do
    action :install
  end

  service 'npm pm2' do
  supports :status => true, :restart => true, :reload => true
  action :start
  end
 end

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
