### ISSUE TITLE
chef-client no connection could be made because target machine actively refusing it

### ISSUE THREAD

**Issue by Sudit1983** [chef/chef#8568]
While executing chef-client -l debug for recipe created in xmledit cookbook, receive a message "No connection could be made because the target machine actively refusing it".

Upon executing chef-client --local-mode on the recipe receive No method error: Undefined method "xmledit".

Since I am new to Chef world & same recipe seems to be working on other nodes can you please help.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
