### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?): https://api.chef.io/organizations/<orgname>

### ISSUE THREAD

**Issue by Sudit1983** [chef/chef#8578]
Generated at 2019-05-23 17:23:23 +0100
URI::InvalidURIError: bad URI(is not URI?): https://api.chef.io/organizations/<orgname>
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split'
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/http.rb:492:in `chef_zero_uri?'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/server_api.rb:38:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/api_client/registration.rb:158:in `new'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/api_client/registration.rb:158:in `http_api'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/api_client/registration.rb:104:in `create'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/api_client/registration.rb:95:in `create_or_update'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/api_client/registration.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:671:in `register'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:264:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chefdk/modules/chef/../../bin/chef-client:312:in `load'
C:/opscode/chefdk/modules/chef/../../bin/chef-client:312:in `<main>'

**Comment by Vasu1105** [comment]
@sudit1983 it would be good if we get steps to reproduce this issue.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
