### ISSUE TITLE
Chef encountered an error attempting to load the node data for *****(node_name)

### ISSUE THREAD

**Issue by saampandit** [chef/chef#8642]
## Description

I am running chef-client run via invoke command. This run happened with command chef-client -j web.json. I received an error as attached in file. Also it says chef_server_url is incorrect. But when I logged onto the server it worked fine. Why I could have received this issue. This is intermittent.

## Chef Version

chef-client 14.10.9

## Platform Version

Windows Server 2016

## Replication Case

Try to run chef-client via invoke command and with -j attribute
## Client Output

![image](https://user-images.githubusercontent.com/5196859/59179918-2340c480-8b81-11e9-8565-bf74f5727167.png)

```

```

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
