### ISSUE TITLE
Habitat Builds for Windows

### ISSUE THREAD

**Issue by btm** [chef/chef#8731]
As an enterprise user of Chef Infra, I need a Habitat package for Windows so I can move to effortless.

Acceptance Criteria:

habitat builds of chef infra client are:

- built in parallel of the omnibus builds
- cause the whole pipeline to appropriately fail if they fail
- run the same test suite as the omnibus packages
 - ~~are promoted in parallel with the omnibus builds~~ pending: https://github.com/chef/expeditor/issues/1132

Aha! Link: https://chef.aha.io/epics/CHEF-E-71

**Comment by robbkidd** [comment]
A solid, official chef-infra-client Habitat package for Windows relies on a solid Ruby package. Ruby being what it is requires fiddling with various environment variables containing file paths (e.g. `GEM_PATH`, `SSL_CERT_FILE`). Habitat+Windows has an [open issue to figure out how to resolve paths at package build time to be able to set paths that are reliable at runtime](https://github.com/habitat-sh/habitat/issues/6483). There is a [design proposal](https://github.com/habitat-sh/habitat/issues/6837) for potential solutions.

**Comment by robbkidd** [comment]
Update!

✅  I've got a `ruby-plus-devkit` (plus git) package that is basically the analog of Stuart's ruby-with-devkit. It can `bundle install` projects that have git references! (because I made it even bigger by baking the DevKit's (a.k.a. MSYS2's) git package into it.

✅  I've got a `chef-infra-client package` that bundle installs. 🎉 And almost appbundles ...

😢  ... but, about that appbundling, running `hab pkg exec robbkidd/chef-infra-client chef-client.bat -v` gets me an error about it being unable to find the "addressable" gem (the first one listed in the precise appbundled manifest).

I'm finally at the point where I need to figure out how appbundler works. I am distressed to discover an `unless A && B .. else ..end` block is [where the attempted use of gems](https://github.com/chef/appbundler/blob/master/lib/appbundler/app.rb#L303-L304) lives. My brain is too tired at the moment to parse that, but I suspect that the `nil`ing out of `GEM_PATH` is a problem within this Habitat package whose gems have been collected into paths that have been added to the `GEM_PATH`.

In a parallel effort—while waiting on these iterations of builds—[the King in the North](https://github.com/TheLunaticScripter) and I started experimenting with a `ruby` plan built from source with `visual-cpp-build-tools-2015` to see how far we could get with a more Hab-philosophically-pure build chain. We only started this afternoon, so progress was short but promising.

**Comment by robbkidd** [comment]
Have solved the appbundling. 

Using [the omnibus package's post-build test](https://github.com/chef/chef/blob/b1a5a4f7e3eb30d30ebd1c5b9e22b299441350a1/omnibus/omnibus-test.sh#L120-L157) as a model:

✅ The executables _intended for end-user use_ all report their version with the `--version` switch. This may seem like a silly test, but it means that the appbundled binstubs successfully locate and load all the gems each command requires.

🚧 The executables _used for testing the package_ are not on the path currently because they're not used by end-users. Experimenting with balancing the package between being testable and communicating to the end-user clearly what is runtime-supported behavior.

Packages being experimented on are:
* https://bldr.habitat.sh/#/pkgs/robbkidd/ruby-plus-devkit/latest
* https://bldr.habitat.sh/#/pkgs/robbkidd/chef-infra-client/latest

**Comment by robbkidd** [comment]
Hit an existing issue working with test builds. https://github.com/habitat-sh/habitat/issues/6657

chef-client shells out to run standard Windows utilities, but these shell-outs fail because Habitat tightly controls the `PATH` to only directories from within Habitat packages and so the commands are not found.

**Comment by robbkidd** [comment]
There is a workaround for the `PATH` lockdown: Habitat-installed binstubs from `hab pkg binstub`. Habitat 0.85.0 (currently unreleased) writes out binstubs that include the environmental settings from the package being stubbed _and_ the binstub's PATH has the current environment's PATH appended to the end. 👍 

Current steps to reproduce a successful package validation (based on [the validation for the omnibus package](https://github.com/chef/chef/blob/d775e6f3d7b584beb523546bbd0ccd85d6fdc133/omnibus/omnibus-test.sh#L155-L157)):

### have 0.85.0+ installed 

This version is needed for the fix for [setting paths for runtime that don't include studio-specific paths](https://github.com/habitat-sh/habitat/issues/6483#issuecomment-517847362). @mwrock helpfully built some experimental packages for us to test with. Here's how to use it until 0.85.0 is released:

* `hab pkg install core/hab --channel setup_env`

### install chef-infra-client on a Windows host (not within a studio)

The experiments are happening in my origin in the unstable channel, so:

* `\hab\pkgs\core\hab\0.85.0\20190823135453\bin\hab pkg install robbkidd/chef-infra-client --binlink --channel unstable`
    - You need to binlink with the 0.85.0 version for the binstubs created to include environmental settings from the packages.
* `chef-client --version` -> `Chef Infra Client: 15.2.24` 🎉 

### Want to run the test suite?

* `cd \hab\pkgs\robbkidd\chef-infra-client\<version>\<release>\vendor\gems\chef-<version>-universal-mingw32`
* `\hab\pkgs\core\hab\0.85.0\20190823135453\bin\hab pkg exec robbkidd/chef-infra-client bundle.cmd install`
* `rspec spec/functional`

```
Finished in 13 minutes 25 seconds (files took 15.54 seconds to load)
3898 examples, 0 failures, 62 pending
```

**Comment by robbkidd** [comment]
# What's next? / Things We Need

0. Releasing this is dependent on a Habitat 0.85.0 release.

1. I believe that the packaging of chef-client is as complete as it can be without a native build of Ruby and the libraries/tooling chef-client currently uses from RubyInstaller+DevKit(MSYS2). These plans and packages need review and testing by people experienced with Effortless Config and Windows.

2. With the chef-infra-client package passing basically the same test as the omnibus package, I need help creating pipelines for the pieces.
    * The ruby-plus-devkit plan needs a more official home and appropriate pipeline.
    * Need to make whatever changes necessary to `chef/chef` for the Habitat pipeline to support Windows packages.

**Comment by btm** [comment]
Number 2 begins here: https://github.com/chef/release-engineering/issues/831

**Comment by robbkidd** [comment]
https://github.com/habitat-sh/habitat/issues/6657 might be a possible blocker.

However, I _think_ that [the supervisor adds the system's `PATH`](https://github.com/habitat-sh/habitat/blob/0.85.0/components/common/src/util/path.rs#L148-L151)—technically, whatever the `PATH` is set to by the thing starting the supervisor, e.g. systemd job, init script, etc—to the runtime `PATH` of a supervised process. So we might be OK from the context of using this HabiWindoChef chef-infra-client in effortless scaffolding, where the chef-client process will be run by the supervisor. Finding out is part of the TODO step I documented as ["Judicious testing with the effortless scaffolding."](https://github.com/chef/chef/pull/8900)

**Comment by mwrock** [comment]
I can absolutely confirm this. The supervisor will add the current path to the service's path.

**Comment by robbkidd** [comment]
Current hurdle: package verification tests to gate a package pipeline. [Details added on a comment on the Windows plan PR](https://github.com/chef/chef/pull/8900#issuecomment-539014282).

**Comment by robbkidd** [comment]
Current things in flight:

* a [new repo to house Chef-specific foundational plans](https://github.com/chef/chef-plans) (a la omnibus-software? but for stuff that isn't appropriate for `core`)
    - its first contestant: a [`chef/ruby-plus-devkit`](https://github.com/chef/chef-plans/pull/1) Windows hab package for Ruby on Windows
* `chef/chef-infra-client`
    - for Windows: chef/chef#8900 (new)
    - for Linux: chef/chef#8941 (updates to Linux plan based on learnings from writing the Windows plan)

The Windows chef-infra-client plan PR has in it an update to the Expeditor Verify pipeline to crank out a throw-away CI build of the plan and run tests on it, both [pestering that executables "work"](https://github.com/chef/chef/pull/8900/files#diff-da1f43916a3ed4a350cbb6036b648b8f) and [a deeper run of the `rspec spec/functional` test suite](https://github.com/chef/chef/pull/8900/files#diff-696d10c71cdfc27f3f3ad4e51d9bb154R13) that is [what validates an omnibus package](https://github.com/chef/chef/blob/v15.3.14/omnibus/omnibus-test.ps1#L94).

The `ruby-plus-devkit` plan works—consider: it's the Ruby underneath the passing tests for the `chef-infra-client`—but we've not yet gotten Expeditor wired up on the new chef/chef-plans repo to run a verify pipeline there and its tests (which are present, at least, just not running anywhere).

**Comment by robbkidd** [comment]
Delivered in #8900.

**Comment by btm** [comment]
@robbkidd we can close this right?

I believe we're pending https://github.com/chef/expeditor/issues/1132 to fix promotion of both habitat and omnibus together.

**Comment by robbkidd** [comment]
@btm Yes, I think so. Maybe update the issue's first comment on the relaxed requirement for "are promoted in parallel with the omnibus builds"?

**Comment by btm** [comment]
:heavy_check_mark: done.
