### ISSUE TITLE
Issue with knife bootstrap in Mac Mojave

### ISSUE THREAD

**Issue by nico01f** [chef/chef#8780]
## Description
After launch bootstrapping command, knife throw me this error

## Chef Version
`chefdk-2.3.4-1.el7.x86_64`

## Platform Version
CentOS Linux release 7.6.1810 (Core)

## Replication Case
knife bootstrap IP -i  key.pem --node-name NODE_NAME --connection-user centos --sudo

## Client Output
```
Are you sure you want to continue connecting
? (Y/N) Y
WARN: [SSH] PTY requested: stderr will be merged into stdout
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `empty?' for nil:NilClass
```

More debugging
https://pastebin.com/d1eUxR1c

**Comment by tas50** [comment]
ChefDK 4 is our current release of ChefDK and we continue to support ChefDK 3 until April 2020. ChefDK 2.x is no longer a supported release. Additional we rewrote the knife bootstrap functionality in the Chef 15 release which is part of ChefDK 4.x. This rewrite changes how all the SSH connections behave during the bootstrap and makes it much more reliable. I'm going to close this out since you're not on a supported release of DK. Give it a try on DK 4.x and let us know if you still have issues.
