### ISSUE TITLE
windows_firewall_rule doesn't support multiple profiles

### ISSUE THREAD

**Issue by Happycoil** [chef/chef#8808]
## Description
`windows_firewall_rule` doesn't support multiple profiles. The property needs to support the Array type.

## Chef Version
14.7+

## Platform Version
Windows

## Replication Case
Try to modify a standard rule with multiple profiles

## Client Output
```
Chef::Exceptions::ValidationFailed
----------------------------------------------------
Option profile must be equal to one of: :public, :private, :domain, :any, :notapplicable!  You passed :"private, public".
```

**Comment by mrmarbury** [comment]
We are facing the same problem. The firewall rule we try to delete has the profile `Domain, Private` and there is no way deleting it. We get the same error message as the OP

**Comment by tecracer-theinen** [comment]
Still not solved: The resources as of today's master branch will work for rules with just one associated profile, but fail validation of current value on those with multiple.

This is because the `load_firewall_state` method of the resource converts the profiles to a String in PowerShell, resulting in a current value like `:"domain, private"` for existing rules with multiple profiles. This is of course not a valid value and it fails validation even before executing the resource.

PowerShell return value:
```json
 {
  "rule_name": "WMPNSS-RME-HTTP-In-TCP",
  "description":"Inbound rule for the Windows Media Player Network Sharing Service to allow HTTP Media Streaming. [TCP 10245]",
  "group": "@FirewallAPI.dll,-31500",
  "local_address": "Any",
  "local_port": "10245",
  "remote_address": "Any",
  "remote_port": "Any",
  "direction": "Inbound",
  "protocol": "TCP",
  "firewall_action": "Allow",
  "profile": "Domain, Private",
  "program": "System",
  "service": "Any",
  "interface_type": "Any",
  "enabled": false
}
```

Failure during loading current state in Chef run:
```
 [2020-03-19T18:30:40-07:00] FATAL: Chef::Exceptions::ValidationFailed: windows_firewall_rule[WMPNSS-RME-HTTP-In-TCP] (appinstall-hardening::set_firewallrules line 28) had an error: Chef::Exceptions::ValidationFailed: Option profile's value [:"domain, private"] contains values not in :public, :private, :domain, :any or :notapplicable!
```
