### ISSUE TITLE
windows_firewall_rule has potentially dangerous defaults

### ISSUE THREAD

**Issue by Happycoil** [chef/chef#8811]
## Description
The default behavior of `windows_firewall_rule` if the rule doesn't exist is to create an "any any any" rule which opens for all traffic on any port. If you intend to enable a default rule like so:

```
windows_firewall_rule "SomeDefaultRule With A Verbose Nam-AndPorts" do
  enabled true
end
```

It'll create a new rule without giving any feedback to the user that the name was misspelled and you just inadvertently opened up your firewall to anything. This problem is compounded by the fact that the resource relies on the `Name` attribute internally, but `DisplayName` is surfaced in the GUI. Multiple default rules with different `Name`s and identical `DisplayName`s exist.

I'd suggest we change the defaults, perhaps defaulting `firewall_action` to `:block`. That would mean having to explicitly pass a `firewall_action` for all new rules, but it would be safer.

## Chef Version
14.7

## Platform Version
Windows

**Comment by tas50** [comment]
@Happycoil Given a time machine I think we'd agree that :block would be a good default, but it's nearly impossible to change it to deny at this point. Users would roll out a new version of chef, without realizing the change and take down their production environments. I think instead we should create a cookstyle rule to make sure people specific the actions here since it's key that folks understand exactly what they're setting. I'll get an issue for that opened today in cookstyle.
