### ISSUE TITLE
Automatic Creating the Security Group while Test Kitchen EC2

### ISSUE THREAD

**Issue by Nara-Sagar** [chef/chef#8830]
![image](https://user-images.githubusercontent.com/48256252/63319863-33231480-c339-11e9-85af-71f74f8f5eae.png)

how to make the chef  to use my existing security group, As it always creates a new security group when I do kitchen converge

**Comment by dheerajd-msys** [comment]
Hi @Nara-Sagar,

From bitmap it seems you are providing _**Security group Name**_ instead of _**ID**_. 
Please follow https://github.com/test-kitchen/kitchen-ec2#security_group_filter and example here https://github.com/test-kitchen/kitchen-ec2#example in order to provide correct value.

Please let us know in case of any issues.
Thanks!

**Comment by lamont-granquist** [comment]
This is also the incorrect repo for this issue and it seems to be a question not a bug.

For bug reports they should go to https://github.com/test-kitchen/test-kitchen/issues and for questions that should go to slack, discord or stackoverflow.
