### ISSUE TITLE
knife ssh should support gssapi/kerberos

### ISSUE THREAD

**Issue by Poohblah** [chef/chef#8837]
I am repeating #3378 , because that issue was closed and locked without explanation.

`knife ssh` does not support kerberos/gssapi auth.  I can use a kerberos ticket to log in to a node with openssh, but not `knife ssh`:

```
[birdsnest ~][I]% kinit *****@*****
Password for *****@*****: 
[birdsnest ~][I]% ssh underling03.*****
Last login: Wed Aug 21 15:00:50 2019 from birdsnest.*****
[hendrenj@underling03 ~]$ exit
logout
Connection to underling03.***** closed.
[birdsnest ~][I]% knife ssh underling03.*****
*****@underling03.*****'s password:
```

**Comment by lamont-granquist** [comment]
We aren't going to patch knife ssh to support gssapi in its current form.  The only path towards getting that support would be both converting knife ssh to use train instead of net-ssh directly, and then getting gssapi support into train.  Patching gssapi support into knife ssh as it is now would only create a technical barrier into getting knife ssh onto train.

That means that this issue goes well beyond a bugfix or simple feature request but becomes dependent upon a major refactor of the whole knife ssh codebase, which makes tracking it in a GH issue poor.  It doesn't help us prioritize anything and it will get lost in the other 400+ issues and won't be useful for communication and will likely be left open until long after it ever gets fixed.  If you've got a paid support contract then you should contact us through those channels in order to actually make prioritization happen.

As it is now knife ssh is built on a bankrupt codebase and we can't accept major features landing in it until it gets cleaned up.  It isn't even a case of "PRs accepted" since nothing major and new should go into it right now.
