### ISSUE TITLE
chef-14 branch needs to be updated to properly build habitat packages

### ISSUE THREAD

**Issue by tas50** [chef/chef#8966]
The chef-14 branch comes from a crazier time where we had 3 or 4 different CI systems and expeditor built our hab packages. Now that everything is in buildkite and that's under expeditor's control we need to update the world. This already happened on master, but needs to be done in chef-14 as well.

@tduffield pointed out this is the legacy way of building hab packages
https://github.com/chef/chef/blob/chef-14/.expeditor/config.yml#L20-L22

Instead we need a file like this: https://github.com/chef/chef/blob/master/.bldr.toml an expeditor pipeline config like this: https://github.com/chef/chef/blob/master/.expeditor/build.habitat.yml and pipeline wiring like this: https://github.com/chef/chef/blob/master/.expeditor/config.yml#L28

**Comment by christopher-snapp** [comment]
It looks like Chef 14 has not had a habitat promotion since the name was changed from `chef-client` to `chef-infra-client` in 40a8fa6173:

https://bldr.habitat.sh/#/pkgs/chef/chef-client
https://bldr.habitat.sh/#/pkgs/chef/chef-infra-client

Can someone confirm that the updated habitat config should use the `chef-infra-client` name?
