### ISSUE TITLE
package resources executed on debian-based distros that specify a source property should default to using the dpkg_package

### ISSUE THREAD

**Issue by tilne** [chef/chef#9014]
## Description
Since apt_package does not support the source option, the package resource should use dpkg_package instead when the source option is provided.

## Chef Version
14.2.0

## Platform Version
Ubuntu 16.04.6

## Replication Case
1) Download the binary package for the hello package:
```
root:~ # apt-get download hello
Get:1 http://us-west-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 hello amd64 2.10-1 [27.3 kB]
Fetched 27.3 kB in 0s (70.6 kB/s)
root:~ # ll hello*
-rw-r--r--  1 root root 27300 May  6  2015 hello_2.10-1_amd64.deb
```
2) Execute a recipe that attempts to install it via a package resource:
```
package "hello" do
  source "/root/hello_2.10-1_amd64.deb"
end
```

## Client Output
The relevant output:
```
    Error executing action `install` on resource 'apt_package[hello]'
    Chef::Exceptions::Package
    -------------------------
    apt package provider cannot handle source attribute. Use dpkg provider instead
```

**Comment by lamont-granquist** [comment]
Sorry that one is a pretty hard 'no', there's already too much magic in the package providers, and the dpkg_package resource is the correct way to install local package on debian/ubuntu.

**Comment by lamont-granquist** [comment]
A much more concrete example of why I have a hard 'no' on this is that the dpkg_package resource is NOT necessarily API compatible with the apt_package resource -- they're very close but they're not identical.  If I allow this magic in the door, then I open the door for all kinds of issues related to sorting out and making it identical so that any property to dpkg_package maps perfectly to every property to apt_package.  The better solution is for users to use the dpkg_package directly and then none of those bugs are ever created, and none of that work needs to be done and/or I don't have to close those issues with WONTFIX.  This is just too minimal of a feature for a thing that can easily be accomplished by using the right tool, which will avoid all those possible headaches in the future (and unfortunately history suggests that while it may take a year or two at some point someone will extend dpkg in some clever way and then we'll get bugs by people expecting apt_package-with-a-source to work absolutely identically and then the headache of adding dpkg-specific properties to apt_package and then having to deal with either hiding them from documentation or dealing with the bug reports of people who expect them to magically work with apt -- after 9 years of maintenance I can bet something that rhymes with this will happen in the future).  The whole thing is vastly simpler by having apt-be-apt and dpkg-be-dpkg.

**Comment by lamont-granquist** [comment]
And its bad OO design because the apt_package resource neither "is-a" dpkg_package resource or "has-a" dpkg_package resource.

See e.g. https://en.wikipedia.org/wiki/Is-a, https://en.wikipedia.org/wiki/Has-a and https://en.wikipedia.org/wiki/Liskov_substitution_principle
