### ISSUE TITLE
Chef-client is not consuming the hash array values declared in normal attributes

### ISSUE THREAD

**Issue by Doltair** [chef/chef#9244]
## Description

In the cookbook a default attribute is specified as:

```
default['mycookbok']['cluster_node'] = {
  'node1' => 'zone1',
  'node2' => 'zone2',
}
```
After converge, I want to change those attributes by specifying normal attributes through chef-api t- chef-server and declare new attribute hashes like

```
{
"mycookbook": {
    "cluster_node": {
      "other_new_node1": "zone1",
       "other_new_node2": "zone2"
      }
}
```

Expected, the cookbook should read the normal_attributes instead of the values from default. For what is happening, it merges the two values and making default and normal coexists. 

The values consists of 4 values, the other was from normal. 

## Chef Version
14+

## Platform Version
Rhel 7 Linux / Windows 2012 

## Replication Case
Create a dummy cookbook with default attributes hashes array value. Converge the cookbook into the node. 
In the template, create a loop each to get the array values.

In the chef server, edit normal attributes and specify new hash values.

Converge again.

The values are merged includes the two which is default and normal. 

Note:

I am not sure if this is the correct repo to open this issue or in https://github.com/chef-cookbooks/chef-client/issues/new, but it seems its not related to chef-client cookbook.

Thank you!!!

**Comment by lamont-granquist** [comment]
That's not a bug, that is how deep merging works.

You have to redefine your data structure.  You might be able to use an array since those are overridden completely between default to normal and normal to override.

so:

```ruby
default['mycookbok']['cluster_node'] = [
  { 'node1' => 'zone1' },
  { 'node2' => 'zone2' },
]
normal['mycookbok']['cluster_node'] = [
  { 'other1' => 'zone1' },
  { 'other2' => 'zone2' },
]
```

The downside of arrays though are is documented here: https://coderanger.net/arrays-and-chef/

Which suggests using hashes instead, to avoid them, which about all i could suggest would be to use fixed keys for the first, second, etc node:

```ruby
default['mycookbok']['cluster_node'] = {
  "member1" => { 
     "name" => 'node1',
     "zone" => 'zone1',
   },
  "member2" => {
     "name" => 'node2',
     "zone" => 'zone2',
   },   
]
default['mycookbok']['cluster_node'] = {
  "member1" => { 
     "name" => 'other1',
     "zone" => 'zone1',
   },
  "member2" => {
     "name" => 'other2',
     "zone" => 'zone2',
   },   
]
```

That sort of creates a pseudo-array using ordered hash key names for the records (and I also went and expanded that out to something that looks like records but you could keep that { <name> => <zone> } if that is unnecessary).

But this IS the expected behavior and public API of the deep merging behavior.
