### ISSUE TITLE
Consider moving the resources in the community IIS cookbook into the Chef Client.

### ISSUE THREAD

**Issue by mcarpenter-cme** [chef/chef#9250]
### Describe the Enhancement:
As a Windows developer we often need to create and configure websites and web applications in IIS.  Currently, we use an internally developed cookbook to do so, however, this cookbook is old and has been neglected is not written well.  We were thinking that we would simply migrate from out internal IIS cookbook to the Chef Community IIS cookbook.  However, the community cookbook has a dependency on the Windows cookbook which, according to our Chef Success folks tells us we should be trying to avoid.  So I think it would be in the best interest for all that the IIS resources just become a part of the Chef Client.

### Describe the Need:
All Windows developers utilizing IIS would benefit from this enhancement.  IIS is a common feature of the Windows operating system and having resources native to the Chef Client would be a huge value add for Windows developers.  And moving the IIS resources into the Chef Client would remove the dependency on the Windows cookbook.

### Current Alternative
The alternative to IIS resources being in the Chef Client is that we would continue to use our internal  
cookbook, which would difficult to maintain.  Or we would migrate to the Chef Community IIS cookbook, which is better than maintaining our own cookbook, but then makes us dependent on the Windows cookbook.

### Can We Help You Implement This?:
It would be awesome for the Chef Community IIS Cookbook resources to be added to the Chef Client since Chef maintains the client.

**Comment by lamont-granquist** [comment]
>  And moving the IIS resources into the Chef Client would remove the dependency on the Windows cookbook.

We'd have to first move all the resources in the windows cookbook into core, which is certainly planned.

I think I'm going to close this one as we're unlikely to have the resources to get this done in the next year or two, and the windows cookbook resources and all of the resource of the cookbook resources which have issues cut against them to get into core take priority.

It is also not clear to me that the IIS cookbook should move into core, since we don't generally tend to have major applications supported by internal core-chef resources.  That is debatable.  We certainly have never planned on pulling httpd/apache/postgres/mysql/mariadb/etc into core.  Once the windows resources are pulled into core, if the iis cookbook is changed to not use the windows cookbook that would also achieve the stated goal here.

**Comment by tas50** [comment]
IIS is a bit weird since it's part of windows. I'm not entirely opposed to shipping it in core. The first focus has to be rewriting the current cookbook to assume PowerShell. That will be a 100% breaking change upgrade. The current code is pretty old and crusty. I wrote some 4 jobs ago and I'll be the first to admit I wasn't the best Chef user back then.
