### ISSUE TITLE
[omnibus] move inspec out of Gemfile and into omnibus/omnibus-software

### ISSUE THREAD

**Issue by tarcinil** [chef/chef#9286]
## Motivation

```
    As a package maintainer,
    I want to move inspec-core and inspec-core-bin into omnibus,
    so that it will make it easier to maintain inspec and its various OSS implementations.
```

At present, `inspec-core` & `inspec-core-bin` are pulled in via a group in the Gemfile at line 28 and 29 respectively.

https://github.com/chef/chef/blob/master/Gemfile#L28
https://github.com/chef/chef/blob/master/Gemfile#L29

This makes changing inspec executables rather difficult, but if they are moved to omnibus software, we can create a cleaner experience for maintaining distributions.

## Specification

I am proposing `inspec-core` and `inspec-core-bin` as omnibus dependencies of the chef software project.

Projected Changes:
- 2 new software items in omnibus-software
- add new software as dependencies of the chef/angrychef projects.
- remove from Gemfile 

## Downstream Impact

This would change how CI processes build the distributions for both OSS and Chef.  If improperly tested, it could lead to distributions that fail to run inspec locally (via Automate or Test-Kitchen).

**Comment by lamont-granquist** [comment]
you can't do this because of appbundler and the need to eliminate duplicate gems.

all the gems which are installed in the chef/chef package need to be in the Gemfile.lock in the chef/chef directory which is solved once and everything is tested against that, and it is installed once via the bundle install.

we have to do this right now with the ohai software definition which pulls from git and it causes endless amounts of issues with duplicated gems (caused issues in building for the release just yesterday).
