### ISSUE TITLE
Error executing action `extract`  -- unable to resolve type 'mode_t'

### ISSUE THREAD

**Issue by zestysoft** [chef/chef#9319]
## Description

I don't think this is a cookbook or plugin issue, even though both are part of this.  I'm trying to spin up a windows 7 enterprise x86 vmware-iso file via a modified bento json file.

It gets all the way to the last recipe 'defrag' which is supposed to download, extract, and run something from an ultradefrag.zip file.  At the extract phase, it errors out with:

```
TypeError
----------
unable to resolve type 'mode_t'
```

I verified that the zip file is not corrupted and was manually able to correctly extract its content after this error.

This plugin and cookbook works fine in Windows 10, so I assume there may be some type of ruby dependency issue with this older version of Windows?  The volume license ISO I'm using is from Microsoft Download Center -- for whatever reason they did not update the ISO after integrating SP1.

Googling for the error was not fruitful for me.

## Chef Version

chef-client-15.7.32-1-x86.msi

## Platform Version

Windows 7 x86 Enterprise SP1
SW_DVD5_SA_Win_Ent_7w_SP1_32BIT_English_-2_MLF_X17-58878.ISO
sha1sum: 4e0450ac73ab6f9f755eb422990cd9c7a1f3509c

## Replication Case

packer build -var headless=false -var iso_checksum_type=none --only=vmware-iso --on-error=abort windows-7-x86.json

## Client Output

```

```

## Stacktrace

[chef-stacktrace.out.txt](https://github.com/chef/chef/files/4143510/chef-stacktrace.out.txt)

**Comment by lamont-granquist** [comment]
This is an issue with ffi-libarchive:

https://github.com/chef/ffi-libarchive/blob/master/lib/ffi-libarchive/archive.rb#L153

Since Window 7 is EOL, we don't have the resources to debug and fix that.  If someone wanted to submit a PR to that repo we could merge and ship it, but that's the intersection of C code with Windows APIs which is not trivial general knowledge.

We could keep this open, but it won't ever get any prioritization, so closing this as it only affects an EOL product.
