### ISSUE TITLE
*_repository use ENV['proxy'] if defined

### ISSUE THREAD

**Issue by faltimiras** [chef/chef#9410]
### Describe the Enhancement:
*_repository do not use environment proxy definition.

### Describe the Need:
I think it would be great if *_repository resoures use environment proxy definition if defined and not overrided

### Current Alternative
apt_repository
    key ENV['proxy'[
  ....

### Can We Help You Implement This?:
I can do a PR if you think makes sense

**Comment by tas50** [comment]
@faltimiras I don't think this is actually the direction we want to head. Apt, Yum and other packing systems each have their own way of configuring proxy settings and users should configure those so that Chef Infra Client behaves in an expected way. Some users may want a proxy to be used with their repositories, but for many other users that would break the way their systems fetch packages.

In apt you can add this config to an apt.d config:

```
Acquire::http::Proxy "http://USERNAME:PASSWORD@SERVER:PORT";
Acquire::https::Proxy "https://USERNAME:PASSWORD@SERVER:PORT";
```

in yum you can add this to your yum.conf:
proxy=http://SERVER:PORT

**Comment by faltimiras** [comment]
@tas50 IMHO this is inconsistent becaues all resources "believes" on this setting and this ones no.

It is not common to use different proxies in the same machine, so I would say that makes sense to just set it once for all http communications. If for some reason you need another proxy, you can always override the proxy setting in the *_repository.

It think it won't break many things because I just proposed to change the default value when a general proxy is defined, If they changed to use they own proxy, nothing will happen because they are overrideing the proxy setting on the *_repository so the default value from ENV['proxy'] won't be used. 

Thanks
