### ISSUE TITLE
Windows functional tests in Buildkite constantly fail

### ISSUE THREAD

**Issue by tas50** [chef/chef#9476]
Our windows functional tests are basically broken. They run on a shared system and fight each other / fail when they try to write / delete the same files. We need to get to a point where this job can reliably run and gets our tests green.

**Comment by lamont-granquist** [comment]
This may be related (similar container issues where we can't run our specs on containers) to why we have most of our testing disabled in the omnibus pipeline on internal Chef Software buildkite.

https://github.com/chef/chef/blob/master/omnibus/omnibus-test.ps1#L94-L97

We need integration, functional and unit testing working on windows there, and need to have the chocolatey testing enabled.

https://github.com/chef/chef/blob/master/omnibus/omnibus-test.sh#L160-L161

Similarly on *nix we need to have those tests re-enabled.

**Comment by lamont-granquist** [comment]
We need to be running all unit, functional and integration tests in all test stages, and need to be running them as root, and that probably means NOT on any containers -- which is why I dumped that comment into this issue, because I suspect that containers are probably at least the first problem we will run into with re-enabling those tests.

**Comment by christopher-snapp** [comment]
with the new win-2019 ami including ruby 2.6 + 2.7 we just needed to ensure we were using privileged `single-use` instances to allow chef 15 + 16 pipelines to avoid clashing
