### ISSUE TITLE
archive_file resource casts mode incorrectly

### ISSUE THREAD

**Issue by sfiggins** [chef/chef#9577]
## Description

When archive file creates the destination folder it incorrectly casts the mode for the directory. What should be by default `0755` becomes `01363`.

## Chef Version

Noted with  15.8.23. Looks like it is still a problem with current master.

## Platform Version

Linux - a centos 7 target. Though this would probably be a problem on any unix like filesystem.

## Replication Case

Use archive_file and give a destination that does not already exist. Created directory will by default be assigned mode 01363.

Problem line is in `lib/chef/resource/archive_file.rb`

```ruby
            FileUtils.mkdir_p(new_resource.destination, mode: new_resource.mode.to_i)
```

Casting '0755' to integer yields 755. When cast back to octal this becomes 01363.

**Comment by lamont-granquist** [comment]
There's code to handle this already in the file provider's mode handling (buried somewhere in a mixin I think).

**Comment by lamont-granquist** [comment]
lib/chef/file_access_control/unix.rb has a `mode_from_resource` method.

that should probably go into a helper in chef-utils so its accessable as "how Chef, Inc coerces string things that might be octals into numbers".

**Comment by tas50** [comment]
@sfiggins I merged in a fix for this. Unfortunately Ruby doesn't expose a way to tell the base of the Integer the user passed in and mkdir_p needs it to be in Octal form. That means there's no reliable way for us to ensure the passed in value is appropriate. I've added a deprecation for passing in Integer values since we can convert String values to octal without issues.
