### ISSUE TITLE
Request backport of #9500 (refresh DNF package provider) to Chef 14 before EOL

### ISSUE THREAD

**Issue by hrak** [chef/chef#9638]
### Describe the Enhancement:
Not sure if you are even taking this kind of requests for Chef 14, but it would be awesome if you could pretty pretty please with sugar on top backport #9500 to Chef 14 before it reaches EOL.

Currently `dnf_package` is missing implementation of the `options` property entirely in Chef 14. I ran into this while trying to disable the AppStream repo to install mysql-community-server from the [mysql repo](https://dev.mysql.com/doc/refman/8.0/en/linux-installation-yum-repo.html) on CentOS 8.

### Describe the Need:
The `dnf_package` resource currently misses vital features, making it incompatible with the interface that the package resource uses towards the yum/apt/etc package resources.

`dnf_package` is the default implementation that the `package` resource uses on any recent RHEL-like distro.

### Current Alternative
I guess you could explicitly use the `yum_package` resource for now, but a lot of cookbooks use the `package` resource and rely on functioning underlying `xxx_package` implementations.

### Can We Help You Implement This?:
You can help by either backporting this PR to Chef 14 (and make all the free Chef users very happy), or by letting me know that you are willing to accept a PR for this so i can prepare one.

**Comment by tas50** [comment]
@hrak We won't be backporting this one due to the risk involved in the change. The fixes to dnf involved some large scale refactoring that may result in some regressions in the dnf package provider. We won't know the full stability of that change until Chef Infra Client 16 sees widescale adoption in RHEL 6 environments. Additionally, that dnf refactoring work relied on a large scale refactoring to yum_package that occurred in Chef Infra Client 15, which would also have to be backported. That change fixed a large number of longstanding issues in ways that could be considered breaking changes to some people. Pulling in those two large changesets seems incredibly destabilizing to users at the end of Chef Infra Client 14 release cycle. Sorry I don't have better news for you, but you're going to need to update in order to get these fixes.
