### ISSUE TITLE
Habitat package for Windows not working with powershell DLL

### ISSUE THREAD

**Issue by tas50** [chef/chef#9754]
The Powershell shim DLL that makes powershell_exec able to talk to the system .net/PS does not work on Habitat which means we can't convert resources to use powershell_exec and any community written resources for powershell_exec will fail in Effortless.

Aha! Link: https://chef.aha.io/features/SH-110

**Comment by btm** [comment]
Some work was done on the DLL in #9739. @mwrock looked at this last night and determined that the DLL was able to be located with that change, but it wasn't in a location that met the .net rules for where libraries could be. As of last night, it looked likely we would have to dirty the ruby package with the DLL to satisfy .net.

**Comment by mwrock** [comment]
To elaborate further here, there are 2 key DLLs `chef.powershell.wrapper.dll` and `chef.powershell.dll`. The first is a small wrapper written in native C++ that simply fires up a .Net environment and loads the latter managed C# DLL that does the actual powershell wireup. With the `ruby_dll_path` set in the referenced PR, ruby can load the wrapper DLL but .Net has its own rules for locating assemblies (DLLs) that is not influenced by environment variables. By default, it will look in the GAC or in the same directory as the binary that owns the process - ruby.exe. The GAC is really not a great option for us because it is a global registry.

Today I'm going to investigate having the native wrapper start .net  and load the managed dll into a custom app domain where it can configure the codebase where .net will probe for assemblies. I know how to do that in C# but will need to do some studying on how to do from unmanaged code.

If that looks untenable, I do think the GAC is better than copying the DLL into the ruby package. We could have an install hook do the GAC registration but if we could provide a hint to the .net runtime with an alternative path for loading assemblies pointing to the same directory that holds the wrapper, that is the best option.

**Comment by mwrock** [comment]
This should be fixed by https://github.com/chef/chef-powershell-shim/pull/11 and https://github.com/chef/chef/pull/10022.
