### ISSUE TITLE
file diff reported to Chef Automate is inaccurate when there are multiple changes in a single run

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/chef#9792]
## Description

If a resource is converged multiple times in a `chef-client` run that generates different diffs the report sent to Chef Automate shows the last diff applied to the resource for both changes.

## Chef Version

15.8.23

## Platform Version

RHEL 7.7

## Replication Case

1. Create file on system

	```bash
	echo "123" > /tmp/example
	```

1. Create recipe w/ template

	```ruby
	# recipes/default.rb
	template "/tmp/example"

    file "/tmp/anotherfile" do
      notify :create, 'template[/tmp/example]', :immediately
    end
	```
	
	```ruby
	# templates/default/example.erb
	<%= rand(1..100000) %>
	```

Although the case above makes no sense realistically, we have use cases where the initial template generation is different at the beginning of the chef run than towards the end. So when you go into Chef Automate to review the diff, it shows the last diff generated and not the intermediate one.

**Comment by lamont-granquist** [comment]
This won't work in any resource in Chef 15. The after_resource introduced in Chef 16 in https://github.com/chef/chef/pull/9562 will fix this for any properly written custom resources with a load_current_value method.  This bug exists in every other resource, so I'm closing this bug report in favor of the epic in #9795 which can cover all of them.  The file resource and service resource are particularly high priority ones to fix because of the hacks that go into trying to work around the new-resource-as-after-resource hack over the years.  Probably won't be fixed soon though.
