### ISSUE TITLE
not able to bootstrap aws windows instance to chef server

### ISSUE THREAD

**Issue by AnamikaN** [chef/chef#9909]
when i am trying to bootstrap aws windows instance to chef server. i am getting below error. Any help would be appreciated.

knife bootstrap -o winrm 10.200.xxx.xxx -U Administrator -P 'xxxxxx' -N WindowsNode -VV
INFO: Using configuration from /Users/anadkarni/Documents/src/chef.deploy.rd.elliemae.io/.chef/knife.rb
DEBUG: Checking if we need to accept Chef license to bootstrap node
DEBUG: Reading products and relationships...
DEBUG: Successfully read products and relationships
DEBUG: License acceptance required for chef version: 15
DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
DEBUG: Found license chef_infra_client at /Users/anadkarni/.chef/accepted_licenses/chef_infra_client
DEBUG: Found license inspec at /Users/anadkarni/.chef/accepted_licenses/inspec
DEBUG: Missing licenses remaining: []
DEBUG: All licenses present
Connecting to 10.200.186.176
DEBUG: winrm-fs requested, loading WinRM::FS gem (~> 1.0)
DEBUG: WinRM::FS previously loaded
DEBUG: [WinRM] @10.200.186.176<{:transport=>:negotiate, :disable_sspi=>false, :basic_auth_only=>false, :endpoint=>"http://10.200.186.176:5985/wsman", :user=>"Administrator", :password=>"<hidden>", :no_ssl_peer_verification=>false, :realm=>nil, :service=>nil, :ca_trust_file=>nil, :ssl_peer_fingerprint=>nil}> (Write-Host '[WinRM] Established
')
DEBUG: [WinRM] opening remote shell on http://10.200.186.176:5985/wsman
DEBUG: [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb
DEBUG: [WinRM] opening remote shell on http://10.200.186.176:5985/wsman
DEBUG: [WinRM] Endpoint doesn't support config request for MaxEnvelopsizekb

**Comment by AnamikaN** [comment]
I found there is uppercase and lowercase issue with property MaxEnvelopsizekb.

on windows node, when i try to set  MaxEnvelopsizekb using winrm, it shows below error.

C:\Windows\System32>  winrm set winrm/config '@{MaxEnvelopsizekb="1024"}'
Error: Parameter name does not match any properties on resource: MaxEnvelopsizekb

The property name on winrm is MaxEnvelopeSizekb (S from size is uppercase)
But through knife bootstrap command , it is internally trying to set or use "MaxEnvelopsizekb".

How to resolve this issue? any suggestions ?

**Comment by phiggins** [comment]
This is probably not the root problem, but in your example the case of the parameter probably does not matter, it is likely because there is [a typo in the error message](https://github.com/WinRb/WinRM/blob/a79d340cf24c5567ab4ec7f211b43c32f78fdd9f/lib/winrm/shells/power_shell.rb#L156) and the parameter is `MaxEnvelopeSizekb`.

**Comment by mwrock** [comment]
Looks like not only does that debug message have a typo but it shouldn't even be rendered. There is a WinRM bug (which I will fix) that puts the debug message in an `ensure` instead of a `rescue`.

So the core issue here is that the bootstrapper just cant get through to the node. This is likely due to one or both of the following:

1. You have not added an inbound rule allowing `WinRM-HTTP` (port 5985) traffic in aws.
2. The local Windows firewall on the node is restricting traffic to its local subnet which is the default. Running `netsh advfirewall firewall add rule name="WinRM-HTTP" dir=in localport=5985 protocol=TCP action=allow` on the node would open that up to outside subnets.
