### ISSUE TITLE
CHEF-3694 is back in Chef 15

### ISSUE THREAD

**Issue by aleksey-hariton** [chef/chef#9964]
## Description

In some sophisticated cases there is possible to return back Chef-3694 bug in Chef 15 and probably on 16!  
Tested on Chef 14, everything is fine, on 15.4.27 bug exist.

## Replication Case

On any CentOS instance with Chef 15:

```
> chef-shell

recipe_mode
yum_package 'vim' do
  allow_downgrade false
end

package 'vim'

run_chef
chef_run.collection.each{|r| puts r.allow_downgrade}

false 
true
```

Expected `false/false` in the end, on Chef 14 works as expected.

**Comment by lamont-granquist** [comment]
This is the expected behavior.  The first resource has allow_downgrade false, the second resource does not copy that setting (no resource cloning) from the first.

The difference in behavior is also likely due to the difference in the default values of allow_downgrade in 15 which was flipped to being true by default.

**Comment by aleksey-hariton** [comment]
@lamont-granquist 
> the second resource does not copy that setting (no resource cloning) from the first.

It should, because `package 'vim'` during chef-run became `yum_package 'vim'`, so its the same resource.
