### ISSUE TITLE
[WIP] [design-proposal] create compliance phase in infra-client

### ISSUE THREAD

**Issue by btm** [chef/chef#9986]
## Purpose

Implement a first-class compliance phase in the infra client that configures and runs InSpec similar to the audit cookbook but without the additional dependency.

## Motivation

- Easier to get started with the combination of Chef + InSpec + Automate (ease of use, time to first value)
- Remove user and Chef maintenance of the audit cookbook (painful and unnecessary)

## Specification

- Allow existing users to remove the audit cookbook from the run list and maintain functionality through compatibility with the existing configuration settings for the audit cookbook as node attributes. (noop if audit cookbook is still in the expanded run list, otherwise run inspec?)
- Continue to support reporting to Automate directly as well as proxied by the Infra Server (reporters moved to inspec in [inspec#5088](https://github.com/inspec/inspec/issues/5088) )
- Evaluate if later work should be considered to move the configuration from node attributes to ChefConfig or another mechanism. (ChefConfig seems much less flexible on its own for changing the behavior for different node sets, see Configuration below)

#### Calling InSpec

Having the user consume whatever version of InSpec is shipped in the infra client distribution is preferable from a support perspective, but having to upgrade infra-client to get a bug-fix for inspec will be a challenge for some. Calling `::Inspec::Runner.new` directly is the most likely path.

- The audit cookbook calls `::Inspec::Runner.new` directly
- The audit cookbook has a recipe/resource for installing a specific version if the inspec gem, but that doesn't work with the appbundles and thus only supports Chef <15. It should be ignored and not brought into core.

- /opt/chef/bin/chef-client and /opt/chef/bin/inspec (and others) are appbundled (look at these files on disk if you're not familiar).
- the appbundles in the two stubs are the same and specify the same version of inspec that is shipped in the chef package
- chef-workstation does the same, but has many more gems and appbundles during its build, so it ends up with a different bundle.

#### Configuration

Options:
1. Core reads directly from node['audit'] for configuration
2. Core reads directly from node['chef_client']['config']['audit'] for config (could read all of node['chef_client']['config'] or just the audit portion)
3. User is required to use chef_client cookbook or another similar to pull config from one of those above places in the node object and push to ChefConfig directly and/or via a client.rb on disk.
4. Read part of the node object, write to an [inspec config](https://www.inspec.io/docs/reference/config/).

The audit cookbook is currently configured through a pile of node attributes. At least temporarily supporting these in core infra client provides a migration path, however infra client almost always is configured through ChefConf.. Managing the client.rb for ChefConfig can be done through the [chef-client cookbook](https://github.com/chef-cookbooks/chef-client) in `node['chef_client']['config']`. 

The audit cookbook contains a [chef_client_config.rb](https://github.com/chef-cookbooks/audit/blob/master/examples/automate_win/recipes/chef_client_config.rb) example for configuring parts of the client.rb by putting a file under `client.d`.

In either case, needing a cookbook to configure any part of core infra client seems like a smell. But typically functionality in core is specified in recipes, with minimal ChefConfig values that aren't regularly changed. An InSpec run is a bit of a special case compared to the rest of core. Having some portion of the node object (e.g. node['audit']) be read by core and then an [InSpec config file](https://www.inspec.io/docs/reference/config/) that is generated by seems like a reasonable separation of concerns.

#### [audit cookbook](https://github.com/chef-cookbooks/audit)

The current solution for running inspec through infra-client.

#### [rfc 035 - audit mode](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc035-audit-mode.md)

audit mode was a pre-inspec impementation of a serverspec based tests run at the end of a client run. It was [removed from Infra Client in 15.0](https://discourse.chef.io/t/chef-infra-client-15-0-293-released/15110).

#### [rfc 083 - audit phase](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc083-audit-phase.md)

An unimplemented proposal from 2016 to remove the rfc 035 audit mode and replace it with a more agnostic option through a test 'segment' in the cookbook. Prior to the implementation of [rfc 067](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc067-cookbook-segment-deprecation.md), cookbooks had an explicit list of 'segments' which were directories in the cookbook that were uploaded to the chef infra server. Adding new cookbook functionality required adding support allow those directories to be uploaded. This was added to infra server in [chef-server#1034](https://github.com/chef/chef-server/pull/1034) and first released in [Infra Server 12.18.14](https://discourse.chef.io/t/chef-server-12-18-14-release/13835) in October 2018.

### InSpec

The audit cookbook contains a number of [reporters](https://github.com/chef-cookbooks/audit/tree/master/libraries/reporters). These are mostly for sending results to Chef Automate, sometimes with the Infra Server as a proxy in cases where there is a local Infra Server but a remote Automate server and firewall considerations. InSpec has [similar reporters](https://github.com/inspec/inspec/blob/master/lib/inspec/reporters/automate.rb) that are duplicative but may not be 100% drop-in replacements. We likely do not want to bring these reporters into core infra client, so we would need to reconcile any differences.

https://github.com/inspec/inspec/issues/5088 exists for investigating moving the reporter plugins from the audit cookbook to inspec as a reporter plugin.

Aha! Link: https://chef.aha.io/features/SH-172

**Comment by lamont-granquist** [comment]
Yeah so I'll accept reading node['audit'] in core for backcompat with the audit cookbook, but that should be deprecated immediately.

RFC-083 is more like the right way to do it.  That should get looked at again and rehashed, and I need to try to refresh my memory about what I hated or didn't about the old audit mode.

**Comment by galenemery** [comment]
I'm a fan.  Removing the external dependency on the audit cookbook is a big win.

I think there's a potential use case to position the InSpec run at the start of the chef-client run, as a way to determine if drift is occurring.  Particularly useful in highly sensitive environments.

An alternate way to solve for that is enhanced reporting capabilities from Chef Infra on 'flapping/drifting' resources.

Not sure if it really applies directly to this proposal but a potential design consideration.

**Comment by galenemery** [comment]
A note as well: The audit cookbook allows for configuring the InSpec run to be on an interval separate from chef-client.  Run chef-client every 15 minutes, but InSpec only every hour.  Due to the potential length of running an entire CIS profile against a node, it would be important to retain the ability to separate the timing between Infra & InSpec.

**Comment by btm** [comment]
> I think there's a potential use case to position the InSpec run at the start of the chef-client run

Yeah, I thought a little about something similar but was worried it may be too big of a jump. In the context of remediation, what if you could Chef -> InSpec -> Chef (remediate) -> [InSpec (verify)]? So like "If Chef has resources changed, run inspec to ensure that we are still compliant, and if we aren't, remediate that, maybe running inspec again to confirm." But that's kind complex and heavy. 

Also, what about "Inspec -> Chef -> Inspec" ? Were we compliant then Chef did something that made us not compliant, or were we not compliant to start with? Piecing together data from automate feels better here, although the time gap between runs leaves more room for entropy.

I'm not arguing for any of those, they're probably all out of scope, but it did make me pause for a minute to wonder if being able to configure some kind of matrix of phases like that would be useful.

**Comment by galenemery** [comment]
> Chef -> InSpec -> Chef (remediate) -> [InSpec (verify)]? So like "If Chef has resources changed, run inspec to ensure that we are still compliant, and if we aren't, remediate that, maybe running inspec again to confirm." But that's kind complex and heavy.

Yeah, I like the theory.  Which feels like "Enforce desired state.  Verify that our security state is compliant.  If not, enforce the security state.  Re-verify".

Definitely feels too heavy for this, and leads us into rabbit holes of precedence levels and multi-master.  But I can see the implementation specifically with multiple teams using Chef for different purposes.

> Inspec -> Chef -> Inspec" ? Were we compliant then Chef did something that made us not compliant, or were we not compliant to start with? Piecing together data from automate feels better here, although the time gap between runs leaves more room for entropy.

I think there's a value in running the audit before doing any work.  "Is the system in my desired state?  Aka, has it drifted at all?"  So InSpec first, or InSpec without remediate at all gives me useful information.

The aggregation of InSpec > Chef > InSpec definitely feels like very useful aggregation in Automate.  The system performed its planned 3-phase run, and was non-compliant before Chef ran, but compliant after.  This system was last known to be in compliance 30 minutes ago.  Possible drift detected.  Or: System is newly registered, this looks like new provisioning (or even on a first run, we wouldn't run InSpec first).

Some of that behavior could be client side, particularly with solo implementations (if this is the first run, do not run InSpec first) and some would be on Automate (aggregating the reporting data into a clear view on system health).

**Comment by lamont-granquist** [comment]
I think the MVP is probably just a slightly more fleshed out RFC-083

- decide on the name of a new cookbook segment - tests or audits or something.

- add an audit_handler which runs probably after report handlers which is generic.

- a few command line flags / config flags to run only-audits, only-chef or both.

then the details come down to writing the inspec audit handler which is shipped inside of the client.

someone can then always run:

chef-client --only-audit && chef-client --only-converge && chef-client --only-audit 

if they strongly desire that kind of reporting to show up.

trying to make it work that way inside of the core of the Chef::Client loop is going to wind up being a lot of messy surgery.

if we hit issues where that's the way everyone decides to use it, and doing it the scripted way is kludgy and really /needs/ tighter integration within a single chef-client run, then I think you could do that as a next step, but i feel like YAGNI probably wins here.  and we did not see this as a problem with the old chef-client audit mode.  mostly we hit problems there where we integrated it way too tightly with too much spaghetti code.

**Comment by btm** [comment]
I have a potential feature that is out of scope for this work. I don't think? it needs to be considered when we think about the future configuration for this functionality right now but I'll mention it all the same.

Given that with Chef YAML we kept the recipes name-spaced under a top-level resources in the YAML, could I have (and would I want to?) the ability to have a configuration and/or audit namespace where I configure the CIS run in the same recipe? 


chef-apply --only-audit -o desktop::mac && chef-apply --only-converge -o desktop::mac && chef-apply --only-audit -o desktop::mac

**Comment by stephenlauck** [comment]
What about using Inspec purely as the guard "not_if" in a simple chef exec resource with the command of the resource as the "remediation"?

This would allow backwards compatibility of existing users wrapping the audit cookbook but also greatly simplify what we're doing in terms of wrapping and also is more in line of what our Users want which is to use Inspec as the assertive check to whether remediation action should happen.

```
execute 'fix' do
  command 'echo "remediation not implemented"'
  not_if <<~EOF                                                                                 
         inspec shell -c "                                                                      
           describe file('/tmp/foo') do                                                         
             it { should exist }                                                                
             end"                                                                               
         EOF                                                                                    
end
```

We could add to chef-client an `:inspec` guard interpreter and just auto push controls from attributes into generated exec resources at compile phase.

**Comment by lamont-granquist** [comment]
^ I asked @stephenlauck to drop that into here.

The guard clause there is quite horrible because its a string.  The first horrible bit is the constant part "inspec shell -c" which would be removable via a specific guard interpreter for inspec.  The second bit is the rest of the string which is where you have to type out an inspec style rspec conditional as a string to make it run which is pretty lousy.  We could build out a string-builder style interface as a class in chef which allowed users to write something that looked like inspec but "compiled" to a string passed to inspec, but that's a super-terribad API, and the problem is the string-api-from-chef-to-inspec.  So the obvious thing to do is to bake inspec more directly into chef so that we could have an inspec guard interpreter, but the block you gave it was directly passed into inspec running in the chef process.

Which is just technical comments on what the interface between inspec and chef guard clauses should look like, I haven't deeply thought about if that's really a good idea or not, but its something that we could build which from a technical standpoint would be a fairly strainght-forward extension.

One concern I've got is that the inspec language itself is very rspec-cy, and `file('/tmp/foo').should exist` as an expression would be way better API than having the describe and it blocks, which become superfluous when used in this context where you want a single expression and not multiple tests.

```
execute 'fix' do
  guard_interpreter :inspec
  command 'do a thing'
  not_if { file('/tmp/foo').should exist }
end
```

Still a bit klunky because "not if file should exist" should really be expressed like "not if file exists", but I don't think(?) that's valid inspec.

I wonder if there's a way to build a more expression-oriented fascade syntax inside of inspec that chef could use, rather than the rspec syntax (the fascade/proxy/delegator/builder/whatever would expose a more expression-like syntax and behind the scenes build up an inspec test and run it).

**Comment by galenemery** [comment]
InSpec likes the should/expect verb.  You're making an assertion on what your intended state is.  In many ways, this guard is looking to move the InSpec test from your tests directory directly into your guard (assuming you wrote one).

Also, if you remove too much.. whats the value of InSpec as a guard interpreter over the defaults?  `not_if { ::File.exist?('/tmp/foo')` already works.

But that's not to say we shouldn't make an InSpec guard.  Provides better consistency for sure.


The guard interpreter doesn't quite solve the "audit-only" mode though, because you are likely to either have a) separate owners between Security Controls and Chef Recipes and/or b) separate controls from your resources.


Aside:

There is also value in a way for a control failure to trigger a specific remediate/converge resource.  Why test/repair loop twice?

**Comment by lamont-granquist** [comment]
Some thoughts on the audit cookbook:

- The configuration in the node object looks like Chef::Config settings and should probably be moved there

- The pulling of profiles from chef-server or automate feels like the cookbook synchronizer.  it should probably be more tightly coupled with a phase "near" the cookbook synchronizer that pulled down profiles.  (but this means that cookbook code cannot tweak those attributes to control where profiles are pulled from -- i can make an argument though that this is a security feature).

- Can we pull profiles from cookbooks with the audit cookbook???  That super isn't clear from the README which seems to be built around the pull-from-a-server use case, but I still think we should support an additional "profiles" or "audit" segment in cookbooks to drop inspec into.  This could then be leveraged easily in test-kitchen.

- On a more mundane level the audit cookbook is still mixing up "the chef node object" from "[inspec] attributes" which is totally confusing.  Inspec attributes got renamed, that word should get used correctly.

- We should consider ways of baking the profile information to run directly into PolicyFiles, similarly to run_lists, along with inspec not-attributes directly into PolicyFiles.  Those could then be placed under the control of the compliance/security group via include_policy.  If you had named_policy_list or whatever similar to named_run_lists, and those policies lived in the cookbook then there'd be a nice easy way to tell test-kitchen to run a named_run_list with a named_policy_list and pass or fail.

- I wonder if we should bake Chef::Config information directly into PolicyFiles (which is a bit tangential -- but shipping configuration through attributes into a cookbook or resources to be rendered into the client.rb feels like a huge round trip through systems that don't offer much at all)

- The reporting should probably be included directly into the data collector payload rather than being separate.  We have to support the existing split-functionality for backcompat, but we should really eliminate that.

- I'm just going to assert that what we should focus on is remediate-with-chef-then-report-we-were-successful.  We can have knobs to change things, but I think this is correct.  And you DO NOT WANT compliance people in charge of producing remediation.  If you split roles up like that, then you have people who don't understand actually managing systems in charge of policy, which means they MUST NOT be doing remediation.  Putting my System Engineering or Software Developer hat on, that group doesn't push out code that alters the system state and to do otherwise is a recipe for downtime and outages and different groups screaming at each other.  If you want that kind of two-phase commit in your organizational structure, that's the price to pay for it.  The whole approach of compliance generating remediation feels like organizational overreach by people who do not have that job.

(At the same time, we can build knobs to change this so you can run only-audit or only-converge and then compose those phases however you like, along with the fact that nothing stops compliance people from pushing out remediation in their own cookbooks, even though I think that's a mistake -- but we should engineer around a default configuration which isn't a footgun)

**Comment by lamont-granquist** [comment]
And, ugh, inspec has policies and chef has policies.  That is, once again, terrible.

**Comment by YAMLcase** [comment]
Is it the intention that compliance phase _can be_ (not _should be_) used with `kitchen converge` instead of `kitchen test` for some use cases?
