### ISSUE TITLE
Disable yum recursive removals

### ISSUE THREAD

**Issue by herrin** [chef/chef#9991]
### Describe the Enhancement:
"rpm -e" refuses to remove an RPM if another RPM still depends on it. "yum -y remove" (which chef uses) expands the removal list to include any packages which require the one being removed. I want Chef-driven removals to behave like "rpm -e."

### Describe the Need:
When used interactively, expanding the removals is reasonable: present the user with the list to be removed and ask if that's what they meant to do.

When used under chef, deleting more than the requested package is usually a mistake: the recipe author didn't know that something they still want requires the package they thought they didn't want. Ideally, yum would fail and stop here rather than wreck the server by removing a potentially unbounded set of packages.

### Current Alternative
Yum has an option to prevent this behavior: "remove_leaf_only=1". It doesn't behave as Chef expects. Yum refuses to remove the package with the dependency but then reports status 0 back to chef - I'm happy, I did as you asked even though I, well, didn't. Chef then tries (and silently fails) to remove the package on every subsequent run.

### Can We Help You Implement This?:
I wrote a patch with units tests which, if a configuration value is set to true, invokes yum with remove_leaf_only=1 and then checks afterward to confirm that the named packages were removed. If they were not, it raises an error stopping the chef run.

https://github.com/herrin/chef/commit/c9ab6fef4ba107357bc974ece739ae0f5f87307a

**Comment by jaymzh** [comment]
Hey @herrin ! Thanks for proposing this! I think there's a lot of good stuff here.

There's a use-case for this for sure, but I want to be clear that the premise of this being a bug and vs the way it "should" be is quite flawed.

If you do `rpm -Uvh <foo>` it'll also fail if all of its dependencies and their dependencies aren't already installed. There is a reason we don't generally install software that way. We intentionally left the days of `rpm` and `dpkg` behind for `yum`, `dnf`, and `apt` and those of us who remember the 90s call it rpmhell. Try to install package, see list of deps. Download deps, try to install the first one, see list of deps. Download all those, rinse and repeat.

We don't uninstall with `rpm -e` for the same reason we don't install with `rpm -Uvh` - we prefer when software does the heavy lifting for us.

Now that said, in a large automated environment with hundreds of developers committing to a complicated and nuanced Chef codebase such as Facebook and others it's not unreasonable to request people specify the full list of packages they intend to remove.

But lets consider an alternative example: I know that machines come out of "the machine factory" at my Company (whatever, call it Company X) as some "golden image" that's supposed to "work for everyone", but I want it to work for a server or a container. I don't want to list the 954 packages that it would then take to uninstall Gnome, X, GDM, alsa, pulseaudio, bluez, and friends. That would be torture, not to mention unreadable code. Instead I want to find some low level library that the whole damn stack depends on and remove that. Something like libxrender or whatever.

So all that said a feature like you describe would be great - but should be configurable. Specifically I think it should be configurable in at least 2 different ways, and possibly a 3rd. Lets start with the 2 required ones:

1. The default must remain the same for most users, but some companies will want the default as you describe. So you'd want a `client.rb` config to be able to set site-chosen default.
2. Regardless of what the default is, it is highly likely - nay! *inevitable* - that you will need exceptions, so you'll want a property on the `package` resource to override this.

That way you could do things like

## Example 1
In `client.rb`:
```ruby
# At BigCompany we never want people accidentally removing
# a bunch of rdeps
pkg_rdep_implicit_removal false
```

Then in some recipe:
```ruby
package 'libxrender1' do
  action :remove
  # I've done all the testing - this removes the 5,341 packages I need it to,
  # but nothing more
  pkg_rdep_implicit_removal true
end
```

Or, alternatively...

## Example 2

Some other place that has keeps the Chef default of allowing implicit rdep removal
```ruby
# The 32-bit version of this got installed by accident a few months ago
# and shouldn't be used by anything. We want to remove it, but in case someone
# started relying on it, don't ever uninstall some huge stack of 32-bit stuff implicitly
package 'libc6:i686' do
  pkg_rdep_implicit_removal false
end
```

For bonus points if you could figure out a way to only force it for specific repos, that would be pretty cool. I can see for example people not wanting to ever do this with system-level packages but very much expecting explicit dependency statements for internal packages. So you might have something like:

```ruby
pkg_rdep_implicit_removal_forbidden_repos 'ourcompany-runtime'
```
(see what I did there?)

The other thing that's missing from this discussion is that this is in no way limited to Yum. If you're going to implement this the wiring should go into the `package` resource itself so that it can easily be wired up into `dnf_package`, `yum_package`, `apt_package`, and the like. This is not some weird yum-ism - this is how all modern package managers behave (by design). I think it's a great idea to support controlling that behavior from configuration management. As you pointed out, Yum is going away, so if you're going to take the time to implement this, please use the time wisely and implement it in the base class (you need not implement it in all the child classes) and wire it into whatever subclasses you'd like so that others may also extend the implementation to their various package manager resources.

**Comment by lamont-granquist** [comment]
Yeah, this is a very hard 'no' for yum_package.

`rpm_package` should be able to do this, even if you have to hammer on it a bit with the options flag.

**Comment by herrin** [comment]
Thanks @jaymzh for the feedback! 

One persons bug is another person's feature. I hope you'll forgive me for thinking it a design bug to make yum's automated behavior uncritically identical to the interactive behavior. 

It turned out to be easy to address the issue in DNF with a plugin that plays well with Chef so I don't anticipate needing code in Chef to get the same results. I hope to publish the plugin soon. I haven't looked in to apt since I don't use Chef on any Debian derivatives.

I think I'd like to start with a client.rb setting that overrides the default behavior we get with yum and gain some operational experience with it before making it more finely adjustable. Does that sound reasonable to you?

**Comment by lamont-granquist** [comment]
You can always use the `execute` resource with a guard to arbitrarily complicated things.

**Comment by jaymzh** [comment]
Heh, @lamont-granquist seems even more opposed than I do. I imagine because it'd be a support nightmare. But if it was configurable enough I imagine a discussion can be had.

**Comment by lamont-granquist** [comment]
Yes, this is such a edge condition and will add more features to already complicated code that there's no way that i would consider it.  This is well into `just use an execute resource` territory, and I don't feel bad about that.

**Comment by jaymzh** [comment]
Well @lamont-granquist - the problem facebook is facing is someone removing something they know think they don't want, but then it removes an rdep that breaks something else. I get the concern, and I think an optional feature is not unreasonable, but certainly changing the default would be chaos.

**Comment by lamont-granquist** [comment]
yeah, but that should be `rpm_package` to start with.  That's the tool for "make it behave like rpm -e".

**Comment by lamont-granquist** [comment]
And one way or another you're going to have to know that you don't want to do this.  We can't change the default so it impossible for users to make a mistake like this.  You're using the thing with the depsolver and getting that sort of behavior by default.  That is 100% by design.

**Comment by jaymzh** [comment]
I guess you could encourage everyone to move to 'rpm_package' for all removals if that's what you want as a local policy, but that's quite an undertaking. Especially since you can't easily wire up a different default based on action.

**Comment by jaymzh** [comment]
Well, not really, right? They're not explicitly using 'yum_package' or `dnf_package' - they're using 'package'.

But perhaps a local foodcritic/cookstyle rule that require `rpm_package` when `action :remove` is not an unreasonable way to go.

**Comment by lamont-granquist** [comment]
Yes, if you want to make that local cookstyle policy, that would be the way to go.

**Comment by davide125** [comment]
`rpm_package` doesn't quite work here because it won't know about the added history database that `yum` (or `dnf`) maintain. It also doesn't lock at all, which can lead to issues if other processes outside of Chef try to do concurrent package operations.

**Comment by davide125** [comment]
I do agree with @jaymzh that if we go down this path, doing it in `package` is likely the better strategy (even if we actually only implement it for yum under the hood for now).

**Comment by herrin** [comment]
Would it be more palatable if I rephrased the problem this way:

Yum with "remove_leaf_only=1" does what I want. Chef, however, does not understand when yum is configured this way and fails. Update the yum provider to correctly understand the results from yum.
